/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.jadsc.stage.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.jadsc.stage.services.model.JadscApplicationInitiateInvestigation;
import com.nbp.jadsc.stage.services.model.JadscApplicationInitiateInvestigationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the JadscApplicationInitiateInvestigation service. Represents a row in the &quot;nbp_jadsc_appli_initi_inves&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>JadscApplicationInitiateInvestigationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JadscApplicationInitiateInvestigationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JadscApplicationInitiateInvestigationImpl
 * @generated
 */
@JSON(strict = true)
public class JadscApplicationInitiateInvestigationModelImpl
	extends BaseModelImpl<JadscApplicationInitiateInvestigation>
	implements JadscApplicationInitiateInvestigationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jadsc application initiate investigation model instance should use the <code>JadscApplicationInitiateInvestigation</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_jadsc_appli_initi_inves";

	public static final Object[][] TABLE_COLUMNS = {
		{"jadscAppliInvestiId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"dateOfIniInvest", Types.TIMESTAMP},
		{"outcome", Types.VARCHAR}, {"caseId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("jadscAppliInvestiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dateOfIniInvest", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("outcome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("caseId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_jadsc_appli_initi_inves (jadscAppliInvestiId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,dateOfIniInvest DATE null,outcome VARCHAR(75) null,caseId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_jadsc_appli_initi_inves";

	public static final String ORDER_BY_JPQL =
		" ORDER BY jadscApplicationInitiateInvestigation.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_jadsc_appli_initi_inves.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CASEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OUTCOME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public JadscApplicationInitiateInvestigationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _jadscAppliInvestiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setJadscAppliInvestiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _jadscAppliInvestiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return JadscApplicationInitiateInvestigation.class;
	}

	@Override
	public String getModelClassName() {
		return JadscApplicationInitiateInvestigation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<JadscApplicationInitiateInvestigation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String,
				 Function<JadscApplicationInitiateInvestigation, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JadscApplicationInitiateInvestigation, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(JadscApplicationInitiateInvestigation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<JadscApplicationInitiateInvestigation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<JadscApplicationInitiateInvestigation, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(JadscApplicationInitiateInvestigation)this,
					entry.getValue());
			}
		}
	}

	public Map<String, Function<JadscApplicationInitiateInvestigation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map
		<String, BiConsumer<JadscApplicationInitiateInvestigation, Object>>
			getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<JadscApplicationInitiateInvestigation, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<JadscApplicationInitiateInvestigation, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function
							 <JadscApplicationInitiateInvestigation, Object>>();

			attributeGetterFunctions.put(
				"jadscAppliInvestiId",
				JadscApplicationInitiateInvestigation::getJadscAppliInvestiId);
			attributeGetterFunctions.put(
				"groupId", JadscApplicationInitiateInvestigation::getGroupId);
			attributeGetterFunctions.put(
				"companyId",
				JadscApplicationInitiateInvestigation::getCompanyId);
			attributeGetterFunctions.put(
				"userId", JadscApplicationInitiateInvestigation::getUserId);
			attributeGetterFunctions.put(
				"userName", JadscApplicationInitiateInvestigation::getUserName);
			attributeGetterFunctions.put(
				"createDate",
				JadscApplicationInitiateInvestigation::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate",
				JadscApplicationInitiateInvestigation::getModifiedDate);
			attributeGetterFunctions.put(
				"dateOfIniInvest",
				JadscApplicationInitiateInvestigation::getDateOfIniInvest);
			attributeGetterFunctions.put(
				"outcome", JadscApplicationInitiateInvestigation::getOutcome);
			attributeGetterFunctions.put(
				"caseId", JadscApplicationInitiateInvestigation::getCaseId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<JadscApplicationInitiateInvestigation, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<JadscApplicationInitiateInvestigation, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String,
						 BiConsumer
							 <JadscApplicationInitiateInvestigation, ?>>();

			attributeSetterBiConsumers.put(
				"jadscAppliInvestiId",
				(BiConsumer<JadscApplicationInitiateInvestigation, Long>)
					JadscApplicationInitiateInvestigation::
						setJadscAppliInvestiId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<JadscApplicationInitiateInvestigation, Long>)
					JadscApplicationInitiateInvestigation::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<JadscApplicationInitiateInvestigation, Long>)
					JadscApplicationInitiateInvestigation::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<JadscApplicationInitiateInvestigation, Long>)
					JadscApplicationInitiateInvestigation::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<JadscApplicationInitiateInvestigation, String>)
					JadscApplicationInitiateInvestigation::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<JadscApplicationInitiateInvestigation, Date>)
					JadscApplicationInitiateInvestigation::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<JadscApplicationInitiateInvestigation, Date>)
					JadscApplicationInitiateInvestigation::setModifiedDate);
			attributeSetterBiConsumers.put(
				"dateOfIniInvest",
				(BiConsumer<JadscApplicationInitiateInvestigation, Date>)
					JadscApplicationInitiateInvestigation::setDateOfIniInvest);
			attributeSetterBiConsumers.put(
				"outcome",
				(BiConsumer<JadscApplicationInitiateInvestigation, String>)
					JadscApplicationInitiateInvestigation::setOutcome);
			attributeSetterBiConsumers.put(
				"caseId",
				(BiConsumer<JadscApplicationInitiateInvestigation, String>)
					JadscApplicationInitiateInvestigation::setCaseId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getJadscAppliInvestiId() {
		return _jadscAppliInvestiId;
	}

	@Override
	public void setJadscAppliInvestiId(long jadscAppliInvestiId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jadscAppliInvestiId = jadscAppliInvestiId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getDateOfIniInvest() {
		return _dateOfIniInvest;
	}

	@Override
	public void setDateOfIniInvest(Date dateOfIniInvest) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfIniInvest = dateOfIniInvest;
	}

	@JSON
	@Override
	public String getOutcome() {
		if (_outcome == null) {
			return "";
		}
		else {
			return _outcome;
		}
	}

	@Override
	public void setOutcome(String outcome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_outcome = outcome;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalOutcome() {
		return getColumnOriginalValue("outcome");
	}

	@JSON
	@Override
	public String getCaseId() {
		if (_caseId == null) {
			return "";
		}
		else {
			return _caseId;
		}
	}

	@Override
	public void setCaseId(String caseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_caseId = caseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCaseId() {
		return getColumnOriginalValue("caseId");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(),
			JadscApplicationInitiateInvestigation.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public JadscApplicationInitiateInvestigation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, JadscApplicationInitiateInvestigation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JadscApplicationInitiateInvestigationImpl
			jadscApplicationInitiateInvestigationImpl =
				new JadscApplicationInitiateInvestigationImpl();

		jadscApplicationInitiateInvestigationImpl.setJadscAppliInvestiId(
			getJadscAppliInvestiId());
		jadscApplicationInitiateInvestigationImpl.setGroupId(getGroupId());
		jadscApplicationInitiateInvestigationImpl.setCompanyId(getCompanyId());
		jadscApplicationInitiateInvestigationImpl.setUserId(getUserId());
		jadscApplicationInitiateInvestigationImpl.setUserName(getUserName());
		jadscApplicationInitiateInvestigationImpl.setCreateDate(
			getCreateDate());
		jadscApplicationInitiateInvestigationImpl.setModifiedDate(
			getModifiedDate());
		jadscApplicationInitiateInvestigationImpl.setDateOfIniInvest(
			getDateOfIniInvest());
		jadscApplicationInitiateInvestigationImpl.setOutcome(getOutcome());
		jadscApplicationInitiateInvestigationImpl.setCaseId(getCaseId());

		jadscApplicationInitiateInvestigationImpl.resetOriginalValues();

		return jadscApplicationInitiateInvestigationImpl;
	}

	@Override
	public JadscApplicationInitiateInvestigation cloneWithOriginalValues() {
		JadscApplicationInitiateInvestigationImpl
			jadscApplicationInitiateInvestigationImpl =
				new JadscApplicationInitiateInvestigationImpl();

		jadscApplicationInitiateInvestigationImpl.setJadscAppliInvestiId(
			this.<Long>getColumnOriginalValue("jadscAppliInvestiId"));
		jadscApplicationInitiateInvestigationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		jadscApplicationInitiateInvestigationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		jadscApplicationInitiateInvestigationImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		jadscApplicationInitiateInvestigationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		jadscApplicationInitiateInvestigationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		jadscApplicationInitiateInvestigationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		jadscApplicationInitiateInvestigationImpl.setDateOfIniInvest(
			this.<Date>getColumnOriginalValue("dateOfIniInvest"));
		jadscApplicationInitiateInvestigationImpl.setOutcome(
			this.<String>getColumnOriginalValue("outcome"));
		jadscApplicationInitiateInvestigationImpl.setCaseId(
			this.<String>getColumnOriginalValue("caseId"));

		return jadscApplicationInitiateInvestigationImpl;
	}

	@Override
	public int compareTo(
		JadscApplicationInitiateInvestigation
			jadscApplicationInitiateInvestigation) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(),
			jadscApplicationInitiateInvestigation.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof JadscApplicationInitiateInvestigation)) {
			return false;
		}

		JadscApplicationInitiateInvestigation
			jadscApplicationInitiateInvestigation =
				(JadscApplicationInitiateInvestigation)object;

		long primaryKey = jadscApplicationInitiateInvestigation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<JadscApplicationInitiateInvestigation> toCacheModel() {
		JadscApplicationInitiateInvestigationCacheModel
			jadscApplicationInitiateInvestigationCacheModel =
				new JadscApplicationInitiateInvestigationCacheModel();

		jadscApplicationInitiateInvestigationCacheModel.jadscAppliInvestiId =
			getJadscAppliInvestiId();

		jadscApplicationInitiateInvestigationCacheModel.groupId = getGroupId();

		jadscApplicationInitiateInvestigationCacheModel.companyId =
			getCompanyId();

		jadscApplicationInitiateInvestigationCacheModel.userId = getUserId();

		jadscApplicationInitiateInvestigationCacheModel.userName =
			getUserName();

		String userName =
			jadscApplicationInitiateInvestigationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			jadscApplicationInitiateInvestigationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			jadscApplicationInitiateInvestigationCacheModel.createDate =
				createDate.getTime();
		}
		else {
			jadscApplicationInitiateInvestigationCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			jadscApplicationInitiateInvestigationCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			jadscApplicationInitiateInvestigationCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		Date dateOfIniInvest = getDateOfIniInvest();

		if (dateOfIniInvest != null) {
			jadscApplicationInitiateInvestigationCacheModel.dateOfIniInvest =
				dateOfIniInvest.getTime();
		}
		else {
			jadscApplicationInitiateInvestigationCacheModel.dateOfIniInvest =
				Long.MIN_VALUE;
		}

		jadscApplicationInitiateInvestigationCacheModel.outcome = getOutcome();

		String outcome =
			jadscApplicationInitiateInvestigationCacheModel.outcome;

		if ((outcome != null) && (outcome.length() == 0)) {
			jadscApplicationInitiateInvestigationCacheModel.outcome = null;
		}

		jadscApplicationInitiateInvestigationCacheModel.caseId = getCaseId();

		String caseId = jadscApplicationInitiateInvestigationCacheModel.caseId;

		if ((caseId != null) && (caseId.length() == 0)) {
			jadscApplicationInitiateInvestigationCacheModel.caseId = null;
		}

		return jadscApplicationInitiateInvestigationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<JadscApplicationInitiateInvestigation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String,
				 Function<JadscApplicationInitiateInvestigation, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JadscApplicationInitiateInvestigation, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(JadscApplicationInitiateInvestigation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, JadscApplicationInitiateInvestigation>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						JadscApplicationInitiateInvestigation.class,
						ModelWrapper.class);

	}

	private long _jadscAppliInvestiId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _dateOfIniInvest;
	private String _outcome;
	private String _caseId;

	public <T> T getColumnValue(String columnName) {
		Function<JadscApplicationInitiateInvestigation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((JadscApplicationInitiateInvestigation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("jadscAppliInvestiId", _jadscAppliInvestiId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("dateOfIniInvest", _dateOfIniInvest);
		_columnOriginalValues.put("outcome", _outcome);
		_columnOriginalValues.put("caseId", _caseId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("jadscAppliInvestiId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("dateOfIniInvest", 128L);

		columnBitmasks.put("outcome", 256L);

		columnBitmasks.put("caseId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private JadscApplicationInitiateInvestigation _escapedModel;

}