create table nbp_pharma_app_payment (
	TourismApplicationPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentDocId VARCHAR(75) null,
	paymentStatus VARCHAR(75) null,
	paymentFee VARCHAR(75) null,
	transactionNumber VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_app_payment (
	TourismApplicationPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentDocId VARCHAR(75) null,
	paymentStatus VARCHAR(75) null,
	paymentFee VARCHAR(75) null,
	amountPaid VARCHAR(75) null,
	amountCurrency VARCHAR(75) null,
	transactionNumber VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_application (
	tourismApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	entityId VARCHAR(75) null,
	requestType VARCHAR(75) null,
	requestTypeTwo VARCHAR(75) null,
	licenseCategory VARCHAR(75) null,
	licenseSubCategory VARCHAR(75) null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	caseId VARCHAR(500) null,
	icmDocumentsPath VARCHAR(500) null,
	pdfFileEntryId LONG,
	appCurrentStageName VARCHAR(75) null
);

create table nbp_tourism_attr_empl (
	tourismBonaAttrEmpId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	actualPermanent VARCHAR(75) null,
	actualTemporary VARCHAR(75) null,
	actualForeign VARCHAR(75) null,
	actualLocal VARCHAR(75) null,
	actualPayroll VARCHAR(75) null,
	projectedPermanent VARCHAR(75) null,
	projectedTemporary VARCHAR(75) null,
	projectedForeign VARCHAR(75) null,
	projectedLocal VARCHAR(75) null,
	projectedPayroll VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_attrac_sign (
	tourismNewAttraSignInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	newSignApplicantName VARCHAR(75) null,
	newSignApplicantStatus VARCHAR(75) null,
	newSignDate DATE null,
	tourismApplicationId LONG
);

create table nbp_tourism_boma_acco_faoo (
	tourismBonaAccommodationFAOOId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addressType VARCHAR(75) null,
	bonaAccoAddress VARCHAR(500) null,
	bonaAccoTelephoneNumber VARCHAR(75) null,
	bonaAccoFaxNumber VARCHAR(75) null,
	bonaAccoEmail VARCHAR(75) null,
	tourismApplicationId LONG,
	tourismBonaAFId LONG
);

create table nbp_tourism_bona_acco_gen (
	tourismBonaAccoGenralInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	establishmentName VARCHAR(75) null,
	establishmentNewName VARCHAR(75) null,
	generalFacilityRoom VARCHAR(75) null,
	existingFacilityRoom VARCHAR(75) null,
	offeredFacilityDetail VARCHAR(75) null,
	plannedFacilityDetail VARCHAR(75) null,
	accomodationToBeOffered VARCHAR(75) null,
	constructionDate DATE null,
	expectedCommenceDate DATE null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_acco_sign (
	tourismBonaAccoSignId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	newSignApplicantName VARCHAR(75) null,
	newSignApplicantStatus VARCHAR(75) null,
	newSignDate DATE null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_aco_asses (
	tourismBonaAccoAssesmentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	countryOrigin VARCHAR(75) null,
	jointVenture VARCHAR(75) null,
	localPer VARCHAR(75) null,
	foreignPer VARCHAR(75) null,
	capitalInvest VARCHAR(75) null,
	sourceAttach VARCHAR(75) null,
	shareCapital VARCHAR(75) null,
	loanCapital VARCHAR(75) null,
	other VARCHAR(75) null,
	permanentLocalMale VARCHAR(75) null,
	permanentLocalFemale VARCHAR(75) null,
	permanentForeignMale VARCHAR(75) null,
	permanentForeignFemale VARCHAR(75) null,
	temporaryLocalMale VARCHAR(75) null,
	temporaryLocalFemale VARCHAR(75) null,
	temporaryForeignMale VARCHAR(75) null,
	temporaryForeignFemale VARCHAR(75) null,
	totalLocalMale VARCHAR(75) null,
	totalLocalFemale VARCHAR(75) null,
	totalForeignMale VARCHAR(75) null,
	totalForeignFemale VARCHAR(75) null,
	salaryWages VARCHAR(75) null,
	estimatedExpenditure VARCHAR(75) null,
	otherExpenditure VARCHAR(75) null,
	staffPermanentLocalMale VARCHAR(75) null,
	staffPermanentLocalFemale VARCHAR(75) null,
	staffForeignLocalMale VARCHAR(75) null,
	staffForeignLocalFemale VARCHAR(75) null,
	staffTemporaryLocalMale VARCHAR(75) null,
	staffTemporaryLocalFemale VARCHAR(75) null,
	staffTemporaryForeignMale VARCHAR(75) null,
	staffTemporaryForeignFemale VARCHAR(75) null,
	staffTotalForeignMale VARCHAR(75) null,
	staffTotalForeignFemale VARCHAR(75) null,
	staffTotalLocalMale VARCHAR(75) null,
	staffTotalLocalFemale VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_af (
	tourismBonaAFId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	bonaAccoDateOfApplication DATE null,
	bonaAccoTypeOfAccommodation VARCHAR(75) null,
	bonaAccoPurposeOfIncentives VARCHAR(75) null,
	bonaAccoOtherIncPurpose VARCHAR(75) null,
	bonaAccoNameOfProperty VARCHAR(75) null,
	bonaAccoNameOfOwner VARCHAR(75) null,
	bonaAccoLocation VARCHAR(75) null,
	bonaAccoCompanyNumber VARCHAR(75) null,
	bonaBusinessRegistrationNumber VARCHAR(75) null,
	bonaAccoDateOfRegistration DATE null,
	bonaAccoOwnerTrnNumber VARCHAR(75) null,
	bonaAccoTccNumber VARCHAR(75) null,
	bonaAccoExpiryDate DATE null,
	bonaAccoNameOfOperator VARCHAR(75) null,
	bonaAccoOperatorTrnNumber VARCHAR(75) null,
	bonaAccoOperatorTccNumber VARCHAR(75) null,
	bonaAccoOperatorExpiryDate DATE null,
	bonaAccoContactPerson VARCHAR(75) null,
	bonaAccoPositionHeld VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_attract_ffa (
	tourismBonaAttractionFFAOOId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addressType VARCHAR(75) null,
	bonaAttractAddress VARCHAR(500) null,
	bonaAttractionTelephoneNo VARCHAR(75) null,
	bonaAttractionFaxNumber VARCHAR(75) null,
	bonaAttractionEmail VARCHAR(75) null,
	tourismApplicationId LONG,
	tourismBonaAttractFormFirstId LONG
);

create table nbp_tourism_bona_attraction_ff (
	tourismBonaAttractFormFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	bonaAttractDateOfApplication DATE null,
	bonaTypeOfAttrcation VARCHAR(75) null,
	bonaAttractPurposeOfIncentives VARCHAR(75) null,
	bonaAttractOtherIncPurpose VARCHAR(75) null,
	bonaAttractionNameOfProperty VARCHAR(75) null,
	bonaAttractionNameOfOwner VARCHAR(75) null,
	bonaAttractionLocation VARCHAR(75) null,
	bonaAttractionCompanyNumber VARCHAR(75) null,
	bonaAttractionBusinessRegisNo VARCHAR(75) null,
	bonaAttractionDateOfRegis DATE null,
	bonaAttractionOwnerTrnNumber VARCHAR(75) null,
	bonaAttractionTccNumber VARCHAR(75) null,
	bonaAttractionExpiryDate DATE null,
	bonaAttractionNameOfOperator VARCHAR(75) null,
	bonaAttractionoperatorTrnNo VARCHAR(75) null,
	bonattractionOperatorTccNO VARCHAR(75) null,
	bonaAttractOperatorExpiryDate DATE null,
	bonaAttractContactPerson VARCHAR(75) null,
	bonaAttractPositionHeld VARCHAR(75) null,
	bonaAttractEntityId VARCHAR(75) null,
	bonaAttractionBriefdescription VARCHAR(500) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_attraction_fs (
	tourismBonaAttractFormSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	bonaTargetMarketLocal VARCHAR(75) null,
	bonaTargetMarketForeign VARCHAR(75) null,
	bonaTargetMarketCountries VARCHAR(75) null,
	bonaOwnerCountryOfOrigin VARCHAR(75) null,
	bonaOwnerJointVenture VARCHAR(75) null,
	bonaOwnerLocal VARCHAR(75) null,
	bonaOwnerForeign VARCHAR(75) null,
	bonaCapitalUSComponent VARCHAR(75) null,
	bonaCapitalizationJEquivalent VARCHAR(75) null,
	bonaCapitalRateOfExchange VARCHAR(75) null,
	bonaCapitalizationJComponent VARCHAR(75) null,
	bonaCapitalCapitalInvest VARCHAR(75) null,
	bonaSourcesLoan  VARCHAR(75) null,
	bonaSourcesEquity VARCHAR(75) null,
	bonaSourcesStateOfLoanFinanc VARCHAR(75) null,
	bonaAnnualProjectedYearOne  VARCHAR(75) null,
	bonaAnnualProjectedYearTwo VARCHAR(75) null,
	bonaAnnualProjectedYearThree  VARCHAR(75) null,
	bonaAnnualProjectedNumber VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_gro_pay (
	tourismBonaGroundPayId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentOtherMethod VARCHAR(75) null,
	paymentProof VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_gro_sign (
	tourismBonaGroundSignInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	carApplicantName VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_gro_tcsign (
	tourismBonaGroTraCoSignId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	contractType VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_gro_tranpay (
	tourismBonaGroTransPayId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	contractType VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_ground_box (
	tourismVehicleBoxBonaId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	vehicleMakeBona VARCHAR(75) null,
	vehiclemodelBona VARCHAR(75) null,
	vehicleYearBona VARCHAR(75) null,
	vehicleCounter VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_ground_t (
	tourismBonaGroundTransportId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	typeOfGroundTransportation VARCHAR(75) null,
	bonaGroundName VARCHAR(75) null,
	bonaGroundLandlineNo VARCHAR(75) null,
	bonaGroundMobileNo VARCHAR(75) null,
	bonaGroundFaxNo VARCHAR(75) null,
	bonaGroundLicensedWith VARCHAR(75) null,
	bonaGroundBoardExpiryDate DATE null,
	bonaGroundHaveYouBenefitBefore VARCHAR(75) null,
	bonaGroundDateOfLastBenefit DATE null,
	bonaGroundEntityType VARCHAR(75) null,
	bonaGroundVehicleInfoMake VARCHAR(75) null,
	bonaGroundVehicleInfoModel VARCHAR(75) null,
	bonaGroundVehicleInfoYear VARCHAR(75) null,
	bonaGroundSeatingCapacity VARCHAR(75) null,
	bonaGroundExistingFleetAmount VARCHAR(75) null,
	bonaGroundIndicateVehicleWill VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_ground_ta (
	tourismBonaGroundTransAddresId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addressType VARCHAR(500) null,
	bonaGroundAddress VARCHAR(500) null,
	tourismApplicationId LONG,
	tourismBonaGroundTransportId LONG
);

create table nbp_tourism_bona_ground_tcr (
	tourismBonaGroundTransportCRId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	TypeOfGroundTransportation VARCHAR(75) null,
	bonaGroundDateOfApplication DATE null,
	bonaGroundNameOfCompany VARCHAR(75) null,
	bonaGroundTradingName VARCHAR(75) null,
	bonaGroundCompanyRegisNo VARCHAR(75) null,
	bonaGroundTelephonNo VARCHAR(75) null,
	bonaGroundAddress VARCHAR(500) null,
	bonaGroundEmailAddress VARCHAR(75) null,
	bonaGroundContactPerson VARCHAR(75) null,
	bonaGroundEntityType VARCHAR(75) null,
	bonaGroundTccNo VARCHAR(75) null,
	bonaGroundExpiryDate DATE null,
	bonaGroundCopyAttached VARCHAR(75) null,
	bonaGroundJtbLicense VARCHAR(75) null,
	bonaGroundExpiryDateTwo DATE null,
	bonaGroundCopyAttachedTwo VARCHAR(75) null,
	bonaGroundTrnNo  VARCHAR(75) null,
	bonaGroundYearInBusiness VARCHAR(75) null,
	bonaGroundCopyOfRegAttached  VARCHAR(75) null,
	bonaGroundExistingFleetAmount VARCHAR(75) null,
	bonaGroundTotalVehicles VARCHAR(75) null,
	bonaGroundHowAdditionToFleet VARCHAR(75) null,
	bonaGroundReplacement VARCHAR(75) null,
	bonaGroundSummaryDealer VARCHAR(75) null,
	bonaGroundSummaryNumOfVechicle VARCHAR(75) null,
	bonaGroundSummarYear VARCHAR(75) null,
	bonaGroundSummaryType VARCHAR(75) null,
	bonaGroundSummaryCCRating VARCHAR(75) null,
	bonaGroundSummaryCommentary VARCHAR(75) null,
	bonaGroundDescription VARCHAR(500) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_operator_info (
	tourismBonaOperatorInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	operatorName VARCHAR(75) null,
	operatorNumber VARCHAR(75) null,
	issueDate DATE null,
	expirationDate DATE null,
	categories VARCHAR(75) null,
	subCategories VARCHAR(500) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_water_emp (
	tourismBonaWSEmplId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	actualPermanent VARCHAR(75) null,
	actualTemporary VARCHAR(75) null,
	actualForeign VARCHAR(75) null,
	actualLocal VARCHAR(75) null,
	actualPayroll VARCHAR(75) null,
	projectedPermanent VARCHAR(75) null,
	projectedTemporary VARCHAR(75) null,
	projectedForeign VARCHAR(75) null,
	projectedLocal VARCHAR(75) null,
	projectedPayroll VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_water_sff (
	tourismBonaWaterSFFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	bonaWaterTypeOfAttract VARCHAR(75) null,
	bonaWaterPurposeOfIncentives VARCHAR(75) null,
	bonaWaterOtherIncPurpose VARCHAR(75) null,
	bonaNameOfWatersportsEntity VARCHAR(75) null,
	bonaWaterNameOfOwnerCompany VARCHAR(75) null,
	bonaWaterLocation VARCHAR(500) null,
	bonaWaterCompanyNo VARCHAR(75) null,
	bonaWaterBusinessRegisNo VARCHAR(75) null,
	bonaWaterDateOfRegistration DATE null,
	bonaWaterOwnerTrnNo VARCHAR(75) null,
	bonaWaterTccNo VARCHAR(75) null,
	bonaWaterExpiryDate VARCHAR(75) null,
	bonaWaterNameOfOperator VARCHAR(75) null,
	bonaWaterOperatorTrnNo VARCHAR(75) null,
	bonaWaterOperatorTccNo VARCHAR(75) null,
	bonaWaterOperatorExpiryDate DATE null,
	bonaWaterContactPerson VARCHAR(75) null,
	bonaWaterPositionHeld VARCHAR(75) null,
	bonaWaterbriefdescription VARCHAR(500) null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_water_sffa (
	tourismBonaWaterSportsFFAId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addressType VARCHAR(75) null,
	bonaWaterAddress VARCHAR(500) null,
	bonaWaterTeleNo VARCHAR(75) null,
	bonaWaterFaxNo VARCHAR(75) null,
	bonaWaterEmail VARCHAR(75) null,
	tourismApplicationId LONG,
	tourismBonaWaterSFFirstId LONG
);

create table nbp_tourism_bona_water_sign (
	tourismBonaWSSignId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicantName VARCHAR(75) null,
	signApplicantStatus VARCHAR(75) null,
	signDate DATE null,
	tourismApplicationId LONG
);

create table nbp_tourism_bona_water_ssf (
	tourismBonaWaterSportsFSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	bonaTargetMarketLocal VARCHAR(75) null,
	bonaTargetMarketForeign VARCHAR(75) null,
	bonaTargetMarketCountries VARCHAR(75) null,
	bonaOwnerCountryOfOrigin VARCHAR(75) null,
	bonaOwnerJointVenture VARCHAR(75) null,
	bonaOwnerLocal VARCHAR(75) null,
	bonaOwnerForeign VARCHAR(75) null,
	bonaCapitalizationUSComponent VARCHAR(75) null,
	bonaCapitalizationJEquivalent VARCHAR(75) null,
	bonaCapitalizationRateExchange VARCHAR(75) null,
	bonaCapitalizationJComponent VARCHAR(75) null,
	bonaCapitalCapitalInvest VARCHAR(75) null,
	bonaSourcesLoan  VARCHAR(75) null,
	bonaSourcesEquity VARCHAR(75) null,
	bonaSourcesStateOfFinanc VARCHAR(75) null,
	bonaAnnualProjectedOne  VARCHAR(75) null,
	bonaAnnualProjectedTwo VARCHAR(75) null,
	bonaAnnualProjectedThree  VARCHAR(75) null,
	bonaAnnualProjectedNumber VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_enter_box_add (
	tourismAnnualEntertainBoxId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	service VARCHAR(75) null,
	local VARCHAR(75) null,
	foreign_ VARCHAR(75) null,
	enterCounter VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_accco_aoo (
	tourismNewAccommodationAOOId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addressType VARCHAR(75) null,
	accoAddress VARCHAR(500) null,
	accoTelephoneNumber VARCHAR(75) null,
	accoFaxNumber VARCHAR(75) null,
	accoEmail VARCHAR(75) null,
	tourismApplicationId LONG,
	tourismNewAccoFormId LONG
);

create table nbp_tourism_new_acco_annual (
	tourismNewAnnualEarningsId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	yearOne VARCHAR(75) null,
	yearTwo VARCHAR(75) null,
	yearThree VARCHAR(75) null,
	targetLocalPer VARCHAR(75) null,
	targetForeignPer VARCHAR(75) null,
	targetCountries VARCHAR(75) null,
	estimatedPer VARCHAR(75) null,
	volume VARCHAR(75) null,
	expenditure VARCHAR(75) null,
	manufactureEstimatedPer VARCHAR(75) null,
	manufactureVolume VARCHAR(75) null,
	manufactureExpenditure VARCHAR(75) null,
	seafoodPer VARCHAR(75) null,
	seafoodVolume VARCHAR(75) null,
	seafoodExpenditure VARCHAR(75) null,
	enterServices VARCHAR(75) null,
	enterLocal VARCHAR(75) null,
	enterForeign VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_acco_assesm (
	TourismNewAccoAssesmentInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	countryOrigin VARCHAR(75) null,
	jointVenture VARCHAR(75) null,
	localPer VARCHAR(75) null,
	foreignPer VARCHAR(75) null,
	capitalInvest VARCHAR(75) null,
	sourceAttach VARCHAR(75) null,
	shareCapital VARCHAR(75) null,
	loanCapital VARCHAR(75) null,
	other VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_acco_assesment (
	TourismNewAccoAssesmentInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	countryOrigin VARCHAR(75) null,
	jointVenture VARCHAR(75) null,
	localPer VARCHAR(75) null,
	foreignPer VARCHAR(75) null,
	capitalInvest VARCHAR(75) null,
	sourceAttach VARCHAR(75) null,
	shareCapital VARCHAR(75) null,
	loanCapital VARCHAR(75) null,
	other VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_acco_employe (
	tourismNewNumberOFEmploymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	permanentLocalMale VARCHAR(75) null,
	permanentLocalFemale VARCHAR(75) null,
	permanentForeignMale VARCHAR(75) null,
	permanentForeignFemale VARCHAR(75) null,
	temporaryLocalMale VARCHAR(75) null,
	temporaryLocalFemale VARCHAR(75) null,
	temporaryForeignMale VARCHAR(75) null,
	temporaryForeignFemale VARCHAR(75) null,
	totalLocalMale VARCHAR(75) null,
	totalLocalFemale VARCHAR(75) null,
	totalForeignMale VARCHAR(75) null,
	totalForeignFemale VARCHAR(75) null,
	salaryWages VARCHAR(75) null,
	estimatedExpenditure VARCHAR(75) null,
	otherExpenditure VARCHAR(75) null,
	perRoomInclusiveCost VARCHAR(75) null,
	perRoomExclusiveCost VARCHAR(75) null,
	staffPermanentLocalMale VARCHAR(75) null,
	staffPermanentLocalFemale VARCHAR(75) null,
	staffPermanentForeignMale VARCHAR(75) null,
	staffPermanentForeignFemale VARCHAR(75) null,
	staffTemporaryLocalMale VARCHAR(75) null,
	staffTemporaryLocalFemale VARCHAR(75) null,
	staffTemporaryForeignMale VARCHAR(75) null,
	staffTemporaryForeignFemale VARCHAR(75) null,
	staffTotalLocalMale VARCHAR(75) null,
	staffTotalLocalFemale VARCHAR(75) null,
	staffTotalForeignMale VARCHAR(75) null,
	staffTotalForeignFemale VARCHAR(75) null,
	salariesAndWages VARCHAR(75) null,
	expectedAnnualFunds VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_acco_gerner (
	tourismNewAccoGenFormId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	establishmentName VARCHAR(75) null,
	accomadationRoom VARCHAR(75) null,
	facilityDetail VARCHAR(75) null,
	hotelOperator VARCHAR(75) null,
	offeredAccomadation VARCHAR(75) null,
	constructionDate DATE null,
	commenceDate DATE null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_acco_gerneral (
	tourismNewAccoGenFormId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	establishmentName VARCHAR(75) null,
	accomadationRoom VARCHAR(75) null,
	facilityDetail VARCHAR(75) null,
	hotelOperator VARCHAR(75) null,
	offeredAccomadation VARCHAR(75) null,
	constructionDate DATE null,
	commenceDate DATE null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_acco_signinfo (
	tourismNewAccoSignInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	signApplicantName VARCHAR(75) null,
	signApplicantStatus VARCHAR(75) null,
	newSignDate DATE null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_accommodation (
	tourismNewAccoFormId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	accoDateOfApplication DATE null,
	accoTypeOfAccommodation VARCHAR(75) null,
	accoNameOfProperty VARCHAR(75) null,
	accoNameOfOwner VARCHAR(75) null,
	accoLocation VARCHAR(500) null,
	accoCompanyNumber VARCHAR(75) null,
	accoBusinessRegistrationNumber VARCHAR(75) null,
	accoDateOfRegistration DATE null,
	accoOwnerTrnNumber VARCHAR(75) null,
	accoTccNumber VARCHAR(75) null,
	accoExpiryDate DATE null,
	accoNameOfOperator VARCHAR(75) null,
	accoOperatorTrnNumber VARCHAR(75) null,
	accoOperatorTccNumber VARCHAR(75) null,
	accoOperatorExpiryDate DATE null,
	accoContactPerson VARCHAR(75) null,
	accoPositionHeld VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_attrac_emp (
	tourismNewAttractionEmploId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	actualPermanent VARCHAR(75) null,
	actualTemporary VARCHAR(75) null,
	actualForeign VARCHAR(75) null,
	actualLocal VARCHAR(75) null,
	actualPayroll VARCHAR(75) null,
	projectedPermanent VARCHAR(75) null,
	projectedTemporary VARCHAR(75) null,
	projectedForeign VARCHAR(75) null,
	projectedLocal VARCHAR(75) null,
	projectedPayroll VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_attract_ffaoo (
	tourismNewAttractionFormFAOOId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addressType VARCHAR(75) null,
	attractionAddress VARCHAR(500) null,
	attractionTelephoneNumber VARCHAR(75) null,
	attractionFaxNumber VARCHAR(75) null,
	attractionEmail VARCHAR(75) null,
	tourismApplicationId LONG,
	tourismNewAttractFormFirstId LONG
);

create table nbp_tourism_new_attraction_ff (
	tourismNewAttractFormFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	attractionDateOfApplication DATE null,
	typeOfAttrcation VARCHAR(75) null,
	attractionNameOfProperty VARCHAR(75) null,
	attractionNameOfOwner VARCHAR(75) null,
	attractionLocation VARCHAR(500) null,
	attractionCompanyNumber VARCHAR(75) null,
	attractionBusinessRegisNo VARCHAR(75) null,
	attractionDateOfRegistration DATE null,
	attractionOwnerTrnNumber VARCHAR(75) null,
	attractionTccNumber VARCHAR(75) null,
	attractionExpiryDate DATE null,
	attractionNameOfOperator VARCHAR(75) null,
	attractionoperatorTrnNumber VARCHAR(75) null,
	attractionOperatorTccNumber VARCHAR(75) null,
	attractOperatorExpiryDate DATE null,
	attractionContactPerson VARCHAR(75) null,
	attractionPositionHeld VARCHAR(75) null,
	attractionEntityId VARCHAR(75) null,
	attractionBriefdescription VARCHAR(500) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_attraction_fs (
	tourismNewAttractionFormSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	targetMarketLocal VARCHAR(75) null,
	targetMarketForeign VARCHAR(75) null,
	targetMarketCountries VARCHAR(75) null,
	ownerCountryOfOrigin VARCHAR(75) null,
	ownerJointVenture VARCHAR(75) null,
	ownerLocal VARCHAR(75) null,
	ownerForeign VARCHAR(75) null,
	capitalizationUSComponent VARCHAR(75) null,
	capitalizationJEquivalent VARCHAR(75) null,
	capitalizationRateOfExchange VARCHAR(75) null,
	capitalizationJComponent VARCHAR(75) null,
	capitalizationCapitalInvest VARCHAR(75) null,
	sourcesLoan  VARCHAR(75) null,
	sourcesEquity VARCHAR(75) null,
	sourcesStateSourceOfLoanFinanc VARCHAR(75) null,
	annualProjectedOne  VARCHAR(75) null,
	annualProjectedTwo VARCHAR(75) null,
	annualProjectedThree  VARCHAR(75) null,
	annualProjectedNumber VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_ground_box (
	tourismVehicleBoxId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	vehicleMake VARCHAR(75) null,
	vehiclemodel VARCHAR(75) null,
	vehicleYear VARCHAR(75) null,
	vehicleCounter VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_ground_sign (
	TourismNewGroundSignatureId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	groundTransportationDate DATE null,
	tourismApplicationId LONG
);

create table nbp_tourism_new_ground_tarns (
	TourismNewGroundTransId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	typeOfGroundTransportation VARCHAR(75) null,
	newGroundName VARCHAR(75) null,
	newGroundHomeAddress VARCHAR(500) null,
	newGroundBusinessAddress VARCHAR(500) null,
	newGroundLandlineNo VARCHAR(75) null,
	newGroundMobileNo VARCHAR(75) null,
	newGroundFaxNo VARCHAR(75) null,
	newGroundLicensedWith VARCHAR(75) null,
	newGroundBoardExpiryDate DATE null,
	newGroundHaveYouBenefitBefore VARCHAR(75) null,
	newGroundHaveBenefitDate DATE null,
	newGroundEntityType VARCHAR(75) null,
	newGroundVehicleInfoMake VARCHAR(75) null,
	newGroundVehicleInfoModel VARCHAR(75) null,
	newGroundVehicleInfoYear VARCHAR(75) null,
	newGroundSeatingCapacity VARCHAR(75) null,
	newGroundExistingFleetAmount VARCHAR(75) null,
	newGroundIndicateVehicleWill VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_stage (
	tourismAppliCurrentStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormStep VARCHAR(75) null,
	tourismApplicationId LONG
);

create table nbp_tourism_summary_box (
	tourismSummaryBoxId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	dealer VARCHAR(75) null,
	numberOfvehicles VARCHAR(75) null,
	year VARCHAR(75) null,
	type_ VARCHAR(75) null,
	ccRating VARCHAR(75) null,
	counterSummary VARCHAR(75) null,
	tourismApplicationId LONG
);