/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.cannabis.application.form.services.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.cannabis.application.form.services.model.CannabisConsentBySoleOwner;
import com.nbp.cannabis.application.form.services.service.CannabisConsentBySoleOwnerLocalService;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisApplicationCompanyAddressPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisApplicationCompanyAuthorizedAgentPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisApplicationCompanyInfoPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisApplicationCurrentStagePersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisApplicationIndividualAddressPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisApplicationIndividualInfoPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisApplicationPaymentPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisApplicationsPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisConsentByPropertyOwnerPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisConsentBySoleOwnerPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisDeclarationOfOwnershipPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisFeeMasterPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisOccupationaLicensePersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisSupplementalInformationPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.CannabisSupportingDocumentsMasterPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.GeneralDelarationsPersistence;
import com.nbp.cannabis.application.form.services.service.persistence.StatementOfFinancialHistoryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cannabis consent by sole owner local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.cannabis.application.form.services.service.impl.CannabisConsentBySoleOwnerLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.cannabis.application.form.services.service.impl.CannabisConsentBySoleOwnerLocalServiceImpl
 * @generated
 */
public abstract class CannabisConsentBySoleOwnerLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CannabisConsentBySoleOwnerLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CannabisConsentBySoleOwnerLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.cannabis.application.form.services.service.CannabisConsentBySoleOwnerLocalServiceUtil</code>.
	 */

	/**
	 * Adds the cannabis consent by sole owner to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CannabisConsentBySoleOwnerLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cannabisConsentBySoleOwner the cannabis consent by sole owner
	 * @return the cannabis consent by sole owner that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CannabisConsentBySoleOwner addCannabisConsentBySoleOwner(
		CannabisConsentBySoleOwner cannabisConsentBySoleOwner) {

		cannabisConsentBySoleOwner.setNew(true);

		return cannabisConsentBySoleOwnerPersistence.update(
			cannabisConsentBySoleOwner);
	}

	/**
	 * Creates a new cannabis consent by sole owner with the primary key. Does not add the cannabis consent by sole owner to the database.
	 *
	 * @param cannabisConsentBySoleOwnerId the primary key for the new cannabis consent by sole owner
	 * @return the new cannabis consent by sole owner
	 */
	@Override
	@Transactional(enabled = false)
	public CannabisConsentBySoleOwner createCannabisConsentBySoleOwner(
		long cannabisConsentBySoleOwnerId) {

		return cannabisConsentBySoleOwnerPersistence.create(
			cannabisConsentBySoleOwnerId);
	}

	/**
	 * Deletes the cannabis consent by sole owner with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CannabisConsentBySoleOwnerLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cannabisConsentBySoleOwnerId the primary key of the cannabis consent by sole owner
	 * @return the cannabis consent by sole owner that was removed
	 * @throws PortalException if a cannabis consent by sole owner with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CannabisConsentBySoleOwner deleteCannabisConsentBySoleOwner(
			long cannabisConsentBySoleOwnerId)
		throws PortalException {

		return cannabisConsentBySoleOwnerPersistence.remove(
			cannabisConsentBySoleOwnerId);
	}

	/**
	 * Deletes the cannabis consent by sole owner from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CannabisConsentBySoleOwnerLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cannabisConsentBySoleOwner the cannabis consent by sole owner
	 * @return the cannabis consent by sole owner that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CannabisConsentBySoleOwner deleteCannabisConsentBySoleOwner(
		CannabisConsentBySoleOwner cannabisConsentBySoleOwner) {

		return cannabisConsentBySoleOwnerPersistence.remove(
			cannabisConsentBySoleOwner);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return cannabisConsentBySoleOwnerPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CannabisConsentBySoleOwner.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return cannabisConsentBySoleOwnerPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.cannabis.application.form.services.model.impl.CannabisConsentBySoleOwnerModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return cannabisConsentBySoleOwnerPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.cannabis.application.form.services.model.impl.CannabisConsentBySoleOwnerModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return cannabisConsentBySoleOwnerPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return cannabisConsentBySoleOwnerPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return cannabisConsentBySoleOwnerPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CannabisConsentBySoleOwner fetchCannabisConsentBySoleOwner(
		long cannabisConsentBySoleOwnerId) {

		return cannabisConsentBySoleOwnerPersistence.fetchByPrimaryKey(
			cannabisConsentBySoleOwnerId);
	}

	/**
	 * Returns the cannabis consent by sole owner with the primary key.
	 *
	 * @param cannabisConsentBySoleOwnerId the primary key of the cannabis consent by sole owner
	 * @return the cannabis consent by sole owner
	 * @throws PortalException if a cannabis consent by sole owner with the primary key could not be found
	 */
	@Override
	public CannabisConsentBySoleOwner getCannabisConsentBySoleOwner(
			long cannabisConsentBySoleOwnerId)
		throws PortalException {

		return cannabisConsentBySoleOwnerPersistence.findByPrimaryKey(
			cannabisConsentBySoleOwnerId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			cannabisConsentBySoleOwnerLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CannabisConsentBySoleOwner.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"cannabisConsentBySoleOwnerId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			cannabisConsentBySoleOwnerLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CannabisConsentBySoleOwner.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"cannabisConsentBySoleOwnerId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			cannabisConsentBySoleOwnerLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CannabisConsentBySoleOwner.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"cannabisConsentBySoleOwnerId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cannabisConsentBySoleOwnerPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CannabisConsentBySoleOwnerLocalServiceImpl#deleteCannabisConsentBySoleOwner(CannabisConsentBySoleOwner) to avoid orphaned data");
		}

		return cannabisConsentBySoleOwnerLocalService.
			deleteCannabisConsentBySoleOwner(
				(CannabisConsentBySoleOwner)persistedModel);
	}

	@Override
	public BasePersistence<CannabisConsentBySoleOwner> getBasePersistence() {
		return cannabisConsentBySoleOwnerPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cannabisConsentBySoleOwnerPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the cannabis consent by sole owners.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.cannabis.application.form.services.model.impl.CannabisConsentBySoleOwnerModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of cannabis consent by sole owners
	 * @param end the upper bound of the range of cannabis consent by sole owners (not inclusive)
	 * @return the range of cannabis consent by sole owners
	 */
	@Override
	public List<CannabisConsentBySoleOwner> getCannabisConsentBySoleOwners(
		int start, int end) {

		return cannabisConsentBySoleOwnerPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cannabis consent by sole owners.
	 *
	 * @return the number of cannabis consent by sole owners
	 */
	@Override
	public int getCannabisConsentBySoleOwnersCount() {
		return cannabisConsentBySoleOwnerPersistence.countAll();
	}

	/**
	 * Updates the cannabis consent by sole owner in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CannabisConsentBySoleOwnerLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cannabisConsentBySoleOwner the cannabis consent by sole owner
	 * @return the cannabis consent by sole owner that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CannabisConsentBySoleOwner updateCannabisConsentBySoleOwner(
		CannabisConsentBySoleOwner cannabisConsentBySoleOwner) {

		return cannabisConsentBySoleOwnerPersistence.update(
			cannabisConsentBySoleOwner);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CannabisConsentBySoleOwnerLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		cannabisConsentBySoleOwnerLocalService =
			(CannabisConsentBySoleOwnerLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CannabisConsentBySoleOwnerLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CannabisConsentBySoleOwner.class;
	}

	protected String getModelClassName() {
		return CannabisConsentBySoleOwner.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				cannabisConsentBySoleOwnerPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected CannabisApplicationCompanyAddressPersistence
		cannabisApplicationCompanyAddressPersistence;

	@Reference
	protected CannabisApplicationCompanyAuthorizedAgentPersistence
		cannabisApplicationCompanyAuthorizedAgentPersistence;

	@Reference
	protected CannabisApplicationCompanyInfoPersistence
		cannabisApplicationCompanyInfoPersistence;

	@Reference
	protected CannabisApplicationCurrentStagePersistence
		cannabisApplicationCurrentStagePersistence;

	@Reference
	protected CannabisApplicationIndividualAddressPersistence
		cannabisApplicationIndividualAddressPersistence;

	@Reference
	protected CannabisApplicationIndividualInfoPersistence
		cannabisApplicationIndividualInfoPersistence;

	@Reference
	protected CannabisApplicationPaymentPersistence
		cannabisApplicationPaymentPersistence;

	@Reference
	protected CannabisApplicationsPersistence cannabisApplicationsPersistence;

	@Reference
	protected CannabisConsentByPropertyOwnerPersistence
		cannabisConsentByPropertyOwnerPersistence;

	protected CannabisConsentBySoleOwnerLocalService
		cannabisConsentBySoleOwnerLocalService;

	@Reference
	protected CannabisConsentBySoleOwnerPersistence
		cannabisConsentBySoleOwnerPersistence;

	@Reference
	protected CannabisDeclarationOfOwnershipPersistence
		cannabisDeclarationOfOwnershipPersistence;

	@Reference
	protected CannabisFeeMasterPersistence cannabisFeeMasterPersistence;

	@Reference
	protected CannabisOccupationaLicensePersistence
		cannabisOccupationaLicensePersistence;

	@Reference
	protected CannabisSupplementalInformationPersistence
		cannabisSupplementalInformationPersistence;

	@Reference
	protected CannabisSupportingDocumentsMasterPersistence
		cannabisSupportingDocumentsMasterPersistence;

	@Reference
	protected GeneralDelarationsPersistence generalDelarationsPersistence;

	@Reference
	protected StatementOfFinancialHistoryPersistence
		statementOfFinancialHistoryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CannabisConsentBySoleOwnerLocalServiceBaseImpl.class);

}