create table nbp_ncbj_additional_loc (
	ncbjAddLocMultiSiteId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	signatureName VARCHAR(75) null,
	centralOfficeLink VARCHAR(75) null,
	commonManagementSystem VARCHAR(75) null,
	substantiallySameProcess VARCHAR(75) null,
	siteSimilarMethod VARCHAR(75) null,
	siteUnderAudit VARCHAR(75) null,
	siteCorrectiveRight VARCHAR(75) null,
	changesAuthority VARCHAR(75) null,
	position VARCHAR(75) null,
	date_ DATE null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_app_payment (
	ncbjAppPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentDocId VARCHAR(75) null,
	paymentStatus VARCHAR(75) null,
	paymentFee VARCHAR(75) null,
	amountPaid VARCHAR(75) null,
	amountCurrency VARCHAR(75) null,
	transactionNumber VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_applicant_detail (
	ncbjApplicantDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	stageOne DATE null,
	stageTwo DATE null,
	surveillanceAudit DATE null,
	recertificationAudit DATE null,
	preAassessmentAudit DATE null,
	anyOtherService  DATE null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_application (
	uuid_ VARCHAR(75) null,
	ncbjApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	typeOfCertification VARCHAR(500) null,
	typeOfTransaction VARCHAR(75) null,
	typeOfServices VARCHAR(75) null,
	subCategoryServices VARCHAR(75) null,
	iso9001CertificationValue VARCHAR(500) null,
	numberOfSite VARCHAR(75) null,
	iso22000CertificationValue TEXT null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	transferReason VARCHAR(75) null,
	expiredLicenseAppNumber VARCHAR(75) null,
	caseId VARCHAR(500) null,
	icmDocumentsPath VARCHAR(500) null,
	pdfFileEntryId LONG,
	dateOfExpiration DATE null,
	appCurrentStageName VARCHAR(75) null
);

create table nbp_ncbj_business_detail (
	ncbjBusinessDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	counter VARCHAR(75) null,
	quotationAddressOne VARCHAR(75) null,
	quotationProductTypes VARCHAR(75) null,
	quotationApplicantShifts VARCHAR(75) null,
	quotationEmpNum VARCHAR(75) null,
	quotationHeadOffices VARCHAR(75) null,
	quotationFullTimeEmploy VARCHAR(75) null,
	quotationPartTimeEmploy VARCHAR(75) null,
	quotationContractors VARCHAR(75) null,
	quotationContractedWorker VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_business_detail_add (
	ncbjBusinessDetailAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	numberAndTimeOfShift VARCHAR(75) null,
	typeOfProduct VARCHAR(75) null,
	businessAddress VARCHAR(500) null,
	headOffices VARCHAR(75) null,
	noOfFullTimeEmployees VARCHAR(75) null,
	noOfPartTimeEmployees VARCHAR(75) null,
	noOfContractors VARCHAR(75) null,
	noOfContractedWorkers VARCHAR(75) null,
	counter VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_company_det_gen (
	ncbjCompanyDetailGenId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyName VARCHAR(75) null,
	companyAddress VARCHAR(500) null,
	headOfCompany VARCHAR(75) null,
	jobTitleOne VARCHAR(75) null,
	companyEmailOne VARCHAR(75) null,
	companyNumOne VARCHAR(75) null,
	contactName VARCHAR(75) null,
	jobTitleTwo VARCHAR(75) null,
	companyEmailTwo VARCHAR(75) null,
	companyNumTwo VARCHAR(75) null,
	counter VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_company_detail (
	ncbjCompanyDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyNameOrHeadOffice VARCHAR(75) null,
	companyAddress VARCHAR(500) null,
	stageOne DATE null,
	stageTwo DATE null,
	surveillanceAudit DATE null,
	recertificationAudit DATE null,
	preAassessmentAudit DATE null,
	anyOtherService  DATE null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_company_detail_add (
	ncbjCompanyDetailAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	headOfCompanyName VARCHAR(75) null,
	companyAddr VARCHAR(75) null,
	jobTitle VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	telephoneNumber VARCHAR(75) null,
	contactName VARCHAR(75) null,
	contactNameJobTitle VARCHAR(75) null,
	contactNameEmailAddress VARCHAR(75) null,
	contactNameTelephoneNum VARCHAR(75) null,
	counter VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_current_stage (
	uuid_ VARCHAR(75) null,
	ncbjCurrentStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormStep VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_new_company (
	nCBJCompanyNewId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyName VARCHAR(75) null,
	companyAddress VARCHAR(75) null,
	headOfCompany VARCHAR(75) null,
	jobTitleOne VARCHAR(75) null,
	companyEmailOne VARCHAR(75) null,
	companyNumOne VARCHAR(75) null,
	contactName VARCHAR(75) null,
	jobTitleTwo VARCHAR(75) null,
	companyEmailTwo VARCHAR(75) null,
	companyNumTwo VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_num_of_emp (
	ncbjNumOfEmpAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	headOffice VARCHAR(75) null,
	administrationOffice VARCHAR(75) null,
	productionProcessing VARCHAR(75) null,
	maintenanceService VARCHAR(75) null,
	logistics VARCHAR(75) null,
	total VARCHAR(75) null,
	seasonal VARCHAR(75) null,
	temporary VARCHAR(75) null,
	subcontracted VARCHAR(75) null,
	counter VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_number_effective_add (
	ncbjNumberEffectiveAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	numberOfFullTimeEmployees VARCHAR(75) null,
	numberOfPartTimeEmployees VARCHAR(75) null,
	department VARCHAR(75) null,
	numberOfcontractors VARCHAR(75) null,
	numberOfContractedWorkers VARCHAR(75) null,
	counter VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_org_detail (
	ncbjOrgDetailInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	newCompanyName VARCHAR(75) null,
	companyEmail VARCHAR(75) null,
	mailingAddress VARCHAR(500) null,
	city VARCHAR(75) null,
	postalCode VARCHAR(75) null,
	country VARCHAR(75) null,
	physicalAddress VARCHAR(75) null,
	physicalCity VARCHAR(75) null,
	physicalPostalCode VARCHAR(75) null,
	physicalCountry VARCHAR(75) null,
	companyHead VARCHAR(75) null,
	companyTitle VARCHAR(75) null,
	companyContact VARCHAR(75) null,
	companyContactTitle VARCHAR(75) null,
	companyTelephone VARCHAR(75) null,
	companyFax VARCHAR(75) null,
	companyWebsite VARCHAR(75) null,
	certificationScope VARCHAR(75) null,
	manageAccessToAuditDet VARCHAR(75) null,
	keyActivity VARCHAR(75) null,
	transferReason VARCHAR(75) null,
	indicateStandard VARCHAR(75) null,
	ceritificationBodyName VARCHAR(75) null,
	consultingFirm VARCHAR(75) null,
	consultant VARCHAR(75) null,
	telephone VARCHAR(75) null,
	email VARCHAR(75) null,
	certificationScopeRadio VARCHAR(75) null,
	outsourceProcess VARCHAR(75) null,
	relevantRequirement VARCHAR(75) null,
	relevantRequirementList VARCHAR(75) null,
	managementAccessToAudit VARCHAR(75) null,
	pleaseManageDetail VARCHAR(75) null,
	desiredCertification VARCHAR(75) null,
	surveillanceSchedule VARCHAR(75) null,
	certifiedManagement VARCHAR(75) null,
	certifiedAccreditedCerti VARCHAR(75) null,
	companyUsedConsulting VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_organization_detail (
	ncbjOrganizationDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfOrganization VARCHAR(75) null,
	address VARCHAR(500) null,
	telephoneNumber VARCHAR(75) null,
	faxNumber VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	headOfOrganization  VARCHAR(75) null,
	position VARCHAR(75) null,
	contactPersonName VARCHAR(75) null,
	contactPersonEmailAddress  VARCHAR(75) null,
	contactPersonPosition  VARCHAR(75) null,
	managementSystem VARCHAR(500) null,
	determinedTheScope VARCHAR(75) null,
	pleaseStageTheScope VARCHAR(75) null,
	positionSecondFo VARCHAR(75) null,
	managementSystemFo VARCHAR(75) null,
	productTypes VARCHAR(75) null,
	productLine VARCHAR(75) null,
	haccpStudies VARCHAR(75) null,
	criticalControlPoints VARCHAR(75) null,
	operationalNumber VARCHAR(75) null,
	productionSize VARCHAR(75) null,
	warehouseSize VARCHAR(75) null,
	warehouseDetailSize VARCHAR(75) null,
	seasonalProcess VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_premises_location (
	ncbjPremisesLocationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	transferReasonDraft VARCHAR(500) null,
	activityExclusion VARCHAR(75) null,
	transferReasonAct VARCHAR(500) null,
	productionFacilitySize VARCHAR(75) null,
	warehouseFacilitySize VARCHAR(75) null,
	facilitiesLocation VARCHAR(500) null,
	detailForDiffManagement VARCHAR(500) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_product_service (
	ncbjProductServiceDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	productType VARCHAR(75) null,
	productList VARCHAR(75) null,
	productLines VARCHAR(75) null,
	counter VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_section_detail (
	ncbjSectionDetailAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addDetails VARCHAR(75) null,
	addNumHaccp VARCHAR(75) null,
	addTypeHaccp VARCHAR(75) null,
	addHazard VARCHAR(75) null,
	addConsentLic VARCHAR(75) null,
	counter VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_section_four (
	ncbjSectionFourId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	consultService VARCHAR(75) null,
	consultTelephone VARCHAR(75) null,
	consultEmail VARCHAR(75) null,
	consultStageOne DATE null,
	consultStageTwo DATE null,
	consultSurveillanceAudit DATE null,
	consultRecertificationAudit DATE null,
	consultPreassessmentAudit DATE null,
	consultOtherService DATE null,
	consultName VARCHAR(75) null,
	consultPosition VARCHAR(75) null,
	consultDate DATE null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_section_one (
	ncbjSectionOneId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	numberOfProductTypes VARCHAR(75) null,
	pleaseListProduct VARCHAR(75) null,
	numberOfProductionLines DATE null,
	exclusionActivities DATE null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_section_one_add (
	ncbjSectionOneAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	headOfCompanyName VARCHAR(75) null,
	JobTitle VARCHAR(75) null,
	eMeilAddress DATE null,
	telephoneNumber DATE null,
	contactName DATE null,
	contactNameJobTitle DATE null,
	contactNameEmailAddress DATE null,
	contactNameTelephoneNum  DATE null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_section_three (
	ncbjSectionThreeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	processActivityDescription VARCHAR(75) null,
	incomingMaterialsDes VARCHAR(75) null,
	processDescription VARCHAR(75) null,
	processActivitiesList VARCHAR(500) null,
	specialActivities VARCHAR(75) null,
	explainationBox VARCHAR(75) null,
	categoryOne VARCHAR(2000) null,
	categoryTwo VARCHAR(75) null,
	categoryThree VARCHAR(75) null,
	categoryFour VARCHAR(75) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_section_two (
	ncbjSectionTwoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	incomingMaterials VARCHAR(500) null,
	productStorage VARCHAR(500) null,
	buildingSiteAspects VARCHAR(500) null,
	wasteDischarges VARCHAR(500) null,
	transportDetails VARCHAR(500) null,
	subcontractedActivities VARCHAR(500) null,
	ncbjApplicationId LONG
);

create table nbp_ncbj_specific_activity (
	ncbjSpecificActivitiesId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	specificActivity VARCHAR(75) null,
	specificActivityNumber VARCHAR(75) null,
	specificActivityChecked VARCHAR(75) null,
	ncbjApplicationId LONG
);