/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.factories.registration.stage.services.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.factories.registration.stage.services.model.FactoriesAppCommitteeDecision;
import com.nbp.factories.registration.stage.services.service.FactoriesAppCommitteeDecisionLocalService;
import com.nbp.factories.registration.stage.services.service.persistence.FactoriesAppCommitteeDecisionPersistence;
import com.nbp.factories.registration.stage.services.service.persistence.FactoriesApplicationStagePersistence;
import com.nbp.factories.registration.stage.services.service.persistence.FactoriesCerticateOfRegisPersistence;
import com.nbp.factories.registration.stage.services.service.persistence.FactoriesInspectionPersistence;
import com.nbp.factories.registration.stage.services.service.persistence.FactoryPaymentVerificationPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the factories app committee decision local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.factories.registration.stage.services.service.impl.FactoriesAppCommitteeDecisionLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.factories.registration.stage.services.service.impl.FactoriesAppCommitteeDecisionLocalServiceImpl
 * @generated
 */
public abstract class FactoriesAppCommitteeDecisionLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FactoriesAppCommitteeDecisionLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FactoriesAppCommitteeDecisionLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.factories.registration.stage.services.service.FactoriesAppCommitteeDecisionLocalServiceUtil</code>.
	 */

	/**
	 * Adds the factories app committee decision to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FactoriesAppCommitteeDecisionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param factoriesAppCommitteeDecision the factories app committee decision
	 * @return the factories app committee decision that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FactoriesAppCommitteeDecision addFactoriesAppCommitteeDecision(
		FactoriesAppCommitteeDecision factoriesAppCommitteeDecision) {

		factoriesAppCommitteeDecision.setNew(true);

		return factoriesAppCommitteeDecisionPersistence.update(
			factoriesAppCommitteeDecision);
	}

	/**
	 * Creates a new factories app committee decision with the primary key. Does not add the factories app committee decision to the database.
	 *
	 * @param factoriesAppCommiDecId the primary key for the new factories app committee decision
	 * @return the new factories app committee decision
	 */
	@Override
	@Transactional(enabled = false)
	public FactoriesAppCommitteeDecision createFactoriesAppCommitteeDecision(
		long factoriesAppCommiDecId) {

		return factoriesAppCommitteeDecisionPersistence.create(
			factoriesAppCommiDecId);
	}

	/**
	 * Deletes the factories app committee decision with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FactoriesAppCommitteeDecisionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param factoriesAppCommiDecId the primary key of the factories app committee decision
	 * @return the factories app committee decision that was removed
	 * @throws PortalException if a factories app committee decision with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FactoriesAppCommitteeDecision deleteFactoriesAppCommitteeDecision(
			long factoriesAppCommiDecId)
		throws PortalException {

		return factoriesAppCommitteeDecisionPersistence.remove(
			factoriesAppCommiDecId);
	}

	/**
	 * Deletes the factories app committee decision from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FactoriesAppCommitteeDecisionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param factoriesAppCommitteeDecision the factories app committee decision
	 * @return the factories app committee decision that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FactoriesAppCommitteeDecision deleteFactoriesAppCommitteeDecision(
		FactoriesAppCommitteeDecision factoriesAppCommitteeDecision) {

		return factoriesAppCommitteeDecisionPersistence.remove(
			factoriesAppCommitteeDecision);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return factoriesAppCommitteeDecisionPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FactoriesAppCommitteeDecision.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return factoriesAppCommitteeDecisionPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.factories.registration.stage.services.model.impl.FactoriesAppCommitteeDecisionModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return factoriesAppCommitteeDecisionPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.factories.registration.stage.services.model.impl.FactoriesAppCommitteeDecisionModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return factoriesAppCommitteeDecisionPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return factoriesAppCommitteeDecisionPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return factoriesAppCommitteeDecisionPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FactoriesAppCommitteeDecision fetchFactoriesAppCommitteeDecision(
		long factoriesAppCommiDecId) {

		return factoriesAppCommitteeDecisionPersistence.fetchByPrimaryKey(
			factoriesAppCommiDecId);
	}

	/**
	 * Returns the factories app committee decision with the primary key.
	 *
	 * @param factoriesAppCommiDecId the primary key of the factories app committee decision
	 * @return the factories app committee decision
	 * @throws PortalException if a factories app committee decision with the primary key could not be found
	 */
	@Override
	public FactoriesAppCommitteeDecision getFactoriesAppCommitteeDecision(
			long factoriesAppCommiDecId)
		throws PortalException {

		return factoriesAppCommitteeDecisionPersistence.findByPrimaryKey(
			factoriesAppCommiDecId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			factoriesAppCommitteeDecisionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			FactoriesAppCommitteeDecision.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"factoriesAppCommiDecId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			factoriesAppCommitteeDecisionLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			FactoriesAppCommitteeDecision.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"factoriesAppCommiDecId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			factoriesAppCommitteeDecisionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			FactoriesAppCommitteeDecision.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"factoriesAppCommiDecId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return factoriesAppCommitteeDecisionPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement FactoriesAppCommitteeDecisionLocalServiceImpl#deleteFactoriesAppCommitteeDecision(FactoriesAppCommitteeDecision) to avoid orphaned data");
		}

		return factoriesAppCommitteeDecisionLocalService.
			deleteFactoriesAppCommitteeDecision(
				(FactoriesAppCommitteeDecision)persistedModel);
	}

	@Override
	public BasePersistence<FactoriesAppCommitteeDecision> getBasePersistence() {
		return factoriesAppCommitteeDecisionPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return factoriesAppCommitteeDecisionPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the factories app committee decisions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.factories.registration.stage.services.model.impl.FactoriesAppCommitteeDecisionModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of factories app committee decisions
	 * @param end the upper bound of the range of factories app committee decisions (not inclusive)
	 * @return the range of factories app committee decisions
	 */
	@Override
	public List<FactoriesAppCommitteeDecision>
		getFactoriesAppCommitteeDecisions(int start, int end) {

		return factoriesAppCommitteeDecisionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of factories app committee decisions.
	 *
	 * @return the number of factories app committee decisions
	 */
	@Override
	public int getFactoriesAppCommitteeDecisionsCount() {
		return factoriesAppCommitteeDecisionPersistence.countAll();
	}

	/**
	 * Updates the factories app committee decision in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FactoriesAppCommitteeDecisionLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param factoriesAppCommitteeDecision the factories app committee decision
	 * @return the factories app committee decision that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FactoriesAppCommitteeDecision updateFactoriesAppCommitteeDecision(
		FactoriesAppCommitteeDecision factoriesAppCommitteeDecision) {

		return factoriesAppCommitteeDecisionPersistence.update(
			factoriesAppCommitteeDecision);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FactoriesAppCommitteeDecisionLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		factoriesAppCommitteeDecisionLocalService =
			(FactoriesAppCommitteeDecisionLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FactoriesAppCommitteeDecisionLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FactoriesAppCommitteeDecision.class;
	}

	protected String getModelClassName() {
		return FactoriesAppCommitteeDecision.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				factoriesAppCommitteeDecisionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected FactoriesAppCommitteeDecisionLocalService
		factoriesAppCommitteeDecisionLocalService;

	@Reference
	protected FactoriesAppCommitteeDecisionPersistence
		factoriesAppCommitteeDecisionPersistence;

	@Reference
	protected FactoriesApplicationStagePersistence
		factoriesApplicationStagePersistence;

	@Reference
	protected FactoriesCerticateOfRegisPersistence
		factoriesCerticateOfRegisPersistence;

	@Reference
	protected FactoriesInspectionPersistence factoriesInspectionPersistence;

	@Reference
	protected FactoryPaymentVerificationPersistence
		factoryPaymentVerificationPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		FactoriesAppCommitteeDecisionLocalServiceBaseImpl.class);

}