/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.quarry.stage.service.model.impl;

import com.nbp.quarry.stage.service.model.QuarryApplicationStage;
import com.nbp.quarry.stage.service.service.QuarryApplicationStageLocalServiceUtil;

/**
 * The extended model base implementation for the QuarryApplicationStage service. Represents a row in the &quot;nbp_quarry_app_stag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QuarryApplicationStageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuarryApplicationStageImpl
 * @see QuarryApplicationStage
 * @generated
 */
public abstract class QuarryApplicationStageBaseImpl
	extends QuarryApplicationStageModelImpl implements QuarryApplicationStage {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a quarry application stage model instance should use the <code>QuarryApplicationStage</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			QuarryApplicationStageLocalServiceUtil.addQuarryApplicationStage(
				this);
		}
		else {
			QuarryApplicationStageLocalServiceUtil.updateQuarryApplicationStage(
				this);
		}
	}

}