create table nbp_blaster_competency (
	blasterCompetencyFormId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	firstName VARCHAR(75) null,
	surName VARCHAR(75) null,
	middleName VARCHAR(75) null,
	gender VARCHAR(75) null,
	officeNumber VARCHAR(75) null,
	cellNum VARCHAR(75) null,
	trnNum VARCHAR(75) null,
	dateOfBirth DATE null,
	address VARCHAR(500) null,
	educationalBack VARCHAR(75) null,
	blastingCourse VARCHAR(75) null,
	state_ VARCHAR(75) null,
	nameOfCourse VARCHAR(75) null,
	courseOrganiser VARCHAR(75) null,
	dateAppli DATE null,
	explosivesApplicationId LONG
);

create table nbp_explosive_payment (
	explosiveAppPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentDocId VARCHAR(75) null,
	paymentStatus VARCHAR(75) null,
	paymentFee VARCHAR(75) null,
	amountPaid VARCHAR(75) null,
	amountCurrency VARCHAR(75) null,
	transactionNumber VARCHAR(75) null,
	explosivesApplicationId LONG
);

create table nbp_explosives_application (
	uuid_ VARCHAR(75) null,
	explosivesApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	typeOfApplicant VARCHAR(75) null,
	typeOfTransaction VARCHAR(75) null,
	competencyCertificateNumber VARCHAR(75) null,
	dateOfIssue DATE null,
	dateOfExpiration DATE null,
	caseId VARCHAR(500) null,
	status INTEGER,
	icmDocumentPath VARCHAR(500) null,
	applicationNumber VARCHAR(75) null,
	expiredLicenseAppNumber VARCHAR(75) null,
	pdfFileEntryId LONG,
	appCurrentStageName VARCHAR(75) null
);

create table nbp_explosives_stage (
	explosiveStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormDetailsStep VARCHAR(75) null,
	explosivesApplicationId LONG
);

create table nbp_pyrotechnic_competency (
	pyrotechnicCompetencyFormId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	firstNamePyro VARCHAR(75) null,
	surNamePyro VARCHAR(75) null,
	middleNamePyro VARCHAR(75) null,
	genderPyro VARCHAR(75) null,
	officeNumberPyro VARCHAR(75) null,
	cellNumPyro VARCHAR(75) null,
	trnNumPyro VARCHAR(75) null,
	dateOfBirthPyro DATE null,
	addressPyro VARCHAR(500) null,
	educationalBackPyro VARCHAR(75) null,
	blastingCoursePyro VARCHAR(75) null,
	statePyro VARCHAR(75) null,
	nameOfCoursePyro VARCHAR(75) null,
	courseOrganiserPyro VARCHAR(75) null,
	dateAppliPyro VARCHAR(75) null,
	explosivesApplicationId LONG
);