/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.ncra.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.ncra.application.form.service.model.NcraFeeSubmission;
import com.nbp.ncra.application.form.service.model.NcraFeeSubmissionModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NcraFeeSubmission service. Represents a row in the &quot;nbp_ncra_fee_payment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NcraFeeSubmissionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NcraFeeSubmissionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NcraFeeSubmissionImpl
 * @generated
 */
@JSON(strict = true)
public class NcraFeeSubmissionModelImpl
	extends BaseModelImpl<NcraFeeSubmission> implements NcraFeeSubmissionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ncra fee submission model instance should use the <code>NcraFeeSubmission</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_ncra_fee_payment";

	public static final Object[][] TABLE_COLUMNS = {
		{"ncraFeeSubmissionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"creditStatus", Types.VARCHAR},
		{"ncraApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ncraFeeSubmissionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("creditStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ncraApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_ncra_fee_payment (ncraFeeSubmissionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,creditStatus VARCHAR(75) null,ncraApplicationId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_ncra_fee_payment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ncraFeeSubmission.ncraFeeSubmissionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_ncra_fee_payment.ncraFeeSubmissionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NCRAAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NCRAFEESUBMISSIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NcraFeeSubmissionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ncraFeeSubmissionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNcraFeeSubmissionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ncraFeeSubmissionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NcraFeeSubmission.class;
	}

	@Override
	public String getModelClassName() {
		return NcraFeeSubmission.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NcraFeeSubmission, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NcraFeeSubmission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NcraFeeSubmission, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NcraFeeSubmission)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NcraFeeSubmission, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NcraFeeSubmission, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NcraFeeSubmission)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NcraFeeSubmission, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NcraFeeSubmission, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<NcraFeeSubmission, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<NcraFeeSubmission, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<NcraFeeSubmission, Object>>();

			attributeGetterFunctions.put(
				"ncraFeeSubmissionId",
				NcraFeeSubmission::getNcraFeeSubmissionId);
			attributeGetterFunctions.put(
				"groupId", NcraFeeSubmission::getGroupId);
			attributeGetterFunctions.put(
				"companyId", NcraFeeSubmission::getCompanyId);
			attributeGetterFunctions.put(
				"userId", NcraFeeSubmission::getUserId);
			attributeGetterFunctions.put(
				"userName", NcraFeeSubmission::getUserName);
			attributeGetterFunctions.put(
				"createDate", NcraFeeSubmission::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", NcraFeeSubmission::getModifiedDate);
			attributeGetterFunctions.put(
				"creditStatus", NcraFeeSubmission::getCreditStatus);
			attributeGetterFunctions.put(
				"ncraApplicationId", NcraFeeSubmission::getNcraApplicationId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<NcraFeeSubmission, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<NcraFeeSubmission, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<NcraFeeSubmission, ?>>();

			attributeSetterBiConsumers.put(
				"ncraFeeSubmissionId",
				(BiConsumer<NcraFeeSubmission, Long>)
					NcraFeeSubmission::setNcraFeeSubmissionId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<NcraFeeSubmission, Long>)
					NcraFeeSubmission::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<NcraFeeSubmission, Long>)
					NcraFeeSubmission::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<NcraFeeSubmission, Long>)
					NcraFeeSubmission::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<NcraFeeSubmission, String>)
					NcraFeeSubmission::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<NcraFeeSubmission, Date>)
					NcraFeeSubmission::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<NcraFeeSubmission, Date>)
					NcraFeeSubmission::setModifiedDate);
			attributeSetterBiConsumers.put(
				"creditStatus",
				(BiConsumer<NcraFeeSubmission, String>)
					NcraFeeSubmission::setCreditStatus);
			attributeSetterBiConsumers.put(
				"ncraApplicationId",
				(BiConsumer<NcraFeeSubmission, Long>)
					NcraFeeSubmission::setNcraApplicationId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getNcraFeeSubmissionId() {
		return _ncraFeeSubmissionId;
	}

	@Override
	public void setNcraFeeSubmissionId(long ncraFeeSubmissionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ncraFeeSubmissionId = ncraFeeSubmissionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCreditStatus() {
		if (_creditStatus == null) {
			return "";
		}
		else {
			return _creditStatus;
		}
	}

	@Override
	public void setCreditStatus(String creditStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creditStatus = creditStatus;
	}

	@JSON
	@Override
	public long getNcraApplicationId() {
		return _ncraApplicationId;
	}

	@Override
	public void setNcraApplicationId(long ncraApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ncraApplicationId = ncraApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalNcraApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("ncraApplicationId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NcraFeeSubmission.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NcraFeeSubmission toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NcraFeeSubmission>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NcraFeeSubmissionImpl ncraFeeSubmissionImpl =
			new NcraFeeSubmissionImpl();

		ncraFeeSubmissionImpl.setNcraFeeSubmissionId(getNcraFeeSubmissionId());
		ncraFeeSubmissionImpl.setGroupId(getGroupId());
		ncraFeeSubmissionImpl.setCompanyId(getCompanyId());
		ncraFeeSubmissionImpl.setUserId(getUserId());
		ncraFeeSubmissionImpl.setUserName(getUserName());
		ncraFeeSubmissionImpl.setCreateDate(getCreateDate());
		ncraFeeSubmissionImpl.setModifiedDate(getModifiedDate());
		ncraFeeSubmissionImpl.setCreditStatus(getCreditStatus());
		ncraFeeSubmissionImpl.setNcraApplicationId(getNcraApplicationId());

		ncraFeeSubmissionImpl.resetOriginalValues();

		return ncraFeeSubmissionImpl;
	}

	@Override
	public NcraFeeSubmission cloneWithOriginalValues() {
		NcraFeeSubmissionImpl ncraFeeSubmissionImpl =
			new NcraFeeSubmissionImpl();

		ncraFeeSubmissionImpl.setNcraFeeSubmissionId(
			this.<Long>getColumnOriginalValue("ncraFeeSubmissionId"));
		ncraFeeSubmissionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		ncraFeeSubmissionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		ncraFeeSubmissionImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		ncraFeeSubmissionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		ncraFeeSubmissionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		ncraFeeSubmissionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		ncraFeeSubmissionImpl.setCreditStatus(
			this.<String>getColumnOriginalValue("creditStatus"));
		ncraFeeSubmissionImpl.setNcraApplicationId(
			this.<Long>getColumnOriginalValue("ncraApplicationId"));

		return ncraFeeSubmissionImpl;
	}

	@Override
	public int compareTo(NcraFeeSubmission ncraFeeSubmission) {
		long primaryKey = ncraFeeSubmission.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NcraFeeSubmission)) {
			return false;
		}

		NcraFeeSubmission ncraFeeSubmission = (NcraFeeSubmission)object;

		long primaryKey = ncraFeeSubmission.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NcraFeeSubmission> toCacheModel() {
		NcraFeeSubmissionCacheModel ncraFeeSubmissionCacheModel =
			new NcraFeeSubmissionCacheModel();

		ncraFeeSubmissionCacheModel.ncraFeeSubmissionId =
			getNcraFeeSubmissionId();

		ncraFeeSubmissionCacheModel.groupId = getGroupId();

		ncraFeeSubmissionCacheModel.companyId = getCompanyId();

		ncraFeeSubmissionCacheModel.userId = getUserId();

		ncraFeeSubmissionCacheModel.userName = getUserName();

		String userName = ncraFeeSubmissionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ncraFeeSubmissionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ncraFeeSubmissionCacheModel.createDate = createDate.getTime();
		}
		else {
			ncraFeeSubmissionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ncraFeeSubmissionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ncraFeeSubmissionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ncraFeeSubmissionCacheModel.creditStatus = getCreditStatus();

		String creditStatus = ncraFeeSubmissionCacheModel.creditStatus;

		if ((creditStatus != null) && (creditStatus.length() == 0)) {
			ncraFeeSubmissionCacheModel.creditStatus = null;
		}

		ncraFeeSubmissionCacheModel.ncraApplicationId = getNcraApplicationId();

		return ncraFeeSubmissionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NcraFeeSubmission, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NcraFeeSubmission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NcraFeeSubmission, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(NcraFeeSubmission)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NcraFeeSubmission>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					NcraFeeSubmission.class, ModelWrapper.class);

	}

	private long _ncraFeeSubmissionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _creditStatus;
	private long _ncraApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<NcraFeeSubmission, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NcraFeeSubmission)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ncraFeeSubmissionId", _ncraFeeSubmissionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("creditStatus", _creditStatus);
		_columnOriginalValues.put("ncraApplicationId", _ncraApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ncraFeeSubmissionId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("creditStatus", 128L);

		columnBitmasks.put("ncraApplicationId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NcraFeeSubmission _escapedModel;

}