/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.creative.stages.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CreativePermit service. Represents a row in the &quot;nbp_creative_permit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nbp.creative.stages.services.model.impl.CreativePermitModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nbp.creative.stages.services.model.impl.CreativePermitImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CreativePermit
 * @generated
 */
@ProviderType
public interface CreativePermitModel
	extends BaseModel<CreativePermit>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a creative permit model instance should use the {@link CreativePermit} interface instead.
	 */

	/**
	 * Returns the primary key of this creative permit.
	 *
	 * @return the primary key of this creative permit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this creative permit.
	 *
	 * @param primaryKey the primary key of this creative permit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the creative permit ID of this creative permit.
	 *
	 * @return the creative permit ID of this creative permit
	 */
	public long getCreativePermitId();

	/**
	 * Sets the creative permit ID of this creative permit.
	 *
	 * @param creativePermitId the creative permit ID of this creative permit
	 */
	public void setCreativePermitId(long creativePermitId);

	/**
	 * Returns the group ID of this creative permit.
	 *
	 * @return the group ID of this creative permit
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this creative permit.
	 *
	 * @param groupId the group ID of this creative permit
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this creative permit.
	 *
	 * @return the company ID of this creative permit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this creative permit.
	 *
	 * @param companyId the company ID of this creative permit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this creative permit.
	 *
	 * @return the user ID of this creative permit
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this creative permit.
	 *
	 * @param userId the user ID of this creative permit
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this creative permit.
	 *
	 * @return the user uuid of this creative permit
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this creative permit.
	 *
	 * @param userUuid the user uuid of this creative permit
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this creative permit.
	 *
	 * @return the user name of this creative permit
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this creative permit.
	 *
	 * @param userName the user name of this creative permit
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this creative permit.
	 *
	 * @return the create date of this creative permit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this creative permit.
	 *
	 * @param createDate the create date of this creative permit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this creative permit.
	 *
	 * @return the modified date of this creative permit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this creative permit.
	 *
	 * @param modifiedDate the modified date of this creative permit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the case ID of this creative permit.
	 *
	 * @return the case ID of this creative permit
	 */
	@AutoEscape
	public String getCaseId();

	/**
	 * Sets the case ID of this creative permit.
	 *
	 * @param caseId the case ID of this creative permit
	 */
	public void setCaseId(String caseId);

	/**
	 * Returns the pir permt number of this creative permit.
	 *
	 * @return the pir permt number of this creative permit
	 */
	@AutoEscape
	public String getPirPermtNumber();

	/**
	 * Sets the pir permt number of this creative permit.
	 *
	 * @param pirPermtNumber the pir permt number of this creative permit
	 */
	public void setPirPermtNumber(String pirPermtNumber);

	/**
	 * Returns the dateof issue of this creative permit.
	 *
	 * @return the dateof issue of this creative permit
	 */
	public Date getDateofIssue();

	/**
	 * Sets the dateof issue of this creative permit.
	 *
	 * @param dateofIssue the dateof issue of this creative permit
	 */
	public void setDateofIssue(Date dateofIssue);

	/**
	 * Returns the date of expiration of this creative permit.
	 *
	 * @return the date of expiration of this creative permit
	 */
	public Date getDateOfExpiration();

	/**
	 * Sets the date of expiration of this creative permit.
	 *
	 * @param dateOfExpiration the date of expiration of this creative permit
	 */
	public void setDateOfExpiration(Date dateOfExpiration);

	/**
	 * Returns the duration of permit of this creative permit.
	 *
	 * @return the duration of permit of this creative permit
	 */
	@AutoEscape
	public String getDurationOfPermit();

	/**
	 * Sets the duration of permit of this creative permit.
	 *
	 * @param durationOfPermit the duration of permit of this creative permit
	 */
	public void setDurationOfPermit(String durationOfPermit);

	/**
	 * Returns the pir certificate number of this creative permit.
	 *
	 * @return the pir certificate number of this creative permit
	 */
	public long getPirCertificateNumber();

	/**
	 * Sets the pir certificate number of this creative permit.
	 *
	 * @param pirCertificateNumber the pir certificate number of this creative permit
	 */
	public void setPirCertificateNumber(long pirCertificateNumber);

	@Override
	public CreativePermit cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}