create table FarmerApplication (
	farmerApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	requestType VARCHAR(75) null,
	perishLocal VARCHAR(75) null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	caseld VARCHAR(75) null
);

create table farmer_Stakeholder_info (
	farmerStakeholderInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyName VARCHAR(75) null,
	firstName VARCHAR(75) null,
	middleName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	alias_ VARCHAR(75) null,
	residentialStreetName VARCHAR(75) null,
	residentialDistrict VARCHAR(75) null,
	residentialPostOffice VARCHAR(75) null,
	residentialParish VARCHAR(75) null,
	residentialtelephoneNumber VARCHAR(75) null,
	businessStreetName VARCHAR(75) null,
	businessDistrict VARCHAR(75) null,
	businessPostOffice VARCHAR(75) null,
	businessParish VARCHAR(75) null,
	businessTelephoneNumber VARCHAR(75) null,
	identificationType VARCHAR(75) null,
	identificationNumber VARCHAR(75) null,
	gender VARCHAR(75) null,
	dateOfBirth DATE null,
	taxpayerRegistrationNumber VARCHAR(75) null,
	cellPhone VARCHAR(75) null,
	fax VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	farmerApplicationId LONG
);

create table farmer_crop (
	farmerCropId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	cropAndVariety VARCHAR(75) null,
	area VARCHAR(75) null,
	unit VARCHAR(75) null,
	cropContent VARCHAR(75) null,
	plantingDate DATE null,
	majorMarket VARCHAR(75) null,
	majorMarketPercentSold VARCHAR(75) null,
	minorMarket VARCHAR(75) null,
	minorMarketPercentSold VARCHAR(75) null,
	remarks VARCHAR(500) null,
	propertyId02 VARCHAR(75) null,
	propertyId03 VARCHAR(75) null,
	cropCounter VARCHAR(75) null,
	farmerApplicationId LONG
);

create table farmer_crop_practice (
	farmerCropPracticeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	crop1landPrepration VARCHAR(75) null,
	crop1CropCare VARCHAR(75) null,
	crop1water VARCHAR(75) null,
	crop1postHarvest VARCHAR(75) null,
	crop02 VARCHAR(75) null,
	crop03 VARCHAR(500) null,
	cropPracticeCounter VARCHAR(75) null,
	farmerApplicationId LONG
);

create table farmer_livestock (
	farmerLiveStockId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	livestockBreed VARCHAR(75) null,
	stageOflife VARCHAR(75) null,
	count VARCHAR(75) null,
	colonies VARCHAR(75) null,
	capacity VARCHAR(75) null,
	majorMarket VARCHAR(75) null,
	majorMarketSold VARCHAR(75) null,
	minorMarket VARCHAR(75) null,
	minorMarketSold VARCHAR(75) null,
	remarks VARCHAR(500) null,
	livestockCounter VARCHAR(75) null,
	farmerApplicationId LONG
);

create table farmer_livestock_practice (
	farmerLivestockPracticeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	husbandry VARCHAR(75) null,
	liveStockCare VARCHAR(75) null,
	nutrient VARCHAR(75) null,
	water VARCHAR(75) null,
	postHarvest VARCHAR(75) null,
	remarks VARCHAR(500) null,
	livestockPracticeCounter VARCHAR(75) null,
	farmerApplicationId LONG
);

create table farmer_profile (
	farmerProfileId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	respondent VARCHAR(75) null,
	manager VARCHAR(75) null,
	liveOnFarm VARCHAR(75) null,
	livelihood VARCHAR(75) null,
	educationLevel VARCHAR(75) null,
	mainOccupation VARCHAR(75) null,
	agriiInstitution VARCHAR(75) null,
	qualification VARCHAR(75) null,
	agriTraining VARCHAR(75) null,
	trainingMethod VARCHAR(75) null,
	mainAgriActivity VARCHAR(75) null,
	neareshPoliceStation VARCHAR(75) null,
	jasBranchGroup VARCHAR(75) null,
	holdingStartYear VARCHAR(75) null,
	farmerType VARCHAR(75) null,
	remarks VARCHAR(500) null,
	mainInformationSources VARCHAR(500) null,
	farmerApplicationId LONG
);

create table farmer_property (
	farmerPropertyId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	property01Extension VARCHAR(75) null,
	property01District VARCHAR(75) null,
	property01Tenure VARCHAR(75) null,
	property01Status VARCHAR(75) null,
	property01Size VARCHAR(75) null,
	property01Usage VARCHAR(75) null,
	property01Volume VARCHAR(75) null,
	property01Folio VARCHAR(75) null,
	property01DistanceFromRoad VARCHAR(75) null,
	propertyId02 VARCHAR(75) null,
	propertyId03 VARCHAR(75) null,
	propertyCounter VARCHAR(75) null,
	remarks VARCHAR(500) null,
	farmerApplicationId LONG
);

create table farmer_stakeholder_address (
	farmerStakeholderAddressId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addressType VARCHAR(75) null,
	streetName VARCHAR(75) null,
	district VARCHAR(75) null,
	postoffice VARCHAR(75) null,
	parish VARCHAR(75) null,
	telephoneNumber VARCHAR(75) null,
	applicationNumber VARCHAR(75) null,
	farmerApplicationId LONG,
	stakeholderAddressId LONG,
	farmerStakeholderInfoId LONG
);

create table nbp_farmer_application (
	farmerApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	requestType VARCHAR(75) null,
	perishLocal VARCHAR(75) null,
	farmType VARCHAR(75) null,
	farmParishLocal VARCHAR(75) null,
	entityId VARCHAR(75) null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	expiredLicenseappNumber VARCHAR(75) null,
	caseld VARCHAR(500) null,
	icmDocumentsPath VARCHAR(500) null,
	PdfFileEntryId LONG,
	appCurrentStageName VARCHAR(75) null
);

create table nbp_farmer_stage (
	uuid_ VARCHAR(75) null,
	farmerCurrentStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormStage VARCHAR(75) null,
	farmerApplicationId LONG
);