create table nbp_film_app_stages (
	filmApplicationStagesId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	stageName VARCHAR(75) null,
	duration VARCHAR(75) null,
	stageStatus VARCHAR(75) null,
	stageStartDate DATE null,
	stageEndDate DATE null,
	filmApplicationId LONG,
	caseId VARCHAR(75) null,
	updatedBySource VARCHAR(75) null
);

create table nbp_film_desk_verification (
	filmDeskVerificaId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	filmApplicationId LONG,
	documentName VARCHAR(75) null,
	status VARCHAR(75) null
);

create table nbp_film_full_registration (
	filmFullRegistrationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	caseId VARCHAR(75) null,
	nameOfApplicant VARCHAR(75) null,
	productionType VARCHAR(75) null,
	registrationNumber VARCHAR(75) null,
	duration VARCHAR(75) null,
	dateOfIssued DATE null,
	productionTitle VARCHAR(75) null,
	productionDateFrom DATE null,
	productionDateTo DATE null,
	termsAndConditions VARCHAR(75) null,
	docFileEntrys LONG
);

create table nbp_film_payment_confirm (
	filmPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	caseId VARCHAR(75) null,
	dateReceived DATE null,
	amountReceived VARCHAR(75) null,
	amountDue VARCHAR(75) null,
	receiptNumber VARCHAR(75) null,
	comment_ VARCHAR(2000) null,
	amountOutstanding VARCHAR(75) null,
	dueDate DATE null,
	status VARCHAR(75) null,
	docFileEntry LONG
);

create table nbp_film_register (
	filmApplicationRegisterId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	caseId VARCHAR(75) null,
	nameOfApplicant VARCHAR(75) null,
	registrationDate DATE null,
	filmRegistrationNum VARCHAR(75) null,
	titleOfProduction VARCHAR(75) null,
	dateOfIssued DATE null,
	productionCompany VARCHAR(75) null,
	technicalFormOfProd VARCHAR(75) null,
	OriginOfProdCom VARCHAR(75) null,
	permitsRequired VARCHAR(75) null,
	shootLocationInJamaica VARCHAR(75) null,
	preProductionDate DATE null,
	productionStartDate DATE null,
	proposedDateOfArrival VARCHAR(75) null,
	portOfEntry VARCHAR(75) null,
	proposedDateOfDeparture DATE null,
	fullProductionBudget VARCHAR(75) null,
	expectedBudgetSpendInJA VARCHAR(75) null,
	numberOFForeignCrewHired VARCHAR(75) null,
	numberJamaicaCrewHired VARCHAR(75) null,
	valueOfBondWaiver VARCHAR(75) null,
	customsBroker VARCHAR(75) null,
	localProductionManagerOrFixer VARCHAR(75) null
);