/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.osi.insolvency.stage.services.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.osi.insolvency.stage.services.model.OsiInsoIIssuanceOfReport;
import com.nbp.osi.insolvency.stage.services.service.OsiInsoIIssuanceOfReportService;
import com.nbp.osi.insolvency.stage.services.service.persistence.OsiInsoIIssuanceOfReportPersistence;
import com.nbp.osi.insolvency.stage.services.service.persistence.OsiInsolDataVerificationPersistence;
import com.nbp.osi.insolvency.stage.services.service.persistence.OsiInsolveDeskVerificationPersistence;
import com.nbp.osi.insolvency.stage.services.service.persistence.OsiInsolvencyApplicationStagesPersistence;
import com.nbp.osi.insolvency.stage.services.service.persistence.OsiInsolvencyPaymentConfirmationPersistence;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the osi inso i issuance of report remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.osi.insolvency.stage.services.service.impl.OsiInsoIIssuanceOfReportServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.osi.insolvency.stage.services.service.impl.OsiInsoIIssuanceOfReportServiceImpl
 * @generated
 */
public abstract class OsiInsoIIssuanceOfReportServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService,
			   OsiInsoIIssuanceOfReportService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>OsiInsoIIssuanceOfReportService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.osi.insolvency.stage.services.service.OsiInsoIIssuanceOfReportServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			OsiInsoIIssuanceOfReportService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		osiInsoIIssuanceOfReportService =
			(OsiInsoIIssuanceOfReportService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return OsiInsoIIssuanceOfReportService.class.getName();
	}

	protected Class<?> getModelClass() {
		return OsiInsoIIssuanceOfReport.class;
	}

	protected String getModelClassName() {
		return OsiInsoIIssuanceOfReport.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				osiInsoIIssuanceOfReportPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected com.nbp.osi.insolvency.stage.services.service.
		OsiInsoIIssuanceOfReportLocalService
			osiInsoIIssuanceOfReportLocalService;

	protected OsiInsoIIssuanceOfReportService osiInsoIIssuanceOfReportService;

	@Reference
	protected OsiInsoIIssuanceOfReportPersistence
		osiInsoIIssuanceOfReportPersistence;

	@Reference
	protected OsiInsolDataVerificationPersistence
		osiInsolDataVerificationPersistence;

	@Reference
	protected OsiInsolveDeskVerificationPersistence
		osiInsolveDeskVerificationPersistence;

	@Reference
	protected OsiInsolvencyApplicationStagesPersistence
		osiInsolvencyApplicationStagesPersistence;

	@Reference
	protected OsiInsolvencyPaymentConfirmationPersistence
		osiInsolvencyPaymentConfirmationPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		OsiInsoIIssuanceOfReportServiceBaseImpl.class);

}