create table nbp_ogt_applications (
	ogtApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	entityId VARCHAR(75) null,
	doYouWant VARCHAR(75) null,
	typeOfApplicant VARCHAR(75) null,
	natureOfApplicant VARCHAR(75) null,
	typeOfMatter VARCHAR(75) null,
	typeOfDebt VARCHAR(75) null,
	debtStatute VARCHAR(75) null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	expiredLicenseAppNumber VARCHAR(75) null,
	caseId VARCHAR(500) null,
	icmDocumentsPath VARCHAR(500) null,
	pdfFileEntryId LONG,
	appCurrentStageName VARCHAR(75) null,
	registeredManufacturer VARCHAR(75) null,
	prospectingRightsNum VARCHAR(75) null,
	typeOfBankruptcy VARCHAR(75) null
);

create table nbp_ogt_claim_property (
	ogtClaimToPropertyId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	propertyDate DATE null,
	propClaimDesc VARCHAR(1000) null,
	affidavitDesc VARCHAR(1000) null,
	ogtApplicationId LONG
);

create table nbp_ogt_claim_to_spouse (
	ogtClaimToSpouseId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	spouseDate DATE null,
	claimSpouseDesc VARCHAR(1000) null,
	nameCompletionForm VARCHAR(75) null,
	nameCompletionDate DATE null,
	compPersonAddress VARCHAR(1000) null,
	justicePeaceParish VARCHAR(75) null,
	nameJusticeOfPeace VARCHAR(75) null,
	nameJusticeDate DATE null,
	officialAmtClaim VARCHAR(75) null,
	officialSection VARCHAR(75) null,
	officialAmtVoting VARCHAR(75) null,
	officialAmtVotingDate DATE null,
	officialPayment VARCHAR(75) null,
	officialPaymentDate DATE null,
	ogtApplicationId LONG
);

create table nbp_ogt_claimant_detail (
	ogtClaimantDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	claimantName VARCHAR(75) null,
	claimantFirstName VARCHAR(75) null,
	claimantLastName VARCHAR(75) null,
	claimantCompanyName VARCHAR(75) null,
	claimantAddress VARCHAR(1000) null,
	claimantEmailAddr VARCHAR(75) null,
	claimantTeleNum VARCHAR(75) null,
	claimantFaxNo VARCHAR(75) null,
	claimantDate DATE null,
	claimantTrn VARCHAR(75) null,
	claimantRelative VARCHAR(75) null,
	ogtApplicationId LONG
);

create table nbp_ogt_current_stage (
	uuid_ VARCHAR(75) null,
	ogtAppCurrentStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormStep VARCHAR(75) null,
	ogtApplicationId LONG
);

create table nbp_ogt_insolvent_person_det (
	ogtInsolventPersonDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	natureOfInsolvent VARCHAR(75) null,
	insolventFirstName VARCHAR(75) null,
	insolventLastName VARCHAR(75) null,
	insolventCompanyName VARCHAR(75) null,
	insolventDebtStatute VARCHAR(75) null,
	ogtApplicationId LONG
);

create table nbp_ogt_proof_of_claim (
	ogtProofOfClaimId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	claimProofMatter VARCHAR(500) null,
	claimDebtorName VARCHAR(75) null,
	claimantName VARCHAR(75) null,
	claimSentAddress VARCHAR(500) null,
	claimSentPhoneNum VARCHAR(75) null,
	claimSentFaxNo VARCHAR(75) null,
	claimSentEmailAddr VARCHAR(75) null,
	claimCompName VARCHAR(75) null,
	claimCertifyCheck VARCHAR(75) null,
	claimCompPosition VARCHAR(75) null,
	claimName VARCHAR(75) null,
	claimByCredDebtor VARCHAR(500) null,
	claimDateAppli DATE null,
	claimByDebtTotalVal VARCHAR(75) null,
	claimByDebtStatement VARCHAR(500) null,
	claimCategory VARCHAR(500) null,
	claimUnsecured VARCHAR(75) null,
	claimRegardingAmt VARCHAR(75) null,
	indicateCategoryOne VARCHAR(500) null,
	indicateCategoryTwo VARCHAR(500) null,
	indicateCategoryThree VARCHAR(500) null,
	indicateCategoryFour VARCHAR(500) null,
	otherPleaseSpecify VARCHAR(75) null,
	claimSecured VARCHAR(75) null,
	claimSecuredOne VARCHAR(75) null,
	claimDesc VARCHAR(500) null,
	aboveNamedCreditor VARCHAR(500) null,
	paymentDetailDesc VARCHAR(1000) null,
	inCaseOfBankruptcy VARCHAR(500) null,
	ogtApplicationId LONG
);

create table nbp_ogt_section_b (
	ogtSectionBId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	theDebtor VARCHAR(75) null,
	name VARCHAR(75) null,
	dateOfInsolvencyOfDebtor DATE null,
	totalValueOfClaim VARCHAR(75) null,
	statementOfAccount VARCHAR(500) null,
	unsecuredClaim VARCHAR(75) null,
	unsecuredClaimOf VARCHAR(75) null,
	regardingTheAmount VARCHAR(75) null,
	categoryOne VARCHAR(500) null,
	categoryTwo VARCHAR(500) null,
	categoryThree VARCHAR(500) null,
	categoryFour VARCHAR(500) null,
	otherPleaseSpecify VARCHAR(75) null,
	securedClaim VARCHAR(75) null,
	securedClaimOf VARCHAR(75) null,
	description VARCHAR(500) null,
	relationWithDebtor VARCHAR(75) null,
	bankruptcyEventDescription VARCHAR(500) null,
	bankruptcyOfAnIndividual VARCHAR(500) null,
	ogtApplicationId LONG
);