/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.acquire.application.form.service.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.acquire.application.form.service.model.AcquireApplication;
import com.nbp.acquire.application.form.service.service.AcquireApplicationLocalService;
import com.nbp.acquire.application.form.service.service.persistence.AcquireApplicationDetailsPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireApplicationPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireCurrentStagePersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireDocumentListPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireLandApplicantDetailsPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireLandEmploymentPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireLandPropertyDetailsPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquirePaymentPlanPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquirePropertyDetailsPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the acquire application local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.acquire.application.form.service.service.impl.AcquireApplicationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.acquire.application.form.service.service.impl.AcquireApplicationLocalServiceImpl
 * @generated
 */
public abstract class AcquireApplicationLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AcquireApplicationLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AcquireApplicationLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.acquire.application.form.service.service.AcquireApplicationLocalServiceUtil</code>.
	 */

	/**
	 * Adds the acquire application to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AcquireApplicationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param acquireApplication the acquire application
	 * @return the acquire application that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AcquireApplication addAcquireApplication(
		AcquireApplication acquireApplication) {

		acquireApplication.setNew(true);

		return acquireApplicationPersistence.update(acquireApplication);
	}

	/**
	 * Creates a new acquire application with the primary key. Does not add the acquire application to the database.
	 *
	 * @param acquireApplicationId the primary key for the new acquire application
	 * @return the new acquire application
	 */
	@Override
	@Transactional(enabled = false)
	public AcquireApplication createAcquireApplication(
		long acquireApplicationId) {

		return acquireApplicationPersistence.create(acquireApplicationId);
	}

	/**
	 * Deletes the acquire application with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AcquireApplicationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param acquireApplicationId the primary key of the acquire application
	 * @return the acquire application that was removed
	 * @throws PortalException if a acquire application with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AcquireApplication deleteAcquireApplication(
			long acquireApplicationId)
		throws PortalException {

		return acquireApplicationPersistence.remove(acquireApplicationId);
	}

	/**
	 * Deletes the acquire application from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AcquireApplicationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param acquireApplication the acquire application
	 * @return the acquire application that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AcquireApplication deleteAcquireApplication(
		AcquireApplication acquireApplication) {

		return acquireApplicationPersistence.remove(acquireApplication);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return acquireApplicationPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AcquireApplication.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return acquireApplicationPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.acquire.application.form.service.model.impl.AcquireApplicationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return acquireApplicationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.acquire.application.form.service.model.impl.AcquireApplicationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return acquireApplicationPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return acquireApplicationPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return acquireApplicationPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AcquireApplication fetchAcquireApplication(
		long acquireApplicationId) {

		return acquireApplicationPersistence.fetchByPrimaryKey(
			acquireApplicationId);
	}

	/**
	 * Returns the acquire application matching the UUID and group.
	 *
	 * @param uuid the acquire application's UUID
	 * @param groupId the primary key of the group
	 * @return the matching acquire application, or <code>null</code> if a matching acquire application could not be found
	 */
	@Override
	public AcquireApplication fetchAcquireApplicationByUuidAndGroupId(
		String uuid, long groupId) {

		return acquireApplicationPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the acquire application with the primary key.
	 *
	 * @param acquireApplicationId the primary key of the acquire application
	 * @return the acquire application
	 * @throws PortalException if a acquire application with the primary key could not be found
	 */
	@Override
	public AcquireApplication getAcquireApplication(long acquireApplicationId)
		throws PortalException {

		return acquireApplicationPersistence.findByPrimaryKey(
			acquireApplicationId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			acquireApplicationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AcquireApplication.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"acquireApplicationId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			acquireApplicationLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AcquireApplication.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"acquireApplicationId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			acquireApplicationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AcquireApplication.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"acquireApplicationId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<AcquireApplication>() {

				@Override
				public void performAction(AcquireApplication acquireApplication)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, acquireApplication);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(AcquireApplication.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return acquireApplicationPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement AcquireApplicationLocalServiceImpl#deleteAcquireApplication(AcquireApplication) to avoid orphaned data");
		}

		return acquireApplicationLocalService.deleteAcquireApplication(
			(AcquireApplication)persistedModel);
	}

	@Override
	public BasePersistence<AcquireApplication> getBasePersistence() {
		return acquireApplicationPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return acquireApplicationPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the acquire applications matching the UUID and company.
	 *
	 * @param uuid the UUID of the acquire applications
	 * @param companyId the primary key of the company
	 * @return the matching acquire applications, or an empty list if no matches were found
	 */
	@Override
	public List<AcquireApplication> getAcquireApplicationsByUuidAndCompanyId(
		String uuid, long companyId) {

		return acquireApplicationPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of acquire applications matching the UUID and company.
	 *
	 * @param uuid the UUID of the acquire applications
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of acquire applications
	 * @param end the upper bound of the range of acquire applications (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching acquire applications, or an empty list if no matches were found
	 */
	@Override
	public List<AcquireApplication> getAcquireApplicationsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<AcquireApplication> orderByComparator) {

		return acquireApplicationPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the acquire application matching the UUID and group.
	 *
	 * @param uuid the acquire application's UUID
	 * @param groupId the primary key of the group
	 * @return the matching acquire application
	 * @throws PortalException if a matching acquire application could not be found
	 */
	@Override
	public AcquireApplication getAcquireApplicationByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return acquireApplicationPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the acquire applications.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.acquire.application.form.service.model.impl.AcquireApplicationModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of acquire applications
	 * @param end the upper bound of the range of acquire applications (not inclusive)
	 * @return the range of acquire applications
	 */
	@Override
	public List<AcquireApplication> getAcquireApplications(int start, int end) {
		return acquireApplicationPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of acquire applications.
	 *
	 * @return the number of acquire applications
	 */
	@Override
	public int getAcquireApplicationsCount() {
		return acquireApplicationPersistence.countAll();
	}

	/**
	 * Updates the acquire application in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AcquireApplicationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param acquireApplication the acquire application
	 * @return the acquire application that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AcquireApplication updateAcquireApplication(
		AcquireApplication acquireApplication) {

		return acquireApplicationPersistence.update(acquireApplication);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AcquireApplicationLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		acquireApplicationLocalService =
			(AcquireApplicationLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AcquireApplicationLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AcquireApplication.class;
	}

	protected String getModelClassName() {
		return AcquireApplication.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				acquireApplicationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected AcquireApplicationLocalService acquireApplicationLocalService;

	@Reference
	protected AcquireApplicationPersistence acquireApplicationPersistence;

	@Reference
	protected AcquireApplicationDetailsPersistence
		acquireApplicationDetailsPersistence;

	@Reference
	protected AcquireCurrentStagePersistence acquireCurrentStagePersistence;

	@Reference
	protected AcquireDocumentListPersistence acquireDocumentListPersistence;

	@Reference
	protected AcquireLandApplicantDetailsPersistence
		acquireLandApplicantDetailsPersistence;

	@Reference
	protected AcquireLandEmploymentPersistence acquireLandEmploymentPersistence;

	@Reference
	protected AcquireLandPropertyDetailsPersistence
		acquireLandPropertyDetailsPersistence;

	@Reference
	protected AcquirePaymentPlanPersistence acquirePaymentPlanPersistence;

	@Reference
	protected AcquirePropertyDetailsPersistence
		acquirePropertyDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AcquireApplicationLocalServiceBaseImpl.class);

}