/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.acquire.application.form.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.acquire.application.form.service.model.AcquireLandEmployment;
import com.nbp.acquire.application.form.service.service.AcquireLandEmploymentLocalService;
import com.nbp.acquire.application.form.service.service.persistence.AcquireApplicationDetailsPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireApplicationPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireCurrentStagePersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireDocumentListPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireLandApplicantDetailsPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireLandEmploymentPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquireLandPropertyDetailsPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquirePaymentPlanPersistence;
import com.nbp.acquire.application.form.service.service.persistence.AcquirePropertyDetailsPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the acquire land employment local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.acquire.application.form.service.service.impl.AcquireLandEmploymentLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.acquire.application.form.service.service.impl.AcquireLandEmploymentLocalServiceImpl
 * @generated
 */
public abstract class AcquireLandEmploymentLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AcquireLandEmploymentLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AcquireLandEmploymentLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.acquire.application.form.service.service.AcquireLandEmploymentLocalServiceUtil</code>.
	 */

	/**
	 * Adds the acquire land employment to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AcquireLandEmploymentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param acquireLandEmployment the acquire land employment
	 * @return the acquire land employment that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AcquireLandEmployment addAcquireLandEmployment(
		AcquireLandEmployment acquireLandEmployment) {

		acquireLandEmployment.setNew(true);

		return acquireLandEmploymentPersistence.update(acquireLandEmployment);
	}

	/**
	 * Creates a new acquire land employment with the primary key. Does not add the acquire land employment to the database.
	 *
	 * @param acquireLandEmploymentId the primary key for the new acquire land employment
	 * @return the new acquire land employment
	 */
	@Override
	@Transactional(enabled = false)
	public AcquireLandEmployment createAcquireLandEmployment(
		long acquireLandEmploymentId) {

		return acquireLandEmploymentPersistence.create(acquireLandEmploymentId);
	}

	/**
	 * Deletes the acquire land employment with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AcquireLandEmploymentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param acquireLandEmploymentId the primary key of the acquire land employment
	 * @return the acquire land employment that was removed
	 * @throws PortalException if a acquire land employment with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AcquireLandEmployment deleteAcquireLandEmployment(
			long acquireLandEmploymentId)
		throws PortalException {

		return acquireLandEmploymentPersistence.remove(acquireLandEmploymentId);
	}

	/**
	 * Deletes the acquire land employment from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AcquireLandEmploymentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param acquireLandEmployment the acquire land employment
	 * @return the acquire land employment that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AcquireLandEmployment deleteAcquireLandEmployment(
		AcquireLandEmployment acquireLandEmployment) {

		return acquireLandEmploymentPersistence.remove(acquireLandEmployment);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return acquireLandEmploymentPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AcquireLandEmployment.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return acquireLandEmploymentPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.acquire.application.form.service.model.impl.AcquireLandEmploymentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return acquireLandEmploymentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.acquire.application.form.service.model.impl.AcquireLandEmploymentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return acquireLandEmploymentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return acquireLandEmploymentPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return acquireLandEmploymentPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AcquireLandEmployment fetchAcquireLandEmployment(
		long acquireLandEmploymentId) {

		return acquireLandEmploymentPersistence.fetchByPrimaryKey(
			acquireLandEmploymentId);
	}

	/**
	 * Returns the acquire land employment with the primary key.
	 *
	 * @param acquireLandEmploymentId the primary key of the acquire land employment
	 * @return the acquire land employment
	 * @throws PortalException if a acquire land employment with the primary key could not be found
	 */
	@Override
	public AcquireLandEmployment getAcquireLandEmployment(
			long acquireLandEmploymentId)
		throws PortalException {

		return acquireLandEmploymentPersistence.findByPrimaryKey(
			acquireLandEmploymentId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			acquireLandEmploymentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AcquireLandEmployment.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"acquireLandEmploymentId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			acquireLandEmploymentLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			AcquireLandEmployment.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"acquireLandEmploymentId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			acquireLandEmploymentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AcquireLandEmployment.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"acquireLandEmploymentId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return acquireLandEmploymentPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement AcquireLandEmploymentLocalServiceImpl#deleteAcquireLandEmployment(AcquireLandEmployment) to avoid orphaned data");
		}

		return acquireLandEmploymentLocalService.deleteAcquireLandEmployment(
			(AcquireLandEmployment)persistedModel);
	}

	@Override
	public BasePersistence<AcquireLandEmployment> getBasePersistence() {
		return acquireLandEmploymentPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return acquireLandEmploymentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the acquire land employments.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.acquire.application.form.service.model.impl.AcquireLandEmploymentModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of acquire land employments
	 * @param end the upper bound of the range of acquire land employments (not inclusive)
	 * @return the range of acquire land employments
	 */
	@Override
	public List<AcquireLandEmployment> getAcquireLandEmployments(
		int start, int end) {

		return acquireLandEmploymentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of acquire land employments.
	 *
	 * @return the number of acquire land employments
	 */
	@Override
	public int getAcquireLandEmploymentsCount() {
		return acquireLandEmploymentPersistence.countAll();
	}

	/**
	 * Updates the acquire land employment in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AcquireLandEmploymentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param acquireLandEmployment the acquire land employment
	 * @return the acquire land employment that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AcquireLandEmployment updateAcquireLandEmployment(
		AcquireLandEmployment acquireLandEmployment) {

		return acquireLandEmploymentPersistence.update(acquireLandEmployment);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AcquireLandEmploymentLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		acquireLandEmploymentLocalService =
			(AcquireLandEmploymentLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AcquireLandEmploymentLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AcquireLandEmployment.class;
	}

	protected String getModelClassName() {
		return AcquireLandEmployment.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				acquireLandEmploymentPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AcquireApplicationPersistence acquireApplicationPersistence;

	@Reference
	protected AcquireApplicationDetailsPersistence
		acquireApplicationDetailsPersistence;

	@Reference
	protected AcquireCurrentStagePersistence acquireCurrentStagePersistence;

	@Reference
	protected AcquireDocumentListPersistence acquireDocumentListPersistence;

	@Reference
	protected AcquireLandApplicantDetailsPersistence
		acquireLandApplicantDetailsPersistence;

	protected AcquireLandEmploymentLocalService
		acquireLandEmploymentLocalService;

	@Reference
	protected AcquireLandEmploymentPersistence acquireLandEmploymentPersistence;

	@Reference
	protected AcquireLandPropertyDetailsPersistence
		acquireLandPropertyDetailsPersistence;

	@Reference
	protected AcquirePaymentPlanPersistence acquirePaymentPlanPersistence;

	@Reference
	protected AcquirePropertyDetailsPersistence
		acquirePropertyDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AcquireLandEmploymentLocalServiceBaseImpl.class);

}