/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.hsra.application.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.hsra.application.service.model.BrokerDeclarationInfo;
import com.nbp.hsra.application.service.model.BrokerDeclarationInfoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BrokerDeclarationInfo service. Represents a row in the &quot;nbp_hsra_broker_declare&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BrokerDeclarationInfoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BrokerDeclarationInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BrokerDeclarationInfoImpl
 * @generated
 */
@JSON(strict = true)
public class BrokerDeclarationInfoModelImpl
	extends BaseModelImpl<BrokerDeclarationInfo>
	implements BrokerDeclarationInfoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a broker declaration info model instance should use the <code>BrokerDeclarationInfo</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_hsra_broker_declare";

	public static final Object[][] TABLE_COLUMNS = {
		{"brokerDeclareInfoId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"brokerOperatorName", Types.VARCHAR}, {"brokerTitle", Types.VARCHAR},
		{"signDate", Types.TIMESTAMP}, {"hsraApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("brokerDeclareInfoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("brokerOperatorName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("brokerTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("signDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hsraApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_hsra_broker_declare (brokerDeclareInfoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,brokerOperatorName VARCHAR(75) null,brokerTitle VARCHAR(75) null,signDate DATE null,hsraApplicationId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_hsra_broker_declare";

	public static final String ORDER_BY_JPQL =
		" ORDER BY brokerDeclarationInfo.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_hsra_broker_declare.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HSRAAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BrokerDeclarationInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _brokerDeclareInfoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBrokerDeclareInfoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _brokerDeclareInfoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BrokerDeclarationInfo.class;
	}

	@Override
	public String getModelClassName() {
		return BrokerDeclarationInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BrokerDeclarationInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BrokerDeclarationInfo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BrokerDeclarationInfo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BrokerDeclarationInfo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BrokerDeclarationInfo, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BrokerDeclarationInfo, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BrokerDeclarationInfo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BrokerDeclarationInfo, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BrokerDeclarationInfo, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<BrokerDeclarationInfo, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<BrokerDeclarationInfo, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BrokerDeclarationInfo, Object>>();

			attributeGetterFunctions.put(
				"brokerDeclareInfoId",
				BrokerDeclarationInfo::getBrokerDeclareInfoId);
			attributeGetterFunctions.put(
				"groupId", BrokerDeclarationInfo::getGroupId);
			attributeGetterFunctions.put(
				"companyId", BrokerDeclarationInfo::getCompanyId);
			attributeGetterFunctions.put(
				"userId", BrokerDeclarationInfo::getUserId);
			attributeGetterFunctions.put(
				"userName", BrokerDeclarationInfo::getUserName);
			attributeGetterFunctions.put(
				"createDate", BrokerDeclarationInfo::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", BrokerDeclarationInfo::getModifiedDate);
			attributeGetterFunctions.put(
				"brokerOperatorName",
				BrokerDeclarationInfo::getBrokerOperatorName);
			attributeGetterFunctions.put(
				"brokerTitle", BrokerDeclarationInfo::getBrokerTitle);
			attributeGetterFunctions.put(
				"signDate", BrokerDeclarationInfo::getSignDate);
			attributeGetterFunctions.put(
				"hsraApplicationId",
				BrokerDeclarationInfo::getHsraApplicationId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<BrokerDeclarationInfo, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BrokerDeclarationInfo, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<BrokerDeclarationInfo, ?>>();

			attributeSetterBiConsumers.put(
				"brokerDeclareInfoId",
				(BiConsumer<BrokerDeclarationInfo, Long>)
					BrokerDeclarationInfo::setBrokerDeclareInfoId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<BrokerDeclarationInfo, Long>)
					BrokerDeclarationInfo::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<BrokerDeclarationInfo, Long>)
					BrokerDeclarationInfo::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<BrokerDeclarationInfo, Long>)
					BrokerDeclarationInfo::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<BrokerDeclarationInfo, String>)
					BrokerDeclarationInfo::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<BrokerDeclarationInfo, Date>)
					BrokerDeclarationInfo::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<BrokerDeclarationInfo, Date>)
					BrokerDeclarationInfo::setModifiedDate);
			attributeSetterBiConsumers.put(
				"brokerOperatorName",
				(BiConsumer<BrokerDeclarationInfo, String>)
					BrokerDeclarationInfo::setBrokerOperatorName);
			attributeSetterBiConsumers.put(
				"brokerTitle",
				(BiConsumer<BrokerDeclarationInfo, String>)
					BrokerDeclarationInfo::setBrokerTitle);
			attributeSetterBiConsumers.put(
				"signDate",
				(BiConsumer<BrokerDeclarationInfo, Date>)
					BrokerDeclarationInfo::setSignDate);
			attributeSetterBiConsumers.put(
				"hsraApplicationId",
				(BiConsumer<BrokerDeclarationInfo, Long>)
					BrokerDeclarationInfo::setHsraApplicationId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getBrokerDeclareInfoId() {
		return _brokerDeclareInfoId;
	}

	@Override
	public void setBrokerDeclareInfoId(long brokerDeclareInfoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_brokerDeclareInfoId = brokerDeclareInfoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getBrokerOperatorName() {
		if (_brokerOperatorName == null) {
			return "";
		}
		else {
			return _brokerOperatorName;
		}
	}

	@Override
	public void setBrokerOperatorName(String brokerOperatorName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_brokerOperatorName = brokerOperatorName;
	}

	@JSON
	@Override
	public String getBrokerTitle() {
		if (_brokerTitle == null) {
			return "";
		}
		else {
			return _brokerTitle;
		}
	}

	@Override
	public void setBrokerTitle(String brokerTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_brokerTitle = brokerTitle;
	}

	@JSON
	@Override
	public Date getSignDate() {
		return _signDate;
	}

	@Override
	public void setSignDate(Date signDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_signDate = signDate;
	}

	@JSON
	@Override
	public long getHsraApplicationId() {
		return _hsraApplicationId;
	}

	@Override
	public void setHsraApplicationId(long hsraApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hsraApplicationId = hsraApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalHsraApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("hsraApplicationId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BrokerDeclarationInfo.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BrokerDeclarationInfo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BrokerDeclarationInfo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BrokerDeclarationInfoImpl brokerDeclarationInfoImpl =
			new BrokerDeclarationInfoImpl();

		brokerDeclarationInfoImpl.setBrokerDeclareInfoId(
			getBrokerDeclareInfoId());
		brokerDeclarationInfoImpl.setGroupId(getGroupId());
		brokerDeclarationInfoImpl.setCompanyId(getCompanyId());
		brokerDeclarationInfoImpl.setUserId(getUserId());
		brokerDeclarationInfoImpl.setUserName(getUserName());
		brokerDeclarationInfoImpl.setCreateDate(getCreateDate());
		brokerDeclarationInfoImpl.setModifiedDate(getModifiedDate());
		brokerDeclarationInfoImpl.setBrokerOperatorName(
			getBrokerOperatorName());
		brokerDeclarationInfoImpl.setBrokerTitle(getBrokerTitle());
		brokerDeclarationInfoImpl.setSignDate(getSignDate());
		brokerDeclarationInfoImpl.setHsraApplicationId(getHsraApplicationId());

		brokerDeclarationInfoImpl.resetOriginalValues();

		return brokerDeclarationInfoImpl;
	}

	@Override
	public BrokerDeclarationInfo cloneWithOriginalValues() {
		BrokerDeclarationInfoImpl brokerDeclarationInfoImpl =
			new BrokerDeclarationInfoImpl();

		brokerDeclarationInfoImpl.setBrokerDeclareInfoId(
			this.<Long>getColumnOriginalValue("brokerDeclareInfoId"));
		brokerDeclarationInfoImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		brokerDeclarationInfoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		brokerDeclarationInfoImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		brokerDeclarationInfoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		brokerDeclarationInfoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		brokerDeclarationInfoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		brokerDeclarationInfoImpl.setBrokerOperatorName(
			this.<String>getColumnOriginalValue("brokerOperatorName"));
		brokerDeclarationInfoImpl.setBrokerTitle(
			this.<String>getColumnOriginalValue("brokerTitle"));
		brokerDeclarationInfoImpl.setSignDate(
			this.<Date>getColumnOriginalValue("signDate"));
		brokerDeclarationInfoImpl.setHsraApplicationId(
			this.<Long>getColumnOriginalValue("hsraApplicationId"));

		return brokerDeclarationInfoImpl;
	}

	@Override
	public int compareTo(BrokerDeclarationInfo brokerDeclarationInfo) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), brokerDeclarationInfo.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BrokerDeclarationInfo)) {
			return false;
		}

		BrokerDeclarationInfo brokerDeclarationInfo =
			(BrokerDeclarationInfo)object;

		long primaryKey = brokerDeclarationInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BrokerDeclarationInfo> toCacheModel() {
		BrokerDeclarationInfoCacheModel brokerDeclarationInfoCacheModel =
			new BrokerDeclarationInfoCacheModel();

		brokerDeclarationInfoCacheModel.brokerDeclareInfoId =
			getBrokerDeclareInfoId();

		brokerDeclarationInfoCacheModel.groupId = getGroupId();

		brokerDeclarationInfoCacheModel.companyId = getCompanyId();

		brokerDeclarationInfoCacheModel.userId = getUserId();

		brokerDeclarationInfoCacheModel.userName = getUserName();

		String userName = brokerDeclarationInfoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			brokerDeclarationInfoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			brokerDeclarationInfoCacheModel.createDate = createDate.getTime();
		}
		else {
			brokerDeclarationInfoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			brokerDeclarationInfoCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			brokerDeclarationInfoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		brokerDeclarationInfoCacheModel.brokerOperatorName =
			getBrokerOperatorName();

		String brokerOperatorName =
			brokerDeclarationInfoCacheModel.brokerOperatorName;

		if ((brokerOperatorName != null) &&
			(brokerOperatorName.length() == 0)) {

			brokerDeclarationInfoCacheModel.brokerOperatorName = null;
		}

		brokerDeclarationInfoCacheModel.brokerTitle = getBrokerTitle();

		String brokerTitle = brokerDeclarationInfoCacheModel.brokerTitle;

		if ((brokerTitle != null) && (brokerTitle.length() == 0)) {
			brokerDeclarationInfoCacheModel.brokerTitle = null;
		}

		Date signDate = getSignDate();

		if (signDate != null) {
			brokerDeclarationInfoCacheModel.signDate = signDate.getTime();
		}
		else {
			brokerDeclarationInfoCacheModel.signDate = Long.MIN_VALUE;
		}

		brokerDeclarationInfoCacheModel.hsraApplicationId =
			getHsraApplicationId();

		return brokerDeclarationInfoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BrokerDeclarationInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BrokerDeclarationInfo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BrokerDeclarationInfo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BrokerDeclarationInfo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BrokerDeclarationInfo>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BrokerDeclarationInfo.class, ModelWrapper.class);

	}

	private long _brokerDeclareInfoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _brokerOperatorName;
	private String _brokerTitle;
	private Date _signDate;
	private long _hsraApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<BrokerDeclarationInfo, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BrokerDeclarationInfo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("brokerDeclareInfoId", _brokerDeclareInfoId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("brokerOperatorName", _brokerOperatorName);
		_columnOriginalValues.put("brokerTitle", _brokerTitle);
		_columnOriginalValues.put("signDate", _signDate);
		_columnOriginalValues.put("hsraApplicationId", _hsraApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("brokerDeclareInfoId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("brokerOperatorName", 128L);

		columnBitmasks.put("brokerTitle", 256L);

		columnBitmasks.put("signDate", 512L);

		columnBitmasks.put("hsraApplicationId", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BrokerDeclarationInfo _escapedModel;

}