/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.hsra.application.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.hsra.application.service.model.DetailOfSources;
import com.nbp.hsra.application.service.model.DetailOfSourcesModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DetailOfSources service. Represents a row in the &quot;nbp_hsra_noti_detail_source&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DetailOfSourcesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DetailOfSourcesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DetailOfSourcesImpl
 * @generated
 */
@JSON(strict = true)
public class DetailOfSourcesModelImpl
	extends BaseModelImpl<DetailOfSources> implements DetailOfSourcesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a detail of sources model instance should use the <code>DetailOfSources</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_hsra_noti_detail_source";

	public static final Object[][] TABLE_COLUMNS = {
		{"detailOfSourcesId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"sourceIdentification", Types.VARCHAR},
		{"sourceLocation", Types.VARCHAR}, {"stateActivity", Types.VARCHAR},
		{"hsraApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("detailOfSourcesId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("sourceIdentification", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sourceLocation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stateActivity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hsraApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_hsra_noti_detail_source (detailOfSourcesId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,sourceIdentification VARCHAR(75) null,sourceLocation VARCHAR(75) null,stateActivity VARCHAR(75) null,hsraApplicationId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_hsra_noti_detail_source";

	public static final String ORDER_BY_JPQL =
		" ORDER BY detailOfSources.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_hsra_noti_detail_source.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HSRAAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DetailOfSourcesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _detailOfSourcesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDetailOfSourcesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _detailOfSourcesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DetailOfSources.class;
	}

	@Override
	public String getModelClassName() {
		return DetailOfSources.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DetailOfSources, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DetailOfSources, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DetailOfSources, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DetailOfSources)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DetailOfSources, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DetailOfSources, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DetailOfSources)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DetailOfSources, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DetailOfSources, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DetailOfSources, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DetailOfSources, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DetailOfSources, Object>>();

			attributeGetterFunctions.put(
				"detailOfSourcesId", DetailOfSources::getDetailOfSourcesId);
			attributeGetterFunctions.put(
				"groupId", DetailOfSources::getGroupId);
			attributeGetterFunctions.put(
				"companyId", DetailOfSources::getCompanyId);
			attributeGetterFunctions.put("userId", DetailOfSources::getUserId);
			attributeGetterFunctions.put(
				"userName", DetailOfSources::getUserName);
			attributeGetterFunctions.put(
				"createDate", DetailOfSources::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", DetailOfSources::getModifiedDate);
			attributeGetterFunctions.put(
				"sourceIdentification",
				DetailOfSources::getSourceIdentification);
			attributeGetterFunctions.put(
				"sourceLocation", DetailOfSources::getSourceLocation);
			attributeGetterFunctions.put(
				"stateActivity", DetailOfSources::getStateActivity);
			attributeGetterFunctions.put(
				"hsraApplicationId", DetailOfSources::getHsraApplicationId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DetailOfSources, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DetailOfSources, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<DetailOfSources, ?>>();

			attributeSetterBiConsumers.put(
				"detailOfSourcesId",
				(BiConsumer<DetailOfSources, Long>)
					DetailOfSources::setDetailOfSourcesId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<DetailOfSources, Long>)DetailOfSources::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<DetailOfSources, Long>)
					DetailOfSources::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<DetailOfSources, Long>)DetailOfSources::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<DetailOfSources, String>)
					DetailOfSources::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<DetailOfSources, Date>)
					DetailOfSources::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<DetailOfSources, Date>)
					DetailOfSources::setModifiedDate);
			attributeSetterBiConsumers.put(
				"sourceIdentification",
				(BiConsumer<DetailOfSources, String>)
					DetailOfSources::setSourceIdentification);
			attributeSetterBiConsumers.put(
				"sourceLocation",
				(BiConsumer<DetailOfSources, String>)
					DetailOfSources::setSourceLocation);
			attributeSetterBiConsumers.put(
				"stateActivity",
				(BiConsumer<DetailOfSources, String>)
					DetailOfSources::setStateActivity);
			attributeSetterBiConsumers.put(
				"hsraApplicationId",
				(BiConsumer<DetailOfSources, Long>)
					DetailOfSources::setHsraApplicationId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getDetailOfSourcesId() {
		return _detailOfSourcesId;
	}

	@Override
	public void setDetailOfSourcesId(long detailOfSourcesId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_detailOfSourcesId = detailOfSourcesId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getSourceIdentification() {
		if (_sourceIdentification == null) {
			return "";
		}
		else {
			return _sourceIdentification;
		}
	}

	@Override
	public void setSourceIdentification(String sourceIdentification) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sourceIdentification = sourceIdentification;
	}

	@JSON
	@Override
	public String getSourceLocation() {
		if (_sourceLocation == null) {
			return "";
		}
		else {
			return _sourceLocation;
		}
	}

	@Override
	public void setSourceLocation(String sourceLocation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sourceLocation = sourceLocation;
	}

	@JSON
	@Override
	public String getStateActivity() {
		if (_stateActivity == null) {
			return "";
		}
		else {
			return _stateActivity;
		}
	}

	@Override
	public void setStateActivity(String stateActivity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateActivity = stateActivity;
	}

	@JSON
	@Override
	public long getHsraApplicationId() {
		return _hsraApplicationId;
	}

	@Override
	public void setHsraApplicationId(long hsraApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hsraApplicationId = hsraApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalHsraApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("hsraApplicationId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DetailOfSources.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DetailOfSources toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DetailOfSources>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DetailOfSourcesImpl detailOfSourcesImpl = new DetailOfSourcesImpl();

		detailOfSourcesImpl.setDetailOfSourcesId(getDetailOfSourcesId());
		detailOfSourcesImpl.setGroupId(getGroupId());
		detailOfSourcesImpl.setCompanyId(getCompanyId());
		detailOfSourcesImpl.setUserId(getUserId());
		detailOfSourcesImpl.setUserName(getUserName());
		detailOfSourcesImpl.setCreateDate(getCreateDate());
		detailOfSourcesImpl.setModifiedDate(getModifiedDate());
		detailOfSourcesImpl.setSourceIdentification(getSourceIdentification());
		detailOfSourcesImpl.setSourceLocation(getSourceLocation());
		detailOfSourcesImpl.setStateActivity(getStateActivity());
		detailOfSourcesImpl.setHsraApplicationId(getHsraApplicationId());

		detailOfSourcesImpl.resetOriginalValues();

		return detailOfSourcesImpl;
	}

	@Override
	public DetailOfSources cloneWithOriginalValues() {
		DetailOfSourcesImpl detailOfSourcesImpl = new DetailOfSourcesImpl();

		detailOfSourcesImpl.setDetailOfSourcesId(
			this.<Long>getColumnOriginalValue("detailOfSourcesId"));
		detailOfSourcesImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		detailOfSourcesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		detailOfSourcesImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		detailOfSourcesImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		detailOfSourcesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		detailOfSourcesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		detailOfSourcesImpl.setSourceIdentification(
			this.<String>getColumnOriginalValue("sourceIdentification"));
		detailOfSourcesImpl.setSourceLocation(
			this.<String>getColumnOriginalValue("sourceLocation"));
		detailOfSourcesImpl.setStateActivity(
			this.<String>getColumnOriginalValue("stateActivity"));
		detailOfSourcesImpl.setHsraApplicationId(
			this.<Long>getColumnOriginalValue("hsraApplicationId"));

		return detailOfSourcesImpl;
	}

	@Override
	public int compareTo(DetailOfSources detailOfSources) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), detailOfSources.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DetailOfSources)) {
			return false;
		}

		DetailOfSources detailOfSources = (DetailOfSources)object;

		long primaryKey = detailOfSources.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DetailOfSources> toCacheModel() {
		DetailOfSourcesCacheModel detailOfSourcesCacheModel =
			new DetailOfSourcesCacheModel();

		detailOfSourcesCacheModel.detailOfSourcesId = getDetailOfSourcesId();

		detailOfSourcesCacheModel.groupId = getGroupId();

		detailOfSourcesCacheModel.companyId = getCompanyId();

		detailOfSourcesCacheModel.userId = getUserId();

		detailOfSourcesCacheModel.userName = getUserName();

		String userName = detailOfSourcesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			detailOfSourcesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			detailOfSourcesCacheModel.createDate = createDate.getTime();
		}
		else {
			detailOfSourcesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			detailOfSourcesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			detailOfSourcesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		detailOfSourcesCacheModel.sourceIdentification =
			getSourceIdentification();

		String sourceIdentification =
			detailOfSourcesCacheModel.sourceIdentification;

		if ((sourceIdentification != null) &&
			(sourceIdentification.length() == 0)) {

			detailOfSourcesCacheModel.sourceIdentification = null;
		}

		detailOfSourcesCacheModel.sourceLocation = getSourceLocation();

		String sourceLocation = detailOfSourcesCacheModel.sourceLocation;

		if ((sourceLocation != null) && (sourceLocation.length() == 0)) {
			detailOfSourcesCacheModel.sourceLocation = null;
		}

		detailOfSourcesCacheModel.stateActivity = getStateActivity();

		String stateActivity = detailOfSourcesCacheModel.stateActivity;

		if ((stateActivity != null) && (stateActivity.length() == 0)) {
			detailOfSourcesCacheModel.stateActivity = null;
		}

		detailOfSourcesCacheModel.hsraApplicationId = getHsraApplicationId();

		return detailOfSourcesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DetailOfSources, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DetailOfSources, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DetailOfSources, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DetailOfSources)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DetailOfSources>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DetailOfSources.class, ModelWrapper.class);

	}

	private long _detailOfSourcesId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _sourceIdentification;
	private String _sourceLocation;
	private String _stateActivity;
	private long _hsraApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<DetailOfSources, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DetailOfSources)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("detailOfSourcesId", _detailOfSourcesId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"sourceIdentification", _sourceIdentification);
		_columnOriginalValues.put("sourceLocation", _sourceLocation);
		_columnOriginalValues.put("stateActivity", _stateActivity);
		_columnOriginalValues.put("hsraApplicationId", _hsraApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("detailOfSourcesId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("sourceIdentification", 128L);

		columnBitmasks.put("sourceLocation", 256L);

		columnBitmasks.put("stateActivity", 512L);

		columnBitmasks.put("hsraApplicationId", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DetailOfSources _escapedModel;

}