/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.acquire.application.form.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AcquireApplicationDetails service. Represents a row in the &quot;nbp_acquire_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nbp.acquire.application.form.service.model.impl.AcquireApplicationDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nbp.acquire.application.form.service.model.impl.AcquireApplicationDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AcquireApplicationDetails
 * @generated
 */
@ProviderType
public interface AcquireApplicationDetailsModel
	extends BaseModel<AcquireApplicationDetails>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a acquire application details model instance should use the {@link AcquireApplicationDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this acquire application details.
	 *
	 * @return the primary key of this acquire application details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this acquire application details.
	 *
	 * @param primaryKey the primary key of this acquire application details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the acquire application details ID of this acquire application details.
	 *
	 * @return the acquire application details ID of this acquire application details
	 */
	public long getAcquireApplicationDetailsId();

	/**
	 * Sets the acquire application details ID of this acquire application details.
	 *
	 * @param acquireApplicationDetailsId the acquire application details ID of this acquire application details
	 */
	public void setAcquireApplicationDetailsId(
		long acquireApplicationDetailsId);

	/**
	 * Returns the group ID of this acquire application details.
	 *
	 * @return the group ID of this acquire application details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this acquire application details.
	 *
	 * @param groupId the group ID of this acquire application details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this acquire application details.
	 *
	 * @return the company ID of this acquire application details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this acquire application details.
	 *
	 * @param companyId the company ID of this acquire application details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this acquire application details.
	 *
	 * @return the user ID of this acquire application details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this acquire application details.
	 *
	 * @param userId the user ID of this acquire application details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this acquire application details.
	 *
	 * @return the user uuid of this acquire application details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this acquire application details.
	 *
	 * @param userUuid the user uuid of this acquire application details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this acquire application details.
	 *
	 * @return the user name of this acquire application details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this acquire application details.
	 *
	 * @param userName the user name of this acquire application details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this acquire application details.
	 *
	 * @return the create date of this acquire application details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this acquire application details.
	 *
	 * @param createDate the create date of this acquire application details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this acquire application details.
	 *
	 * @return the modified date of this acquire application details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this acquire application details.
	 *
	 * @param modifiedDate the modified date of this acquire application details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the applicant name of this acquire application details.
	 *
	 * @return the applicant name of this acquire application details
	 */
	@AutoEscape
	public String getApplicantName();

	/**
	 * Sets the applicant name of this acquire application details.
	 *
	 * @param applicantName the applicant name of this acquire application details
	 */
	public void setApplicantName(String applicantName);

	/**
	 * Returns the applicant organisation of this acquire application details.
	 *
	 * @return the applicant organisation of this acquire application details
	 */
	@AutoEscape
	public String getApplicantOrganisation();

	/**
	 * Sets the applicant organisation of this acquire application details.
	 *
	 * @param applicantOrganisation the applicant organisation of this acquire application details
	 */
	public void setApplicantOrganisation(String applicantOrganisation);

	/**
	 * Returns the applicant postal addr of this acquire application details.
	 *
	 * @return the applicant postal addr of this acquire application details
	 */
	@AutoEscape
	public String getApplicantPostalAddr();

	/**
	 * Sets the applicant postal addr of this acquire application details.
	 *
	 * @param applicantPostalAddr the applicant postal addr of this acquire application details
	 */
	public void setApplicantPostalAddr(String applicantPostalAddr);

	/**
	 * Returns the applicant email of this acquire application details.
	 *
	 * @return the applicant email of this acquire application details
	 */
	@AutoEscape
	public String getApplicantEmail();

	/**
	 * Sets the applicant email of this acquire application details.
	 *
	 * @param applicantEmail the applicant email of this acquire application details
	 */
	public void setApplicantEmail(String applicantEmail);

	/**
	 * Returns the applicant tele num of this acquire application details.
	 *
	 * @return the applicant tele num of this acquire application details
	 */
	@AutoEscape
	public String getApplicantTeleNum();

	/**
	 * Sets the applicant tele num of this acquire application details.
	 *
	 * @param applicantTeleNum the applicant tele num of this acquire application details
	 */
	public void setApplicantTeleNum(String applicantTeleNum);

	/**
	 * Returns the acquire application ID of this acquire application details.
	 *
	 * @return the acquire application ID of this acquire application details
	 */
	public long getAcquireApplicationId();

	/**
	 * Sets the acquire application ID of this acquire application details.
	 *
	 * @param acquireApplicationId the acquire application ID of this acquire application details
	 */
	public void setAcquireApplicationId(long acquireApplicationId);

	@Override
	public AcquireApplicationDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}