/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.agriculture.application.form.service.service.base;

import com.agriculture.application.form.service.model.AgricultureApiculture;
import com.agriculture.application.form.service.service.AgricultureApicultureService;
import com.agriculture.application.form.service.service.persistence.AgriApplicationCurrentStagePersistence;
import com.agriculture.application.form.service.service.persistence.AgricultueFarmerPersistence;
import com.agriculture.application.form.service.service.persistence.AgricultureApiculturePersistence;
import com.agriculture.application.form.service.service.persistence.AgricultureApplicationPersistence;
import com.agriculture.application.form.service.service.persistence.AgricultureAquaculturePersistence;
import com.agriculture.application.form.service.service.persistence.AgricultureBuildingPersistence;
import com.agriculture.application.form.service.service.persistence.AgricultureCropPersistence;
import com.agriculture.application.form.service.service.persistence.AgricultureFarmPersistence;
import com.agriculture.application.form.service.service.persistence.AgricultureLivestockPersistence;
import com.agriculture.application.form.service.service.persistence.AgricultureOrnamentalPersistence;
import com.agriculture.application.form.service.service.persistence.AgriculturePoultryPersistence;
import com.agriculture.application.form.service.service.persistence.AgriultureForestryPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the agriculture apiculture remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.agriculture.application.form.service.service.impl.AgricultureApicultureServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.agriculture.application.form.service.service.impl.AgricultureApicultureServiceImpl
 * @generated
 */
public abstract class AgricultureApicultureServiceBaseImpl
	extends BaseServiceImpl
	implements AgricultureApicultureService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AgricultureApicultureService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.agriculture.application.form.service.service.AgricultureApicultureServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AgricultureApicultureService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		agricultureApicultureService = (AgricultureApicultureService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AgricultureApicultureService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AgricultureApiculture.class;
	}

	protected String getModelClassName() {
		return AgricultureApiculture.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				agricultureApiculturePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AgriApplicationCurrentStagePersistence
		agriApplicationCurrentStagePersistence;

	@Reference
	protected AgricultueFarmerPersistence agricultueFarmerPersistence;

	@Reference
	protected com.agriculture.application.form.service.service.
		AgricultureApicultureLocalService agricultureApicultureLocalService;

	protected AgricultureApicultureService agricultureApicultureService;

	@Reference
	protected AgricultureApiculturePersistence agricultureApiculturePersistence;

	@Reference
	protected AgricultureApplicationPersistence
		agricultureApplicationPersistence;

	@Reference
	protected AgricultureAquaculturePersistence
		agricultureAquaculturePersistence;

	@Reference
	protected AgricultureBuildingPersistence agricultureBuildingPersistence;

	@Reference
	protected AgricultureCropPersistence agricultureCropPersistence;

	@Reference
	protected AgricultureFarmPersistence agricultureFarmPersistence;

	@Reference
	protected AgricultureLivestockPersistence agricultureLivestockPersistence;

	@Reference
	protected AgricultureOrnamentalPersistence agricultureOrnamentalPersistence;

	@Reference
	protected AgriculturePoultryPersistence agriculturePoultryPersistence;

	@Reference
	protected AgriultureForestryPersistence agriultureForestryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		AgricultureApicultureServiceBaseImpl.class);

}