create table nbp_film_additional_equip_list (
	FilmAdditionalEquipmentListId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	arrivalDate DATE null,
	airlineShipper VARCHAR(75) null,
	flightVesselNum VARCHAR(75) null,
	passengerName VARCHAR(75) null,
	entryPort VARCHAR(75) null,
	customsBroker VARCHAR(75) null,
	flightNumber VARCHAR(75) null,
	counter VARCHAR(75) null,
	filmApplicationId LONG
);

create table nbp_film_application (
	uuid_ VARCHAR(75) null,
	filmApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	entityId VARCHAR(75) null,
	typeOfTransaction VARCHAR(75) null,
	projectType VARCHAR(75) null,
	productionType VARCHAR(75) null,
	importEquipment VARCHAR(75) null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	caseId VARCHAR(500) null,
	icmDocumentsPath VARCHAR(500) null,
	pdfFileEntryId LONG,
	appCurrentStageName VARCHAR(75) null,
	isUpdateEquipmentList VARCHAR(75) null
);

create table nbp_film_application_payment (
	filmApplicationPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentDocId VARCHAR(75) null,
	paymentStatus VARCHAR(75) null,
	paymentFee VARCHAR(75) null,
	amountPaid VARCHAR(75) null,
	amountCurrency VARCHAR(75) null,
	transactionNumber VARCHAR(75) null,
	filmApplicationId LONG
);

create table nbp_film_company_details (
	filmCompanyDetailsId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyName VARCHAR(75) null,
	address VARCHAR(500) null,
	countryOrigin VARCHAR(75) null,
	telephoneNumber VARCHAR(75) null,
	mobile VARCHAR(75) null,
	contactPerson VARCHAR(75) null,
	email VARCHAR(75) null,
	position VARCHAR(75) null,
	filmApplicationId LONG
);

create table nbp_film_equipment_list (
	filmEquipmentListId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	item VARCHAR(75) null,
	serialNumber VARCHAR(75) null,
	weight VARCHAR(75) null,
	quantity VARCHAR(75) null,
	unitPrice VARCHAR(75) null,
	description VARCHAR(500) null,
	total VARCHAR(75) null,
	counter VARCHAR(75) null,
	equipmentList VARCHAR(75) null,
	flightNumber VARCHAR(75) null,
	filmApplicationId LONG
);

create table nbp_film_other_details (
	filmOtherDetailsId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	additionalPermits VARCHAR(500) null,
	additionalOtherPermits VARCHAR(75) null,
	insurance VARCHAR(75) null,
	copyOfInsurance VARCHAR(75) null,
	temporaryImportEquipment VARCHAR(75) null,
	personnelTravellingEquipment VARCHAR(75) null,
	portOfEntry VARCHAR(500) null,
	arrivalDate DATE null,
	departureDate DATE null,
	flightDetails VARCHAR(75) null,
	shippingCompany VARCHAR(75) null,
	shippingVesselNo VARCHAR(75) null,
	customsBroker VARCHAR(75) null,
	brokerEmail VARCHAR(75) null,
	brokerMobile VARCHAR(75) null,
	typeOfEquipmentJamaica VARCHAR(75) null,
	rentalArrangedThrough VARCHAR(75) null,
	filmApplicationId LONG
);

create table nbp_film_production_details (
	filmProductionDetailsId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	productionTitle VARCHAR(75) null,
	totalProductionBudget VARCHAR(75) null,
	expenditureInJamaica VARCHAR(75) null,
	foreignPersonnel VARCHAR(75) null,
	jamaicanPersonnel VARCHAR(75) null,
	productionType VARCHAR(75) null,
	companyName VARCHAR(75) null,
	fixerName VARCHAR(75) null,
	fixerMobile VARCHAR(75) null,
	fixerEmail VARCHAR(75) null,
	preProductionDates DATE null,
	productionDates DATE null,
	productionStartDate DATE null,
	productionEndDate DATE null,
	proposedProductionLocations VARCHAR(500) null,
	productionInternationalCrew VARCHAR(75) null,
	productionjamaicanCrew VARCHAR(75) null,
	productionExternalPermit VARCHAR(500) null,
	filmApplicationId LONG
);

create table nbp_film_stage (
	filmApplicationCurrentStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormStage VARCHAR(75) null,
	filmApplicationId LONG
);

create table nbp_other_details (
	filmOtherDetailsId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	additionalPermits VARCHAR(75) null,
	insurance VARCHAR(75) null,
	copyOfInsurance VARCHAR(75) null,
	temporaryImportEquipment VARCHAR(75) null,
	personnelTravellingEquipment VARCHAR(75) null,
	portOfEntry VARCHAR(75) null,
	flightDetails VARCHAR(75) null,
	customsBroker VARCHAR(75) null,
	brokerEmail VARCHAR(75) null,
	brokerMobile VARCHAR(75) null,
	typeOfEquipmentJamaica VARCHAR(75) null,
	rentalArrangedThrough VARCHAR(75) null,
	filmApplicationId VARCHAR(75) null
);