/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.collaboration.services.model.impl;

import com.nbp.collaboration.services.model.Collobartion;
import com.nbp.collaboration.services.service.CollobartionLocalServiceUtil;

/**
 * The extended model base implementation for the Collobartion service. Represents a row in the &quot;nbp_collaboration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CollobartionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CollobartionImpl
 * @see Collobartion
 * @generated
 */
public abstract class CollobartionBaseImpl
	extends CollobartionModelImpl implements Collobartion {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a collobartion model instance should use the <code>Collobartion</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CollobartionLocalServiceUtil.addCollobartion(this);
		}
		else {
			CollobartionLocalServiceUtil.updateCollobartion(this);
		}
	}

}