/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.wra.stage.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.wra.stage.service.model.WRAApplicationDueDiligence;
import com.nbp.wra.stage.service.model.WRAApplicationDueDiligenceModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WRAApplicationDueDiligence service. Represents a row in the &quot;nbp_wra_app_duediligence&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WRAApplicationDueDiligenceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WRAApplicationDueDiligenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WRAApplicationDueDiligenceImpl
 * @generated
 */
@JSON(strict = true)
public class WRAApplicationDueDiligenceModelImpl
	extends BaseModelImpl<WRAApplicationDueDiligence>
	implements WRAApplicationDueDiligenceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wra application due diligence model instance should use the <code>WRAApplicationDueDiligence</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_wra_app_duediligence";

	public static final Object[][] TABLE_COLUMNS = {
		{"wRAApplicationDueDiligenceId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"transactionNumber", Types.VARCHAR}, {"entityName", Types.VARCHAR},
		{"dateOfApplication", Types.TIMESTAMP},
		{"agencyContactName", Types.VARCHAR},
		{"agencyEmailAddress", Types.VARCHAR}, {"licenseNumber", Types.VARCHAR},
		{"agencyName", Types.VARCHAR},
		{"submittedToAgencyDate", Types.TIMESTAMP},
		{"feedbackReceivedDate", Types.TIMESTAMP},
		{"feedbackReceived", Types.VARCHAR}, {"deadlineDate", Types.TIMESTAMP},
		{"wraApplicationId", Types.BIGINT}, {"updatedBySource", Types.VARCHAR},
		{"durationOfTimeSpent", Types.VARCHAR},
		{"agencyDecision", Types.VARCHAR}, {"status", Types.VARCHAR},
		{"caseId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("wRAApplicationDueDiligenceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("transactionNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dateOfApplication", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("agencyContactName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agencyEmailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agencyName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("submittedToAgencyDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("feedbackReceivedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("feedbackReceived", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deadlineDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("wraApplicationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("updatedBySource", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("durationOfTimeSpent", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agencyDecision", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("caseId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_wra_app_duediligence (wRAApplicationDueDiligenceId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,transactionNumber VARCHAR(75) null,entityName VARCHAR(75) null,dateOfApplication DATE null,agencyContactName VARCHAR(75) null,agencyEmailAddress VARCHAR(75) null,licenseNumber VARCHAR(75) null,agencyName VARCHAR(75) null,submittedToAgencyDate DATE null,feedbackReceivedDate DATE null,feedbackReceived VARCHAR(75) null,deadlineDate DATE null,wraApplicationId LONG,updatedBySource VARCHAR(75) null,durationOfTimeSpent VARCHAR(75) null,agencyDecision VARCHAR(75) null,status VARCHAR(75) null,caseId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_wra_app_duediligence";

	public static final String ORDER_BY_JPQL =
		" ORDER BY wraApplicationDueDiligence.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_wra_app_duediligence.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AGENCYNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CASEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WRAAPPLICATIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public WRAApplicationDueDiligenceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _wRAApplicationDueDiligenceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWRAApplicationDueDiligenceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _wRAApplicationDueDiligenceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WRAApplicationDueDiligence.class;
	}

	@Override
	public String getModelClassName() {
		return WRAApplicationDueDiligence.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WRAApplicationDueDiligence, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WRAApplicationDueDiligence, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WRAApplicationDueDiligence, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(WRAApplicationDueDiligence)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WRAApplicationDueDiligence, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WRAApplicationDueDiligence, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WRAApplicationDueDiligence)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WRAApplicationDueDiligence, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WRAApplicationDueDiligence, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<WRAApplicationDueDiligence, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<WRAApplicationDueDiligence, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<WRAApplicationDueDiligence, Object>>();

			attributeGetterFunctions.put(
				"wRAApplicationDueDiligenceId",
				WRAApplicationDueDiligence::getWRAApplicationDueDiligenceId);
			attributeGetterFunctions.put(
				"groupId", WRAApplicationDueDiligence::getGroupId);
			attributeGetterFunctions.put(
				"companyId", WRAApplicationDueDiligence::getCompanyId);
			attributeGetterFunctions.put(
				"userId", WRAApplicationDueDiligence::getUserId);
			attributeGetterFunctions.put(
				"userName", WRAApplicationDueDiligence::getUserName);
			attributeGetterFunctions.put(
				"createDate", WRAApplicationDueDiligence::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", WRAApplicationDueDiligence::getModifiedDate);
			attributeGetterFunctions.put(
				"transactionNumber",
				WRAApplicationDueDiligence::getTransactionNumber);
			attributeGetterFunctions.put(
				"entityName", WRAApplicationDueDiligence::getEntityName);
			attributeGetterFunctions.put(
				"dateOfApplication",
				WRAApplicationDueDiligence::getDateOfApplication);
			attributeGetterFunctions.put(
				"agencyContactName",
				WRAApplicationDueDiligence::getAgencyContactName);
			attributeGetterFunctions.put(
				"agencyEmailAddress",
				WRAApplicationDueDiligence::getAgencyEmailAddress);
			attributeGetterFunctions.put(
				"licenseNumber", WRAApplicationDueDiligence::getLicenseNumber);
			attributeGetterFunctions.put(
				"agencyName", WRAApplicationDueDiligence::getAgencyName);
			attributeGetterFunctions.put(
				"submittedToAgencyDate",
				WRAApplicationDueDiligence::getSubmittedToAgencyDate);
			attributeGetterFunctions.put(
				"feedbackReceivedDate",
				WRAApplicationDueDiligence::getFeedbackReceivedDate);
			attributeGetterFunctions.put(
				"feedbackReceived",
				WRAApplicationDueDiligence::getFeedbackReceived);
			attributeGetterFunctions.put(
				"deadlineDate", WRAApplicationDueDiligence::getDeadlineDate);
			attributeGetterFunctions.put(
				"wraApplicationId",
				WRAApplicationDueDiligence::getWraApplicationId);
			attributeGetterFunctions.put(
				"updatedBySource",
				WRAApplicationDueDiligence::getUpdatedBySource);
			attributeGetterFunctions.put(
				"durationOfTimeSpent",
				WRAApplicationDueDiligence::getDurationOfTimeSpent);
			attributeGetterFunctions.put(
				"agencyDecision",
				WRAApplicationDueDiligence::getAgencyDecision);
			attributeGetterFunctions.put(
				"status", WRAApplicationDueDiligence::getStatus);
			attributeGetterFunctions.put(
				"caseId", WRAApplicationDueDiligence::getCaseId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<WRAApplicationDueDiligence, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<WRAApplicationDueDiligence, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<WRAApplicationDueDiligence, ?>>();

			attributeSetterBiConsumers.put(
				"wRAApplicationDueDiligenceId",
				(BiConsumer<WRAApplicationDueDiligence, Long>)
					WRAApplicationDueDiligence::
						setWRAApplicationDueDiligenceId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<WRAApplicationDueDiligence, Long>)
					WRAApplicationDueDiligence::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<WRAApplicationDueDiligence, Long>)
					WRAApplicationDueDiligence::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<WRAApplicationDueDiligence, Long>)
					WRAApplicationDueDiligence::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<WRAApplicationDueDiligence, Date>)
					WRAApplicationDueDiligence::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<WRAApplicationDueDiligence, Date>)
					WRAApplicationDueDiligence::setModifiedDate);
			attributeSetterBiConsumers.put(
				"transactionNumber",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setTransactionNumber);
			attributeSetterBiConsumers.put(
				"entityName",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setEntityName);
			attributeSetterBiConsumers.put(
				"dateOfApplication",
				(BiConsumer<WRAApplicationDueDiligence, Date>)
					WRAApplicationDueDiligence::setDateOfApplication);
			attributeSetterBiConsumers.put(
				"agencyContactName",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setAgencyContactName);
			attributeSetterBiConsumers.put(
				"agencyEmailAddress",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setAgencyEmailAddress);
			attributeSetterBiConsumers.put(
				"licenseNumber",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setLicenseNumber);
			attributeSetterBiConsumers.put(
				"agencyName",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setAgencyName);
			attributeSetterBiConsumers.put(
				"submittedToAgencyDate",
				(BiConsumer<WRAApplicationDueDiligence, Date>)
					WRAApplicationDueDiligence::setSubmittedToAgencyDate);
			attributeSetterBiConsumers.put(
				"feedbackReceivedDate",
				(BiConsumer<WRAApplicationDueDiligence, Date>)
					WRAApplicationDueDiligence::setFeedbackReceivedDate);
			attributeSetterBiConsumers.put(
				"feedbackReceived",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setFeedbackReceived);
			attributeSetterBiConsumers.put(
				"deadlineDate",
				(BiConsumer<WRAApplicationDueDiligence, Date>)
					WRAApplicationDueDiligence::setDeadlineDate);
			attributeSetterBiConsumers.put(
				"wraApplicationId",
				(BiConsumer<WRAApplicationDueDiligence, Long>)
					WRAApplicationDueDiligence::setWraApplicationId);
			attributeSetterBiConsumers.put(
				"updatedBySource",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setUpdatedBySource);
			attributeSetterBiConsumers.put(
				"durationOfTimeSpent",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setDurationOfTimeSpent);
			attributeSetterBiConsumers.put(
				"agencyDecision",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setAgencyDecision);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setStatus);
			attributeSetterBiConsumers.put(
				"caseId",
				(BiConsumer<WRAApplicationDueDiligence, String>)
					WRAApplicationDueDiligence::setCaseId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getWRAApplicationDueDiligenceId() {
		return _wRAApplicationDueDiligenceId;
	}

	@Override
	public void setWRAApplicationDueDiligenceId(
		long wRAApplicationDueDiligenceId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_wRAApplicationDueDiligenceId = wRAApplicationDueDiligenceId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTransactionNumber() {
		if (_transactionNumber == null) {
			return "";
		}
		else {
			return _transactionNumber;
		}
	}

	@Override
	public void setTransactionNumber(String transactionNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_transactionNumber = transactionNumber;
	}

	@JSON
	@Override
	public String getEntityName() {
		if (_entityName == null) {
			return "";
		}
		else {
			return _entityName;
		}
	}

	@Override
	public void setEntityName(String entityName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityName = entityName;
	}

	@JSON
	@Override
	public Date getDateOfApplication() {
		return _dateOfApplication;
	}

	@Override
	public void setDateOfApplication(Date dateOfApplication) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfApplication = dateOfApplication;
	}

	@JSON
	@Override
	public String getAgencyContactName() {
		if (_agencyContactName == null) {
			return "";
		}
		else {
			return _agencyContactName;
		}
	}

	@Override
	public void setAgencyContactName(String agencyContactName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agencyContactName = agencyContactName;
	}

	@JSON
	@Override
	public String getAgencyEmailAddress() {
		if (_agencyEmailAddress == null) {
			return "";
		}
		else {
			return _agencyEmailAddress;
		}
	}

	@Override
	public void setAgencyEmailAddress(String agencyEmailAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agencyEmailAddress = agencyEmailAddress;
	}

	@JSON
	@Override
	public String getLicenseNumber() {
		if (_licenseNumber == null) {
			return "";
		}
		else {
			return _licenseNumber;
		}
	}

	@Override
	public void setLicenseNumber(String licenseNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_licenseNumber = licenseNumber;
	}

	@JSON
	@Override
	public String getAgencyName() {
		if (_agencyName == null) {
			return "";
		}
		else {
			return _agencyName;
		}
	}

	@Override
	public void setAgencyName(String agencyName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agencyName = agencyName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAgencyName() {
		return getColumnOriginalValue("agencyName");
	}

	@JSON
	@Override
	public Date getSubmittedToAgencyDate() {
		return _submittedToAgencyDate;
	}

	@Override
	public void setSubmittedToAgencyDate(Date submittedToAgencyDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_submittedToAgencyDate = submittedToAgencyDate;
	}

	@JSON
	@Override
	public Date getFeedbackReceivedDate() {
		return _feedbackReceivedDate;
	}

	@Override
	public void setFeedbackReceivedDate(Date feedbackReceivedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_feedbackReceivedDate = feedbackReceivedDate;
	}

	@JSON
	@Override
	public String getFeedbackReceived() {
		if (_feedbackReceived == null) {
			return "";
		}
		else {
			return _feedbackReceived;
		}
	}

	@Override
	public void setFeedbackReceived(String feedbackReceived) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_feedbackReceived = feedbackReceived;
	}

	@JSON
	@Override
	public Date getDeadlineDate() {
		return _deadlineDate;
	}

	@Override
	public void setDeadlineDate(Date deadlineDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deadlineDate = deadlineDate;
	}

	@JSON
	@Override
	public long getWraApplicationId() {
		return _wraApplicationId;
	}

	@Override
	public void setWraApplicationId(long wraApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_wraApplicationId = wraApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalWraApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("wraApplicationId"));
	}

	@JSON
	@Override
	public String getUpdatedBySource() {
		if (_updatedBySource == null) {
			return "";
		}
		else {
			return _updatedBySource;
		}
	}

	@Override
	public void setUpdatedBySource(String updatedBySource) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedBySource = updatedBySource;
	}

	@JSON
	@Override
	public String getDurationOfTimeSpent() {
		if (_durationOfTimeSpent == null) {
			return "";
		}
		else {
			return _durationOfTimeSpent;
		}
	}

	@Override
	public void setDurationOfTimeSpent(String durationOfTimeSpent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_durationOfTimeSpent = durationOfTimeSpent;
	}

	@JSON
	@Override
	public String getAgencyDecision() {
		if (_agencyDecision == null) {
			return "";
		}
		else {
			return _agencyDecision;
		}
	}

	@Override
	public void setAgencyDecision(String agencyDecision) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agencyDecision = agencyDecision;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public String getCaseId() {
		if (_caseId == null) {
			return "";
		}
		else {
			return _caseId;
		}
	}

	@Override
	public void setCaseId(String caseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_caseId = caseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCaseId() {
		return getColumnOriginalValue("caseId");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WRAApplicationDueDiligence.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WRAApplicationDueDiligence toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WRAApplicationDueDiligence>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WRAApplicationDueDiligenceImpl wraApplicationDueDiligenceImpl =
			new WRAApplicationDueDiligenceImpl();

		wraApplicationDueDiligenceImpl.setWRAApplicationDueDiligenceId(
			getWRAApplicationDueDiligenceId());
		wraApplicationDueDiligenceImpl.setGroupId(getGroupId());
		wraApplicationDueDiligenceImpl.setCompanyId(getCompanyId());
		wraApplicationDueDiligenceImpl.setUserId(getUserId());
		wraApplicationDueDiligenceImpl.setUserName(getUserName());
		wraApplicationDueDiligenceImpl.setCreateDate(getCreateDate());
		wraApplicationDueDiligenceImpl.setModifiedDate(getModifiedDate());
		wraApplicationDueDiligenceImpl.setTransactionNumber(
			getTransactionNumber());
		wraApplicationDueDiligenceImpl.setEntityName(getEntityName());
		wraApplicationDueDiligenceImpl.setDateOfApplication(
			getDateOfApplication());
		wraApplicationDueDiligenceImpl.setAgencyContactName(
			getAgencyContactName());
		wraApplicationDueDiligenceImpl.setAgencyEmailAddress(
			getAgencyEmailAddress());
		wraApplicationDueDiligenceImpl.setLicenseNumber(getLicenseNumber());
		wraApplicationDueDiligenceImpl.setAgencyName(getAgencyName());
		wraApplicationDueDiligenceImpl.setSubmittedToAgencyDate(
			getSubmittedToAgencyDate());
		wraApplicationDueDiligenceImpl.setFeedbackReceivedDate(
			getFeedbackReceivedDate());
		wraApplicationDueDiligenceImpl.setFeedbackReceived(
			getFeedbackReceived());
		wraApplicationDueDiligenceImpl.setDeadlineDate(getDeadlineDate());
		wraApplicationDueDiligenceImpl.setWraApplicationId(
			getWraApplicationId());
		wraApplicationDueDiligenceImpl.setUpdatedBySource(getUpdatedBySource());
		wraApplicationDueDiligenceImpl.setDurationOfTimeSpent(
			getDurationOfTimeSpent());
		wraApplicationDueDiligenceImpl.setAgencyDecision(getAgencyDecision());
		wraApplicationDueDiligenceImpl.setStatus(getStatus());
		wraApplicationDueDiligenceImpl.setCaseId(getCaseId());

		wraApplicationDueDiligenceImpl.resetOriginalValues();

		return wraApplicationDueDiligenceImpl;
	}

	@Override
	public WRAApplicationDueDiligence cloneWithOriginalValues() {
		WRAApplicationDueDiligenceImpl wraApplicationDueDiligenceImpl =
			new WRAApplicationDueDiligenceImpl();

		wraApplicationDueDiligenceImpl.setWRAApplicationDueDiligenceId(
			this.<Long>getColumnOriginalValue("wRAApplicationDueDiligenceId"));
		wraApplicationDueDiligenceImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		wraApplicationDueDiligenceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		wraApplicationDueDiligenceImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		wraApplicationDueDiligenceImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		wraApplicationDueDiligenceImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		wraApplicationDueDiligenceImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		wraApplicationDueDiligenceImpl.setTransactionNumber(
			this.<String>getColumnOriginalValue("transactionNumber"));
		wraApplicationDueDiligenceImpl.setEntityName(
			this.<String>getColumnOriginalValue("entityName"));
		wraApplicationDueDiligenceImpl.setDateOfApplication(
			this.<Date>getColumnOriginalValue("dateOfApplication"));
		wraApplicationDueDiligenceImpl.setAgencyContactName(
			this.<String>getColumnOriginalValue("agencyContactName"));
		wraApplicationDueDiligenceImpl.setAgencyEmailAddress(
			this.<String>getColumnOriginalValue("agencyEmailAddress"));
		wraApplicationDueDiligenceImpl.setLicenseNumber(
			this.<String>getColumnOriginalValue("licenseNumber"));
		wraApplicationDueDiligenceImpl.setAgencyName(
			this.<String>getColumnOriginalValue("agencyName"));
		wraApplicationDueDiligenceImpl.setSubmittedToAgencyDate(
			this.<Date>getColumnOriginalValue("submittedToAgencyDate"));
		wraApplicationDueDiligenceImpl.setFeedbackReceivedDate(
			this.<Date>getColumnOriginalValue("feedbackReceivedDate"));
		wraApplicationDueDiligenceImpl.setFeedbackReceived(
			this.<String>getColumnOriginalValue("feedbackReceived"));
		wraApplicationDueDiligenceImpl.setDeadlineDate(
			this.<Date>getColumnOriginalValue("deadlineDate"));
		wraApplicationDueDiligenceImpl.setWraApplicationId(
			this.<Long>getColumnOriginalValue("wraApplicationId"));
		wraApplicationDueDiligenceImpl.setUpdatedBySource(
			this.<String>getColumnOriginalValue("updatedBySource"));
		wraApplicationDueDiligenceImpl.setDurationOfTimeSpent(
			this.<String>getColumnOriginalValue("durationOfTimeSpent"));
		wraApplicationDueDiligenceImpl.setAgencyDecision(
			this.<String>getColumnOriginalValue("agencyDecision"));
		wraApplicationDueDiligenceImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		wraApplicationDueDiligenceImpl.setCaseId(
			this.<String>getColumnOriginalValue("caseId"));

		return wraApplicationDueDiligenceImpl;
	}

	@Override
	public int compareTo(
		WRAApplicationDueDiligence wraApplicationDueDiligence) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), wraApplicationDueDiligence.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WRAApplicationDueDiligence)) {
			return false;
		}

		WRAApplicationDueDiligence wraApplicationDueDiligence =
			(WRAApplicationDueDiligence)object;

		long primaryKey = wraApplicationDueDiligence.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<WRAApplicationDueDiligence> toCacheModel() {
		WRAApplicationDueDiligenceCacheModel
			wraApplicationDueDiligenceCacheModel =
				new WRAApplicationDueDiligenceCacheModel();

		wraApplicationDueDiligenceCacheModel.wRAApplicationDueDiligenceId =
			getWRAApplicationDueDiligenceId();

		wraApplicationDueDiligenceCacheModel.groupId = getGroupId();

		wraApplicationDueDiligenceCacheModel.companyId = getCompanyId();

		wraApplicationDueDiligenceCacheModel.userId = getUserId();

		wraApplicationDueDiligenceCacheModel.userName = getUserName();

		String userName = wraApplicationDueDiligenceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			wraApplicationDueDiligenceCacheModel.createDate =
				createDate.getTime();
		}
		else {
			wraApplicationDueDiligenceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			wraApplicationDueDiligenceCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			wraApplicationDueDiligenceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		wraApplicationDueDiligenceCacheModel.transactionNumber =
			getTransactionNumber();

		String transactionNumber =
			wraApplicationDueDiligenceCacheModel.transactionNumber;

		if ((transactionNumber != null) && (transactionNumber.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.transactionNumber = null;
		}

		wraApplicationDueDiligenceCacheModel.entityName = getEntityName();

		String entityName = wraApplicationDueDiligenceCacheModel.entityName;

		if ((entityName != null) && (entityName.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.entityName = null;
		}

		Date dateOfApplication = getDateOfApplication();

		if (dateOfApplication != null) {
			wraApplicationDueDiligenceCacheModel.dateOfApplication =
				dateOfApplication.getTime();
		}
		else {
			wraApplicationDueDiligenceCacheModel.dateOfApplication =
				Long.MIN_VALUE;
		}

		wraApplicationDueDiligenceCacheModel.agencyContactName =
			getAgencyContactName();

		String agencyContactName =
			wraApplicationDueDiligenceCacheModel.agencyContactName;

		if ((agencyContactName != null) && (agencyContactName.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.agencyContactName = null;
		}

		wraApplicationDueDiligenceCacheModel.agencyEmailAddress =
			getAgencyEmailAddress();

		String agencyEmailAddress =
			wraApplicationDueDiligenceCacheModel.agencyEmailAddress;

		if ((agencyEmailAddress != null) &&
			(agencyEmailAddress.length() == 0)) {

			wraApplicationDueDiligenceCacheModel.agencyEmailAddress = null;
		}

		wraApplicationDueDiligenceCacheModel.licenseNumber = getLicenseNumber();

		String licenseNumber =
			wraApplicationDueDiligenceCacheModel.licenseNumber;

		if ((licenseNumber != null) && (licenseNumber.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.licenseNumber = null;
		}

		wraApplicationDueDiligenceCacheModel.agencyName = getAgencyName();

		String agencyName = wraApplicationDueDiligenceCacheModel.agencyName;

		if ((agencyName != null) && (agencyName.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.agencyName = null;
		}

		Date submittedToAgencyDate = getSubmittedToAgencyDate();

		if (submittedToAgencyDate != null) {
			wraApplicationDueDiligenceCacheModel.submittedToAgencyDate =
				submittedToAgencyDate.getTime();
		}
		else {
			wraApplicationDueDiligenceCacheModel.submittedToAgencyDate =
				Long.MIN_VALUE;
		}

		Date feedbackReceivedDate = getFeedbackReceivedDate();

		if (feedbackReceivedDate != null) {
			wraApplicationDueDiligenceCacheModel.feedbackReceivedDate =
				feedbackReceivedDate.getTime();
		}
		else {
			wraApplicationDueDiligenceCacheModel.feedbackReceivedDate =
				Long.MIN_VALUE;
		}

		wraApplicationDueDiligenceCacheModel.feedbackReceived =
			getFeedbackReceived();

		String feedbackReceived =
			wraApplicationDueDiligenceCacheModel.feedbackReceived;

		if ((feedbackReceived != null) && (feedbackReceived.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.feedbackReceived = null;
		}

		Date deadlineDate = getDeadlineDate();

		if (deadlineDate != null) {
			wraApplicationDueDiligenceCacheModel.deadlineDate =
				deadlineDate.getTime();
		}
		else {
			wraApplicationDueDiligenceCacheModel.deadlineDate = Long.MIN_VALUE;
		}

		wraApplicationDueDiligenceCacheModel.wraApplicationId =
			getWraApplicationId();

		wraApplicationDueDiligenceCacheModel.updatedBySource =
			getUpdatedBySource();

		String updatedBySource =
			wraApplicationDueDiligenceCacheModel.updatedBySource;

		if ((updatedBySource != null) && (updatedBySource.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.updatedBySource = null;
		}

		wraApplicationDueDiligenceCacheModel.durationOfTimeSpent =
			getDurationOfTimeSpent();

		String durationOfTimeSpent =
			wraApplicationDueDiligenceCacheModel.durationOfTimeSpent;

		if ((durationOfTimeSpent != null) &&
			(durationOfTimeSpent.length() == 0)) {

			wraApplicationDueDiligenceCacheModel.durationOfTimeSpent = null;
		}

		wraApplicationDueDiligenceCacheModel.agencyDecision =
			getAgencyDecision();

		String agencyDecision =
			wraApplicationDueDiligenceCacheModel.agencyDecision;

		if ((agencyDecision != null) && (agencyDecision.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.agencyDecision = null;
		}

		wraApplicationDueDiligenceCacheModel.status = getStatus();

		String status = wraApplicationDueDiligenceCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.status = null;
		}

		wraApplicationDueDiligenceCacheModel.caseId = getCaseId();

		String caseId = wraApplicationDueDiligenceCacheModel.caseId;

		if ((caseId != null) && (caseId.length() == 0)) {
			wraApplicationDueDiligenceCacheModel.caseId = null;
		}

		return wraApplicationDueDiligenceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WRAApplicationDueDiligence, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WRAApplicationDueDiligence, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WRAApplicationDueDiligence, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(WRAApplicationDueDiligence)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, WRAApplicationDueDiligence>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						WRAApplicationDueDiligence.class, ModelWrapper.class);

	}

	private long _wRAApplicationDueDiligenceId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _transactionNumber;
	private String _entityName;
	private Date _dateOfApplication;
	private String _agencyContactName;
	private String _agencyEmailAddress;
	private String _licenseNumber;
	private String _agencyName;
	private Date _submittedToAgencyDate;
	private Date _feedbackReceivedDate;
	private String _feedbackReceived;
	private Date _deadlineDate;
	private long _wraApplicationId;
	private String _updatedBySource;
	private String _durationOfTimeSpent;
	private String _agencyDecision;
	private String _status;
	private String _caseId;

	public <T> T getColumnValue(String columnName) {
		Function<WRAApplicationDueDiligence, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((WRAApplicationDueDiligence)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"wRAApplicationDueDiligenceId", _wRAApplicationDueDiligenceId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("transactionNumber", _transactionNumber);
		_columnOriginalValues.put("entityName", _entityName);
		_columnOriginalValues.put("dateOfApplication", _dateOfApplication);
		_columnOriginalValues.put("agencyContactName", _agencyContactName);
		_columnOriginalValues.put("agencyEmailAddress", _agencyEmailAddress);
		_columnOriginalValues.put("licenseNumber", _licenseNumber);
		_columnOriginalValues.put("agencyName", _agencyName);
		_columnOriginalValues.put(
			"submittedToAgencyDate", _submittedToAgencyDate);
		_columnOriginalValues.put(
			"feedbackReceivedDate", _feedbackReceivedDate);
		_columnOriginalValues.put("feedbackReceived", _feedbackReceived);
		_columnOriginalValues.put("deadlineDate", _deadlineDate);
		_columnOriginalValues.put("wraApplicationId", _wraApplicationId);
		_columnOriginalValues.put("updatedBySource", _updatedBySource);
		_columnOriginalValues.put("durationOfTimeSpent", _durationOfTimeSpent);
		_columnOriginalValues.put("agencyDecision", _agencyDecision);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("caseId", _caseId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("wRAApplicationDueDiligenceId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("transactionNumber", 128L);

		columnBitmasks.put("entityName", 256L);

		columnBitmasks.put("dateOfApplication", 512L);

		columnBitmasks.put("agencyContactName", 1024L);

		columnBitmasks.put("agencyEmailAddress", 2048L);

		columnBitmasks.put("licenseNumber", 4096L);

		columnBitmasks.put("agencyName", 8192L);

		columnBitmasks.put("submittedToAgencyDate", 16384L);

		columnBitmasks.put("feedbackReceivedDate", 32768L);

		columnBitmasks.put("feedbackReceived", 65536L);

		columnBitmasks.put("deadlineDate", 131072L);

		columnBitmasks.put("wraApplicationId", 262144L);

		columnBitmasks.put("updatedBySource", 524288L);

		columnBitmasks.put("durationOfTimeSpent", 1048576L);

		columnBitmasks.put("agencyDecision", 2097152L);

		columnBitmasks.put("status", 4194304L);

		columnBitmasks.put("caseId", 8388608L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private WRAApplicationDueDiligence _escapedModel;

}