/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.sez.status.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.sez.status.application.form.service.model.SezDevDisasterManagementAdd;
import com.nbp.sez.status.application.form.service.model.SezDevDisasterManagementAddModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SezDevDisasterManagementAdd service. Represents a row in the &quot;nbp_sez_dev_disast_manag_add&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SezDevDisasterManagementAddModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SezDevDisasterManagementAddImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SezDevDisasterManagementAddImpl
 * @generated
 */
@JSON(strict = true)
public class SezDevDisasterManagementAddModelImpl
	extends BaseModelImpl<SezDevDisasterManagementAdd>
	implements SezDevDisasterManagementAddModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sez dev disaster management add model instance should use the <code>SezDevDisasterManagementAdd</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_sez_dev_disast_manag_add";

	public static final Object[][] TABLE_COLUMNS = {
		{"sezDevDisasterManagementAddId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"disasterMitigationPlan", Types.VARCHAR}, {"counter", Types.VARCHAR},
		{"sezStatusApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("sezDevDisasterManagementAddId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("disasterMitigationPlan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("counter", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sezStatusApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_sez_dev_disast_manag_add (sezDevDisasterManagementAddId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,disasterMitigationPlan VARCHAR(75) null,counter VARCHAR(75) null,sezStatusApplicationId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_sez_dev_disast_manag_add";

	public static final String ORDER_BY_JPQL =
		" ORDER BY sezDevDisasterManagementAdd.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_sez_dev_disast_manag_add.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SEZSTATUSAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SezDevDisasterManagementAddModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sezDevDisasterManagementAddId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSezDevDisasterManagementAddId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sezDevDisasterManagementAddId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SezDevDisasterManagementAdd.class;
	}

	@Override
	public String getModelClassName() {
		return SezDevDisasterManagementAdd.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SezDevDisasterManagementAdd, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SezDevDisasterManagementAdd, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SezDevDisasterManagementAdd, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(SezDevDisasterManagementAdd)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SezDevDisasterManagementAdd, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SezDevDisasterManagementAdd, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SezDevDisasterManagementAdd)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SezDevDisasterManagementAdd, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SezDevDisasterManagementAdd, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<SezDevDisasterManagementAdd, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<SezDevDisasterManagementAdd, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<SezDevDisasterManagementAdd, Object>>();

			attributeGetterFunctions.put(
				"sezDevDisasterManagementAddId",
				SezDevDisasterManagementAdd::getSezDevDisasterManagementAddId);
			attributeGetterFunctions.put(
				"groupId", SezDevDisasterManagementAdd::getGroupId);
			attributeGetterFunctions.put(
				"companyId", SezDevDisasterManagementAdd::getCompanyId);
			attributeGetterFunctions.put(
				"userId", SezDevDisasterManagementAdd::getUserId);
			attributeGetterFunctions.put(
				"userName", SezDevDisasterManagementAdd::getUserName);
			attributeGetterFunctions.put(
				"createDate", SezDevDisasterManagementAdd::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", SezDevDisasterManagementAdd::getModifiedDate);
			attributeGetterFunctions.put(
				"disasterMitigationPlan",
				SezDevDisasterManagementAdd::getDisasterMitigationPlan);
			attributeGetterFunctions.put(
				"counter", SezDevDisasterManagementAdd::getCounter);
			attributeGetterFunctions.put(
				"sezStatusApplicationId",
				SezDevDisasterManagementAdd::getSezStatusApplicationId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<SezDevDisasterManagementAdd, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SezDevDisasterManagementAdd, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<SezDevDisasterManagementAdd, ?>>();

			attributeSetterBiConsumers.put(
				"sezDevDisasterManagementAddId",
				(BiConsumer<SezDevDisasterManagementAdd, Long>)
					SezDevDisasterManagementAdd::
						setSezDevDisasterManagementAddId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<SezDevDisasterManagementAdd, Long>)
					SezDevDisasterManagementAdd::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<SezDevDisasterManagementAdd, Long>)
					SezDevDisasterManagementAdd::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<SezDevDisasterManagementAdd, Long>)
					SezDevDisasterManagementAdd::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<SezDevDisasterManagementAdd, String>)
					SezDevDisasterManagementAdd::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<SezDevDisasterManagementAdd, Date>)
					SezDevDisasterManagementAdd::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<SezDevDisasterManagementAdd, Date>)
					SezDevDisasterManagementAdd::setModifiedDate);
			attributeSetterBiConsumers.put(
				"disasterMitigationPlan",
				(BiConsumer<SezDevDisasterManagementAdd, String>)
					SezDevDisasterManagementAdd::setDisasterMitigationPlan);
			attributeSetterBiConsumers.put(
				"counter",
				(BiConsumer<SezDevDisasterManagementAdd, String>)
					SezDevDisasterManagementAdd::setCounter);
			attributeSetterBiConsumers.put(
				"sezStatusApplicationId",
				(BiConsumer<SezDevDisasterManagementAdd, Long>)
					SezDevDisasterManagementAdd::setSezStatusApplicationId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getSezDevDisasterManagementAddId() {
		return _sezDevDisasterManagementAddId;
	}

	@Override
	public void setSezDevDisasterManagementAddId(
		long sezDevDisasterManagementAddId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sezDevDisasterManagementAddId = sezDevDisasterManagementAddId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDisasterMitigationPlan() {
		if (_disasterMitigationPlan == null) {
			return "";
		}
		else {
			return _disasterMitigationPlan;
		}
	}

	@Override
	public void setDisasterMitigationPlan(String disasterMitigationPlan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_disasterMitigationPlan = disasterMitigationPlan;
	}

	@JSON
	@Override
	public String getCounter() {
		if (_counter == null) {
			return "";
		}
		else {
			return _counter;
		}
	}

	@Override
	public void setCounter(String counter) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_counter = counter;
	}

	@JSON
	@Override
	public long getSezStatusApplicationId() {
		return _sezStatusApplicationId;
	}

	@Override
	public void setSezStatusApplicationId(long sezStatusApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sezStatusApplicationId = sezStatusApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSezStatusApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("sezStatusApplicationId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SezDevDisasterManagementAdd.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SezDevDisasterManagementAdd toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SezDevDisasterManagementAdd>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SezDevDisasterManagementAddImpl sezDevDisasterManagementAddImpl =
			new SezDevDisasterManagementAddImpl();

		sezDevDisasterManagementAddImpl.setSezDevDisasterManagementAddId(
			getSezDevDisasterManagementAddId());
		sezDevDisasterManagementAddImpl.setGroupId(getGroupId());
		sezDevDisasterManagementAddImpl.setCompanyId(getCompanyId());
		sezDevDisasterManagementAddImpl.setUserId(getUserId());
		sezDevDisasterManagementAddImpl.setUserName(getUserName());
		sezDevDisasterManagementAddImpl.setCreateDate(getCreateDate());
		sezDevDisasterManagementAddImpl.setModifiedDate(getModifiedDate());
		sezDevDisasterManagementAddImpl.setDisasterMitigationPlan(
			getDisasterMitigationPlan());
		sezDevDisasterManagementAddImpl.setCounter(getCounter());
		sezDevDisasterManagementAddImpl.setSezStatusApplicationId(
			getSezStatusApplicationId());

		sezDevDisasterManagementAddImpl.resetOriginalValues();

		return sezDevDisasterManagementAddImpl;
	}

	@Override
	public SezDevDisasterManagementAdd cloneWithOriginalValues() {
		SezDevDisasterManagementAddImpl sezDevDisasterManagementAddImpl =
			new SezDevDisasterManagementAddImpl();

		sezDevDisasterManagementAddImpl.setSezDevDisasterManagementAddId(
			this.<Long>getColumnOriginalValue("sezDevDisasterManagementAddId"));
		sezDevDisasterManagementAddImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		sezDevDisasterManagementAddImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		sezDevDisasterManagementAddImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		sezDevDisasterManagementAddImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		sezDevDisasterManagementAddImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		sezDevDisasterManagementAddImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		sezDevDisasterManagementAddImpl.setDisasterMitigationPlan(
			this.<String>getColumnOriginalValue("disasterMitigationPlan"));
		sezDevDisasterManagementAddImpl.setCounter(
			this.<String>getColumnOriginalValue("counter"));
		sezDevDisasterManagementAddImpl.setSezStatusApplicationId(
			this.<Long>getColumnOriginalValue("sezStatusApplicationId"));

		return sezDevDisasterManagementAddImpl;
	}

	@Override
	public int compareTo(
		SezDevDisasterManagementAdd sezDevDisasterManagementAdd) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), sezDevDisasterManagementAdd.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SezDevDisasterManagementAdd)) {
			return false;
		}

		SezDevDisasterManagementAdd sezDevDisasterManagementAdd =
			(SezDevDisasterManagementAdd)object;

		long primaryKey = sezDevDisasterManagementAdd.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SezDevDisasterManagementAdd> toCacheModel() {
		SezDevDisasterManagementAddCacheModel
			sezDevDisasterManagementAddCacheModel =
				new SezDevDisasterManagementAddCacheModel();

		sezDevDisasterManagementAddCacheModel.sezDevDisasterManagementAddId =
			getSezDevDisasterManagementAddId();

		sezDevDisasterManagementAddCacheModel.groupId = getGroupId();

		sezDevDisasterManagementAddCacheModel.companyId = getCompanyId();

		sezDevDisasterManagementAddCacheModel.userId = getUserId();

		sezDevDisasterManagementAddCacheModel.userName = getUserName();

		String userName = sezDevDisasterManagementAddCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sezDevDisasterManagementAddCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sezDevDisasterManagementAddCacheModel.createDate =
				createDate.getTime();
		}
		else {
			sezDevDisasterManagementAddCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sezDevDisasterManagementAddCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			sezDevDisasterManagementAddCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sezDevDisasterManagementAddCacheModel.disasterMitigationPlan =
			getDisasterMitigationPlan();

		String disasterMitigationPlan =
			sezDevDisasterManagementAddCacheModel.disasterMitigationPlan;

		if ((disasterMitigationPlan != null) &&
			(disasterMitigationPlan.length() == 0)) {

			sezDevDisasterManagementAddCacheModel.disasterMitigationPlan = null;
		}

		sezDevDisasterManagementAddCacheModel.counter = getCounter();

		String counter = sezDevDisasterManagementAddCacheModel.counter;

		if ((counter != null) && (counter.length() == 0)) {
			sezDevDisasterManagementAddCacheModel.counter = null;
		}

		sezDevDisasterManagementAddCacheModel.sezStatusApplicationId =
			getSezStatusApplicationId();

		return sezDevDisasterManagementAddCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SezDevDisasterManagementAdd, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SezDevDisasterManagementAdd, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SezDevDisasterManagementAdd, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SezDevDisasterManagementAdd)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, SezDevDisasterManagementAdd>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						SezDevDisasterManagementAdd.class, ModelWrapper.class);

	}

	private long _sezDevDisasterManagementAddId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _disasterMitigationPlan;
	private String _counter;
	private long _sezStatusApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<SezDevDisasterManagementAdd, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SezDevDisasterManagementAdd)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"sezDevDisasterManagementAddId", _sezDevDisasterManagementAddId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"disasterMitigationPlan", _disasterMitigationPlan);
		_columnOriginalValues.put("counter", _counter);
		_columnOriginalValues.put(
			"sezStatusApplicationId", _sezStatusApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("sezDevDisasterManagementAddId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("disasterMitigationPlan", 128L);

		columnBitmasks.put("counter", 256L);

		columnBitmasks.put("sezStatusApplicationId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SezDevDisasterManagementAdd _escapedModel;

}