/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.sez.status.application.form.service.model.impl;

import com.nbp.sez.status.application.form.service.model.SezDevSharePrincipalAdd;
import com.nbp.sez.status.application.form.service.service.SezDevSharePrincipalAddLocalServiceUtil;

/**
 * The extended model base implementation for the SezDevSharePrincipalAdd service. Represents a row in the &quot;nbp_sez_dev_share_pricipal_add&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SezDevSharePrincipalAddImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SezDevSharePrincipalAddImpl
 * @see SezDevSharePrincipalAdd
 * @generated
 */
public abstract class SezDevSharePrincipalAddBaseImpl
	extends SezDevSharePrincipalAddModelImpl
	implements SezDevSharePrincipalAdd {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sez dev share principal add model instance should use the <code>SezDevSharePrincipalAdd</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SezDevSharePrincipalAddLocalServiceUtil.addSezDevSharePrincipalAdd(
				this);
		}
		else {
			SezDevSharePrincipalAddLocalServiceUtil.
				updateSezDevSharePrincipalAdd(this);
		}
	}

}