/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.sez.status.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.sez.status.application.form.service.model.SezOccupantUserUndertakingInfo;
import com.nbp.sez.status.application.form.service.model.SezOccupantUserUndertakingInfoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SezOccupantUserUndertakingInfo service. Represents a row in the &quot;nbp_sez_occ_user_under_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SezOccupantUserUndertakingInfoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SezOccupantUserUndertakingInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SezOccupantUserUndertakingInfoImpl
 * @generated
 */
@JSON(strict = true)
public class SezOccupantUserUndertakingInfoModelImpl
	extends BaseModelImpl<SezOccupantUserUndertakingInfo>
	implements SezOccupantUserUndertakingInfoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sez occupant user undertaking info model instance should use the <code>SezOccupantUserUndertakingInfo</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_sez_occ_user_under_info";

	public static final Object[][] TABLE_COLUMNS = {
		{"sezOccUserunderId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"occApplicantTitle", Types.VARCHAR},
		{"occApplicantName", Types.VARCHAR},
		{"occApplicantTeleNum", Types.VARCHAR},
		{"occApplicantEmail", Types.VARCHAR},
		{"occApplicantSignDate", Types.TIMESTAMP},
		{"occPublicNotaryName", Types.VARCHAR},
		{"occPublicNotarySignDate", Types.TIMESTAMP},
		{"sezStatusApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("sezOccUserunderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("occApplicantTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("occApplicantName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("occApplicantTeleNum", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("occApplicantEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("occApplicantSignDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("occPublicNotaryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("occPublicNotarySignDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("sezStatusApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_sez_occ_user_under_info (sezOccUserunderId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,occApplicantTitle VARCHAR(75) null,occApplicantName VARCHAR(75) null,occApplicantTeleNum VARCHAR(75) null,occApplicantEmail VARCHAR(75) null,occApplicantSignDate DATE null,occPublicNotaryName VARCHAR(75) null,occPublicNotarySignDate DATE null,sezStatusApplicationId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_sez_occ_user_under_info";

	public static final String ORDER_BY_JPQL =
		" ORDER BY sezOccupantUserUndertakingInfo.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_sez_occ_user_under_info.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SEZSTATUSAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SezOccupantUserUndertakingInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sezOccUserunderId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSezOccUserunderId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sezOccUserunderId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SezOccupantUserUndertakingInfo.class;
	}

	@Override
	public String getModelClassName() {
		return SezOccupantUserUndertakingInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SezOccupantUserUndertakingInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SezOccupantUserUndertakingInfo, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SezOccupantUserUndertakingInfo, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(SezOccupantUserUndertakingInfo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SezOccupantUserUndertakingInfo, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SezOccupantUserUndertakingInfo, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SezOccupantUserUndertakingInfo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SezOccupantUserUndertakingInfo, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SezOccupantUserUndertakingInfo, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<SezOccupantUserUndertakingInfo, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<SezOccupantUserUndertakingInfo, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<SezOccupantUserUndertakingInfo, Object>>();

			attributeGetterFunctions.put(
				"sezOccUserunderId",
				SezOccupantUserUndertakingInfo::getSezOccUserunderId);
			attributeGetterFunctions.put(
				"groupId", SezOccupantUserUndertakingInfo::getGroupId);
			attributeGetterFunctions.put(
				"companyId", SezOccupantUserUndertakingInfo::getCompanyId);
			attributeGetterFunctions.put(
				"userId", SezOccupantUserUndertakingInfo::getUserId);
			attributeGetterFunctions.put(
				"userName", SezOccupantUserUndertakingInfo::getUserName);
			attributeGetterFunctions.put(
				"createDate", SezOccupantUserUndertakingInfo::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate",
				SezOccupantUserUndertakingInfo::getModifiedDate);
			attributeGetterFunctions.put(
				"occApplicantTitle",
				SezOccupantUserUndertakingInfo::getOccApplicantTitle);
			attributeGetterFunctions.put(
				"occApplicantName",
				SezOccupantUserUndertakingInfo::getOccApplicantName);
			attributeGetterFunctions.put(
				"occApplicantTeleNum",
				SezOccupantUserUndertakingInfo::getOccApplicantTeleNum);
			attributeGetterFunctions.put(
				"occApplicantEmail",
				SezOccupantUserUndertakingInfo::getOccApplicantEmail);
			attributeGetterFunctions.put(
				"occApplicantSignDate",
				SezOccupantUserUndertakingInfo::getOccApplicantSignDate);
			attributeGetterFunctions.put(
				"occPublicNotaryName",
				SezOccupantUserUndertakingInfo::getOccPublicNotaryName);
			attributeGetterFunctions.put(
				"occPublicNotarySignDate",
				SezOccupantUserUndertakingInfo::getOccPublicNotarySignDate);
			attributeGetterFunctions.put(
				"sezStatusApplicationId",
				SezOccupantUserUndertakingInfo::getSezStatusApplicationId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<SezOccupantUserUndertakingInfo, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SezOccupantUserUndertakingInfo, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String,
						 BiConsumer<SezOccupantUserUndertakingInfo, ?>>();

			attributeSetterBiConsumers.put(
				"sezOccUserunderId",
				(BiConsumer<SezOccupantUserUndertakingInfo, Long>)
					SezOccupantUserUndertakingInfo::setSezOccUserunderId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<SezOccupantUserUndertakingInfo, Long>)
					SezOccupantUserUndertakingInfo::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<SezOccupantUserUndertakingInfo, Long>)
					SezOccupantUserUndertakingInfo::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<SezOccupantUserUndertakingInfo, Long>)
					SezOccupantUserUndertakingInfo::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<SezOccupantUserUndertakingInfo, String>)
					SezOccupantUserUndertakingInfo::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<SezOccupantUserUndertakingInfo, Date>)
					SezOccupantUserUndertakingInfo::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<SezOccupantUserUndertakingInfo, Date>)
					SezOccupantUserUndertakingInfo::setModifiedDate);
			attributeSetterBiConsumers.put(
				"occApplicantTitle",
				(BiConsumer<SezOccupantUserUndertakingInfo, String>)
					SezOccupantUserUndertakingInfo::setOccApplicantTitle);
			attributeSetterBiConsumers.put(
				"occApplicantName",
				(BiConsumer<SezOccupantUserUndertakingInfo, String>)
					SezOccupantUserUndertakingInfo::setOccApplicantName);
			attributeSetterBiConsumers.put(
				"occApplicantTeleNum",
				(BiConsumer<SezOccupantUserUndertakingInfo, String>)
					SezOccupantUserUndertakingInfo::setOccApplicantTeleNum);
			attributeSetterBiConsumers.put(
				"occApplicantEmail",
				(BiConsumer<SezOccupantUserUndertakingInfo, String>)
					SezOccupantUserUndertakingInfo::setOccApplicantEmail);
			attributeSetterBiConsumers.put(
				"occApplicantSignDate",
				(BiConsumer<SezOccupantUserUndertakingInfo, Date>)
					SezOccupantUserUndertakingInfo::setOccApplicantSignDate);
			attributeSetterBiConsumers.put(
				"occPublicNotaryName",
				(BiConsumer<SezOccupantUserUndertakingInfo, String>)
					SezOccupantUserUndertakingInfo::setOccPublicNotaryName);
			attributeSetterBiConsumers.put(
				"occPublicNotarySignDate",
				(BiConsumer<SezOccupantUserUndertakingInfo, Date>)
					SezOccupantUserUndertakingInfo::setOccPublicNotarySignDate);
			attributeSetterBiConsumers.put(
				"sezStatusApplicationId",
				(BiConsumer<SezOccupantUserUndertakingInfo, Long>)
					SezOccupantUserUndertakingInfo::setSezStatusApplicationId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getSezOccUserunderId() {
		return _sezOccUserunderId;
	}

	@Override
	public void setSezOccUserunderId(long sezOccUserunderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sezOccUserunderId = sezOccUserunderId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getOccApplicantTitle() {
		if (_occApplicantTitle == null) {
			return "";
		}
		else {
			return _occApplicantTitle;
		}
	}

	@Override
	public void setOccApplicantTitle(String occApplicantTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occApplicantTitle = occApplicantTitle;
	}

	@JSON
	@Override
	public String getOccApplicantName() {
		if (_occApplicantName == null) {
			return "";
		}
		else {
			return _occApplicantName;
		}
	}

	@Override
	public void setOccApplicantName(String occApplicantName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occApplicantName = occApplicantName;
	}

	@JSON
	@Override
	public String getOccApplicantTeleNum() {
		if (_occApplicantTeleNum == null) {
			return "";
		}
		else {
			return _occApplicantTeleNum;
		}
	}

	@Override
	public void setOccApplicantTeleNum(String occApplicantTeleNum) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occApplicantTeleNum = occApplicantTeleNum;
	}

	@JSON
	@Override
	public String getOccApplicantEmail() {
		if (_occApplicantEmail == null) {
			return "";
		}
		else {
			return _occApplicantEmail;
		}
	}

	@Override
	public void setOccApplicantEmail(String occApplicantEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occApplicantEmail = occApplicantEmail;
	}

	@JSON
	@Override
	public Date getOccApplicantSignDate() {
		return _occApplicantSignDate;
	}

	@Override
	public void setOccApplicantSignDate(Date occApplicantSignDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occApplicantSignDate = occApplicantSignDate;
	}

	@JSON
	@Override
	public String getOccPublicNotaryName() {
		if (_occPublicNotaryName == null) {
			return "";
		}
		else {
			return _occPublicNotaryName;
		}
	}

	@Override
	public void setOccPublicNotaryName(String occPublicNotaryName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occPublicNotaryName = occPublicNotaryName;
	}

	@JSON
	@Override
	public Date getOccPublicNotarySignDate() {
		return _occPublicNotarySignDate;
	}

	@Override
	public void setOccPublicNotarySignDate(Date occPublicNotarySignDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_occPublicNotarySignDate = occPublicNotarySignDate;
	}

	@JSON
	@Override
	public long getSezStatusApplicationId() {
		return _sezStatusApplicationId;
	}

	@Override
	public void setSezStatusApplicationId(long sezStatusApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sezStatusApplicationId = sezStatusApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSezStatusApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("sezStatusApplicationId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SezOccupantUserUndertakingInfo.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SezOccupantUserUndertakingInfo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SezOccupantUserUndertakingInfo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SezOccupantUserUndertakingInfoImpl sezOccupantUserUndertakingInfoImpl =
			new SezOccupantUserUndertakingInfoImpl();

		sezOccupantUserUndertakingInfoImpl.setSezOccUserunderId(
			getSezOccUserunderId());
		sezOccupantUserUndertakingInfoImpl.setGroupId(getGroupId());
		sezOccupantUserUndertakingInfoImpl.setCompanyId(getCompanyId());
		sezOccupantUserUndertakingInfoImpl.setUserId(getUserId());
		sezOccupantUserUndertakingInfoImpl.setUserName(getUserName());
		sezOccupantUserUndertakingInfoImpl.setCreateDate(getCreateDate());
		sezOccupantUserUndertakingInfoImpl.setModifiedDate(getModifiedDate());
		sezOccupantUserUndertakingInfoImpl.setOccApplicantTitle(
			getOccApplicantTitle());
		sezOccupantUserUndertakingInfoImpl.setOccApplicantName(
			getOccApplicantName());
		sezOccupantUserUndertakingInfoImpl.setOccApplicantTeleNum(
			getOccApplicantTeleNum());
		sezOccupantUserUndertakingInfoImpl.setOccApplicantEmail(
			getOccApplicantEmail());
		sezOccupantUserUndertakingInfoImpl.setOccApplicantSignDate(
			getOccApplicantSignDate());
		sezOccupantUserUndertakingInfoImpl.setOccPublicNotaryName(
			getOccPublicNotaryName());
		sezOccupantUserUndertakingInfoImpl.setOccPublicNotarySignDate(
			getOccPublicNotarySignDate());
		sezOccupantUserUndertakingInfoImpl.setSezStatusApplicationId(
			getSezStatusApplicationId());

		sezOccupantUserUndertakingInfoImpl.resetOriginalValues();

		return sezOccupantUserUndertakingInfoImpl;
	}

	@Override
	public SezOccupantUserUndertakingInfo cloneWithOriginalValues() {
		SezOccupantUserUndertakingInfoImpl sezOccupantUserUndertakingInfoImpl =
			new SezOccupantUserUndertakingInfoImpl();

		sezOccupantUserUndertakingInfoImpl.setSezOccUserunderId(
			this.<Long>getColumnOriginalValue("sezOccUserunderId"));
		sezOccupantUserUndertakingInfoImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		sezOccupantUserUndertakingInfoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		sezOccupantUserUndertakingInfoImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		sezOccupantUserUndertakingInfoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		sezOccupantUserUndertakingInfoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		sezOccupantUserUndertakingInfoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		sezOccupantUserUndertakingInfoImpl.setOccApplicantTitle(
			this.<String>getColumnOriginalValue("occApplicantTitle"));
		sezOccupantUserUndertakingInfoImpl.setOccApplicantName(
			this.<String>getColumnOriginalValue("occApplicantName"));
		sezOccupantUserUndertakingInfoImpl.setOccApplicantTeleNum(
			this.<String>getColumnOriginalValue("occApplicantTeleNum"));
		sezOccupantUserUndertakingInfoImpl.setOccApplicantEmail(
			this.<String>getColumnOriginalValue("occApplicantEmail"));
		sezOccupantUserUndertakingInfoImpl.setOccApplicantSignDate(
			this.<Date>getColumnOriginalValue("occApplicantSignDate"));
		sezOccupantUserUndertakingInfoImpl.setOccPublicNotaryName(
			this.<String>getColumnOriginalValue("occPublicNotaryName"));
		sezOccupantUserUndertakingInfoImpl.setOccPublicNotarySignDate(
			this.<Date>getColumnOriginalValue("occPublicNotarySignDate"));
		sezOccupantUserUndertakingInfoImpl.setSezStatusApplicationId(
			this.<Long>getColumnOriginalValue("sezStatusApplicationId"));

		return sezOccupantUserUndertakingInfoImpl;
	}

	@Override
	public int compareTo(
		SezOccupantUserUndertakingInfo sezOccupantUserUndertakingInfo) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), sezOccupantUserUndertakingInfo.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SezOccupantUserUndertakingInfo)) {
			return false;
		}

		SezOccupantUserUndertakingInfo sezOccupantUserUndertakingInfo =
			(SezOccupantUserUndertakingInfo)object;

		long primaryKey = sezOccupantUserUndertakingInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SezOccupantUserUndertakingInfo> toCacheModel() {
		SezOccupantUserUndertakingInfoCacheModel
			sezOccupantUserUndertakingInfoCacheModel =
				new SezOccupantUserUndertakingInfoCacheModel();

		sezOccupantUserUndertakingInfoCacheModel.sezOccUserunderId =
			getSezOccUserunderId();

		sezOccupantUserUndertakingInfoCacheModel.groupId = getGroupId();

		sezOccupantUserUndertakingInfoCacheModel.companyId = getCompanyId();

		sezOccupantUserUndertakingInfoCacheModel.userId = getUserId();

		sezOccupantUserUndertakingInfoCacheModel.userName = getUserName();

		String userName = sezOccupantUserUndertakingInfoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sezOccupantUserUndertakingInfoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sezOccupantUserUndertakingInfoCacheModel.createDate =
				createDate.getTime();
		}
		else {
			sezOccupantUserUndertakingInfoCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sezOccupantUserUndertakingInfoCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			sezOccupantUserUndertakingInfoCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		sezOccupantUserUndertakingInfoCacheModel.occApplicantTitle =
			getOccApplicantTitle();

		String occApplicantTitle =
			sezOccupantUserUndertakingInfoCacheModel.occApplicantTitle;

		if ((occApplicantTitle != null) && (occApplicantTitle.length() == 0)) {
			sezOccupantUserUndertakingInfoCacheModel.occApplicantTitle = null;
		}

		sezOccupantUserUndertakingInfoCacheModel.occApplicantName =
			getOccApplicantName();

		String occApplicantName =
			sezOccupantUserUndertakingInfoCacheModel.occApplicantName;

		if ((occApplicantName != null) && (occApplicantName.length() == 0)) {
			sezOccupantUserUndertakingInfoCacheModel.occApplicantName = null;
		}

		sezOccupantUserUndertakingInfoCacheModel.occApplicantTeleNum =
			getOccApplicantTeleNum();

		String occApplicantTeleNum =
			sezOccupantUserUndertakingInfoCacheModel.occApplicantTeleNum;

		if ((occApplicantTeleNum != null) &&
			(occApplicantTeleNum.length() == 0)) {

			sezOccupantUserUndertakingInfoCacheModel.occApplicantTeleNum = null;
		}

		sezOccupantUserUndertakingInfoCacheModel.occApplicantEmail =
			getOccApplicantEmail();

		String occApplicantEmail =
			sezOccupantUserUndertakingInfoCacheModel.occApplicantEmail;

		if ((occApplicantEmail != null) && (occApplicantEmail.length() == 0)) {
			sezOccupantUserUndertakingInfoCacheModel.occApplicantEmail = null;
		}

		Date occApplicantSignDate = getOccApplicantSignDate();

		if (occApplicantSignDate != null) {
			sezOccupantUserUndertakingInfoCacheModel.occApplicantSignDate =
				occApplicantSignDate.getTime();
		}
		else {
			sezOccupantUserUndertakingInfoCacheModel.occApplicantSignDate =
				Long.MIN_VALUE;
		}

		sezOccupantUserUndertakingInfoCacheModel.occPublicNotaryName =
			getOccPublicNotaryName();

		String occPublicNotaryName =
			sezOccupantUserUndertakingInfoCacheModel.occPublicNotaryName;

		if ((occPublicNotaryName != null) &&
			(occPublicNotaryName.length() == 0)) {

			sezOccupantUserUndertakingInfoCacheModel.occPublicNotaryName = null;
		}

		Date occPublicNotarySignDate = getOccPublicNotarySignDate();

		if (occPublicNotarySignDate != null) {
			sezOccupantUserUndertakingInfoCacheModel.occPublicNotarySignDate =
				occPublicNotarySignDate.getTime();
		}
		else {
			sezOccupantUserUndertakingInfoCacheModel.occPublicNotarySignDate =
				Long.MIN_VALUE;
		}

		sezOccupantUserUndertakingInfoCacheModel.sezStatusApplicationId =
			getSezStatusApplicationId();

		return sezOccupantUserUndertakingInfoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SezOccupantUserUndertakingInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SezOccupantUserUndertakingInfo, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SezOccupantUserUndertakingInfo, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SezOccupantUserUndertakingInfo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, SezOccupantUserUndertakingInfo>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						SezOccupantUserUndertakingInfo.class,
						ModelWrapper.class);

	}

	private long _sezOccUserunderId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _occApplicantTitle;
	private String _occApplicantName;
	private String _occApplicantTeleNum;
	private String _occApplicantEmail;
	private Date _occApplicantSignDate;
	private String _occPublicNotaryName;
	private Date _occPublicNotarySignDate;
	private long _sezStatusApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<SezOccupantUserUndertakingInfo, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SezOccupantUserUndertakingInfo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("sezOccUserunderId", _sezOccUserunderId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("occApplicantTitle", _occApplicantTitle);
		_columnOriginalValues.put("occApplicantName", _occApplicantName);
		_columnOriginalValues.put("occApplicantTeleNum", _occApplicantTeleNum);
		_columnOriginalValues.put("occApplicantEmail", _occApplicantEmail);
		_columnOriginalValues.put(
			"occApplicantSignDate", _occApplicantSignDate);
		_columnOriginalValues.put("occPublicNotaryName", _occPublicNotaryName);
		_columnOriginalValues.put(
			"occPublicNotarySignDate", _occPublicNotarySignDate);
		_columnOriginalValues.put(
			"sezStatusApplicationId", _sezStatusApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("sezOccUserunderId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("occApplicantTitle", 128L);

		columnBitmasks.put("occApplicantName", 256L);

		columnBitmasks.put("occApplicantTeleNum", 512L);

		columnBitmasks.put("occApplicantEmail", 1024L);

		columnBitmasks.put("occApplicantSignDate", 2048L);

		columnBitmasks.put("occPublicNotaryName", 4096L);

		columnBitmasks.put("occPublicNotarySignDate", 8192L);

		columnBitmasks.put("sezStatusApplicationId", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SezOccupantUserUndertakingInfo _escapedModel;

}