/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.hsra.stage.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.hsra.stage.services.model.HsraApplicationDeskVeri;
import com.nbp.hsra.stage.services.model.HsraApplicationDeskVeriModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the HsraApplicationDeskVeri service. Represents a row in the &quot;nbp_hsra_desk_verifi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HsraApplicationDeskVeriModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HsraApplicationDeskVeriImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HsraApplicationDeskVeriImpl
 * @generated
 */
@JSON(strict = true)
public class HsraApplicationDeskVeriModelImpl
	extends BaseModelImpl<HsraApplicationDeskVeri>
	implements HsraApplicationDeskVeriModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hsra application desk veri model instance should use the <code>HsraApplicationDeskVeri</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_hsra_desk_verifi";

	public static final Object[][] TABLE_COLUMNS = {
		{"hsraApplicationDeskVeriId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"hsraApplicationId", Types.BIGINT},
		{"documentStatus", Types.VARCHAR}, {"documentName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("hsraApplicationDeskVeriId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hsraApplicationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_hsra_desk_verifi (hsraApplicationDeskVeriId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,hsraApplicationId LONG,documentStatus VARCHAR(75) null,documentName VARCHAR(700) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_hsra_desk_verifi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY hsraApplicationDeskVeri.hsraApplicationDeskVeriId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_hsra_desk_verifi.hsraApplicationDeskVeriId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HSRAAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HSRAAPPLICATIONDESKVERIID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public HsraApplicationDeskVeriModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _hsraApplicationDeskVeriId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHsraApplicationDeskVeriId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _hsraApplicationDeskVeriId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return HsraApplicationDeskVeri.class;
	}

	@Override
	public String getModelClassName() {
		return HsraApplicationDeskVeri.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<HsraApplicationDeskVeri, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<HsraApplicationDeskVeri, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HsraApplicationDeskVeri, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((HsraApplicationDeskVeri)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<HsraApplicationDeskVeri, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<HsraApplicationDeskVeri, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(HsraApplicationDeskVeri)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<HsraApplicationDeskVeri, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<HsraApplicationDeskVeri, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<HsraApplicationDeskVeri, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<HsraApplicationDeskVeri, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<HsraApplicationDeskVeri, Object>>();

			attributeGetterFunctions.put(
				"hsraApplicationDeskVeriId",
				HsraApplicationDeskVeri::getHsraApplicationDeskVeriId);
			attributeGetterFunctions.put(
				"groupId", HsraApplicationDeskVeri::getGroupId);
			attributeGetterFunctions.put(
				"companyId", HsraApplicationDeskVeri::getCompanyId);
			attributeGetterFunctions.put(
				"userId", HsraApplicationDeskVeri::getUserId);
			attributeGetterFunctions.put(
				"userName", HsraApplicationDeskVeri::getUserName);
			attributeGetterFunctions.put(
				"createDate", HsraApplicationDeskVeri::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", HsraApplicationDeskVeri::getModifiedDate);
			attributeGetterFunctions.put(
				"hsraApplicationId",
				HsraApplicationDeskVeri::getHsraApplicationId);
			attributeGetterFunctions.put(
				"documentStatus", HsraApplicationDeskVeri::getDocumentStatus);
			attributeGetterFunctions.put(
				"documentName", HsraApplicationDeskVeri::getDocumentName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<HsraApplicationDeskVeri, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<HsraApplicationDeskVeri, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<HsraApplicationDeskVeri, ?>>();

			attributeSetterBiConsumers.put(
				"hsraApplicationDeskVeriId",
				(BiConsumer<HsraApplicationDeskVeri, Long>)
					HsraApplicationDeskVeri::setHsraApplicationDeskVeriId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<HsraApplicationDeskVeri, Long>)
					HsraApplicationDeskVeri::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<HsraApplicationDeskVeri, Long>)
					HsraApplicationDeskVeri::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<HsraApplicationDeskVeri, Long>)
					HsraApplicationDeskVeri::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<HsraApplicationDeskVeri, String>)
					HsraApplicationDeskVeri::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<HsraApplicationDeskVeri, Date>)
					HsraApplicationDeskVeri::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<HsraApplicationDeskVeri, Date>)
					HsraApplicationDeskVeri::setModifiedDate);
			attributeSetterBiConsumers.put(
				"hsraApplicationId",
				(BiConsumer<HsraApplicationDeskVeri, Long>)
					HsraApplicationDeskVeri::setHsraApplicationId);
			attributeSetterBiConsumers.put(
				"documentStatus",
				(BiConsumer<HsraApplicationDeskVeri, String>)
					HsraApplicationDeskVeri::setDocumentStatus);
			attributeSetterBiConsumers.put(
				"documentName",
				(BiConsumer<HsraApplicationDeskVeri, String>)
					HsraApplicationDeskVeri::setDocumentName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getHsraApplicationDeskVeriId() {
		return _hsraApplicationDeskVeriId;
	}

	@Override
	public void setHsraApplicationDeskVeriId(long hsraApplicationDeskVeriId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hsraApplicationDeskVeriId = hsraApplicationDeskVeriId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getHsraApplicationId() {
		return _hsraApplicationId;
	}

	@Override
	public void setHsraApplicationId(long hsraApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hsraApplicationId = hsraApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalHsraApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("hsraApplicationId"));
	}

	@JSON
	@Override
	public String getDocumentStatus() {
		if (_documentStatus == null) {
			return "";
		}
		else {
			return _documentStatus;
		}
	}

	@Override
	public void setDocumentStatus(String documentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentStatus = documentStatus;
	}

	@JSON
	@Override
	public String getDocumentName() {
		if (_documentName == null) {
			return "";
		}
		else {
			return _documentName;
		}
	}

	@Override
	public void setDocumentName(String documentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentName = documentName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), HsraApplicationDeskVeri.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public HsraApplicationDeskVeri toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, HsraApplicationDeskVeri>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HsraApplicationDeskVeriImpl hsraApplicationDeskVeriImpl =
			new HsraApplicationDeskVeriImpl();

		hsraApplicationDeskVeriImpl.setHsraApplicationDeskVeriId(
			getHsraApplicationDeskVeriId());
		hsraApplicationDeskVeriImpl.setGroupId(getGroupId());
		hsraApplicationDeskVeriImpl.setCompanyId(getCompanyId());
		hsraApplicationDeskVeriImpl.setUserId(getUserId());
		hsraApplicationDeskVeriImpl.setUserName(getUserName());
		hsraApplicationDeskVeriImpl.setCreateDate(getCreateDate());
		hsraApplicationDeskVeriImpl.setModifiedDate(getModifiedDate());
		hsraApplicationDeskVeriImpl.setHsraApplicationId(
			getHsraApplicationId());
		hsraApplicationDeskVeriImpl.setDocumentStatus(getDocumentStatus());
		hsraApplicationDeskVeriImpl.setDocumentName(getDocumentName());

		hsraApplicationDeskVeriImpl.resetOriginalValues();

		return hsraApplicationDeskVeriImpl;
	}

	@Override
	public HsraApplicationDeskVeri cloneWithOriginalValues() {
		HsraApplicationDeskVeriImpl hsraApplicationDeskVeriImpl =
			new HsraApplicationDeskVeriImpl();

		hsraApplicationDeskVeriImpl.setHsraApplicationDeskVeriId(
			this.<Long>getColumnOriginalValue("hsraApplicationDeskVeriId"));
		hsraApplicationDeskVeriImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		hsraApplicationDeskVeriImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		hsraApplicationDeskVeriImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		hsraApplicationDeskVeriImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		hsraApplicationDeskVeriImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		hsraApplicationDeskVeriImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		hsraApplicationDeskVeriImpl.setHsraApplicationId(
			this.<Long>getColumnOriginalValue("hsraApplicationId"));
		hsraApplicationDeskVeriImpl.setDocumentStatus(
			this.<String>getColumnOriginalValue("documentStatus"));
		hsraApplicationDeskVeriImpl.setDocumentName(
			this.<String>getColumnOriginalValue("documentName"));

		return hsraApplicationDeskVeriImpl;
	}

	@Override
	public int compareTo(HsraApplicationDeskVeri hsraApplicationDeskVeri) {
		long primaryKey = hsraApplicationDeskVeri.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof HsraApplicationDeskVeri)) {
			return false;
		}

		HsraApplicationDeskVeri hsraApplicationDeskVeri =
			(HsraApplicationDeskVeri)object;

		long primaryKey = hsraApplicationDeskVeri.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<HsraApplicationDeskVeri> toCacheModel() {
		HsraApplicationDeskVeriCacheModel hsraApplicationDeskVeriCacheModel =
			new HsraApplicationDeskVeriCacheModel();

		hsraApplicationDeskVeriCacheModel.hsraApplicationDeskVeriId =
			getHsraApplicationDeskVeriId();

		hsraApplicationDeskVeriCacheModel.groupId = getGroupId();

		hsraApplicationDeskVeriCacheModel.companyId = getCompanyId();

		hsraApplicationDeskVeriCacheModel.userId = getUserId();

		hsraApplicationDeskVeriCacheModel.userName = getUserName();

		String userName = hsraApplicationDeskVeriCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			hsraApplicationDeskVeriCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			hsraApplicationDeskVeriCacheModel.createDate = createDate.getTime();
		}
		else {
			hsraApplicationDeskVeriCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			hsraApplicationDeskVeriCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			hsraApplicationDeskVeriCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		hsraApplicationDeskVeriCacheModel.hsraApplicationId =
			getHsraApplicationId();

		hsraApplicationDeskVeriCacheModel.documentStatus = getDocumentStatus();

		String documentStatus =
			hsraApplicationDeskVeriCacheModel.documentStatus;

		if ((documentStatus != null) && (documentStatus.length() == 0)) {
			hsraApplicationDeskVeriCacheModel.documentStatus = null;
		}

		hsraApplicationDeskVeriCacheModel.documentName = getDocumentName();

		String documentName = hsraApplicationDeskVeriCacheModel.documentName;

		if ((documentName != null) && (documentName.length() == 0)) {
			hsraApplicationDeskVeriCacheModel.documentName = null;
		}

		return hsraApplicationDeskVeriCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<HsraApplicationDeskVeri, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<HsraApplicationDeskVeri, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HsraApplicationDeskVeri, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(HsraApplicationDeskVeri)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, HsraApplicationDeskVeri>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						HsraApplicationDeskVeri.class, ModelWrapper.class);

	}

	private long _hsraApplicationDeskVeriId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _hsraApplicationId;
	private String _documentStatus;
	private String _documentName;

	public <T> T getColumnValue(String columnName) {
		Function<HsraApplicationDeskVeri, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((HsraApplicationDeskVeri)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"hsraApplicationDeskVeriId", _hsraApplicationDeskVeriId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("hsraApplicationId", _hsraApplicationId);
		_columnOriginalValues.put("documentStatus", _documentStatus);
		_columnOriginalValues.put("documentName", _documentName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("hsraApplicationDeskVeriId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("hsraApplicationId", 128L);

		columnBitmasks.put("documentStatus", 256L);

		columnBitmasks.put("documentName", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private HsraApplicationDeskVeri _escapedModel;

}