/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.medical.facilities.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.medical.facilities.application.form.service.model.MedicalFacilitiesNurseDetail;
import com.nbp.medical.facilities.application.form.service.model.MedicalFacilitiesNurseDetailModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MedicalFacilitiesNurseDetail service. Represents a row in the &quot;nbp_medical_nurse_detail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MedicalFacilitiesNurseDetailModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MedicalFacilitiesNurseDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MedicalFacilitiesNurseDetailImpl
 * @generated
 */
@JSON(strict = true)
public class MedicalFacilitiesNurseDetailModelImpl
	extends BaseModelImpl<MedicalFacilitiesNurseDetail>
	implements MedicalFacilitiesNurseDetailModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a medical facilities nurse detail model instance should use the <code>MedicalFacilitiesNurseDetail</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_medical_nurse_detail";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR},
		{"medicalFacilitiesNurseDetailId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"qNurseName", Types.VARCHAR}, {"qNurseQualification", Types.VARCHAR},
		{"ratioOfQNurses", Types.VARCHAR}, {"counter", Types.VARCHAR},
		{"medicalFacilitiesAppId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("medicalFacilitiesNurseDetailId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("qNurseName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("qNurseQualification", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ratioOfQNurses", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("counter", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("medicalFacilitiesAppId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_medical_nurse_detail (uuid_ VARCHAR(75) null,medicalFacilitiesNurseDetailId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,qNurseName VARCHAR(75) null,qNurseQualification VARCHAR(75) null,ratioOfQNurses VARCHAR(75) null,counter VARCHAR(75) null,medicalFacilitiesAppId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_medical_nurse_detail";

	public static final String ORDER_BY_JPQL =
		" ORDER BY medicalFacilitiesNurseDetail.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_medical_nurse_detail.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MEDICALFACILITIESAPPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MedicalFacilitiesNurseDetailModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _medicalFacilitiesNurseDetailId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMedicalFacilitiesNurseDetailId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _medicalFacilitiesNurseDetailId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MedicalFacilitiesNurseDetail.class;
	}

	@Override
	public String getModelClassName() {
		return MedicalFacilitiesNurseDetail.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MedicalFacilitiesNurseDetail, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MedicalFacilitiesNurseDetail, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MedicalFacilitiesNurseDetail, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(MedicalFacilitiesNurseDetail)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MedicalFacilitiesNurseDetail, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MedicalFacilitiesNurseDetail, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MedicalFacilitiesNurseDetail)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MedicalFacilitiesNurseDetail, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MedicalFacilitiesNurseDetail, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<MedicalFacilitiesNurseDetail, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<MedicalFacilitiesNurseDetail, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<MedicalFacilitiesNurseDetail, Object>>();

			attributeGetterFunctions.put(
				"uuid", MedicalFacilitiesNurseDetail::getUuid);
			attributeGetterFunctions.put(
				"medicalFacilitiesNurseDetailId",
				MedicalFacilitiesNurseDetail::
					getMedicalFacilitiesNurseDetailId);
			attributeGetterFunctions.put(
				"groupId", MedicalFacilitiesNurseDetail::getGroupId);
			attributeGetterFunctions.put(
				"companyId", MedicalFacilitiesNurseDetail::getCompanyId);
			attributeGetterFunctions.put(
				"userId", MedicalFacilitiesNurseDetail::getUserId);
			attributeGetterFunctions.put(
				"userName", MedicalFacilitiesNurseDetail::getUserName);
			attributeGetterFunctions.put(
				"createDate", MedicalFacilitiesNurseDetail::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", MedicalFacilitiesNurseDetail::getModifiedDate);
			attributeGetterFunctions.put(
				"qNurseName", MedicalFacilitiesNurseDetail::getQNurseName);
			attributeGetterFunctions.put(
				"qNurseQualification",
				MedicalFacilitiesNurseDetail::getQNurseQualification);
			attributeGetterFunctions.put(
				"ratioOfQNurses",
				MedicalFacilitiesNurseDetail::getRatioOfQNurses);
			attributeGetterFunctions.put(
				"counter", MedicalFacilitiesNurseDetail::getCounter);
			attributeGetterFunctions.put(
				"medicalFacilitiesAppId",
				MedicalFacilitiesNurseDetail::getMedicalFacilitiesAppId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<MedicalFacilitiesNurseDetail, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<MedicalFacilitiesNurseDetail, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<MedicalFacilitiesNurseDetail, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<MedicalFacilitiesNurseDetail, String>)
					MedicalFacilitiesNurseDetail::setUuid);
			attributeSetterBiConsumers.put(
				"medicalFacilitiesNurseDetailId",
				(BiConsumer<MedicalFacilitiesNurseDetail, Long>)
					MedicalFacilitiesNurseDetail::
						setMedicalFacilitiesNurseDetailId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<MedicalFacilitiesNurseDetail, Long>)
					MedicalFacilitiesNurseDetail::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<MedicalFacilitiesNurseDetail, Long>)
					MedicalFacilitiesNurseDetail::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<MedicalFacilitiesNurseDetail, Long>)
					MedicalFacilitiesNurseDetail::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<MedicalFacilitiesNurseDetail, String>)
					MedicalFacilitiesNurseDetail::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<MedicalFacilitiesNurseDetail, Date>)
					MedicalFacilitiesNurseDetail::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<MedicalFacilitiesNurseDetail, Date>)
					MedicalFacilitiesNurseDetail::setModifiedDate);
			attributeSetterBiConsumers.put(
				"qNurseName",
				(BiConsumer<MedicalFacilitiesNurseDetail, String>)
					MedicalFacilitiesNurseDetail::setQNurseName);
			attributeSetterBiConsumers.put(
				"qNurseQualification",
				(BiConsumer<MedicalFacilitiesNurseDetail, String>)
					MedicalFacilitiesNurseDetail::setQNurseQualification);
			attributeSetterBiConsumers.put(
				"ratioOfQNurses",
				(BiConsumer<MedicalFacilitiesNurseDetail, String>)
					MedicalFacilitiesNurseDetail::setRatioOfQNurses);
			attributeSetterBiConsumers.put(
				"counter",
				(BiConsumer<MedicalFacilitiesNurseDetail, String>)
					MedicalFacilitiesNurseDetail::setCounter);
			attributeSetterBiConsumers.put(
				"medicalFacilitiesAppId",
				(BiConsumer<MedicalFacilitiesNurseDetail, Long>)
					MedicalFacilitiesNurseDetail::setMedicalFacilitiesAppId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getMedicalFacilitiesNurseDetailId() {
		return _medicalFacilitiesNurseDetailId;
	}

	@Override
	public void setMedicalFacilitiesNurseDetailId(
		long medicalFacilitiesNurseDetailId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_medicalFacilitiesNurseDetailId = medicalFacilitiesNurseDetailId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getQNurseName() {
		if (_qNurseName == null) {
			return "";
		}
		else {
			return _qNurseName;
		}
	}

	@Override
	public void setQNurseName(String qNurseName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qNurseName = qNurseName;
	}

	@JSON
	@Override
	public String getQNurseQualification() {
		if (_qNurseQualification == null) {
			return "";
		}
		else {
			return _qNurseQualification;
		}
	}

	@Override
	public void setQNurseQualification(String qNurseQualification) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qNurseQualification = qNurseQualification;
	}

	@JSON
	@Override
	public String getRatioOfQNurses() {
		if (_ratioOfQNurses == null) {
			return "";
		}
		else {
			return _ratioOfQNurses;
		}
	}

	@Override
	public void setRatioOfQNurses(String ratioOfQNurses) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ratioOfQNurses = ratioOfQNurses;
	}

	@JSON
	@Override
	public String getCounter() {
		if (_counter == null) {
			return "";
		}
		else {
			return _counter;
		}
	}

	@Override
	public void setCounter(String counter) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_counter = counter;
	}

	@JSON
	@Override
	public long getMedicalFacilitiesAppId() {
		return _medicalFacilitiesAppId;
	}

	@Override
	public void setMedicalFacilitiesAppId(long medicalFacilitiesAppId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_medicalFacilitiesAppId = medicalFacilitiesAppId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMedicalFacilitiesAppId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("medicalFacilitiesAppId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				MedicalFacilitiesNurseDetail.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MedicalFacilitiesNurseDetail.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MedicalFacilitiesNurseDetail toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MedicalFacilitiesNurseDetail>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MedicalFacilitiesNurseDetailImpl medicalFacilitiesNurseDetailImpl =
			new MedicalFacilitiesNurseDetailImpl();

		medicalFacilitiesNurseDetailImpl.setUuid(getUuid());
		medicalFacilitiesNurseDetailImpl.setMedicalFacilitiesNurseDetailId(
			getMedicalFacilitiesNurseDetailId());
		medicalFacilitiesNurseDetailImpl.setGroupId(getGroupId());
		medicalFacilitiesNurseDetailImpl.setCompanyId(getCompanyId());
		medicalFacilitiesNurseDetailImpl.setUserId(getUserId());
		medicalFacilitiesNurseDetailImpl.setUserName(getUserName());
		medicalFacilitiesNurseDetailImpl.setCreateDate(getCreateDate());
		medicalFacilitiesNurseDetailImpl.setModifiedDate(getModifiedDate());
		medicalFacilitiesNurseDetailImpl.setQNurseName(getQNurseName());
		medicalFacilitiesNurseDetailImpl.setQNurseQualification(
			getQNurseQualification());
		medicalFacilitiesNurseDetailImpl.setRatioOfQNurses(getRatioOfQNurses());
		medicalFacilitiesNurseDetailImpl.setCounter(getCounter());
		medicalFacilitiesNurseDetailImpl.setMedicalFacilitiesAppId(
			getMedicalFacilitiesAppId());

		medicalFacilitiesNurseDetailImpl.resetOriginalValues();

		return medicalFacilitiesNurseDetailImpl;
	}

	@Override
	public MedicalFacilitiesNurseDetail cloneWithOriginalValues() {
		MedicalFacilitiesNurseDetailImpl medicalFacilitiesNurseDetailImpl =
			new MedicalFacilitiesNurseDetailImpl();

		medicalFacilitiesNurseDetailImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		medicalFacilitiesNurseDetailImpl.setMedicalFacilitiesNurseDetailId(
			this.<Long>getColumnOriginalValue(
				"medicalFacilitiesNurseDetailId"));
		medicalFacilitiesNurseDetailImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		medicalFacilitiesNurseDetailImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		medicalFacilitiesNurseDetailImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		medicalFacilitiesNurseDetailImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		medicalFacilitiesNurseDetailImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		medicalFacilitiesNurseDetailImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		medicalFacilitiesNurseDetailImpl.setQNurseName(
			this.<String>getColumnOriginalValue("qNurseName"));
		medicalFacilitiesNurseDetailImpl.setQNurseQualification(
			this.<String>getColumnOriginalValue("qNurseQualification"));
		medicalFacilitiesNurseDetailImpl.setRatioOfQNurses(
			this.<String>getColumnOriginalValue("ratioOfQNurses"));
		medicalFacilitiesNurseDetailImpl.setCounter(
			this.<String>getColumnOriginalValue("counter"));
		medicalFacilitiesNurseDetailImpl.setMedicalFacilitiesAppId(
			this.<Long>getColumnOriginalValue("medicalFacilitiesAppId"));

		return medicalFacilitiesNurseDetailImpl;
	}

	@Override
	public int compareTo(
		MedicalFacilitiesNurseDetail medicalFacilitiesNurseDetail) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), medicalFacilitiesNurseDetail.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MedicalFacilitiesNurseDetail)) {
			return false;
		}

		MedicalFacilitiesNurseDetail medicalFacilitiesNurseDetail =
			(MedicalFacilitiesNurseDetail)object;

		long primaryKey = medicalFacilitiesNurseDetail.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MedicalFacilitiesNurseDetail> toCacheModel() {
		MedicalFacilitiesNurseDetailCacheModel
			medicalFacilitiesNurseDetailCacheModel =
				new MedicalFacilitiesNurseDetailCacheModel();

		medicalFacilitiesNurseDetailCacheModel.uuid = getUuid();

		String uuid = medicalFacilitiesNurseDetailCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			medicalFacilitiesNurseDetailCacheModel.uuid = null;
		}

		medicalFacilitiesNurseDetailCacheModel.medicalFacilitiesNurseDetailId =
			getMedicalFacilitiesNurseDetailId();

		medicalFacilitiesNurseDetailCacheModel.groupId = getGroupId();

		medicalFacilitiesNurseDetailCacheModel.companyId = getCompanyId();

		medicalFacilitiesNurseDetailCacheModel.userId = getUserId();

		medicalFacilitiesNurseDetailCacheModel.userName = getUserName();

		String userName = medicalFacilitiesNurseDetailCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			medicalFacilitiesNurseDetailCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			medicalFacilitiesNurseDetailCacheModel.createDate =
				createDate.getTime();
		}
		else {
			medicalFacilitiesNurseDetailCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			medicalFacilitiesNurseDetailCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			medicalFacilitiesNurseDetailCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		medicalFacilitiesNurseDetailCacheModel.qNurseName = getQNurseName();

		String qNurseName = medicalFacilitiesNurseDetailCacheModel.qNurseName;

		if ((qNurseName != null) && (qNurseName.length() == 0)) {
			medicalFacilitiesNurseDetailCacheModel.qNurseName = null;
		}

		medicalFacilitiesNurseDetailCacheModel.qNurseQualification =
			getQNurseQualification();

		String qNurseQualification =
			medicalFacilitiesNurseDetailCacheModel.qNurseQualification;

		if ((qNurseQualification != null) &&
			(qNurseQualification.length() == 0)) {

			medicalFacilitiesNurseDetailCacheModel.qNurseQualification = null;
		}

		medicalFacilitiesNurseDetailCacheModel.ratioOfQNurses =
			getRatioOfQNurses();

		String ratioOfQNurses =
			medicalFacilitiesNurseDetailCacheModel.ratioOfQNurses;

		if ((ratioOfQNurses != null) && (ratioOfQNurses.length() == 0)) {
			medicalFacilitiesNurseDetailCacheModel.ratioOfQNurses = null;
		}

		medicalFacilitiesNurseDetailCacheModel.counter = getCounter();

		String counter = medicalFacilitiesNurseDetailCacheModel.counter;

		if ((counter != null) && (counter.length() == 0)) {
			medicalFacilitiesNurseDetailCacheModel.counter = null;
		}

		medicalFacilitiesNurseDetailCacheModel.medicalFacilitiesAppId =
			getMedicalFacilitiesAppId();

		return medicalFacilitiesNurseDetailCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MedicalFacilitiesNurseDetail, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MedicalFacilitiesNurseDetail, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MedicalFacilitiesNurseDetail, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MedicalFacilitiesNurseDetail)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, MedicalFacilitiesNurseDetail>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						MedicalFacilitiesNurseDetail.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _medicalFacilitiesNurseDetailId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _qNurseName;
	private String _qNurseQualification;
	private String _ratioOfQNurses;
	private String _counter;
	private long _medicalFacilitiesAppId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MedicalFacilitiesNurseDetail, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MedicalFacilitiesNurseDetail)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"medicalFacilitiesNurseDetailId", _medicalFacilitiesNurseDetailId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("qNurseName", _qNurseName);
		_columnOriginalValues.put("qNurseQualification", _qNurseQualification);
		_columnOriginalValues.put("ratioOfQNurses", _ratioOfQNurses);
		_columnOriginalValues.put("counter", _counter);
		_columnOriginalValues.put(
			"medicalFacilitiesAppId", _medicalFacilitiesAppId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("medicalFacilitiesNurseDetailId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("qNurseName", 256L);

		columnBitmasks.put("qNurseQualification", 512L);

		columnBitmasks.put("ratioOfQNurses", 1024L);

		columnBitmasks.put("counter", 2048L);

		columnBitmasks.put("medicalFacilitiesAppId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MedicalFacilitiesNurseDetail _escapedModel;

}