/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.medical.facilities.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.medical.facilities.application.form.service.model.MedicalFacilitiesNurseStaff;
import com.nbp.medical.facilities.application.form.service.model.MedicalFacilitiesNurseStaffModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MedicalFacilitiesNurseStaff service. Represents a row in the &quot;nbp_medical_nursing_staff&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MedicalFacilitiesNurseStaffModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MedicalFacilitiesNurseStaffImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MedicalFacilitiesNurseStaffImpl
 * @generated
 */
@JSON(strict = true)
public class MedicalFacilitiesNurseStaffModelImpl
	extends BaseModelImpl<MedicalFacilitiesNurseStaff>
	implements MedicalFacilitiesNurseStaffModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a medical facilities nurse staff model instance should use the <code>MedicalFacilitiesNurseStaff</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_medical_nursing_staff";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR},
		{"medicalFacilitiesNurseStaffId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"nStaffName", Types.VARCHAR}, {"nStaffQualification", Types.VARCHAR},
		{"nStaffState", Types.VARCHAR}, {"counter", Types.VARCHAR},
		{"medicalFacilitiesAppId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("medicalFacilitiesNurseStaffId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nStaffName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nStaffQualification", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nStaffState", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("counter", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("medicalFacilitiesAppId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_medical_nursing_staff (uuid_ VARCHAR(75) null,medicalFacilitiesNurseStaffId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nStaffName VARCHAR(75) null,nStaffQualification VARCHAR(75) null,nStaffState VARCHAR(75) null,counter VARCHAR(75) null,medicalFacilitiesAppId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_medical_nursing_staff";

	public static final String ORDER_BY_JPQL =
		" ORDER BY medicalFacilitiesNurseStaff.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_medical_nursing_staff.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MEDICALFACILITIESAPPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MedicalFacilitiesNurseStaffModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _medicalFacilitiesNurseStaffId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMedicalFacilitiesNurseStaffId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _medicalFacilitiesNurseStaffId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MedicalFacilitiesNurseStaff.class;
	}

	@Override
	public String getModelClassName() {
		return MedicalFacilitiesNurseStaff.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MedicalFacilitiesNurseStaff, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MedicalFacilitiesNurseStaff, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MedicalFacilitiesNurseStaff, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(MedicalFacilitiesNurseStaff)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MedicalFacilitiesNurseStaff, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MedicalFacilitiesNurseStaff, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MedicalFacilitiesNurseStaff)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MedicalFacilitiesNurseStaff, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MedicalFacilitiesNurseStaff, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<MedicalFacilitiesNurseStaff, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<MedicalFacilitiesNurseStaff, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<MedicalFacilitiesNurseStaff, Object>>();

			attributeGetterFunctions.put(
				"uuid", MedicalFacilitiesNurseStaff::getUuid);
			attributeGetterFunctions.put(
				"medicalFacilitiesNurseStaffId",
				MedicalFacilitiesNurseStaff::getMedicalFacilitiesNurseStaffId);
			attributeGetterFunctions.put(
				"groupId", MedicalFacilitiesNurseStaff::getGroupId);
			attributeGetterFunctions.put(
				"companyId", MedicalFacilitiesNurseStaff::getCompanyId);
			attributeGetterFunctions.put(
				"userId", MedicalFacilitiesNurseStaff::getUserId);
			attributeGetterFunctions.put(
				"userName", MedicalFacilitiesNurseStaff::getUserName);
			attributeGetterFunctions.put(
				"createDate", MedicalFacilitiesNurseStaff::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", MedicalFacilitiesNurseStaff::getModifiedDate);
			attributeGetterFunctions.put(
				"nStaffName", MedicalFacilitiesNurseStaff::getNStaffName);
			attributeGetterFunctions.put(
				"nStaffQualification",
				MedicalFacilitiesNurseStaff::getNStaffQualification);
			attributeGetterFunctions.put(
				"nStaffState", MedicalFacilitiesNurseStaff::getNStaffState);
			attributeGetterFunctions.put(
				"counter", MedicalFacilitiesNurseStaff::getCounter);
			attributeGetterFunctions.put(
				"medicalFacilitiesAppId",
				MedicalFacilitiesNurseStaff::getMedicalFacilitiesAppId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<MedicalFacilitiesNurseStaff, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<MedicalFacilitiesNurseStaff, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<MedicalFacilitiesNurseStaff, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<MedicalFacilitiesNurseStaff, String>)
					MedicalFacilitiesNurseStaff::setUuid);
			attributeSetterBiConsumers.put(
				"medicalFacilitiesNurseStaffId",
				(BiConsumer<MedicalFacilitiesNurseStaff, Long>)
					MedicalFacilitiesNurseStaff::
						setMedicalFacilitiesNurseStaffId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<MedicalFacilitiesNurseStaff, Long>)
					MedicalFacilitiesNurseStaff::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<MedicalFacilitiesNurseStaff, Long>)
					MedicalFacilitiesNurseStaff::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<MedicalFacilitiesNurseStaff, Long>)
					MedicalFacilitiesNurseStaff::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<MedicalFacilitiesNurseStaff, String>)
					MedicalFacilitiesNurseStaff::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<MedicalFacilitiesNurseStaff, Date>)
					MedicalFacilitiesNurseStaff::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<MedicalFacilitiesNurseStaff, Date>)
					MedicalFacilitiesNurseStaff::setModifiedDate);
			attributeSetterBiConsumers.put(
				"nStaffName",
				(BiConsumer<MedicalFacilitiesNurseStaff, String>)
					MedicalFacilitiesNurseStaff::setNStaffName);
			attributeSetterBiConsumers.put(
				"nStaffQualification",
				(BiConsumer<MedicalFacilitiesNurseStaff, String>)
					MedicalFacilitiesNurseStaff::setNStaffQualification);
			attributeSetterBiConsumers.put(
				"nStaffState",
				(BiConsumer<MedicalFacilitiesNurseStaff, String>)
					MedicalFacilitiesNurseStaff::setNStaffState);
			attributeSetterBiConsumers.put(
				"counter",
				(BiConsumer<MedicalFacilitiesNurseStaff, String>)
					MedicalFacilitiesNurseStaff::setCounter);
			attributeSetterBiConsumers.put(
				"medicalFacilitiesAppId",
				(BiConsumer<MedicalFacilitiesNurseStaff, Long>)
					MedicalFacilitiesNurseStaff::setMedicalFacilitiesAppId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getMedicalFacilitiesNurseStaffId() {
		return _medicalFacilitiesNurseStaffId;
	}

	@Override
	public void setMedicalFacilitiesNurseStaffId(
		long medicalFacilitiesNurseStaffId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_medicalFacilitiesNurseStaffId = medicalFacilitiesNurseStaffId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getNStaffName() {
		if (_nStaffName == null) {
			return "";
		}
		else {
			return _nStaffName;
		}
	}

	@Override
	public void setNStaffName(String nStaffName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nStaffName = nStaffName;
	}

	@JSON
	@Override
	public String getNStaffQualification() {
		if (_nStaffQualification == null) {
			return "";
		}
		else {
			return _nStaffQualification;
		}
	}

	@Override
	public void setNStaffQualification(String nStaffQualification) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nStaffQualification = nStaffQualification;
	}

	@JSON
	@Override
	public String getNStaffState() {
		if (_nStaffState == null) {
			return "";
		}
		else {
			return _nStaffState;
		}
	}

	@Override
	public void setNStaffState(String nStaffState) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nStaffState = nStaffState;
	}

	@JSON
	@Override
	public String getCounter() {
		if (_counter == null) {
			return "";
		}
		else {
			return _counter;
		}
	}

	@Override
	public void setCounter(String counter) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_counter = counter;
	}

	@JSON
	@Override
	public long getMedicalFacilitiesAppId() {
		return _medicalFacilitiesAppId;
	}

	@Override
	public void setMedicalFacilitiesAppId(long medicalFacilitiesAppId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_medicalFacilitiesAppId = medicalFacilitiesAppId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMedicalFacilitiesAppId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("medicalFacilitiesAppId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				MedicalFacilitiesNurseStaff.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MedicalFacilitiesNurseStaff.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MedicalFacilitiesNurseStaff toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MedicalFacilitiesNurseStaff>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MedicalFacilitiesNurseStaffImpl medicalFacilitiesNurseStaffImpl =
			new MedicalFacilitiesNurseStaffImpl();

		medicalFacilitiesNurseStaffImpl.setUuid(getUuid());
		medicalFacilitiesNurseStaffImpl.setMedicalFacilitiesNurseStaffId(
			getMedicalFacilitiesNurseStaffId());
		medicalFacilitiesNurseStaffImpl.setGroupId(getGroupId());
		medicalFacilitiesNurseStaffImpl.setCompanyId(getCompanyId());
		medicalFacilitiesNurseStaffImpl.setUserId(getUserId());
		medicalFacilitiesNurseStaffImpl.setUserName(getUserName());
		medicalFacilitiesNurseStaffImpl.setCreateDate(getCreateDate());
		medicalFacilitiesNurseStaffImpl.setModifiedDate(getModifiedDate());
		medicalFacilitiesNurseStaffImpl.setNStaffName(getNStaffName());
		medicalFacilitiesNurseStaffImpl.setNStaffQualification(
			getNStaffQualification());
		medicalFacilitiesNurseStaffImpl.setNStaffState(getNStaffState());
		medicalFacilitiesNurseStaffImpl.setCounter(getCounter());
		medicalFacilitiesNurseStaffImpl.setMedicalFacilitiesAppId(
			getMedicalFacilitiesAppId());

		medicalFacilitiesNurseStaffImpl.resetOriginalValues();

		return medicalFacilitiesNurseStaffImpl;
	}

	@Override
	public MedicalFacilitiesNurseStaff cloneWithOriginalValues() {
		MedicalFacilitiesNurseStaffImpl medicalFacilitiesNurseStaffImpl =
			new MedicalFacilitiesNurseStaffImpl();

		medicalFacilitiesNurseStaffImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		medicalFacilitiesNurseStaffImpl.setMedicalFacilitiesNurseStaffId(
			this.<Long>getColumnOriginalValue("medicalFacilitiesNurseStaffId"));
		medicalFacilitiesNurseStaffImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		medicalFacilitiesNurseStaffImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		medicalFacilitiesNurseStaffImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		medicalFacilitiesNurseStaffImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		medicalFacilitiesNurseStaffImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		medicalFacilitiesNurseStaffImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		medicalFacilitiesNurseStaffImpl.setNStaffName(
			this.<String>getColumnOriginalValue("nStaffName"));
		medicalFacilitiesNurseStaffImpl.setNStaffQualification(
			this.<String>getColumnOriginalValue("nStaffQualification"));
		medicalFacilitiesNurseStaffImpl.setNStaffState(
			this.<String>getColumnOriginalValue("nStaffState"));
		medicalFacilitiesNurseStaffImpl.setCounter(
			this.<String>getColumnOriginalValue("counter"));
		medicalFacilitiesNurseStaffImpl.setMedicalFacilitiesAppId(
			this.<Long>getColumnOriginalValue("medicalFacilitiesAppId"));

		return medicalFacilitiesNurseStaffImpl;
	}

	@Override
	public int compareTo(
		MedicalFacilitiesNurseStaff medicalFacilitiesNurseStaff) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), medicalFacilitiesNurseStaff.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MedicalFacilitiesNurseStaff)) {
			return false;
		}

		MedicalFacilitiesNurseStaff medicalFacilitiesNurseStaff =
			(MedicalFacilitiesNurseStaff)object;

		long primaryKey = medicalFacilitiesNurseStaff.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MedicalFacilitiesNurseStaff> toCacheModel() {
		MedicalFacilitiesNurseStaffCacheModel
			medicalFacilitiesNurseStaffCacheModel =
				new MedicalFacilitiesNurseStaffCacheModel();

		medicalFacilitiesNurseStaffCacheModel.uuid = getUuid();

		String uuid = medicalFacilitiesNurseStaffCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			medicalFacilitiesNurseStaffCacheModel.uuid = null;
		}

		medicalFacilitiesNurseStaffCacheModel.medicalFacilitiesNurseStaffId =
			getMedicalFacilitiesNurseStaffId();

		medicalFacilitiesNurseStaffCacheModel.groupId = getGroupId();

		medicalFacilitiesNurseStaffCacheModel.companyId = getCompanyId();

		medicalFacilitiesNurseStaffCacheModel.userId = getUserId();

		medicalFacilitiesNurseStaffCacheModel.userName = getUserName();

		String userName = medicalFacilitiesNurseStaffCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			medicalFacilitiesNurseStaffCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			medicalFacilitiesNurseStaffCacheModel.createDate =
				createDate.getTime();
		}
		else {
			medicalFacilitiesNurseStaffCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			medicalFacilitiesNurseStaffCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			medicalFacilitiesNurseStaffCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		medicalFacilitiesNurseStaffCacheModel.nStaffName = getNStaffName();

		String nStaffName = medicalFacilitiesNurseStaffCacheModel.nStaffName;

		if ((nStaffName != null) && (nStaffName.length() == 0)) {
			medicalFacilitiesNurseStaffCacheModel.nStaffName = null;
		}

		medicalFacilitiesNurseStaffCacheModel.nStaffQualification =
			getNStaffQualification();

		String nStaffQualification =
			medicalFacilitiesNurseStaffCacheModel.nStaffQualification;

		if ((nStaffQualification != null) &&
			(nStaffQualification.length() == 0)) {

			medicalFacilitiesNurseStaffCacheModel.nStaffQualification = null;
		}

		medicalFacilitiesNurseStaffCacheModel.nStaffState = getNStaffState();

		String nStaffState = medicalFacilitiesNurseStaffCacheModel.nStaffState;

		if ((nStaffState != null) && (nStaffState.length() == 0)) {
			medicalFacilitiesNurseStaffCacheModel.nStaffState = null;
		}

		medicalFacilitiesNurseStaffCacheModel.counter = getCounter();

		String counter = medicalFacilitiesNurseStaffCacheModel.counter;

		if ((counter != null) && (counter.length() == 0)) {
			medicalFacilitiesNurseStaffCacheModel.counter = null;
		}

		medicalFacilitiesNurseStaffCacheModel.medicalFacilitiesAppId =
			getMedicalFacilitiesAppId();

		return medicalFacilitiesNurseStaffCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MedicalFacilitiesNurseStaff, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MedicalFacilitiesNurseStaff, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MedicalFacilitiesNurseStaff, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MedicalFacilitiesNurseStaff)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, MedicalFacilitiesNurseStaff>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						MedicalFacilitiesNurseStaff.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _medicalFacilitiesNurseStaffId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _nStaffName;
	private String _nStaffQualification;
	private String _nStaffState;
	private String _counter;
	private long _medicalFacilitiesAppId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MedicalFacilitiesNurseStaff, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MedicalFacilitiesNurseStaff)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"medicalFacilitiesNurseStaffId", _medicalFacilitiesNurseStaffId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("nStaffName", _nStaffName);
		_columnOriginalValues.put("nStaffQualification", _nStaffQualification);
		_columnOriginalValues.put("nStaffState", _nStaffState);
		_columnOriginalValues.put("counter", _counter);
		_columnOriginalValues.put(
			"medicalFacilitiesAppId", _medicalFacilitiesAppId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("medicalFacilitiesNurseStaffId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("nStaffName", 256L);

		columnBitmasks.put("nStaffQualification", 512L);

		columnBitmasks.put("nStaffState", 1024L);

		columnBitmasks.put("counter", 2048L);

		columnBitmasks.put("medicalFacilitiesAppId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MedicalFacilitiesNurseStaff _escapedModel;

}