/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.janaac.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.janaac.application.form.service.model.AddFdaAppliInfo;
import com.nbp.janaac.application.form.service.model.AddFdaAppliInfoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AddFdaAppliInfo service. Represents a row in the &quot;nbp_janaac_add_fda_Appli_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AddFdaAppliInfoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AddFdaAppliInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AddFdaAppliInfoImpl
 * @generated
 */
@JSON(strict = true)
public class AddFdaAppliInfoModelImpl
	extends BaseModelImpl<AddFdaAppliInfo> implements AddFdaAppliInfoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a add fda appli info model instance should use the <code>AddFdaAppliInfo</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_janaac_add_fda_Appli_info";

	public static final Object[][] TABLE_COLUMNS = {
		{"addFdaAppliInfoId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"janaacApplicationId", Types.BIGINT},
		{"counter", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("addFdaAppliInfoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("janaacApplicationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("counter", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_janaac_add_fda_Appli_info (addFdaAppliInfoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,email VARCHAR(75) null,janaacApplicationId LONG,counter VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_janaac_add_fda_Appli_info";

	public static final String ORDER_BY_JPQL =
		" ORDER BY addFdaAppliInfo.addFdaAppliInfoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_janaac_add_fda_Appli_info.addFdaAppliInfoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long JANAACAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ADDFDAAPPLIINFOID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AddFdaAppliInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _addFdaAppliInfoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAddFdaAppliInfoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _addFdaAppliInfoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AddFdaAppliInfo.class;
	}

	@Override
	public String getModelClassName() {
		return AddFdaAppliInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AddFdaAppliInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AddFdaAppliInfo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AddFdaAppliInfo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AddFdaAppliInfo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AddFdaAppliInfo, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AddFdaAppliInfo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AddFdaAppliInfo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AddFdaAppliInfo, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AddFdaAppliInfo, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AddFdaAppliInfo, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AddFdaAppliInfo, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AddFdaAppliInfo, Object>>();

			attributeGetterFunctions.put(
				"addFdaAppliInfoId", AddFdaAppliInfo::getAddFdaAppliInfoId);
			attributeGetterFunctions.put(
				"groupId", AddFdaAppliInfo::getGroupId);
			attributeGetterFunctions.put(
				"companyId", AddFdaAppliInfo::getCompanyId);
			attributeGetterFunctions.put("userId", AddFdaAppliInfo::getUserId);
			attributeGetterFunctions.put(
				"userName", AddFdaAppliInfo::getUserName);
			attributeGetterFunctions.put(
				"createDate", AddFdaAppliInfo::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AddFdaAppliInfo::getModifiedDate);
			attributeGetterFunctions.put("name", AddFdaAppliInfo::getName);
			attributeGetterFunctions.put("email", AddFdaAppliInfo::getEmail);
			attributeGetterFunctions.put(
				"janaacApplicationId", AddFdaAppliInfo::getJanaacApplicationId);
			attributeGetterFunctions.put(
				"counter", AddFdaAppliInfo::getCounter);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AddFdaAppliInfo, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AddFdaAppliInfo, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<AddFdaAppliInfo, ?>>();

			attributeSetterBiConsumers.put(
				"addFdaAppliInfoId",
				(BiConsumer<AddFdaAppliInfo, Long>)
					AddFdaAppliInfo::setAddFdaAppliInfoId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AddFdaAppliInfo, Long>)AddFdaAppliInfo::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AddFdaAppliInfo, Long>)
					AddFdaAppliInfo::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<AddFdaAppliInfo, Long>)AddFdaAppliInfo::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<AddFdaAppliInfo, String>)
					AddFdaAppliInfo::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AddFdaAppliInfo, Date>)
					AddFdaAppliInfo::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AddFdaAppliInfo, Date>)
					AddFdaAppliInfo::setModifiedDate);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<AddFdaAppliInfo, String>)AddFdaAppliInfo::setName);
			attributeSetterBiConsumers.put(
				"email",
				(BiConsumer<AddFdaAppliInfo, String>)AddFdaAppliInfo::setEmail);
			attributeSetterBiConsumers.put(
				"janaacApplicationId",
				(BiConsumer<AddFdaAppliInfo, Long>)
					AddFdaAppliInfo::setJanaacApplicationId);
			attributeSetterBiConsumers.put(
				"counter",
				(BiConsumer<AddFdaAppliInfo, String>)
					AddFdaAppliInfo::setCounter);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getAddFdaAppliInfoId() {
		return _addFdaAppliInfoId;
	}

	@Override
	public void setAddFdaAppliInfoId(long addFdaAppliInfoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addFdaAppliInfoId = addFdaAppliInfoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public long getJanaacApplicationId() {
		return _janaacApplicationId;
	}

	@Override
	public void setJanaacApplicationId(long janaacApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_janaacApplicationId = janaacApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalJanaacApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("janaacApplicationId"));
	}

	@JSON
	@Override
	public String getCounter() {
		if (_counter == null) {
			return "";
		}
		else {
			return _counter;
		}
	}

	@Override
	public void setCounter(String counter) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_counter = counter;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AddFdaAppliInfo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AddFdaAppliInfo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AddFdaAppliInfo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AddFdaAppliInfoImpl addFdaAppliInfoImpl = new AddFdaAppliInfoImpl();

		addFdaAppliInfoImpl.setAddFdaAppliInfoId(getAddFdaAppliInfoId());
		addFdaAppliInfoImpl.setGroupId(getGroupId());
		addFdaAppliInfoImpl.setCompanyId(getCompanyId());
		addFdaAppliInfoImpl.setUserId(getUserId());
		addFdaAppliInfoImpl.setUserName(getUserName());
		addFdaAppliInfoImpl.setCreateDate(getCreateDate());
		addFdaAppliInfoImpl.setModifiedDate(getModifiedDate());
		addFdaAppliInfoImpl.setName(getName());
		addFdaAppliInfoImpl.setEmail(getEmail());
		addFdaAppliInfoImpl.setJanaacApplicationId(getJanaacApplicationId());
		addFdaAppliInfoImpl.setCounter(getCounter());

		addFdaAppliInfoImpl.resetOriginalValues();

		return addFdaAppliInfoImpl;
	}

	@Override
	public AddFdaAppliInfo cloneWithOriginalValues() {
		AddFdaAppliInfoImpl addFdaAppliInfoImpl = new AddFdaAppliInfoImpl();

		addFdaAppliInfoImpl.setAddFdaAppliInfoId(
			this.<Long>getColumnOriginalValue("addFdaAppliInfoId"));
		addFdaAppliInfoImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		addFdaAppliInfoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		addFdaAppliInfoImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		addFdaAppliInfoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		addFdaAppliInfoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		addFdaAppliInfoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		addFdaAppliInfoImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		addFdaAppliInfoImpl.setEmail(
			this.<String>getColumnOriginalValue("email"));
		addFdaAppliInfoImpl.setJanaacApplicationId(
			this.<Long>getColumnOriginalValue("janaacApplicationId"));
		addFdaAppliInfoImpl.setCounter(
			this.<String>getColumnOriginalValue("counter"));

		return addFdaAppliInfoImpl;
	}

	@Override
	public int compareTo(AddFdaAppliInfo addFdaAppliInfo) {
		long primaryKey = addFdaAppliInfo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AddFdaAppliInfo)) {
			return false;
		}

		AddFdaAppliInfo addFdaAppliInfo = (AddFdaAppliInfo)object;

		long primaryKey = addFdaAppliInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AddFdaAppliInfo> toCacheModel() {
		AddFdaAppliInfoCacheModel addFdaAppliInfoCacheModel =
			new AddFdaAppliInfoCacheModel();

		addFdaAppliInfoCacheModel.addFdaAppliInfoId = getAddFdaAppliInfoId();

		addFdaAppliInfoCacheModel.groupId = getGroupId();

		addFdaAppliInfoCacheModel.companyId = getCompanyId();

		addFdaAppliInfoCacheModel.userId = getUserId();

		addFdaAppliInfoCacheModel.userName = getUserName();

		String userName = addFdaAppliInfoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			addFdaAppliInfoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			addFdaAppliInfoCacheModel.createDate = createDate.getTime();
		}
		else {
			addFdaAppliInfoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			addFdaAppliInfoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			addFdaAppliInfoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		addFdaAppliInfoCacheModel.name = getName();

		String name = addFdaAppliInfoCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			addFdaAppliInfoCacheModel.name = null;
		}

		addFdaAppliInfoCacheModel.email = getEmail();

		String email = addFdaAppliInfoCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			addFdaAppliInfoCacheModel.email = null;
		}

		addFdaAppliInfoCacheModel.janaacApplicationId =
			getJanaacApplicationId();

		addFdaAppliInfoCacheModel.counter = getCounter();

		String counter = addFdaAppliInfoCacheModel.counter;

		if ((counter != null) && (counter.length() == 0)) {
			addFdaAppliInfoCacheModel.counter = null;
		}

		return addFdaAppliInfoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AddFdaAppliInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AddFdaAppliInfo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AddFdaAppliInfo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AddFdaAppliInfo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AddFdaAppliInfo>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AddFdaAppliInfo.class, ModelWrapper.class);

	}

	private long _addFdaAppliInfoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _email;
	private long _janaacApplicationId;
	private String _counter;

	public <T> T getColumnValue(String columnName) {
		Function<AddFdaAppliInfo, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AddFdaAppliInfo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("addFdaAppliInfoId", _addFdaAppliInfoId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("janaacApplicationId", _janaacApplicationId);
		_columnOriginalValues.put("counter", _counter);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("addFdaAppliInfoId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("email", 256L);

		columnBitmasks.put("janaacApplicationId", 512L);

		columnBitmasks.put("counter", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AddFdaAppliInfo _escapedModel;

}