/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.janaac.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.janaac.application.form.service.model.JanaacAppliCurrentStage;
import com.nbp.janaac.application.form.service.model.JanaacAppliCurrentStageModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the JanaacAppliCurrentStage service. Represents a row in the &quot;nbp_janaac_appli_current_stage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>JanaacAppliCurrentStageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JanaacAppliCurrentStageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JanaacAppliCurrentStageImpl
 * @generated
 */
@JSON(strict = true)
public class JanaacAppliCurrentStageModelImpl
	extends BaseModelImpl<JanaacAppliCurrentStage>
	implements JanaacAppliCurrentStageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a janaac appli current stage model instance should use the <code>JanaacAppliCurrentStage</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_janaac_appli_current_stage";

	public static final Object[][] TABLE_COLUMNS = {
		{"janaacAppliCurrentStageId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"currentStage", Types.VARCHAR},
		{"lastFormStep", Types.VARCHAR}, {"janaacApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("janaacAppliCurrentStageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("currentStage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastFormStep", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("janaacApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_janaac_appli_current_stage (janaacAppliCurrentStageId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,currentStage VARCHAR(75) null,lastFormStep VARCHAR(75) null,janaacApplicationId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_janaac_appli_current_stage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY janaacAppliCurrentStage.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_janaac_appli_current_stage.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long JANAACAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public JanaacAppliCurrentStageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _janaacAppliCurrentStageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setJanaacAppliCurrentStageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _janaacAppliCurrentStageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return JanaacAppliCurrentStage.class;
	}

	@Override
	public String getModelClassName() {
		return JanaacAppliCurrentStage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<JanaacAppliCurrentStage, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<JanaacAppliCurrentStage, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JanaacAppliCurrentStage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((JanaacAppliCurrentStage)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<JanaacAppliCurrentStage, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<JanaacAppliCurrentStage, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(JanaacAppliCurrentStage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<JanaacAppliCurrentStage, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<JanaacAppliCurrentStage, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<JanaacAppliCurrentStage, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<JanaacAppliCurrentStage, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<JanaacAppliCurrentStage, Object>>();

			attributeGetterFunctions.put(
				"janaacAppliCurrentStageId",
				JanaacAppliCurrentStage::getJanaacAppliCurrentStageId);
			attributeGetterFunctions.put(
				"groupId", JanaacAppliCurrentStage::getGroupId);
			attributeGetterFunctions.put(
				"companyId", JanaacAppliCurrentStage::getCompanyId);
			attributeGetterFunctions.put(
				"userId", JanaacAppliCurrentStage::getUserId);
			attributeGetterFunctions.put(
				"userName", JanaacAppliCurrentStage::getUserName);
			attributeGetterFunctions.put(
				"createDate", JanaacAppliCurrentStage::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", JanaacAppliCurrentStage::getModifiedDate);
			attributeGetterFunctions.put(
				"currentStage", JanaacAppliCurrentStage::getCurrentStage);
			attributeGetterFunctions.put(
				"lastFormStep", JanaacAppliCurrentStage::getLastFormStep);
			attributeGetterFunctions.put(
				"janaacApplicationId",
				JanaacAppliCurrentStage::getJanaacApplicationId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<JanaacAppliCurrentStage, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<JanaacAppliCurrentStage, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<JanaacAppliCurrentStage, ?>>();

			attributeSetterBiConsumers.put(
				"janaacAppliCurrentStageId",
				(BiConsumer<JanaacAppliCurrentStage, Long>)
					JanaacAppliCurrentStage::setJanaacAppliCurrentStageId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<JanaacAppliCurrentStage, Long>)
					JanaacAppliCurrentStage::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<JanaacAppliCurrentStage, Long>)
					JanaacAppliCurrentStage::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<JanaacAppliCurrentStage, Long>)
					JanaacAppliCurrentStage::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<JanaacAppliCurrentStage, String>)
					JanaacAppliCurrentStage::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<JanaacAppliCurrentStage, Date>)
					JanaacAppliCurrentStage::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<JanaacAppliCurrentStage, Date>)
					JanaacAppliCurrentStage::setModifiedDate);
			attributeSetterBiConsumers.put(
				"currentStage",
				(BiConsumer<JanaacAppliCurrentStage, String>)
					JanaacAppliCurrentStage::setCurrentStage);
			attributeSetterBiConsumers.put(
				"lastFormStep",
				(BiConsumer<JanaacAppliCurrentStage, String>)
					JanaacAppliCurrentStage::setLastFormStep);
			attributeSetterBiConsumers.put(
				"janaacApplicationId",
				(BiConsumer<JanaacAppliCurrentStage, Long>)
					JanaacAppliCurrentStage::setJanaacApplicationId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getJanaacAppliCurrentStageId() {
		return _janaacAppliCurrentStageId;
	}

	@Override
	public void setJanaacAppliCurrentStageId(long janaacAppliCurrentStageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_janaacAppliCurrentStageId = janaacAppliCurrentStageId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCurrentStage() {
		if (_currentStage == null) {
			return "";
		}
		else {
			return _currentStage;
		}
	}

	@Override
	public void setCurrentStage(String currentStage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currentStage = currentStage;
	}

	@JSON
	@Override
	public String getLastFormStep() {
		if (_lastFormStep == null) {
			return "";
		}
		else {
			return _lastFormStep;
		}
	}

	@Override
	public void setLastFormStep(String lastFormStep) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastFormStep = lastFormStep;
	}

	@JSON
	@Override
	public long getJanaacApplicationId() {
		return _janaacApplicationId;
	}

	@Override
	public void setJanaacApplicationId(long janaacApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_janaacApplicationId = janaacApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalJanaacApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("janaacApplicationId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), JanaacAppliCurrentStage.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public JanaacAppliCurrentStage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, JanaacAppliCurrentStage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JanaacAppliCurrentStageImpl janaacAppliCurrentStageImpl =
			new JanaacAppliCurrentStageImpl();

		janaacAppliCurrentStageImpl.setJanaacAppliCurrentStageId(
			getJanaacAppliCurrentStageId());
		janaacAppliCurrentStageImpl.setGroupId(getGroupId());
		janaacAppliCurrentStageImpl.setCompanyId(getCompanyId());
		janaacAppliCurrentStageImpl.setUserId(getUserId());
		janaacAppliCurrentStageImpl.setUserName(getUserName());
		janaacAppliCurrentStageImpl.setCreateDate(getCreateDate());
		janaacAppliCurrentStageImpl.setModifiedDate(getModifiedDate());
		janaacAppliCurrentStageImpl.setCurrentStage(getCurrentStage());
		janaacAppliCurrentStageImpl.setLastFormStep(getLastFormStep());
		janaacAppliCurrentStageImpl.setJanaacApplicationId(
			getJanaacApplicationId());

		janaacAppliCurrentStageImpl.resetOriginalValues();

		return janaacAppliCurrentStageImpl;
	}

	@Override
	public JanaacAppliCurrentStage cloneWithOriginalValues() {
		JanaacAppliCurrentStageImpl janaacAppliCurrentStageImpl =
			new JanaacAppliCurrentStageImpl();

		janaacAppliCurrentStageImpl.setJanaacAppliCurrentStageId(
			this.<Long>getColumnOriginalValue("janaacAppliCurrentStageId"));
		janaacAppliCurrentStageImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		janaacAppliCurrentStageImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		janaacAppliCurrentStageImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		janaacAppliCurrentStageImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		janaacAppliCurrentStageImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		janaacAppliCurrentStageImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		janaacAppliCurrentStageImpl.setCurrentStage(
			this.<String>getColumnOriginalValue("currentStage"));
		janaacAppliCurrentStageImpl.setLastFormStep(
			this.<String>getColumnOriginalValue("lastFormStep"));
		janaacAppliCurrentStageImpl.setJanaacApplicationId(
			this.<Long>getColumnOriginalValue("janaacApplicationId"));

		return janaacAppliCurrentStageImpl;
	}

	@Override
	public int compareTo(JanaacAppliCurrentStage janaacAppliCurrentStage) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), janaacAppliCurrentStage.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof JanaacAppliCurrentStage)) {
			return false;
		}

		JanaacAppliCurrentStage janaacAppliCurrentStage =
			(JanaacAppliCurrentStage)object;

		long primaryKey = janaacAppliCurrentStage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<JanaacAppliCurrentStage> toCacheModel() {
		JanaacAppliCurrentStageCacheModel janaacAppliCurrentStageCacheModel =
			new JanaacAppliCurrentStageCacheModel();

		janaacAppliCurrentStageCacheModel.janaacAppliCurrentStageId =
			getJanaacAppliCurrentStageId();

		janaacAppliCurrentStageCacheModel.groupId = getGroupId();

		janaacAppliCurrentStageCacheModel.companyId = getCompanyId();

		janaacAppliCurrentStageCacheModel.userId = getUserId();

		janaacAppliCurrentStageCacheModel.userName = getUserName();

		String userName = janaacAppliCurrentStageCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			janaacAppliCurrentStageCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			janaacAppliCurrentStageCacheModel.createDate = createDate.getTime();
		}
		else {
			janaacAppliCurrentStageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			janaacAppliCurrentStageCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			janaacAppliCurrentStageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		janaacAppliCurrentStageCacheModel.currentStage = getCurrentStage();

		String currentStage = janaacAppliCurrentStageCacheModel.currentStage;

		if ((currentStage != null) && (currentStage.length() == 0)) {
			janaacAppliCurrentStageCacheModel.currentStage = null;
		}

		janaacAppliCurrentStageCacheModel.lastFormStep = getLastFormStep();

		String lastFormStep = janaacAppliCurrentStageCacheModel.lastFormStep;

		if ((lastFormStep != null) && (lastFormStep.length() == 0)) {
			janaacAppliCurrentStageCacheModel.lastFormStep = null;
		}

		janaacAppliCurrentStageCacheModel.janaacApplicationId =
			getJanaacApplicationId();

		return janaacAppliCurrentStageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<JanaacAppliCurrentStage, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<JanaacAppliCurrentStage, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JanaacAppliCurrentStage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(JanaacAppliCurrentStage)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, JanaacAppliCurrentStage>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						JanaacAppliCurrentStage.class, ModelWrapper.class);

	}

	private long _janaacAppliCurrentStageId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _currentStage;
	private String _lastFormStep;
	private long _janaacApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<JanaacAppliCurrentStage, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((JanaacAppliCurrentStage)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"janaacAppliCurrentStageId", _janaacAppliCurrentStageId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("currentStage", _currentStage);
		_columnOriginalValues.put("lastFormStep", _lastFormStep);
		_columnOriginalValues.put("janaacApplicationId", _janaacApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("janaacAppliCurrentStageId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("currentStage", 128L);

		columnBitmasks.put("lastFormStep", 256L);

		columnBitmasks.put("janaacApplicationId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private JanaacAppliCurrentStage _escapedModel;

}