/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.npm.cannabis.application.stages.services.model.impl;

import com.npm.cannabis.application.stages.services.model.CannabisInspection;
import com.npm.cannabis.application.stages.services.service.CannabisInspectionLocalServiceUtil;

/**
 * The extended model base implementation for the CannabisInspection service. Represents a row in the &quot;nbp_cannabis_inspection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CannabisInspectionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CannabisInspectionImpl
 * @see CannabisInspection
 * @generated
 */
public abstract class CannabisInspectionBaseImpl
	extends CannabisInspectionModelImpl implements CannabisInspection {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cannabis inspection model instance should use the <code>CannabisInspection</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CannabisInspectionLocalServiceUtil.addCannabisInspection(this);
		}
		else {
			CannabisInspectionLocalServiceUtil.updateCannabisInspection(this);
		}
	}

}