/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.janaac.stages.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.janaac.stages.services.model.JanaacCommitteeDecision;
import com.nbp.janaac.stages.services.model.JanaacCommitteeDecisionModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the JanaacCommitteeDecision service. Represents a row in the &quot;nbp_janaac_committee_decision&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>JanaacCommitteeDecisionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JanaacCommitteeDecisionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JanaacCommitteeDecisionImpl
 * @generated
 */
@JSON(strict = true)
public class JanaacCommitteeDecisionModelImpl
	extends BaseModelImpl<JanaacCommitteeDecision>
	implements JanaacCommitteeDecisionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a janaac committee decision model instance should use the <code>JanaacCommitteeDecision</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_janaac_committee_decision";

	public static final Object[][] TABLE_COLUMNS = {
		{"janaacCommitteeDecisionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"dateOfCommitteeDecision", Types.TIMESTAMP},
		{"committeeDecision", Types.VARCHAR}, {"caseId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("janaacCommitteeDecisionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dateOfCommitteeDecision", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("committeeDecision", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("caseId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_janaac_committee_decision (janaacCommitteeDecisionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,dateOfCommitteeDecision DATE null,committeeDecision VARCHAR(75) null,caseId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_janaac_committee_decision";

	public static final String ORDER_BY_JPQL =
		" ORDER BY janaacCommitteeDecision.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_janaac_committee_decision.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CASEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public JanaacCommitteeDecisionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _janaacCommitteeDecisionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setJanaacCommitteeDecisionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _janaacCommitteeDecisionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return JanaacCommitteeDecision.class;
	}

	@Override
	public String getModelClassName() {
		return JanaacCommitteeDecision.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<JanaacCommitteeDecision, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<JanaacCommitteeDecision, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JanaacCommitteeDecision, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((JanaacCommitteeDecision)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<JanaacCommitteeDecision, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<JanaacCommitteeDecision, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(JanaacCommitteeDecision)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<JanaacCommitteeDecision, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<JanaacCommitteeDecision, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<JanaacCommitteeDecision, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<JanaacCommitteeDecision, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<JanaacCommitteeDecision, Object>>();

			attributeGetterFunctions.put(
				"janaacCommitteeDecisionId",
				JanaacCommitteeDecision::getJanaacCommitteeDecisionId);
			attributeGetterFunctions.put(
				"groupId", JanaacCommitteeDecision::getGroupId);
			attributeGetterFunctions.put(
				"companyId", JanaacCommitteeDecision::getCompanyId);
			attributeGetterFunctions.put(
				"userId", JanaacCommitteeDecision::getUserId);
			attributeGetterFunctions.put(
				"userName", JanaacCommitteeDecision::getUserName);
			attributeGetterFunctions.put(
				"createDate", JanaacCommitteeDecision::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", JanaacCommitteeDecision::getModifiedDate);
			attributeGetterFunctions.put(
				"dateOfCommitteeDecision",
				JanaacCommitteeDecision::getDateOfCommitteeDecision);
			attributeGetterFunctions.put(
				"committeeDecision",
				JanaacCommitteeDecision::getCommitteeDecision);
			attributeGetterFunctions.put(
				"caseId", JanaacCommitteeDecision::getCaseId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<JanaacCommitteeDecision, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<JanaacCommitteeDecision, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<JanaacCommitteeDecision, ?>>();

			attributeSetterBiConsumers.put(
				"janaacCommitteeDecisionId",
				(BiConsumer<JanaacCommitteeDecision, Long>)
					JanaacCommitteeDecision::setJanaacCommitteeDecisionId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<JanaacCommitteeDecision, Long>)
					JanaacCommitteeDecision::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<JanaacCommitteeDecision, Long>)
					JanaacCommitteeDecision::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<JanaacCommitteeDecision, Long>)
					JanaacCommitteeDecision::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<JanaacCommitteeDecision, String>)
					JanaacCommitteeDecision::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<JanaacCommitteeDecision, Date>)
					JanaacCommitteeDecision::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<JanaacCommitteeDecision, Date>)
					JanaacCommitteeDecision::setModifiedDate);
			attributeSetterBiConsumers.put(
				"dateOfCommitteeDecision",
				(BiConsumer<JanaacCommitteeDecision, Date>)
					JanaacCommitteeDecision::setDateOfCommitteeDecision);
			attributeSetterBiConsumers.put(
				"committeeDecision",
				(BiConsumer<JanaacCommitteeDecision, String>)
					JanaacCommitteeDecision::setCommitteeDecision);
			attributeSetterBiConsumers.put(
				"caseId",
				(BiConsumer<JanaacCommitteeDecision, String>)
					JanaacCommitteeDecision::setCaseId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getJanaacCommitteeDecisionId() {
		return _janaacCommitteeDecisionId;
	}

	@Override
	public void setJanaacCommitteeDecisionId(long janaacCommitteeDecisionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_janaacCommitteeDecisionId = janaacCommitteeDecisionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getDateOfCommitteeDecision() {
		return _dateOfCommitteeDecision;
	}

	@Override
	public void setDateOfCommitteeDecision(Date dateOfCommitteeDecision) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfCommitteeDecision = dateOfCommitteeDecision;
	}

	@JSON
	@Override
	public String getCommitteeDecision() {
		if (_committeeDecision == null) {
			return "";
		}
		else {
			return _committeeDecision;
		}
	}

	@Override
	public void setCommitteeDecision(String committeeDecision) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_committeeDecision = committeeDecision;
	}

	@JSON
	@Override
	public String getCaseId() {
		if (_caseId == null) {
			return "";
		}
		else {
			return _caseId;
		}
	}

	@Override
	public void setCaseId(String caseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_caseId = caseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCaseId() {
		return getColumnOriginalValue("caseId");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), JanaacCommitteeDecision.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public JanaacCommitteeDecision toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, JanaacCommitteeDecision>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JanaacCommitteeDecisionImpl janaacCommitteeDecisionImpl =
			new JanaacCommitteeDecisionImpl();

		janaacCommitteeDecisionImpl.setJanaacCommitteeDecisionId(
			getJanaacCommitteeDecisionId());
		janaacCommitteeDecisionImpl.setGroupId(getGroupId());
		janaacCommitteeDecisionImpl.setCompanyId(getCompanyId());
		janaacCommitteeDecisionImpl.setUserId(getUserId());
		janaacCommitteeDecisionImpl.setUserName(getUserName());
		janaacCommitteeDecisionImpl.setCreateDate(getCreateDate());
		janaacCommitteeDecisionImpl.setModifiedDate(getModifiedDate());
		janaacCommitteeDecisionImpl.setDateOfCommitteeDecision(
			getDateOfCommitteeDecision());
		janaacCommitteeDecisionImpl.setCommitteeDecision(
			getCommitteeDecision());
		janaacCommitteeDecisionImpl.setCaseId(getCaseId());

		janaacCommitteeDecisionImpl.resetOriginalValues();

		return janaacCommitteeDecisionImpl;
	}

	@Override
	public JanaacCommitteeDecision cloneWithOriginalValues() {
		JanaacCommitteeDecisionImpl janaacCommitteeDecisionImpl =
			new JanaacCommitteeDecisionImpl();

		janaacCommitteeDecisionImpl.setJanaacCommitteeDecisionId(
			this.<Long>getColumnOriginalValue("janaacCommitteeDecisionId"));
		janaacCommitteeDecisionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		janaacCommitteeDecisionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		janaacCommitteeDecisionImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		janaacCommitteeDecisionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		janaacCommitteeDecisionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		janaacCommitteeDecisionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		janaacCommitteeDecisionImpl.setDateOfCommitteeDecision(
			this.<Date>getColumnOriginalValue("dateOfCommitteeDecision"));
		janaacCommitteeDecisionImpl.setCommitteeDecision(
			this.<String>getColumnOriginalValue("committeeDecision"));
		janaacCommitteeDecisionImpl.setCaseId(
			this.<String>getColumnOriginalValue("caseId"));

		return janaacCommitteeDecisionImpl;
	}

	@Override
	public int compareTo(JanaacCommitteeDecision janaacCommitteeDecision) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), janaacCommitteeDecision.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof JanaacCommitteeDecision)) {
			return false;
		}

		JanaacCommitteeDecision janaacCommitteeDecision =
			(JanaacCommitteeDecision)object;

		long primaryKey = janaacCommitteeDecision.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<JanaacCommitteeDecision> toCacheModel() {
		JanaacCommitteeDecisionCacheModel janaacCommitteeDecisionCacheModel =
			new JanaacCommitteeDecisionCacheModel();

		janaacCommitteeDecisionCacheModel.janaacCommitteeDecisionId =
			getJanaacCommitteeDecisionId();

		janaacCommitteeDecisionCacheModel.groupId = getGroupId();

		janaacCommitteeDecisionCacheModel.companyId = getCompanyId();

		janaacCommitteeDecisionCacheModel.userId = getUserId();

		janaacCommitteeDecisionCacheModel.userName = getUserName();

		String userName = janaacCommitteeDecisionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			janaacCommitteeDecisionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			janaacCommitteeDecisionCacheModel.createDate = createDate.getTime();
		}
		else {
			janaacCommitteeDecisionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			janaacCommitteeDecisionCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			janaacCommitteeDecisionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date dateOfCommitteeDecision = getDateOfCommitteeDecision();

		if (dateOfCommitteeDecision != null) {
			janaacCommitteeDecisionCacheModel.dateOfCommitteeDecision =
				dateOfCommitteeDecision.getTime();
		}
		else {
			janaacCommitteeDecisionCacheModel.dateOfCommitteeDecision =
				Long.MIN_VALUE;
		}

		janaacCommitteeDecisionCacheModel.committeeDecision =
			getCommitteeDecision();

		String committeeDecision =
			janaacCommitteeDecisionCacheModel.committeeDecision;

		if ((committeeDecision != null) && (committeeDecision.length() == 0)) {
			janaacCommitteeDecisionCacheModel.committeeDecision = null;
		}

		janaacCommitteeDecisionCacheModel.caseId = getCaseId();

		String caseId = janaacCommitteeDecisionCacheModel.caseId;

		if ((caseId != null) && (caseId.length() == 0)) {
			janaacCommitteeDecisionCacheModel.caseId = null;
		}

		return janaacCommitteeDecisionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<JanaacCommitteeDecision, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<JanaacCommitteeDecision, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JanaacCommitteeDecision, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(JanaacCommitteeDecision)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, JanaacCommitteeDecision>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						JanaacCommitteeDecision.class, ModelWrapper.class);

	}

	private long _janaacCommitteeDecisionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _dateOfCommitteeDecision;
	private String _committeeDecision;
	private String _caseId;

	public <T> T getColumnValue(String columnName) {
		Function<JanaacCommitteeDecision, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((JanaacCommitteeDecision)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"janaacCommitteeDecisionId", _janaacCommitteeDecisionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"dateOfCommitteeDecision", _dateOfCommitteeDecision);
		_columnOriginalValues.put("committeeDecision", _committeeDecision);
		_columnOriginalValues.put("caseId", _caseId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("janaacCommitteeDecisionId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("dateOfCommitteeDecision", 128L);

		columnBitmasks.put("committeeDecision", 256L);

		columnBitmasks.put("caseId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private JanaacCommitteeDecision _escapedModel;

}