create table nbp_entity_info (
	uuid_ VARCHAR(75) null,
	entityInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	entityName VARCHAR(75) null,
	entityAddressOne VARCHAR(75) null,
	entityAddressTwo VARCHAR(75) null,
	telephone VARCHAR(75) null,
	mailingAdd VARCHAR(75) null,
	permanentAdd VARCHAR(75) null,
	fax VARCHAR(75) null,
	website VARCHAR(75) null,
	postalCode VARCHAR(75) null,
	parish VARCHAR(75) null,
	officeEmail VARCHAR(75) null,
	country VARCHAR(75) null,
	incorporationDate DATE null,
	incorporationPlace VARCHAR(75) null,
	isUserPrimaryUser VARCHAR(75) null,
	entityNumber VARCHAR(75) null,
	userType VARCHAR(75) null,
	trn VARCHAR(75) null
);