pipeline {
    agent any

    environment {
        LIFERAY_HOME = "C:\\JBG\\Server\\liferay-dxp" 
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/VipinSingh112/jenkins_prc.git'
            }
        }

        stage('Build with Gradle') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Deploy to Liferay') {
            steps {
                sh 'cp modules/build/libs/*.jar $LIFERAY_HOME/deploy/' 
            }
        }
    }
}
