pipeline {
    agent any

    environment {
        LIFERAY_HOME = "C:\\JBG\\Server\\liferay-dxp" 
    }

    stages {
        stage('Clone Repo') {
            steps {
               git branch: 'main', url: 'https://github.com/VipinSingh112/jenkins_prc.git'
            }
        }

        stage('Build with Gradle') {
            steps {
                dir('nbp-portal'){
                    bat 'gradle deploy -PLIFERAY_HOME="%LIFERAY_HOME%"'  
                }
            }
        }

        stage('Deploy to Liferay') {
            steps {
                bat "copy nbp-portal\\build\\libs\\*.jar %LIFERAY_HOME%\\deploy\\"
            }
        }
    }
}
