/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.healthcare.application.form.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.healthcare.application.form.service.model.HealthCareBussinessInfo;
import com.nbp.healthcare.application.form.service.service.HealthCareBussinessInfoLocalService;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareApplicantAddressPersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareApplicantInfoPersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareApplicationPaymentPersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareApplicationPersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareBusinessAddressPersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareBussinessInfoPersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareCurrentStagePersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareDescriptionOfServicePersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthCareEquipmentInfoPersistence;
import com.nbp.healthcare.application.form.service.service.persistence.HealthcareEquipHeadingListPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the health care bussiness info local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.healthcare.application.form.service.service.impl.HealthCareBussinessInfoLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.healthcare.application.form.service.service.impl.HealthCareBussinessInfoLocalServiceImpl
 * @generated
 */
public abstract class HealthCareBussinessInfoLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, HealthCareBussinessInfoLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>HealthCareBussinessInfoLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.healthcare.application.form.service.service.HealthCareBussinessInfoLocalServiceUtil</code>.
	 */

	/**
	 * Adds the health care bussiness info to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect HealthCareBussinessInfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param healthCareBussinessInfo the health care bussiness info
	 * @return the health care bussiness info that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public HealthCareBussinessInfo addHealthCareBussinessInfo(
		HealthCareBussinessInfo healthCareBussinessInfo) {

		healthCareBussinessInfo.setNew(true);

		return healthCareBussinessInfoPersistence.update(
			healthCareBussinessInfo);
	}

	/**
	 * Creates a new health care bussiness info with the primary key. Does not add the health care bussiness info to the database.
	 *
	 * @param healthCareBussinessInfoId the primary key for the new health care bussiness info
	 * @return the new health care bussiness info
	 */
	@Override
	@Transactional(enabled = false)
	public HealthCareBussinessInfo createHealthCareBussinessInfo(
		long healthCareBussinessInfoId) {

		return healthCareBussinessInfoPersistence.create(
			healthCareBussinessInfoId);
	}

	/**
	 * Deletes the health care bussiness info with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect HealthCareBussinessInfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param healthCareBussinessInfoId the primary key of the health care bussiness info
	 * @return the health care bussiness info that was removed
	 * @throws PortalException if a health care bussiness info with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public HealthCareBussinessInfo deleteHealthCareBussinessInfo(
			long healthCareBussinessInfoId)
		throws PortalException {

		return healthCareBussinessInfoPersistence.remove(
			healthCareBussinessInfoId);
	}

	/**
	 * Deletes the health care bussiness info from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect HealthCareBussinessInfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param healthCareBussinessInfo the health care bussiness info
	 * @return the health care bussiness info that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public HealthCareBussinessInfo deleteHealthCareBussinessInfo(
		HealthCareBussinessInfo healthCareBussinessInfo) {

		return healthCareBussinessInfoPersistence.remove(
			healthCareBussinessInfo);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return healthCareBussinessInfoPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			HealthCareBussinessInfo.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return healthCareBussinessInfoPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.healthcare.application.form.service.model.impl.HealthCareBussinessInfoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return healthCareBussinessInfoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.healthcare.application.form.service.model.impl.HealthCareBussinessInfoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return healthCareBussinessInfoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return healthCareBussinessInfoPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return healthCareBussinessInfoPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public HealthCareBussinessInfo fetchHealthCareBussinessInfo(
		long healthCareBussinessInfoId) {

		return healthCareBussinessInfoPersistence.fetchByPrimaryKey(
			healthCareBussinessInfoId);
	}

	/**
	 * Returns the health care bussiness info with the primary key.
	 *
	 * @param healthCareBussinessInfoId the primary key of the health care bussiness info
	 * @return the health care bussiness info
	 * @throws PortalException if a health care bussiness info with the primary key could not be found
	 */
	@Override
	public HealthCareBussinessInfo getHealthCareBussinessInfo(
			long healthCareBussinessInfoId)
		throws PortalException {

		return healthCareBussinessInfoPersistence.findByPrimaryKey(
			healthCareBussinessInfoId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			healthCareBussinessInfoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(HealthCareBussinessInfo.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"healthCareBussinessInfoId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			healthCareBussinessInfoLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			HealthCareBussinessInfo.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"healthCareBussinessInfoId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			healthCareBussinessInfoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(HealthCareBussinessInfo.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"healthCareBussinessInfoId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return healthCareBussinessInfoPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement HealthCareBussinessInfoLocalServiceImpl#deleteHealthCareBussinessInfo(HealthCareBussinessInfo) to avoid orphaned data");
		}

		return healthCareBussinessInfoLocalService.
			deleteHealthCareBussinessInfo(
				(HealthCareBussinessInfo)persistedModel);
	}

	@Override
	public BasePersistence<HealthCareBussinessInfo> getBasePersistence() {
		return healthCareBussinessInfoPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return healthCareBussinessInfoPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the health care bussiness infos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.healthcare.application.form.service.model.impl.HealthCareBussinessInfoModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of health care bussiness infos
	 * @param end the upper bound of the range of health care bussiness infos (not inclusive)
	 * @return the range of health care bussiness infos
	 */
	@Override
	public List<HealthCareBussinessInfo> getHealthCareBussinessInfos(
		int start, int end) {

		return healthCareBussinessInfoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of health care bussiness infos.
	 *
	 * @return the number of health care bussiness infos
	 */
	@Override
	public int getHealthCareBussinessInfosCount() {
		return healthCareBussinessInfoPersistence.countAll();
	}

	/**
	 * Updates the health care bussiness info in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect HealthCareBussinessInfoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param healthCareBussinessInfo the health care bussiness info
	 * @return the health care bussiness info that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public HealthCareBussinessInfo updateHealthCareBussinessInfo(
		HealthCareBussinessInfo healthCareBussinessInfo) {

		return healthCareBussinessInfoPersistence.update(
			healthCareBussinessInfo);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			HealthCareBussinessInfoLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		healthCareBussinessInfoLocalService =
			(HealthCareBussinessInfoLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return HealthCareBussinessInfoLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return HealthCareBussinessInfo.class;
	}

	protected String getModelClassName() {
		return HealthCareBussinessInfo.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				healthCareBussinessInfoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected HealthCareApplicantAddressPersistence
		healthCareApplicantAddressPersistence;

	@Reference
	protected HealthCareApplicantInfoPersistence
		healthCareApplicantInfoPersistence;

	@Reference
	protected HealthCareApplicationPersistence healthCareApplicationPersistence;

	@Reference
	protected HealthCareApplicationPaymentPersistence
		healthCareApplicationPaymentPersistence;

	@Reference
	protected HealthCareBusinessAddressPersistence
		healthCareBusinessAddressPersistence;

	protected HealthCareBussinessInfoLocalService
		healthCareBussinessInfoLocalService;

	@Reference
	protected HealthCareBussinessInfoPersistence
		healthCareBussinessInfoPersistence;

	@Reference
	protected HealthCareCurrentStagePersistence
		healthCareCurrentStagePersistence;

	@Reference
	protected HealthCareDescriptionOfServicePersistence
		healthCareDescriptionOfServicePersistence;

	@Reference
	protected HealthcareEquipHeadingListPersistence
		healthcareEquipHeadingListPersistence;

	@Reference
	protected HealthCareEquipmentInfoPersistence
		healthCareEquipmentInfoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		HealthCareBussinessInfoLocalServiceBaseImpl.class);

}