/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.hsra.application.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RadiationDeclaration service. Represents a row in the &quot;nbp_hsra_rad_declaration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nbp.hsra.application.service.model.impl.RadiationDeclarationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nbp.hsra.application.service.model.impl.RadiationDeclarationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RadiationDeclaration
 * @generated
 */
@ProviderType
public interface RadiationDeclarationModel
	extends BaseModel<RadiationDeclaration>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a radiation declaration model instance should use the {@link RadiationDeclaration} interface instead.
	 */

	/**
	 * Returns the primary key of this radiation declaration.
	 *
	 * @return the primary key of this radiation declaration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this radiation declaration.
	 *
	 * @param primaryKey the primary key of this radiation declaration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the radiation declaration ID of this radiation declaration.
	 *
	 * @return the radiation declaration ID of this radiation declaration
	 */
	public long getRadiationDeclarationId();

	/**
	 * Sets the radiation declaration ID of this radiation declaration.
	 *
	 * @param radiationDeclarationId the radiation declaration ID of this radiation declaration
	 */
	public void setRadiationDeclarationId(long radiationDeclarationId);

	/**
	 * Returns the group ID of this radiation declaration.
	 *
	 * @return the group ID of this radiation declaration
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this radiation declaration.
	 *
	 * @param groupId the group ID of this radiation declaration
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this radiation declaration.
	 *
	 * @return the company ID of this radiation declaration
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this radiation declaration.
	 *
	 * @param companyId the company ID of this radiation declaration
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this radiation declaration.
	 *
	 * @return the user ID of this radiation declaration
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this radiation declaration.
	 *
	 * @param userId the user ID of this radiation declaration
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this radiation declaration.
	 *
	 * @return the user uuid of this radiation declaration
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this radiation declaration.
	 *
	 * @param userUuid the user uuid of this radiation declaration
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this radiation declaration.
	 *
	 * @return the user name of this radiation declaration
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this radiation declaration.
	 *
	 * @param userName the user name of this radiation declaration
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this radiation declaration.
	 *
	 * @return the create date of this radiation declaration
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this radiation declaration.
	 *
	 * @param createDate the create date of this radiation declaration
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this radiation declaration.
	 *
	 * @return the modified date of this radiation declaration
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this radiation declaration.
	 *
	 * @param modifiedDate the modified date of this radiation declaration
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the legal operator name of this radiation declaration.
	 *
	 * @return the legal operator name of this radiation declaration
	 */
	@AutoEscape
	public String getLegalOperatorName();

	/**
	 * Sets the legal operator name of this radiation declaration.
	 *
	 * @param legalOperatorName the legal operator name of this radiation declaration
	 */
	public void setLegalOperatorName(String legalOperatorName);

	/**
	 * Returns the operator title of this radiation declaration.
	 *
	 * @return the operator title of this radiation declaration
	 */
	@AutoEscape
	public String getOperatorTitle();

	/**
	 * Sets the operator title of this radiation declaration.
	 *
	 * @param operatorTitle the operator title of this radiation declaration
	 */
	public void setOperatorTitle(String operatorTitle);

	/**
	 * Returns the operator date of this radiation declaration.
	 *
	 * @return the operator date of this radiation declaration
	 */
	public Date getOperatorDate();

	/**
	 * Sets the operator date of this radiation declaration.
	 *
	 * @param operatorDate the operator date of this radiation declaration
	 */
	public void setOperatorDate(Date operatorDate);

	/**
	 * Returns the hsra application ID of this radiation declaration.
	 *
	 * @return the hsra application ID of this radiation declaration
	 */
	public long getHsraApplicationId();

	/**
	 * Sets the hsra application ID of this radiation declaration.
	 *
	 * @param hsraApplicationId the hsra application ID of this radiation declaration
	 */
	public void setHsraApplicationId(long hsraApplicationId);

	@Override
	public RadiationDeclaration cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}