/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.cannabis.application.form.services.model.impl;

import com.nbp.cannabis.application.form.services.model.CannabisOccupationaLicense;
import com.nbp.cannabis.application.form.services.service.CannabisOccupationaLicenseLocalServiceUtil;

/**
 * The extended model base implementation for the CannabisOccupationaLicense service. Represents a row in the &quot;nbp_cannabis_occ_license&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CannabisOccupationaLicenseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CannabisOccupationaLicenseImpl
 * @see CannabisOccupationaLicense
 * @generated
 */
public abstract class CannabisOccupationaLicenseBaseImpl
	extends CannabisOccupationaLicenseModelImpl
	implements CannabisOccupationaLicense {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cannabis occupationa license model instance should use the <code>CannabisOccupationaLicense</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CannabisOccupationaLicenseLocalServiceUtil.
				addCannabisOccupationaLicense(this);
		}
		else {
			CannabisOccupationaLicenseLocalServiceUtil.
				updateCannabisOccupationaLicense(this);
		}
	}

}