/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.creative.application.form.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CreativeIndividualGeneralInformation service. Represents a row in the &quot;nbp_creative_indi_general_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nbp.creative.application.form.service.model.impl.CreativeIndividualGeneralInformationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nbp.creative.application.form.service.model.impl.CreativeIndividualGeneralInformationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CreativeIndividualGeneralInformation
 * @generated
 */
@ProviderType
public interface CreativeIndividualGeneralInformationModel
	extends BaseModel<CreativeIndividualGeneralInformation>, GroupedModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a creative individual general information model instance should use the {@link CreativeIndividualGeneralInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this creative individual general information.
	 *
	 * @return the primary key of this creative individual general information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this creative individual general information.
	 *
	 * @param primaryKey the primary key of this creative individual general information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the creative indi general info ID of this creative individual general information.
	 *
	 * @return the creative indi general info ID of this creative individual general information
	 */
	public long getCreativeIndiGeneralInfoId();

	/**
	 * Sets the creative indi general info ID of this creative individual general information.
	 *
	 * @param creativeIndiGeneralInfoId the creative indi general info ID of this creative individual general information
	 */
	public void setCreativeIndiGeneralInfoId(long creativeIndiGeneralInfoId);

	/**
	 * Returns the group ID of this creative individual general information.
	 *
	 * @return the group ID of this creative individual general information
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this creative individual general information.
	 *
	 * @param groupId the group ID of this creative individual general information
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this creative individual general information.
	 *
	 * @return the company ID of this creative individual general information
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this creative individual general information.
	 *
	 * @param companyId the company ID of this creative individual general information
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this creative individual general information.
	 *
	 * @return the user ID of this creative individual general information
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this creative individual general information.
	 *
	 * @param userId the user ID of this creative individual general information
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this creative individual general information.
	 *
	 * @return the user uuid of this creative individual general information
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this creative individual general information.
	 *
	 * @param userUuid the user uuid of this creative individual general information
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this creative individual general information.
	 *
	 * @return the user name of this creative individual general information
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this creative individual general information.
	 *
	 * @param userName the user name of this creative individual general information
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this creative individual general information.
	 *
	 * @return the create date of this creative individual general information
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this creative individual general information.
	 *
	 * @param createDate the create date of this creative individual general information
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this creative individual general information.
	 *
	 * @return the modified date of this creative individual general information
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this creative individual general information.
	 *
	 * @param modifiedDate the modified date of this creative individual general information
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the profile of this creative individual general information.
	 *
	 * @return the profile of this creative individual general information
	 */
	@AutoEscape
	public String getProfile();

	/**
	 * Sets the profile of this creative individual general information.
	 *
	 * @param profile the profile of this creative individual general information
	 */
	public void setProfile(String profile);

	/**
	 * Returns the creative application ID of this creative individual general information.
	 *
	 * @return the creative application ID of this creative individual general information
	 */
	public long getCreativeApplicationId();

	/**
	 * Sets the creative application ID of this creative individual general information.
	 *
	 * @param CreativeApplicationId the creative application ID of this creative individual general information
	 */
	public void setCreativeApplicationId(long CreativeApplicationId);

	@Override
	public CreativeIndividualGeneralInformation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}