create table nbp_hsra_alter_rso_one_add (
	alternateRsoOneAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	alternateRsoOneName VARCHAR(75) null,
	alternateRsoOneTitle VARCHAR(75) null,
	alternateRsoOneTelephone VARCHAR(75) null,
	alternateRsoOneExt VARCHAR(75) null,
	alternateRsoOneFax VARCHAR(75) null,
	alternateRsoOneEmailAdd VARCHAR(75) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_alternate_rso_add (
	alternateRsoAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	alternateRsoName VARCHAR(75) null,
	alternateRsoTitle VARCHAR(75) null,
	alternateRsoTelephone VARCHAR(75) null,
	alternateRsoExt VARCHAR(75) null,
	alternateRsoFax VARCHAR(75) null,
	alternateRsoEmailAdd VARCHAR(75) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_appli_current_stage (
	hsraApplicationCurrentStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormStep VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_appli_payment (
	hsraApplicationPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentFee VARCHAR(75) null,
	amountPaid VARCHAR(75) null,
	amountCurrency VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_applicant (
	uuid_ VARCHAR(75) null,
	addApplicantPractitionerId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicantDate DATE null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_application (
	uuid_ VARCHAR(75) null,
	hsraApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	typeOfApplicant VARCHAR(75) null,
	typeOfActivities VARCHAR(75) null,
	categoryOfSources VARCHAR(75) null,
	highOne VARCHAR(500) null,
	highTwo VARCHAR(500) null,
	medium VARCHAR(500) null,
	lowOne VARCHAR(500) null,
	lowTwo VARCHAR(500) null,
	typeOfTransaction VARCHAR(75) null,
	riskLevel VARCHAR(75) null,
	typeOfApplication VARCHAR(75) null,
	brokerTransactionType VARCHAR(75) null,
	specificApplicable VARCHAR(500) null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	expiredLicenseAppNumber VARCHAR(75) null,
	caseId VARCHAR(500) null,
	icmDocumentsPath VARCHAR(500) null,
	entityId VARCHAR(75) null,
	pdfFileEntryId LONG,
	appCurrentStageName VARCHAR(75) null,
	qualifiedArea VARCHAR(1000) null,
	expiredDate DATE null
);

create table nbp_hsra_broker_declare (
	brokerDeclareInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	brokerOperatorName VARCHAR(75) null,
	brokerTitle VARCHAR(75) null,
	signDate DATE null,
	hsraApplicationId LONG
);

create table nbp_hsra_broker_employee (
	qualityEmploymentInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyName VARCHAR(75) null,
	teleNo VARCHAR(75) null,
	address VARCHAR(75) null,
	parish VARCHAR(75) null,
	mobileNo VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_broker_proficiency (
	qualityProficiDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	proficiencyDetails VARCHAR(75) null,
	workDurationOne VARCHAR(75) null,
	capacityOne VARCHAR(75) null,
	workDurationTwo VARCHAR(75) null,
	capacityTwo VARCHAR(75) null,
	workDurationThree VARCHAR(75) null,
	capacityThree VARCHAR(75) null,
	workDurationFour VARCHAR(75) null,
	capacityFour VARCHAR(75) null,
	workDurationFive VARCHAR(75) null,
	capacityFive VARCHAR(75) null,
	workDurationSix VARCHAR(75) null,
	capacitySix VARCHAR(75) null,
	workDurationSeven VARCHAR(75) null,
	capacitySeven VARCHAR(75) null,
	workDurationEight VARCHAR(75) null,
	capacityEight VARCHAR(75) null,
	workDurationNine VARCHAR(75) null,
	capacityNine VARCHAR(75) null,
	workDurationTen VARCHAR(75) null,
	capacityTen VARCHAR(75) null,
	workDurationEleven VARCHAR(75) null,
	capacityEleven VARCHAR(75) null,
	workDurationTwelve VARCHAR(75) null,
	capacityTwelve VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_broker_regst (
	brokerRegstInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicationTypes VARCHAR(75) null,
	organizationNameD VARCHAR(75) null,
	businessPlace VARCHAR(75) null,
	organizationTrn VARCHAR(75) null,
	organizationTeleNum VARCHAR(75) null,
	organizationFaxNum VARCHAR(75) null,
	organizationEmailAdd VARCHAR(75) null,
	businessTypeBroker VARCHAR(75) null,
	businessNumberBroker VARCHAR(75) null,
	corporationNumberBroker VARCHAR(75) null,
	publicActBroker VARCHAR(75) null,
	licenceNumberBroker VARCHAR(75) null,
	expirationDateBroker DATE null,
	radioactiveMaterial VARCHAR(75) null,
	nuclearMaterial VARCHAR(75) null,
	nuclearTechnology VARCHAR(75) null,
	ionizingApparatus VARCHAR(75) null,
	radiationSource VARCHAR(75) null,
	organizationTransfer VARCHAR(75) null,
	nuclearProtection VARCHAR(75) null,
	storageFacility VARCHAR(75) null,
	additionalInformation VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_det_business (
	detailOfBusinessSecThreeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	businessType VARCHAR(75) null,
	nuclearBusinessNumber VARCHAR(75) null,
	nuclearCorporationNum VARCHAR(75) null,
	nuclearPublicAct VARCHAR(500) null,
	nuclearName VARCHAR(75) null,
	nuclearAddressThird VARCHAR(500) null,
	nuclearThirdParish VARCHAR(75) null,
	nuclearTelephoneNum VARCHAR(75) null,
	nuclearfaxNumber VARCHAR(75) null,
	nuclearEmailAdd VARCHAR(75) null,
	nuclearFinancial VARCHAR(500) null,
	hsraApplicationId LONG
);

create table nbp_hsra_detail_applicant (
	detailOfAppliSecTwoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	organizationName VARCHAR(75) null,
	nuclearMailingAddr VARCHAR(500) null,
	parish VARCHAR(75) null,
	nuclearTrnNumber VARCHAR(75) null,
	nuclearTelephoneNo VARCHAR(75) null,
	nuclearFaxNo VARCHAR(75) null,
	nuclearEmailAddr VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_equipment_add (
	genEquipmentDataId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	manufacturerEquipment VARCHAR(1000) null,
	equipmentModel VARCHAR(75) null,
	equipmentSerial VARCHAR(75) null,
	operatingPotential VARCHAR(75) null,
	natureEquipment VARCHAR(1000) null,
	radiationGeneratingLoc VARCHAR(1000) null,
	equipmentModels VARCHAR(75) null,
	equipmentStatusDetail VARCHAR(75) null,
	equipmentDate DATE null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_fitprop_business (
	fitPropBusinessInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyType VARCHAR(75) null,
	applicantBusinessName VARCHAR(75) null,
	applicantcomName VARCHAR(75) null,
	applicantComAddress VARCHAR(75) null,
	applicantComAddressParish VARCHAR(75) null,
	applicantComNo VARCHAR(75) null,
	applicantComEmail VARCHAR(75) null,
	applicantComTelephone VARCHAR(75) null,
	applicantComTitle VARCHAR(75) null,
	materialTechnology VARCHAR(75) null,
	relevantBox VARCHAR(75) null,
	corporateDirector VARCHAR(75) null,
	facilitySources VARCHAR(75) null,
	criminalFraud VARCHAR(75) null,
	professionalSubject VARCHAR(75) null,
	employmentResign VARCHAR(75) null,
	mentallyIll VARCHAR(75) null,
	bankruptAuthority VARCHAR(75) null,
	circumstancesEvent VARCHAR(75) null,
	partnershipHsra VARCHAR(75) null,
	facilityAssociated VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_fitprop_declare (
	fitPropDeclareApplicantId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameApplicant VARCHAR(75) null,
	dateApplicant DATE null,
	hsraApplicationId LONG
);

create table nbp_hsra_fitprop_financial (
	fitPropFinancialProfileId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	financialInstitution VARCHAR(75) null,
	creditfacility VARCHAR(75) null,
	surroundingAction VARCHAR(75) null,
	jamaicaInstitution VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_fitprop_personal (
	fitPropPersonalDetailInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicantFirstName VARCHAR(75) null,
	applicantMiddleName VARCHAR(75) null,
	applicantSurname VARCHAR(75) null,
	applicantFormerName VARCHAR(75) null,
	applicantAlias VARCHAR(75) null,
	applicantStreetName VARCHAR(75) null,
	applicantStreetNo VARCHAR(75) null,
	applicantPostalCode VARCHAR(75) null,
	applicantCountry VARCHAR(75) null,
	applicantTownName VARCHAR(75) null,
	applicantCity VARCHAR(75) null,
	applicantParish VARCHAR(75) null,
	applicantTelephoneNum VARCHAR(75) null,
	applicantEmailAdd VARCHAR(75) null,
	applicantDateBirth DATE null,
	applicantPlaceOfBirthTown VARCHAR(75) null,
	applicantPlaceOfBirthParish VARCHAR(75) null,
	applicantPlaceOfBirthCountry VARCHAR(75) null,
	applicantNationality VARCHAR(75) null,
	applicantNisNum VARCHAR(75) null,
	applicantSocialNum VARCHAR(75) null,
	applicantNationalNum VARCHAR(75) null,
	applicantRegistrationNum VARCHAR(75) null,
	maritalStatusDetails VARCHAR(75) null,
	applicantRelationship VARCHAR(75) null,
	applicantSecTelephone VARCHAR(75) null,
	applicantSecMail VARCHAR(75) null,
	applicantSecAddress VARCHAR(75) null,
	applicantSecAddressParish VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_low_risk_safety (
	radiationSafetyLowRiskId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	appendixRsoName VARCHAR(75) null,
	appendixRsoTitle VARCHAR(75) null,
	appendixRsoTeleNo VARCHAR(75) null,
	appendixRsoExt VARCHAR(75) null,
	appendixRsoFax VARCHAR(75) null,
	appendixRsoEmail VARCHAR(75) null,
	appendixRsoDetails VARCHAR(1000) null,
	qualifiedAppendixName VARCHAR(75) null,
	qualifiedAppendixTitle VARCHAR(75) null,
	qualifiedAppendixTele VARCHAR(75) null,
	qualifiedAppendixExt VARCHAR(75) null,
	qualifiedAppendixFax VARCHAR(75) null,
	qualifiedAppendixEmail VARCHAR(75) null,
	qualifiedAppendixRegstNo VARCHAR(75) null,
	qualifiedAppendixDate DATE null,
	qualifiedAppendixDetails VARCHAR(1000) null,
	monitoringExposure VARCHAR(1000) null,
	recordSystem VARCHAR(1000) null,
	securityAccess VARCHAR(1000) null,
	trainingInformation VARCHAR(1000) null,
	leakTesting VARCHAR(1000) null,
	emergencyProcedures VARCHAR(1000) null,
	managementSourcesDis VARCHAR(1000) null,
	hsraApplicationId LONG
);

create table nbp_hsra_medical_pract_add (
	medicalPractitionerAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	medicalPractitionerName VARCHAR(75) null,
	medicalPractitionerAddress VARCHAR(75) null,
	medicalPractitionerTelephone VARCHAR(75) null,
	medicalPractitionerFax VARCHAR(75) null,
	medicalPractitionerEmail VARCHAR(75) null,
	medicalPractitionerLicenceNo VARCHAR(75) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_medical_practitioner (
	uuid_ VARCHAR(75) null,
	addMedicalPractitionerId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	medicalPractitionerDate DATE null,
	applicantDate DATE null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_noti_detail_source (
	detailOfSourcesId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	sourceIdentification VARCHAR(75) null,
	sourceLocation VARCHAR(75) null,
	stateActivity VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_noti_gen_equip (
	GenerateEquipmentInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	manufacturerEquipment VARCHAR(75) null,
	equipmentModel VARCHAR(75) null,
	equipmentSerial VARCHAR(75) null,
	operatingPotential VARCHAR(75) null,
	equipmentModels VARCHAR(75) null,
	natureEquipment VARCHAR(75) null,
	equipmentStatusDetail VARCHAR(75) null,
	equipmentDate DATE null,
	hsraApplicationId LONG
);

create table nbp_hsra_noti_legal_info (
	notifiLegalInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	legalPersonName VARCHAR(75) null,
	legalPersonAddress VARCHAR(1000) null,
	organizationName VARCHAR(75) null,
	organizationAddress VARCHAR(1000) null,
	contactNumber VARCHAR(75) null,
	legalPersonEmail VARCHAR(75) null,
	practiceNature VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_noti_radionuclide (
	radionuclideInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	radionuclideDetails VARCHAR(75) null,
	activityDetails VARCHAR(75) null,
	activityDetailBq VARCHAR(75) null,
	activityDate DATE null,
	chemicalDetailsForm VARCHAR(75) null,
	serialNo VARCHAR(75) null,
	sealedSource VARCHAR(75) null,
	manufacturerDetails VARCHAR(75) null,
	modelNo VARCHAR(75) null,
	identificationNo VARCHAR(75) null,
	statusDetails VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_purpose_regst (
	purposeOfPropLicenceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nuclearRegstLic VARCHAR(75) null,
	nuclearBusinessPlace VARCHAR(500) null,
	nuclearActivityMainAdd VARCHAR(500) null,
	applicationType VARCHAR(75) null,
	nuclearAdditionalLoc VARCHAR(500) null,
	hsraApplicationId LONG
);

create table nbp_hsra_quali_expert_one_add (
	qualifedExpertOneAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	qualifedOneName VARCHAR(75) null,
	qualifedOneTitle VARCHAR(75) null,
	qualifedOneTelephone VARCHAR(75) null,
	qualifedOneExt VARCHAR(75) null,
	qualifedOneFax VARCHAR(75) null,
	qualifedOneEmailAdd VARCHAR(75) null,
	qualifedOneRegistrationNo VARCHAR(75) null,
	qualifedOneExpirationDate DATE null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_qualified_expert_add (
	qualifedExpertAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	qualifedName VARCHAR(75) null,
	qualifedTitle VARCHAR(75) null,
	qualifedTelephone VARCHAR(75) null,
	qualifedExt VARCHAR(75) null,
	qualifedFax VARCHAR(75) null,
	qualifedEmailAdd VARCHAR(75) null,
	qualifedRegistrationNo VARCHAR(75) null,
	qualifedExpirationDate DATE null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_quality_applicant (
	qualityApplicantDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	expertSurname VARCHAR(75) null,
	expertFirstName VARCHAR(75) null,
	expertId VARCHAR(75) null,
	expertPosition VARCHAR(75) null,
	expertTelephone VARCHAR(75) null,
	expertMobile VARCHAR(75) null,
	expertEmail VARCHAR(75) null,
	expertDate DATE null,
	hsraApplicationId LONG
);

create table nbp_hsra_quality_declare (
	qualityDeclarationInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	declarationSignDate DATE null,
	hsraApplicationId LONG
);

create table nbp_hsra_quality_employee (
	qualityEmploymentInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	companyName VARCHAR(75) null,
	teleNo VARCHAR(75) null,
	address VARCHAR(75) null,
	parish VARCHAR(75) null,
	mobileNo VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_quality_proficient (
	qualityProficiDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	proficiencyDetails VARCHAR(2000) null,
	workDurationOne VARCHAR(75) null,
	capacityOne VARCHAR(75) null,
	workDurationTwo VARCHAR(75) null,
	capacityTwo VARCHAR(75) null,
	workDurationThree VARCHAR(75) null,
	capacityThree VARCHAR(75) null,
	workDurationFour VARCHAR(75) null,
	capacityFour VARCHAR(75) null,
	workDurationFive VARCHAR(75) null,
	capacityFive VARCHAR(75) null,
	workDurationSix VARCHAR(75) null,
	capacitySix VARCHAR(75) null,
	workDurationSeven VARCHAR(75) null,
	capacitySeven VARCHAR(75) null,
	workDurationEight VARCHAR(75) null,
	capacityEight VARCHAR(75) null,
	workDurationNine VARCHAR(75) null,
	capacityNine VARCHAR(75) null,
	workDurationTen VARCHAR(75) null,
	capacityTen VARCHAR(75) null,
	workDurationEleven VARCHAR(75) null,
	capacityEleven VARCHAR(75) null,
	workDurationTwelve VARCHAR(75) null,
	capacityTwelve VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_rad_declaration (
	radiationDeclarationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	legalOperatorName VARCHAR(75) null,
	operatorTitle VARCHAR(75) null,
	operatorDate DATE null,
	hsraApplicationId LONG
);

create table nbp_hsra_rad_section_one (
	radiationProtectSecOneId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentAuthNum VARCHAR(75) null,
	reasonForAmendment VARCHAR(500) null,
	typeOfApplication VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_radiation_dev (
	radiationDevicesAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	radiationDevicesRadio VARCHAR(75) null,
	radiationDevicesMaxActivity VARCHAR(75) null,
	radiationDevicesManufacturer VARCHAR(75) null,
	radiationDevicesName VARCHAR(75) null,
	radiationDevicesModelNo VARCHAR(75) null,
	radiationDevicesNumber VARCHAR(75) null,
	radiationDevicesUse VARCHAR(75) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_radiation_device_add (
	radiationDevicesDetailAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	radiationDevicesRadio VARCHAR(75) null,
	radiationDevicesMaxActivity VARCHAR(75) null,
	radiationDevicesManufacturer VARCHAR(75) null,
	radiationDevicesName VARCHAR(75) null,
	radiationDevicesModelNo VARCHAR(75) null,
	radiationDevicesNumber VARCHAR(75) null,
	radiationDevicesUse VARCHAR(75) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_radionuclide_add (
	radionuclideAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	radionuclideDetails VARCHAR(75) null,
	activityDetails VARCHAR(75) null,
	activityDate DATE null,
	chemicalDetailsForm VARCHAR(75) null,
	serialNo VARCHAR(75) null,
	radionuclideLocation VARCHAR(1000) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_safety_prog (
	radiationSafetyProgramId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nuclearRsoName VARCHAR(75) null,
	nuclearRsoTitle VARCHAR(75) null,
	nuclearRsoTeleNo VARCHAR(75) null,
	nuclearRsoExt VARCHAR(75) null,
	nuclearRsoFax VARCHAR(75) null,
	nuclearRsoEmail VARCHAR(75) null,
	rsoDetails VARCHAR(1000) null,
	qualifiedExpertName VARCHAR(75) null,
	qualifiedExpertTitle VARCHAR(75) null,
	qualifiedExpertTele VARCHAR(75) null,
	qualifiedExpertExt VARCHAR(75) null,
	qualifiedExpertFax VARCHAR(75) null,
	qualifiedExpertEmail VARCHAR(75) null,
	qualifiedExpertRegstNo VARCHAR(75) null,
	qualifiedExpertDate DATE null,
	qualifiedDetails VARCHAR(1000) null,
	applicantName VARCHAR(75) null,
	applicantTitle VARCHAR(75) null,
	otherLimitationAuth VARCHAR(75) null,
	otherDate DATE null,
	classifiWorkersList VARCHAR(500) null,
	respiPleaseSpecify VARCHAR(1000) null,
	tongsPleaseSpecify VARCHAR(1000) null,
	scopeOfActivities VARCHAR(1000) null,
	managementSystem VARCHAR(1000) null,
	workerRecordings VARCHAR(1000) null,
	categoriesLicence VARCHAR(1000) null,
	renewalsSummary VARCHAR(1000) null,
	constraintsLimits VARCHAR(1000) null,
	equipmentMonitoring VARCHAR(1000) null,
	areasControl VARCHAR(1000) null,
	radioactiveSources VARCHAR(1000) null,
	radiationiInstruments VARCHAR(1000) null,
	healthWorkers VARCHAR(1000) null,
	investigationLevel VARCHAR(1000) null,
	policyDetails VARCHAR(1000) null,
	securityAccess VARCHAR(1000) null,
	raditionSources VARCHAR(1000) null,
	workerTraining VARCHAR(1000) null,
	publicControl VARCHAR(1000) null,
	managementSources VARCHAR(1000) null,
	emergencyProcedure VARCHAR(1000) null,
	licenceLocation VARCHAR(1000) null,
	achievableProgram VARCHAR(1000) null,
	leakedTestingSources VARCHAR(1000) null,
	transferSources VARCHAR(1000) null,
	nuclearMaterials VARCHAR(1000) null,
	transportPackaging VARCHAR(1000) null,
	internalReview VARCHAR(1000) null,
	sourcesActivities VARCHAR(1000) null,
	individualProtectiveEquipment VARCHAR(1000) null,
	ResProPleaseSpecify VARCHAR(1000) null,
	hsraApplicationId LONG
);

create table nbp_hsra_sealed_source (
	sealedSourcesAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	sealedSourcesRadionu VARCHAR(75) null,
	sealedSourcesMaxActivity VARCHAR(75) null,
	sealedSourcesActivityDate DATE null,
	sealedSourcesCategories VARCHAR(75) null,
	sealedSourcesUse VARCHAR(75) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_source_detail_add (
	sourcesDetailAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	sourceIdentification VARCHAR(75) null,
	stateActivity VARCHAR(1000) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);

create table nbp_hsra_specific_require (
	specificReqPropLicActivityId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	adminTreatment VARCHAR(1000) null,
	qualityProgramme VARCHAR(1000) null,
	instructionsCaregivers VARCHAR(1000) null,
	instructionsPatients VARCHAR(1000) null,
	patientsRelease VARCHAR(1000) null,
	treatmentRooms VARCHAR(1000) null,
	medicalEmergencies VARCHAR(1000) null,
	nuclearMedicine VARCHAR(1000) null,
	diagnosticStudies VARCHAR(1000) null,
	biomedicalResearch VARCHAR(1000) null,
	researchReview VARCHAR(1000) null,
	emergencyOperating VARCHAR(1000) null,
	certificatePackages VARCHAR(1000) null,
	exposureDevices VARCHAR(1000) null,
	equipmentSafety VARCHAR(1000) null,
	transportPlan VARCHAR(1000) null,
	animalsTreatment VARCHAR(1000) null,
	animalHousing VARCHAR(1000) null,
	disposalWaste VARCHAR(1000) null,
	monitoringAnimalHousing VARCHAR(1000) null,
	releaseAnimals VARCHAR(1000) null,
	proceduresApp VARCHAR(1000) null,
	disposalsApp VARCHAR(1000) null,
	monitoringMaterialNu VARCHAR(1000) null,
	handlingProcedures VARCHAR(1000) null,
	hoppersEntry VARCHAR(1000) null,
	operatingConditions VARCHAR(1000) null,
	insertionType VARCHAR(1000) null,
	installationFixed VARCHAR(1000) null,
	transportPlanGauge VARCHAR(1000) null,
	emergencyAddition VARCHAR(1000) null,
	nuclearEnviroment VARCHAR(1000) null,
	fishingTool VARCHAR(1000) null,
	sealedSources VARCHAR(1000) null,
	abandonmentZone VARCHAR(1000) null,
	servicingCopy VARCHAR(1000) null,
	manufacturingDevelopment VARCHAR(1000) null,
	hsraApplicationId LONG
);

create table nbp_hsra_unsealed_sources (
	unsealedSourceAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	unsealedSourcesRadionu VARCHAR(75) null,
	unsealedSourcesActivity VARCHAR(75) null,
	unsealedSourcesTotalYear VARCHAR(75) null,
	unsealedSourcesUse VARCHAR(75) null,
	counter VARCHAR(75) null,
	hsraApplicationId LONG
);