create table nbp_janaac_acc_cer_app_info (
	uuid_ VARCHAR(75) null,
	accCerBodyApplicantInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicantName VARCHAR(75) null,
	applicantAddress VARCHAR(75) null,
	applicantTelephone VARCHAR(75) null,
	applicantFaxNo VARCHAR(75) null,
	applicantWebsite VARCHAR(75) null,
	certificationName VARCHAR(75) null,
	certiAddress VARCHAR(75) null,
	personnelName VARCHAR(75) null,
	personnelEmail VARCHAR(75) null,
	personnelContactName VARCHAR(75) null,
	personnelContactEmail VARCHAR(75) null,
	personnelFMName VARCHAR(75) null,
	personnelFMEmail VARCHAR(75) null,
	accreditationRequest VARCHAR(75) null,
	managementSystem VARCHAR(75) null,
	specifyOther VARCHAR(75) null,
	listOfStandard VARCHAR(75) null,
	authorizedPersonnelName VARCHAR(75) null,
	authorizedPersonnelPos VARCHAR(75) null,
	authorizedPersonnelDate DATE null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_cer_general (
	uuid_ VARCHAR(75) null,
	accCerBodyGeneralId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	cerLegalEntity VARCHAR(75) null,
	cerLegalStatusEntity VARCHAR(75) null,
	cerMajorIncomeSources VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_cer_info (
	uuid_ VARCHAR(75) null,
	accCerBodyInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	describeMechanism VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_cer_manage (
	uuid_ VARCHAR(75) null,
	accCerBodyManageReqId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	optionFollow VARCHAR(75) null,
	impartialityPolicy VARCHAR(75) null,
	qMRefImpartiality VARCHAR(75) null,
	riskAssessment VARCHAR(75) null,
	qMRefRisk VARCHAR(75) null,
	orgStructure VARCHAR(75) null,
	qMRefOrgStruct VARCHAR(75) null,
	termsOfReference VARCHAR(75) null,
	qMRefTerms VARCHAR(75) null,
	processForControl VARCHAR(75) null,
	qMRefProcess VARCHAR(75) null,
	criteriaReq VARCHAR(75) null,
	qMRefCriteria VARCHAR(75) null,
	initialCompetence VARCHAR(75) null,
	qMRefInitial VARCHAR(75) null,
	selectingTraining VARCHAR(75) null,
	qMRefSelecting VARCHAR(75) null,
	monitoringCompetence VARCHAR(75) null,
	qMRefMonitoring VARCHAR(75) null,
	writtenAgreement VARCHAR(75) null,
	qMRefWritten VARCHAR(75) null,
	descOfProcess VARCHAR(75) null,
	qMRefDescProcess VARCHAR(75) null,
	processForMonitor VARCHAR(75) null,
	qMRefMonitorProcess VARCHAR(75) null,
	auditProcess VARCHAR(75) null,
	qMRefAuditProcess VARCHAR(75) null,
	processGranting VARCHAR(75) null,
	qMRefGranting VARCHAR(75) null,
	managemntSys VARCHAR(75) null,
	qMRefManagemnt VARCHAR(75) null,
	useOfCertification VARCHAR(75) null,
	qMRefUseOfCerti VARCHAR(75) null,
	handlingReq VARCHAR(75) null,
	qMRefHandling VARCHAR(75) null,
	impartialityPolicies VARCHAR(75) null,
	qMRefImpartPolicy VARCHAR(75) null,
	provisionInform VARCHAR(75) null,
	qMRefProvision VARCHAR(75) null,
	certificationDoc VARCHAR(75) null,
	qMRefCertification VARCHAR(75) null,
	rulesGoverning VARCHAR(75) null,
	qMRefGoverning VARCHAR(75) null,
	enforcableArrangements VARCHAR(75) null,
	qMRefEnforcable VARCHAR(75) null,
	ensureConfidential VARCHAR(75) null,
	qMRefEnsureConfid VARCHAR(75) null,
	informingMechanism VARCHAR(75) null,
	qMRefInforming VARCHAR(75) null,
	applicationProcess VARCHAR(75) null,
	qMRefApplication VARCHAR(75) null,
	applicationReview VARCHAR(75) null,
	qMRefReview VARCHAR(75) null,
	certificationCycle VARCHAR(75) null,
	qMRefCertiCycle VARCHAR(75) null,
	auditTime VARCHAR(75) null,
	qMRefAuditTime VARCHAR(75) null,
	samplingProgram VARCHAR(75) null,
	qMRefSampling VARCHAR(75) null,
	auditPlanning VARCHAR(75) null,
	qMRefPlanning VARCHAR(75) null,
	auditTeam VARCHAR(75) null,
	qMRefAuditTeam VARCHAR(75) null,
	onSiteAudit VARCHAR(75) null,
	qMRefonSiteAudit VARCHAR(75) null,
	auditReport VARCHAR(75) null,
	qMRefAuditReport VARCHAR(75) null,
	correctiveActions VARCHAR(75) null,
	qMRefCorrective VARCHAR(75) null,
	reviewPriorDecision VARCHAR(75) null,
	qMRefReviewPrior VARCHAR(75) null,
	transferCertification VARCHAR(75) null,
	qMRefTransfer VARCHAR(75) null,
	suspensionPolicies VARCHAR(75) null,
	qMRefSuspension VARCHAR(75) null,
	suspensionProcedure VARCHAR(75) null,
	qMRefSuspensionProc VARCHAR(75) null,
	decisionOnAppeals VARCHAR(75) null,
	qMRefDecision VARCHAR(75) null,
	handlingComplaints VARCHAR(75) null,
	qMRefComplaints VARCHAR(75) null,
	recordRetentionPolicy VARCHAR(75) null,
	qMRefRetentionPolicy VARCHAR(75) null,
	recordRetentionProc VARCHAR(75) null,
	qMRefRetentionProc VARCHAR(75) null,
	manageSysPolicies VARCHAR(75) null,
	qMRefPolicies VARCHAR(75) null,
	manageSysObjective VARCHAR(75) null,
	qMRefObjective VARCHAR(75) null,
	manageSysManual VARCHAR(75) null,
	qMRefManual VARCHAR(75) null,
	docControlProcedure VARCHAR(75) null,
	qMRefDocControl VARCHAR(75) null,
	recControlProc VARCHAR(75) null,
	qMRefRecControl VARCHAR(75) null,
	managementReview VARCHAR(75) null,
	qMRefManagementRev VARCHAR(75) null,
	internalAudits VARCHAR(75) null,
	qMRefInternal VARCHAR(75) null,
	identificationProc VARCHAR(75) null,
	qMRefIdentification VARCHAR(75) null,
	qMSScopeB VARCHAR(75) null,
	qMRefQMSScopeB VARCHAR(75) null,
	designDevB VARCHAR(75) null,
	qMRefDesignB VARCHAR(75) null,
	interestedPartyNeedsB VARCHAR(75) null,
	qMRefInterestedB VARCHAR(75) null,
	managementReviewB VARCHAR(75) null,
	qMRefmanagementReviewB VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_cer_manage_2 (
	uuid_ VARCHAR(75) null,
	accCerBodyMngReqTwoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	optionFollow VARCHAR(75) null,
	certiAgreement VARCHAR(75) null,
	qMRefCertiAgreement VARCHAR(75) null,
	riskAssessment VARCHAR(75) null,
	qMRefRisk VARCHAR(75) null,
	confidentiality VARCHAR(75) null,
	qMRefConfidentiality VARCHAR(75) null,
	security VARCHAR(75) null,
	qMRefSecurity VARCHAR(75) null,
	certificationScheme VARCHAR(75) null,
	qMRefCertifiScheme VARCHAR(75) null,
	validCertification VARCHAR(75) null,
	qMRefValidCertification VARCHAR(75) null,
	preRequisites VARCHAR(75) null,
	qMRefPrerequisites VARCHAR(75) null,
	infoProvided VARCHAR(75) null,
	qMRefInfoProvided VARCHAR(75) null,
	handlingAppeals VARCHAR(75) null,
	qMRefHandlingAppeals VARCHAR(75) null,
	handlingComplaints VARCHAR(75) null,
	qMRefHandlingComplaint VARCHAR(75) null,
	orgStructure VARCHAR(75) null,
	qMRefOrgStructure VARCHAR(75) null,
	formalRules VARCHAR(75) null,
	qMRefFormalRules VARCHAR(75) null,
	safeguardingMechanism VARCHAR(75) null,
	qMRefSafeguarding VARCHAR(75) null,
	managementProc VARCHAR(75) null,
	qMRefManagementProc VARCHAR(75) null,
	contractExaminer VARCHAR(75) null,
	qMRefExaminer VARCHAR(75) null,
	contractBody VARCHAR(75) null,
	qMRefContractBody VARCHAR(75) null,
	docPolicies VARCHAR(75) null,
	qMRefDocPolicies VARCHAR(75) null,
	specifiedStandard VARCHAR(75) null,
	qMRefSpecified VARCHAR(75) null,
	applicationForm VARCHAR(75) null,
	qMRefAppliForm VARCHAR(75) null,
	applicationReview VARCHAR(75) null,
	qMRefAppliReview VARCHAR(75) null,
	assessmentPlan VARCHAR(75) null,
	qMRefAssessmentPlan VARCHAR(75) null,
	examinationProcess VARCHAR(75) null,
	qMRefExamProcess VARCHAR(75) null,
	certificationDecision VARCHAR(75) null,
	qMRefCertiDecision VARCHAR(75) null,
	certificationDoc VARCHAR(75) null,
	qMRefCertiDoc VARCHAR(75) null,
	useOfCertificates VARCHAR(75) null,
	qMRefUseOfCertificate VARCHAR(75) null,
	suspension VARCHAR(75) null,
	qMRefSuspension VARCHAR(75) null,
	processToReceive VARCHAR(75) null,
	qMRefReceiveProcess VARCHAR(75) null,
	generalManage VARCHAR(75) null,
	qMRefGeneral VARCHAR(75) null,
	docControl VARCHAR(75) null,
	qMRefDocControl VARCHAR(75) null,
	recordControl VARCHAR(75) null,
	qMRefRecControl VARCHAR(75) null,
	manageReview VARCHAR(75) null,
	qMRefManageReview VARCHAR(75) null,
	internalAudit VARCHAR(75) null,
	qMRefInternal VARCHAR(75) null,
	correctiveAction VARCHAR(75) null,
	qMRefCorrective VARCHAR(75) null,
	preventiveAction VARCHAR(75) null,
	qMRefPreventive VARCHAR(75) null,
	docInKeeping VARCHAR(75) null,
	qMRefDocInKeeping VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_cer_personnel (
	uuid_ VARCHAR(75) null,
	accCerBodyPersonnelId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	internalStaffSize VARCHAR(75) null,
	auditorsNum VARCHAR(75) null,
	contractedPerNum VARCHAR(75) null,
	bodyOutsource VARCHAR(75) null,
	descSecurity VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_cer_pro_scope (
	uuid_ VARCHAR(75) null,
	accCerBodyProdScopeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	cerIntrestedParties VARCHAR(75) null,
	otherServices VARCHAR(75) null,
	otherServicesDescribe VARCHAR(75) null,
	establishedRelation VARCHAR(75) null,
	establishedRelDesc VARCHAR(75) null,
	clientService VARCHAR(75) null,
	orgAccredited VARCHAR(75) null,
	responsibleBody VARCHAR(75) null,
	accExpDate DATE null,
	certBodyScope VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_cer_scope (
	uuid_ VARCHAR(75) null,
	accCerBodyScopeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	certificationStandard TEXT null,
	expertiseField1 TEXT null,
	expertiseField2 TEXT null,
	expertiseField3 TEXT null,
	expertiseField4 TEXT null,
	expertiseField5 TEXT null,
	expertiseField6 TEXT null,
	expertiseField7 TEXT null,
	expertiseField8 TEXT null,
	expertiseField9 TEXT null,
	expertiseField10 TEXT null,
	expertiseField11 TEXT null,
	expertiseField12 TEXT null,
	expertiseField13 TEXT null,
	expertiseField14 TEXT null,
	cerIntrestedParties TEXT null,
	otherServices TEXT null,
	otherServicesDescribe TEXT null,
	establishedRelation TEXT null,
	establishedRelDesc TEXT null,
	clientService TEXT null,
	certificationCerBody TEXT null,
	orgAccredited TEXT null,
	responsibleBody TEXT null,
	accExpDate DATE null,
	certBodyScope TEXT null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_ins_body_manag (
	uuid_ VARCHAR(75) null,
	accInsBodiesManageSysId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	optionFollow VARCHAR(75) null,
	manualApproval VARCHAR(75) null,
	qMRefManual VARCHAR(75) null,
	relevantPolicies VARCHAR(75) null,
	qMRefRelevant VARCHAR(75) null,
	overallObj VARCHAR(75) null,
	qMRefOverallObj VARCHAR(75) null,
	supportingProcedure VARCHAR(75) null,
	qMRefSupporting VARCHAR(75) null,
	technicalMangmnt VARCHAR(75) null,
	qMRefTechnical VARCHAR(75) null,
	documentation VARCHAR(75) null,
	qMRefDocumentation VARCHAR(75) null,
	docContolProc VARCHAR(75) null,
	qMRefDocControl VARCHAR(75) null,
	documntChanges VARCHAR(75) null,
	qMRefDocumntChanges VARCHAR(75) null,
	controlOfQuality VARCHAR(75) null,
	qMRefControl VARCHAR(75) null,
	managementReview VARCHAR(75) null,
	qMRefManage VARCHAR(75) null,
	insInternalAudits VARCHAR(75) null,
	qMRefInternalAudit VARCHAR(75) null,
	insCorrectiveAction VARCHAR(75) null,
	qMRefCorrect VARCHAR(75) null,
	insPreventiveAction VARCHAR(75) null,
	qMRefPreventive VARCHAR(75) null,
	personnel VARCHAR(75) null,
	qMRefPersonnel VARCHAR(75) null,
	equipment VARCHAR(75) null,
	qMRefEquip VARCHAR(75) null,
	inspection VARCHAR(75) null,
	qMRefInspection VARCHAR(75) null,
	contractualArrange VARCHAR(75) null,
	qMRefContractual VARCHAR(75) null,
	handlingInsItem VARCHAR(75) null,
	qMRefHandling VARCHAR(75) null,
	complaintsAppeals VARCHAR(75) null,
	qMRefComplaints VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_ins_body_org (
	uuid_ VARCHAR(75) null,
	accInsBodiesOrganizationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	insLegalEntity VARCHAR(75) null,
	insLegalStatusEntity VARCHAR(75) null,
	insBodyOrgPart VARCHAR(75) null,
	insPersonnelName VARCHAR(75) null,
	insPersonnelPosition VARCHAR(75) null,
	insStaffSize VARCHAR(75) null,
	insStaffComplement VARCHAR(75) null,
	insIncomeSource VARCHAR(75) null,
	insOrgBodyType VARCHAR(75) null,
	insBodyOwnOrgClient VARCHAR(75) null,
	insBodyOtherOrgClient VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_ins_body_other (
	uuid_ VARCHAR(75) null,
	accInsBodiesOtherReqId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicationFees VARCHAR(75) null,
	insPaymentMethod VARCHAR(75) null,
	applicantRepName VARCHAR(75) null,
	applicantRepPosition VARCHAR(75) null,
	signatureDate DATE null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_ins_body_phys (
	uuid_ VARCHAR(75) null,
	accInsBodiesPhyResourceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	insBodiesfacilities VARCHAR(75) null,
	insSafetyFeatures VARCHAR(75) null,
	insSecurityArrangements VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_med_activity (
	uuid_ VARCHAR(75) null,
	accMediLabActivitiesDescId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	activitiesDescription VARCHAR(75) null,
	shiftWork VARCHAR(75) null,
	specimenNo VARCHAR(75) null,
	specimenLocation VARCHAR(75) null,
	requestedPOCT VARCHAR(75) null,
	requestedPOCTLocation VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_med_manage_req (
	uuid_ VARCHAR(75) null,
	accMediLabManagementReqId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	managementEstablished VARCHAR(75) null,
	qMRefManagement VARCHAR(75) null,
	personAware VARCHAR(75) null,
	qMRefPerson VARCHAR(75) null,
	policiesAcknowledged VARCHAR(75) null,
	qMRefPolicies VARCHAR(75) null,
	controlledDocument VARCHAR(75) null,
	qMRefControlDoc VARCHAR(75) null,
	laboratoryEstablished VARCHAR(75) null,
	qMReflabEstab VARCHAR(75) null,
	identifiedRisks VARCHAR(75) null,
	qMRefRisks VARCHAR(75) null,
	havePersonnel VARCHAR(75) null,
	qMRefPersonnel VARCHAR(75) null,
	authorizePersonnel VARCHAR(75) null,
	qMRefAuthorize VARCHAR(75) null,
	labControlDocsFulfilment VARCHAR(75) null,
	otherRefFulfil VARCHAR(75) null,
	legibleRecordsFulfil VARCHAR(75) null,
	otherRefLegibleRec VARCHAR(75) null,
	proceduresInPlace VARCHAR(75) null,
	otherRefProcedure VARCHAR(75) null,
	communicatedRequirement VARCHAR(75) null,
	otherRefRequirement VARCHAR(75) null,
	procedureForSelection VARCHAR(75) null,
	otherRefSelection VARCHAR(75) null,
	arrangementInPlace VARCHAR(75) null,
	otherRefArrange VARCHAR(75) null,
	processInPlace VARCHAR(75) null,
	otherRefProcess VARCHAR(75) null,
	labOperateProgramme VARCHAR(75) null,
	otherRefLabOperate VARCHAR(75) null,
	identifyOpportunities VARCHAR(75) null,
	otherRefOpportunity VARCHAR(75) null,
	demonstrateFulfilment VARCHAR(75) null,
	otherRefDemonstrate VARCHAR(75) null,
	ensureLabPlan VARCHAR(75) null,
	otherRefEnsurePlan VARCHAR(75) null,
	plannedManageReview VARCHAR(75) null,
	otherRefPlanned VARCHAR(75) null,
	availablePersonnel VARCHAR(75) null,
	manualRefAvailable VARCHAR(75) null,
	educationProgramme VARCHAR(75) null,
	manualRefEducation VARCHAR(75) null,
	ensureAccomodation VARCHAR(75) null,
	manualRefAccom VARCHAR(75) null,
	processForSelection VARCHAR(75) null,
	manualRefSelection VARCHAR(75) null,
	verifyReagents VARCHAR(75) null,
	manualRefReagents VARCHAR(75) null,
	docProcedure VARCHAR(75) null,
	manualRefDocProce VARCHAR(75) null,
	useExamMethods VARCHAR(75) null,
	manualRefExam VARCHAR(75) null,
	monitoringValidity VARCHAR(75) null,
	manualRefValidity VARCHAR(75) null,
	validateExam VARCHAR(75) null,
	manualRefValidateExam VARCHAR(75) null,
	uncertainityReview VARCHAR(75) null,
	manualRefUncertainity VARCHAR(75) null,
	preventResRelease VARCHAR(75) null,
	manualRefPrevent VARCHAR(75) null,
	equipmentMaintenance VARCHAR(75) null,
	manualRefMaintenance VARCHAR(75) null,
	equipCalibration VARCHAR(75) null,
	manualRefCalibrat VARCHAR(75) null,
	proficencyTesting VARCHAR(75) null,
	manualRefProfiTest VARCHAR(75) null,
	postExamReliabilty VARCHAR(75) null,
	manualRefPostExam VARCHAR(75) null,
	reportedAccurately VARCHAR(75) null,
	manualRefReported VARCHAR(75) null,
	responsiblitySpecified VARCHAR(75) null,
	manualRefSpecified VARCHAR(75) null,
	ensureAuthorities VARCHAR(75) null,
	manualRefAuthorities VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_med_other_req (
	uuid_ VARCHAR(75) null,
	accMediLabOtherReqId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	representativeName VARCHAR(75) null,
	representativePos VARCHAR(75) null,
	signDate DATE null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_med_test_desc (
	uuid_ VARCHAR(75) null,
	accMediLabTestDescriptionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	testClinicalActivity VARCHAR(75) null,
	testLabShiftWork VARCHAR(75) null,
	testLabSpecimenNo VARCHAR(75) null,
	testSpecimenLocation VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_med_test_manage (
	uuid_ VARCHAR(75) null,
	accMediLabTestManageReqId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	policiesForFulfil VARCHAR(75) null,
	labDocRefPolicies VARCHAR(75) null,
	impartialityProvision VARCHAR(75) null,
	labDocRefImpartProv VARCHAR(75) null,
	confidientialityProv VARCHAR(75) null,
	labDocRefConfid VARCHAR(75) null,
	commitmentEvidence VARCHAR(75) null,
	labDocRefCommitment VARCHAR(75) null,
	referenceEvidence VARCHAR(75) null,
	labDocRefReference VARCHAR(75) null,
	docDescribingRole VARCHAR(75) null,
	labDocRefDocDes VARCHAR(75) null,
	rolesofPersonnel VARCHAR(75) null,
	labDocRefRoles VARCHAR(75) null,
	competenceReq VARCHAR(75) null,
	labDocRefCompetence VARCHAR(75) null,
	selectionOfPerson VARCHAR(75) null,
	labDocRefSelection VARCHAR(75) null,
	handlingEquip VARCHAR(75) null,
	labDocRefHandling VARCHAR(75) null,
	calibrationProgram VARCHAR(75) null,
	labDocRefCalibrat VARCHAR(75) null,
	approvingReq VARCHAR(75) null,
	labDocRefApproving VARCHAR(75) null,
	monitorPerformance VARCHAR(75) null,
	labDocRefMonitor VARCHAR(75) null,
	ensuringService VARCHAR(75) null,
	labDocRefEnsuring VARCHAR(75) null,
	reviewOfRequest VARCHAR(75) null,
	labDocRefRequest VARCHAR(75) null,
	procedureForLab VARCHAR(75) null,
	labDocRefProcedure VARCHAR(75) null,
	testMethodValidat VARCHAR(75) null,
	labDocRefTestMethod VARCHAR(75) null,
	samplingPlan VARCHAR(75) null,
	labDocRefSampling VARCHAR(75) null,
	transportationReciept VARCHAR(75) null,
	labDocRefTransport VARCHAR(75) null,
	uncertainityMeasure VARCHAR(75) null,
	labDocRefUncertain VARCHAR(75) null,
	testResultValidity VARCHAR(75) null,
	labDocReftestResult VARCHAR(75) null,
	complaints VARCHAR(75) null,
	labDocRefComplaints VARCHAR(75) null,
	nonConformingWork VARCHAR(75) null,
	labDocRefNonConfirm VARCHAR(75) null,
	uniqueIdentification VARCHAR(75) null,
	labDocRefUnique VARCHAR(75) null,
	currentRevisionStatus VARCHAR(75) null,
	labDocRefCurrentRev VARCHAR(75) null,
	docChangeIdentify VARCHAR(75) null,
	labDocRefDocChange VARCHAR(75) null,
	recordControl VARCHAR(75) null,
	labDocRefRecordControl VARCHAR(75) null,
	plannedAction VARCHAR(75) null,
	labDocRefPlanned VARCHAR(75) null,
	imporvementOpportunity VARCHAR(75) null,
	labDocRefImprovement VARCHAR(75) null,
	correctiveAction VARCHAR(75) null,
	labDocRefCorrective VARCHAR(75) null,
	internalAudits VARCHAR(75) null,
	labDocRefInternal VARCHAR(75) null,
	managementReview VARCHAR(75) null,
	labDocRefManagement VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_med_test_reso (
	uuid_ VARCHAR(75) null,
	accMediLabTestResourceReqId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	testExternal VARCHAR(75) null,
	testCompetence VARCHAR(75) null,
	testLabFacilities VARCHAR(75) null,
	testLabContracted VARCHAR(75) null,
	testLabFacilityEnv VARCHAR(75) null,
	testSpecialEnv VARCHAR(75) null,
	testMonitoringAct VARCHAR(75) null,
	testLabRelatedEquip VARCHAR(75) null,
	testSecurityArrange VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_med_test_struct (
	uuid_ VARCHAR(75) null,
	accMediLabTestStructuralId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	testLabLegalEntity VARCHAR(75) null,
	testlegalStatus VARCHAR(75) null,
	testlabPartOfOrg VARCHAR(75) null,
	testlabPartOfOrgName VARCHAR(75) null,
	testLabPartOfOrgPos VARCHAR(75) null,
	testMangerialStaff VARCHAR(75) null,
	testTechnicalStaff VARCHAR(75) null,
	testingRelevantDoc VARCHAR(75) null,
	testMajorIncome VARCHAR(75) null,
	testLabClients VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_medi_app_info (
	uuid_ VARCHAR(75) null,
	accMediLabApplicationInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfApplicant VARCHAR(75) null,
	applicantAddress VARCHAR(75) null,
	appliTelephoneNo VARCHAR(75) null,
	appliFaxNo VARCHAR(75) null,
	appliWebsite VARCHAR(75) null,
	laboratoryName VARCHAR(75) null,
	laboratoryAddress VARCHAR(75) null,
	nameOfIncharge VARCHAR(75) null,
	emailOfIncharge VARCHAR(75) null,
	personnelQMName VARCHAR(75) null,
	personnelQMEmail VARCHAR(75) null,
	deputyInchargeName VARCHAR(75) null,
	deputyInchargeEmail VARCHAR(75) null,
	personnelFMName VARCHAR(75) null,
	personnelFMEmail VARCHAR(75) null,
	accRequestType VARCHAR(75) null,
	authorizedPersonnelName VARCHAR(75) null,
	authorizedPosition VARCHAR(75) null,
	authorizedPersonnelDate DATE null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_medi_org (
	uuid_ VARCHAR(75) null,
	accMediLabOrganizationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	laboratoryLegalEntity VARCHAR(75) null,
	legalStatus VARCHAR(75) null,
	laboratoryPartOfOrg VARCHAR(75) null,
	laboratoryPartOfOrgName VARCHAR(75) null,
	laboratoryPartOfOrgPos VARCHAR(75) null,
	nameOfAnalysts VARCHAR(75) null,
	majorIncomeSource VARCHAR(75) null,
	laboratoryClients VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_medi_physical (
	uuid_ VARCHAR(75) null,
	accMediLabPhysicalResourceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	laboratoryfacilities VARCHAR(75) null,
	safetyFeatures VARCHAR(75) null,
	specialEnvironment VARCHAR(75) null,
	monitoringActivities VARCHAR(75) null,
	securityArrangements VARCHAR(75) null,
	laboratoryDocumented VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_third_app_info (
	uuid_ VARCHAR(75) null,
	accThirdPartyAppliInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicantName VARCHAR(75) null,
	applicantAddress VARCHAR(75) null,
	applicantTelephone VARCHAR(75) null,
	applicantFaxNo VARCHAR(75) null,
	applicantWebsite VARCHAR(75) null,
	certificationName VARCHAR(75) null,
	certiAddress VARCHAR(75) null,
	personnelName VARCHAR(75) null,
	personnelEmail VARCHAR(75) null,
	personnelContactName VARCHAR(75) null,
	personnelContactEmail VARCHAR(75) null,
	personnelFMName VARCHAR(75) null,
	personnelFMEmail VARCHAR(75) null,
	accreditationRequest VARCHAR(75) null,
	accFdaScheme VARCHAR(75) null,
	specifyOther VARCHAR(75) null,
	supplementaryCertificate VARCHAR(75) null,
	supplementaryOther VARCHAR(75) null,
	listOfStandard VARCHAR(75) null,
	authorizedPersonnelName VARCHAR(75) null,
	authorizedPersonnelPos VARCHAR(75) null,
	authorizedPersonnelDate DATE null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_third_appli (
	uuid_ VARCHAR(75) null,
	accThirdPartyAppliInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicantName VARCHAR(75) null,
	applicantAddress VARCHAR(75) null,
	applicantTelephone VARCHAR(75) null,
	applicantFaxNo VARCHAR(75) null,
	applicantWebsite VARCHAR(75) null,
	certificationName VARCHAR(75) null,
	certiAddress VARCHAR(75) null,
	personnelName VARCHAR(75) null,
	personnelEmail VARCHAR(75) null,
	personnelContactName VARCHAR(75) null,
	personnelContactEmail VARCHAR(75) null,
	personnelFMName VARCHAR(75) null,
	personnelFMEmail VARCHAR(75) null,
	accreditationRequest VARCHAR(75) null,
	accFdaScheme VARCHAR(75) null,
	specifyOther VARCHAR(75) null,
	supplementaryCertificate VARCHAR(75) null,
	supplementaryOther VARCHAR(75) null,
	listOfStandard VARCHAR(75) null,
	authorizedPersonnelName VARCHAR(75) null,
	authorizedPersonnelPos VARCHAR(75) null,
	authorizedPersonnelDate DATE null,
	janaacApplicationId LONG
);

create table nbp_janaac_acc_third_scope (
	uuid_ VARCHAR(75) null,
	accThirdPartyScopeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	accreditationCategory VARCHAR(1000) null,
	foodProduct1 VARCHAR(75) null,
	foodRegulation1 VARCHAR(75) null,
	foodProduct2 VARCHAR(75) null,
	foodRegulation2 VARCHAR(75) null,
	foodProduct3 VARCHAR(75) null,
	foodRegulation3 VARCHAR(75) null,
	foodProduct4 VARCHAR(75) null,
	foodRegulation4 VARCHAR(75) null,
	foodProduct5 VARCHAR(75) null,
	foodRegulation5 VARCHAR(75) null,
	foodProduct6 VARCHAR(75) null,
	foodRegulation6 VARCHAR(75) null,
	foodProduct7 VARCHAR(75) null,
	foodRegulation7 VARCHAR(75) null,
	foodProduct8 VARCHAR(75) null,
	foodRegulation8 VARCHAR(75) null,
	foodProduct9 VARCHAR(75) null,
	foodRegulation9 VARCHAR(75) null,
	foodProduct10 VARCHAR(75) null,
	foodRegulation10 VARCHAR(75) null,
	accCategoryOther VARCHAR(75) null,
	foodProduct11 VARCHAR(75) null,
	foodRegulation11 VARCHAR(75) null,
	accCategoryOther12 VARCHAR(75) null,
	foodProduct12 VARCHAR(75) null,
	foodRegulation12 VARCHAR(75) null,
	cerIntrestedParties VARCHAR(75) null,
	otherServices VARCHAR(75) null,
	otherServicesDescribe VARCHAR(75) null,
	establishedRelation VARCHAR(75) null,
	establishedRelDesc VARCHAR(75) null,
	clientService VARCHAR(75) null,
	certificationCerBody VARCHAR(75) null,
	orgAccredited VARCHAR(75) null,
	responsibleBody VARCHAR(75) null,
	accExpDate DATE null,
	certBodyScope VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_add_cer_appli_info (
	addCerApplicationInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	email VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_cer_per_first (
	addCerPersonnelFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfStaff VARCHAR(75) null,
	jobTitle VARCHAR(75) null,
	majorResponsibility VARCHAR(75) null,
	specificFunctions VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_cer_per_sec (
	addCerPersonnelSecondId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	role_ VARCHAR(75) null,
	certificateStandard VARCHAR(75) null,
	areaOfExpertise VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_cer_per_third (
	addCerPersonnelThirdId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	number_ VARCHAR(75) null,
	location VARCHAR(75) null,
	certificationActivities VARCHAR(75) null,
	contactDetails VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_cer_scope_ser (
	addCerScopeServiceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	clientOrganization VARCHAR(75) null,
	certificationStandards VARCHAR(75) null,
	currentCertification VARCHAR(75) null,
	dateFirstGranted DATE null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_fda_Appli_info (
	addFdaAppliInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	email VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_fda_per_first (
	addFdaPersonnelFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfStaff VARCHAR(75) null,
	jobTitle VARCHAR(75) null,
	majorResponsibilites VARCHAR(75) null,
	specificFunctions VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_fda_per_four (
	addFdaPersonnelFourId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	number_ VARCHAR(75) null,
	locationAddress VARCHAR(75) null,
	certificationActivities VARCHAR(75) null,
	contactDetails VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_fda_per_sec (
	addFdaPersonnelSecondId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	role_ VARCHAR(75) null,
	fdaRegulation VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_fda_per_third (
	addFdaPersonnelThirdId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	outsourcedActivity VARCHAR(75) null,
	supplierServiceProvider VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_fda_scop_client (
	addFdaScopeClientId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	clientOrganization VARCHAR(75) null,
	foodProducts VARCHAR(75) null,
	fdaRegulations VARCHAR(75) null,
	dateGranted DATE null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_ins_appli_info (
	addInsApplicationInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	email VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_ins_lab_org (
	addLaboratoryPartOfOrgId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	laboratoryPartOfOrgName VARCHAR(75) null,
	laboratoryPartOfOrgPosition VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_ins_org_first (
	addInsOrgInfoFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	position VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_ins_org_sec (
	addInsOrgInfoSecondId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfStaff VARCHAR(75) null,
	jobTitle VARCHAR(75) null,
	majorResponsibilities VARCHAR(75) null,
	indexInspector VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_ins_org_third (
	AddInsOrgInfoThirdId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	inspectionActivity VARCHAR(75) null,
	fieldOfInspection VARCHAR(75) null,
	typeOfInspection VARCHAR(75) null,
	method VARCHAR(75) null,
	eqipment VARCHAR(75) null,
	limitsOfCapabilities VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_ins_phy_first (
	addPhyResourceFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	inventoryNumber VARCHAR(75) null,
	item VARCHAR(75) null,
	manufacturer VARCHAR(75) null,
	modelNumber VARCHAR(75) null,
	calibrationInterval VARCHAR(75) null,
	calibratedBy VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_ins_phy_sec (
	addPhyResourceSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	number_ VARCHAR(75) null,
	location VARCHAR(75) null,
	activitiesPerformed VARCHAR(75) null,
	contactDetails VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_aapli_info (
	addLabAppliInfoId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	email VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_carStrucSec (
	addLabCalibraStrucReqSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	number_ VARCHAR(75) null,
	measuredQuantity VARCHAR(75) null,
	calibrationItem VARCHAR(75) null,
	range_ VARCHAR(75) null,
	measurementProcedure VARCHAR(75) null,
	calibration VARCHAR(75) null,
	remarks VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_des_of_act (
	addLabDescOfActivityId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	number_ VARCHAR(75) null,
	location VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_med_dec_sec (
	addLabMedicalDescOfActiSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	requestedPoct VARCHAR(75) null,
	location VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_med_or_fir (
	addLabMedicalOrganFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfStaff VARCHAR(75) null,
	jobTitle VARCHAR(75) null,
	majorResponsibilities VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_med_or_sec (
	addLabMedicalOrganSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	product VARCHAR(75) null,
	examination VARCHAR(75) null,
	methods VARCHAR(75) null,
	equipment VARCHAR(75) null,
	referenceRange VARCHAR(75) null,
	measurementUncertainty VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_med_phy_sec (
	addLabMedicalPhysicalSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	number_ VARCHAR(75) null,
	location VARCHAR(75) null,
	activitiesPerformed VARCHAR(75) null,
	contactDetails VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_res_req_fir (
	addLabResourceReqFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	num VARCHAR(75) null,
	location VARCHAR(75) null,
	activities VARCHAR(75) null,
	contactDetails VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_res_req_sec (
	addLabResourceReqSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	inventoryNumber VARCHAR(75) null,
	item VARCHAR(75) null,
	manufacturer VARCHAR(75) null,
	modelNumber VARCHAR(75) null,
	calibrationInterval VARCHAR(75) null,
	calibratedBy VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_stru_req (
	addLabStructuralRequirementId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfStaff VARCHAR(75) null,
	jobTitle VARCHAR(75) null,
	majorResponsibilities VARCHAR(75) null,
	indicateAnalysts  VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_lab_testStr_sec (
	addLabTestStructuralReqSecId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	productMaterial VARCHAR(75) null,
	tests VARCHAR(75) null,
	method VARCHAR(75) null,
	equipment VARCHAR(75) null,
	listOfCapability VARCHAR(75) null,
	estimateOfMeasurement VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_medi_phy_first (
	addLabMedicalPhysicalFirstId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	inventoryNum VARCHAR(75) null,
	item VARCHAR(75) null,
	manufacturer VARCHAR(75) null,
	modelNum VARCHAR(75) null,
	calibrationInterval VARCHAR(75) null,
	calibratedBy VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_out_src_act (
	addOutsourcedActivitiesId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	outSourcedActivity VARCHAR(75) null,
	serviceProvider VARCHAR(75) null,
	locationAddress VARCHAR(75) null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_add_scope_ser_third (
	addCerScopeServiceThirdId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	organizationName VARCHAR(75) null,
	organizationAddress VARCHAR(75) null,
	certificationScheme VARCHAR(75) null,
	currentStatus VARCHAR(75) null,
	dateFirstGranted DATE null,
	DateOfNextExamination DATE null,
	janaacApplicationId LONG,
	counter VARCHAR(75) null
);

create table nbp_janaac_appli_current_stage (
	janaacAppliCurrentStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormStep VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_appli_payment (
	janaacApplicationPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentFee VARCHAR(75) null,
	amountPaid VARCHAR(75) null,
	amountCurrency VARCHAR(75) null,
	janaacApplicationId LONG
);

create table nbp_janaac_application (
	uuid_ VARCHAR(75) null,
	janaacApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	accreditationType VARCHAR(75) null,
	accServiceType VARCHAR(500) null,
	transactionType VARCHAR(75) null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	caseId VARCHAR(500) null,
	icmDocumentsPath VARCHAR(500) null,
	pdfFileEntryId LONG,
	appCurrentStageName VARCHAR(75) null
);