/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.miic.stages.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.miic.stages.service.model.MiicCertificateOfIssuance;
import com.nbp.miic.stages.service.model.MiicCertificateOfIssuanceModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MiicCertificateOfIssuance service. Represents a row in the &quot;nbp_miic_certificate_of_issuan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MiicCertificateOfIssuanceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MiicCertificateOfIssuanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MiicCertificateOfIssuanceImpl
 * @generated
 */
@JSON(strict = true)
public class MiicCertificateOfIssuanceModelImpl
	extends BaseModelImpl<MiicCertificateOfIssuance>
	implements MiicCertificateOfIssuanceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a miic certificate of issuance model instance should use the <code>MiicCertificateOfIssuance</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_miic_certificate_of_issuan";

	public static final Object[][] TABLE_COLUMNS = {
		{"miicCertificateOfIssuanceId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"certificateNumber", Types.VARCHAR},
		{"dateCertificateIssued", Types.TIMESTAMP},
		{"dateOfExpiration", Types.TIMESTAMP},
		{"documentFileEntryId", Types.BIGINT}, {"caseId", Types.VARCHAR},
		{"nameOfLicensedTrustee", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("miicCertificateOfIssuanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("certificateNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dateCertificateIssued", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dateOfExpiration", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("documentFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("caseId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nameOfLicensedTrustee", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_miic_certificate_of_issuan (miicCertificateOfIssuanceId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,certificateNumber VARCHAR(75) null,dateCertificateIssued DATE null,dateOfExpiration DATE null,documentFileEntryId LONG,caseId VARCHAR(75) null,nameOfLicensedTrustee VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_miic_certificate_of_issuan";

	public static final String ORDER_BY_JPQL =
		" ORDER BY miicCertificateOfIssuance.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_miic_certificate_of_issuan.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CASEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MiicCertificateOfIssuanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _miicCertificateOfIssuanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMiicCertificateOfIssuanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _miicCertificateOfIssuanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MiicCertificateOfIssuance.class;
	}

	@Override
	public String getModelClassName() {
		return MiicCertificateOfIssuance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MiicCertificateOfIssuance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MiicCertificateOfIssuance, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MiicCertificateOfIssuance, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MiicCertificateOfIssuance)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MiicCertificateOfIssuance, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MiicCertificateOfIssuance, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MiicCertificateOfIssuance)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MiicCertificateOfIssuance, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MiicCertificateOfIssuance, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<MiicCertificateOfIssuance, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<MiicCertificateOfIssuance, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<MiicCertificateOfIssuance, Object>>();

			attributeGetterFunctions.put(
				"miicCertificateOfIssuanceId",
				MiicCertificateOfIssuance::getMiicCertificateOfIssuanceId);
			attributeGetterFunctions.put(
				"groupId", MiicCertificateOfIssuance::getGroupId);
			attributeGetterFunctions.put(
				"companyId", MiicCertificateOfIssuance::getCompanyId);
			attributeGetterFunctions.put(
				"userId", MiicCertificateOfIssuance::getUserId);
			attributeGetterFunctions.put(
				"userName", MiicCertificateOfIssuance::getUserName);
			attributeGetterFunctions.put(
				"createDate", MiicCertificateOfIssuance::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", MiicCertificateOfIssuance::getModifiedDate);
			attributeGetterFunctions.put(
				"certificateNumber",
				MiicCertificateOfIssuance::getCertificateNumber);
			attributeGetterFunctions.put(
				"dateCertificateIssued",
				MiicCertificateOfIssuance::getDateCertificateIssued);
			attributeGetterFunctions.put(
				"dateOfExpiration",
				MiicCertificateOfIssuance::getDateOfExpiration);
			attributeGetterFunctions.put(
				"documentFileEntryId",
				MiicCertificateOfIssuance::getDocumentFileEntryId);
			attributeGetterFunctions.put(
				"caseId", MiicCertificateOfIssuance::getCaseId);
			attributeGetterFunctions.put(
				"nameOfLicensedTrustee",
				MiicCertificateOfIssuance::getNameOfLicensedTrustee);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<MiicCertificateOfIssuance, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<MiicCertificateOfIssuance, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<MiicCertificateOfIssuance, ?>>();

			attributeSetterBiConsumers.put(
				"miicCertificateOfIssuanceId",
				(BiConsumer<MiicCertificateOfIssuance, Long>)
					MiicCertificateOfIssuance::setMiicCertificateOfIssuanceId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<MiicCertificateOfIssuance, Long>)
					MiicCertificateOfIssuance::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<MiicCertificateOfIssuance, Long>)
					MiicCertificateOfIssuance::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<MiicCertificateOfIssuance, Long>)
					MiicCertificateOfIssuance::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<MiicCertificateOfIssuance, String>)
					MiicCertificateOfIssuance::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<MiicCertificateOfIssuance, Date>)
					MiicCertificateOfIssuance::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<MiicCertificateOfIssuance, Date>)
					MiicCertificateOfIssuance::setModifiedDate);
			attributeSetterBiConsumers.put(
				"certificateNumber",
				(BiConsumer<MiicCertificateOfIssuance, String>)
					MiicCertificateOfIssuance::setCertificateNumber);
			attributeSetterBiConsumers.put(
				"dateCertificateIssued",
				(BiConsumer<MiicCertificateOfIssuance, Date>)
					MiicCertificateOfIssuance::setDateCertificateIssued);
			attributeSetterBiConsumers.put(
				"dateOfExpiration",
				(BiConsumer<MiicCertificateOfIssuance, Date>)
					MiicCertificateOfIssuance::setDateOfExpiration);
			attributeSetterBiConsumers.put(
				"documentFileEntryId",
				(BiConsumer<MiicCertificateOfIssuance, Long>)
					MiicCertificateOfIssuance::setDocumentFileEntryId);
			attributeSetterBiConsumers.put(
				"caseId",
				(BiConsumer<MiicCertificateOfIssuance, String>)
					MiicCertificateOfIssuance::setCaseId);
			attributeSetterBiConsumers.put(
				"nameOfLicensedTrustee",
				(BiConsumer<MiicCertificateOfIssuance, String>)
					MiicCertificateOfIssuance::setNameOfLicensedTrustee);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMiicCertificateOfIssuanceId() {
		return _miicCertificateOfIssuanceId;
	}

	@Override
	public void setMiicCertificateOfIssuanceId(
		long miicCertificateOfIssuanceId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_miicCertificateOfIssuanceId = miicCertificateOfIssuanceId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCertificateNumber() {
		if (_certificateNumber == null) {
			return "";
		}
		else {
			return _certificateNumber;
		}
	}

	@Override
	public void setCertificateNumber(String certificateNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_certificateNumber = certificateNumber;
	}

	@JSON
	@Override
	public Date getDateCertificateIssued() {
		return _dateCertificateIssued;
	}

	@Override
	public void setDateCertificateIssued(Date dateCertificateIssued) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateCertificateIssued = dateCertificateIssued;
	}

	@JSON
	@Override
	public Date getDateOfExpiration() {
		return _dateOfExpiration;
	}

	@Override
	public void setDateOfExpiration(Date dateOfExpiration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfExpiration = dateOfExpiration;
	}

	@JSON
	@Override
	public long getDocumentFileEntryId() {
		return _documentFileEntryId;
	}

	@Override
	public void setDocumentFileEntryId(long documentFileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentFileEntryId = documentFileEntryId;
	}

	@JSON
	@Override
	public String getCaseId() {
		if (_caseId == null) {
			return "";
		}
		else {
			return _caseId;
		}
	}

	@Override
	public void setCaseId(String caseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_caseId = caseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCaseId() {
		return getColumnOriginalValue("caseId");
	}

	@JSON
	@Override
	public String getNameOfLicensedTrustee() {
		if (_nameOfLicensedTrustee == null) {
			return "";
		}
		else {
			return _nameOfLicensedTrustee;
		}
	}

	@Override
	public void setNameOfLicensedTrustee(String nameOfLicensedTrustee) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameOfLicensedTrustee = nameOfLicensedTrustee;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MiicCertificateOfIssuance.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MiicCertificateOfIssuance toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MiicCertificateOfIssuance>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MiicCertificateOfIssuanceImpl miicCertificateOfIssuanceImpl =
			new MiicCertificateOfIssuanceImpl();

		miicCertificateOfIssuanceImpl.setMiicCertificateOfIssuanceId(
			getMiicCertificateOfIssuanceId());
		miicCertificateOfIssuanceImpl.setGroupId(getGroupId());
		miicCertificateOfIssuanceImpl.setCompanyId(getCompanyId());
		miicCertificateOfIssuanceImpl.setUserId(getUserId());
		miicCertificateOfIssuanceImpl.setUserName(getUserName());
		miicCertificateOfIssuanceImpl.setCreateDate(getCreateDate());
		miicCertificateOfIssuanceImpl.setModifiedDate(getModifiedDate());
		miicCertificateOfIssuanceImpl.setCertificateNumber(
			getCertificateNumber());
		miicCertificateOfIssuanceImpl.setDateCertificateIssued(
			getDateCertificateIssued());
		miicCertificateOfIssuanceImpl.setDateOfExpiration(
			getDateOfExpiration());
		miicCertificateOfIssuanceImpl.setDocumentFileEntryId(
			getDocumentFileEntryId());
		miicCertificateOfIssuanceImpl.setCaseId(getCaseId());
		miicCertificateOfIssuanceImpl.setNameOfLicensedTrustee(
			getNameOfLicensedTrustee());

		miicCertificateOfIssuanceImpl.resetOriginalValues();

		return miicCertificateOfIssuanceImpl;
	}

	@Override
	public MiicCertificateOfIssuance cloneWithOriginalValues() {
		MiicCertificateOfIssuanceImpl miicCertificateOfIssuanceImpl =
			new MiicCertificateOfIssuanceImpl();

		miicCertificateOfIssuanceImpl.setMiicCertificateOfIssuanceId(
			this.<Long>getColumnOriginalValue("miicCertificateOfIssuanceId"));
		miicCertificateOfIssuanceImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		miicCertificateOfIssuanceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		miicCertificateOfIssuanceImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		miicCertificateOfIssuanceImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		miicCertificateOfIssuanceImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		miicCertificateOfIssuanceImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		miicCertificateOfIssuanceImpl.setCertificateNumber(
			this.<String>getColumnOriginalValue("certificateNumber"));
		miicCertificateOfIssuanceImpl.setDateCertificateIssued(
			this.<Date>getColumnOriginalValue("dateCertificateIssued"));
		miicCertificateOfIssuanceImpl.setDateOfExpiration(
			this.<Date>getColumnOriginalValue("dateOfExpiration"));
		miicCertificateOfIssuanceImpl.setDocumentFileEntryId(
			this.<Long>getColumnOriginalValue("documentFileEntryId"));
		miicCertificateOfIssuanceImpl.setCaseId(
			this.<String>getColumnOriginalValue("caseId"));
		miicCertificateOfIssuanceImpl.setNameOfLicensedTrustee(
			this.<String>getColumnOriginalValue("nameOfLicensedTrustee"));

		return miicCertificateOfIssuanceImpl;
	}

	@Override
	public int compareTo(MiicCertificateOfIssuance miicCertificateOfIssuance) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), miicCertificateOfIssuance.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MiicCertificateOfIssuance)) {
			return false;
		}

		MiicCertificateOfIssuance miicCertificateOfIssuance =
			(MiicCertificateOfIssuance)object;

		long primaryKey = miicCertificateOfIssuance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MiicCertificateOfIssuance> toCacheModel() {
		MiicCertificateOfIssuanceCacheModel
			miicCertificateOfIssuanceCacheModel =
				new MiicCertificateOfIssuanceCacheModel();

		miicCertificateOfIssuanceCacheModel.miicCertificateOfIssuanceId =
			getMiicCertificateOfIssuanceId();

		miicCertificateOfIssuanceCacheModel.groupId = getGroupId();

		miicCertificateOfIssuanceCacheModel.companyId = getCompanyId();

		miicCertificateOfIssuanceCacheModel.userId = getUserId();

		miicCertificateOfIssuanceCacheModel.userName = getUserName();

		String userName = miicCertificateOfIssuanceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			miicCertificateOfIssuanceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			miicCertificateOfIssuanceCacheModel.createDate =
				createDate.getTime();
		}
		else {
			miicCertificateOfIssuanceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			miicCertificateOfIssuanceCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			miicCertificateOfIssuanceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		miicCertificateOfIssuanceCacheModel.certificateNumber =
			getCertificateNumber();

		String certificateNumber =
			miicCertificateOfIssuanceCacheModel.certificateNumber;

		if ((certificateNumber != null) && (certificateNumber.length() == 0)) {
			miicCertificateOfIssuanceCacheModel.certificateNumber = null;
		}

		Date dateCertificateIssued = getDateCertificateIssued();

		if (dateCertificateIssued != null) {
			miicCertificateOfIssuanceCacheModel.dateCertificateIssued =
				dateCertificateIssued.getTime();
		}
		else {
			miicCertificateOfIssuanceCacheModel.dateCertificateIssued =
				Long.MIN_VALUE;
		}

		Date dateOfExpiration = getDateOfExpiration();

		if (dateOfExpiration != null) {
			miicCertificateOfIssuanceCacheModel.dateOfExpiration =
				dateOfExpiration.getTime();
		}
		else {
			miicCertificateOfIssuanceCacheModel.dateOfExpiration =
				Long.MIN_VALUE;
		}

		miicCertificateOfIssuanceCacheModel.documentFileEntryId =
			getDocumentFileEntryId();

		miicCertificateOfIssuanceCacheModel.caseId = getCaseId();

		String caseId = miicCertificateOfIssuanceCacheModel.caseId;

		if ((caseId != null) && (caseId.length() == 0)) {
			miicCertificateOfIssuanceCacheModel.caseId = null;
		}

		miicCertificateOfIssuanceCacheModel.nameOfLicensedTrustee =
			getNameOfLicensedTrustee();

		String nameOfLicensedTrustee =
			miicCertificateOfIssuanceCacheModel.nameOfLicensedTrustee;

		if ((nameOfLicensedTrustee != null) &&
			(nameOfLicensedTrustee.length() == 0)) {

			miicCertificateOfIssuanceCacheModel.nameOfLicensedTrustee = null;
		}

		return miicCertificateOfIssuanceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MiicCertificateOfIssuance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MiicCertificateOfIssuance, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MiicCertificateOfIssuance, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MiicCertificateOfIssuance)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, MiicCertificateOfIssuance>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						MiicCertificateOfIssuance.class, ModelWrapper.class);

	}

	private long _miicCertificateOfIssuanceId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _certificateNumber;
	private Date _dateCertificateIssued;
	private Date _dateOfExpiration;
	private long _documentFileEntryId;
	private String _caseId;
	private String _nameOfLicensedTrustee;

	public <T> T getColumnValue(String columnName) {
		Function<MiicCertificateOfIssuance, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MiicCertificateOfIssuance)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"miicCertificateOfIssuanceId", _miicCertificateOfIssuanceId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("certificateNumber", _certificateNumber);
		_columnOriginalValues.put(
			"dateCertificateIssued", _dateCertificateIssued);
		_columnOriginalValues.put("dateOfExpiration", _dateOfExpiration);
		_columnOriginalValues.put("documentFileEntryId", _documentFileEntryId);
		_columnOriginalValues.put("caseId", _caseId);
		_columnOriginalValues.put(
			"nameOfLicensedTrustee", _nameOfLicensedTrustee);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("miicCertificateOfIssuanceId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("certificateNumber", 128L);

		columnBitmasks.put("dateCertificateIssued", 256L);

		columnBitmasks.put("dateOfExpiration", 512L);

		columnBitmasks.put("documentFileEntryId", 1024L);

		columnBitmasks.put("caseId", 2048L);

		columnBitmasks.put("nameOfLicensedTrustee", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MiicCertificateOfIssuance _escapedModel;

}