/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.creative.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.creative.application.form.service.model.CreativeContactInfoAddBox;
import com.nbp.creative.application.form.service.model.CreativeContactInfoAddBoxModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CreativeContactInfoAddBox service. Represents a row in the &quot;nbp_creative_contact_box&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CreativeContactInfoAddBoxModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CreativeContactInfoAddBoxImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CreativeContactInfoAddBoxImpl
 * @generated
 */
@JSON(strict = true)
public class CreativeContactInfoAddBoxModelImpl
	extends BaseModelImpl<CreativeContactInfoAddBox>
	implements CreativeContactInfoAddBoxModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a creative contact info add box model instance should use the <code>CreativeContactInfoAddBox</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_creative_contact_box";

	public static final Object[][] TABLE_COLUMNS = {
		{"creativeContactBoxId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"contactTelephone", Types.VARCHAR},
		{"contactFax", Types.VARCHAR}, {"contactEmailAddress", Types.VARCHAR},
		{"counterContact", Types.VARCHAR},
		{"CreativeApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("creativeContactBoxId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("contactTelephone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactFax", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactEmailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("counterContact", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreativeApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_creative_contact_box (creativeContactBoxId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,contactTelephone VARCHAR(75) null,contactFax VARCHAR(75) null,contactEmailAddress VARCHAR(75) null,counterContact VARCHAR(75) null,CreativeApplicationId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_creative_contact_box";

	public static final String ORDER_BY_JPQL =
		" ORDER BY creativeContactInfoAddBox.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_creative_contact_box.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATIVEAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CreativeContactInfoAddBoxModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _creativeContactBoxId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCreativeContactBoxId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _creativeContactBoxId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CreativeContactInfoAddBox.class;
	}

	@Override
	public String getModelClassName() {
		return CreativeContactInfoAddBox.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CreativeContactInfoAddBox, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CreativeContactInfoAddBox, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CreativeContactInfoAddBox, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CreativeContactInfoAddBox)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CreativeContactInfoAddBox, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CreativeContactInfoAddBox, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CreativeContactInfoAddBox)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CreativeContactInfoAddBox, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CreativeContactInfoAddBox, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CreativeContactInfoAddBox, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CreativeContactInfoAddBox, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CreativeContactInfoAddBox, Object>>();

			attributeGetterFunctions.put(
				"creativeContactBoxId",
				CreativeContactInfoAddBox::getCreativeContactBoxId);
			attributeGetterFunctions.put(
				"groupId", CreativeContactInfoAddBox::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CreativeContactInfoAddBox::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CreativeContactInfoAddBox::getUserId);
			attributeGetterFunctions.put(
				"userName", CreativeContactInfoAddBox::getUserName);
			attributeGetterFunctions.put(
				"createDate", CreativeContactInfoAddBox::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CreativeContactInfoAddBox::getModifiedDate);
			attributeGetterFunctions.put(
				"contactTelephone",
				CreativeContactInfoAddBox::getContactTelephone);
			attributeGetterFunctions.put(
				"contactFax", CreativeContactInfoAddBox::getContactFax);
			attributeGetterFunctions.put(
				"contactEmailAddress",
				CreativeContactInfoAddBox::getContactEmailAddress);
			attributeGetterFunctions.put(
				"counterContact", CreativeContactInfoAddBox::getCounterContact);
			attributeGetterFunctions.put(
				"CreativeApplicationId",
				CreativeContactInfoAddBox::getCreativeApplicationId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CreativeContactInfoAddBox, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CreativeContactInfoAddBox, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CreativeContactInfoAddBox, ?>>();

			attributeSetterBiConsumers.put(
				"creativeContactBoxId",
				(BiConsumer<CreativeContactInfoAddBox, Long>)
					CreativeContactInfoAddBox::setCreativeContactBoxId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CreativeContactInfoAddBox, Long>)
					CreativeContactInfoAddBox::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CreativeContactInfoAddBox, Long>)
					CreativeContactInfoAddBox::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CreativeContactInfoAddBox, Long>)
					CreativeContactInfoAddBox::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CreativeContactInfoAddBox, String>)
					CreativeContactInfoAddBox::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CreativeContactInfoAddBox, Date>)
					CreativeContactInfoAddBox::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CreativeContactInfoAddBox, Date>)
					CreativeContactInfoAddBox::setModifiedDate);
			attributeSetterBiConsumers.put(
				"contactTelephone",
				(BiConsumer<CreativeContactInfoAddBox, String>)
					CreativeContactInfoAddBox::setContactTelephone);
			attributeSetterBiConsumers.put(
				"contactFax",
				(BiConsumer<CreativeContactInfoAddBox, String>)
					CreativeContactInfoAddBox::setContactFax);
			attributeSetterBiConsumers.put(
				"contactEmailAddress",
				(BiConsumer<CreativeContactInfoAddBox, String>)
					CreativeContactInfoAddBox::setContactEmailAddress);
			attributeSetterBiConsumers.put(
				"counterContact",
				(BiConsumer<CreativeContactInfoAddBox, String>)
					CreativeContactInfoAddBox::setCounterContact);
			attributeSetterBiConsumers.put(
				"CreativeApplicationId",
				(BiConsumer<CreativeContactInfoAddBox, Long>)
					CreativeContactInfoAddBox::setCreativeApplicationId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getCreativeContactBoxId() {
		return _creativeContactBoxId;
	}

	@Override
	public void setCreativeContactBoxId(long creativeContactBoxId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creativeContactBoxId = creativeContactBoxId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getContactTelephone() {
		if (_contactTelephone == null) {
			return "";
		}
		else {
			return _contactTelephone;
		}
	}

	@Override
	public void setContactTelephone(String contactTelephone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactTelephone = contactTelephone;
	}

	@JSON
	@Override
	public String getContactFax() {
		if (_contactFax == null) {
			return "";
		}
		else {
			return _contactFax;
		}
	}

	@Override
	public void setContactFax(String contactFax) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactFax = contactFax;
	}

	@JSON
	@Override
	public String getContactEmailAddress() {
		if (_contactEmailAddress == null) {
			return "";
		}
		else {
			return _contactEmailAddress;
		}
	}

	@Override
	public void setContactEmailAddress(String contactEmailAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactEmailAddress = contactEmailAddress;
	}

	@JSON
	@Override
	public String getCounterContact() {
		if (_counterContact == null) {
			return "";
		}
		else {
			return _counterContact;
		}
	}

	@Override
	public void setCounterContact(String counterContact) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_counterContact = counterContact;
	}

	@JSON
	@Override
	public long getCreativeApplicationId() {
		return _CreativeApplicationId;
	}

	@Override
	public void setCreativeApplicationId(long CreativeApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreativeApplicationId = CreativeApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCreativeApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("CreativeApplicationId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CreativeContactInfoAddBox.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CreativeContactInfoAddBox toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CreativeContactInfoAddBox>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CreativeContactInfoAddBoxImpl creativeContactInfoAddBoxImpl =
			new CreativeContactInfoAddBoxImpl();

		creativeContactInfoAddBoxImpl.setCreativeContactBoxId(
			getCreativeContactBoxId());
		creativeContactInfoAddBoxImpl.setGroupId(getGroupId());
		creativeContactInfoAddBoxImpl.setCompanyId(getCompanyId());
		creativeContactInfoAddBoxImpl.setUserId(getUserId());
		creativeContactInfoAddBoxImpl.setUserName(getUserName());
		creativeContactInfoAddBoxImpl.setCreateDate(getCreateDate());
		creativeContactInfoAddBoxImpl.setModifiedDate(getModifiedDate());
		creativeContactInfoAddBoxImpl.setContactTelephone(
			getContactTelephone());
		creativeContactInfoAddBoxImpl.setContactFax(getContactFax());
		creativeContactInfoAddBoxImpl.setContactEmailAddress(
			getContactEmailAddress());
		creativeContactInfoAddBoxImpl.setCounterContact(getCounterContact());
		creativeContactInfoAddBoxImpl.setCreativeApplicationId(
			getCreativeApplicationId());

		creativeContactInfoAddBoxImpl.resetOriginalValues();

		return creativeContactInfoAddBoxImpl;
	}

	@Override
	public CreativeContactInfoAddBox cloneWithOriginalValues() {
		CreativeContactInfoAddBoxImpl creativeContactInfoAddBoxImpl =
			new CreativeContactInfoAddBoxImpl();

		creativeContactInfoAddBoxImpl.setCreativeContactBoxId(
			this.<Long>getColumnOriginalValue("creativeContactBoxId"));
		creativeContactInfoAddBoxImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		creativeContactInfoAddBoxImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		creativeContactInfoAddBoxImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		creativeContactInfoAddBoxImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		creativeContactInfoAddBoxImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		creativeContactInfoAddBoxImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		creativeContactInfoAddBoxImpl.setContactTelephone(
			this.<String>getColumnOriginalValue("contactTelephone"));
		creativeContactInfoAddBoxImpl.setContactFax(
			this.<String>getColumnOriginalValue("contactFax"));
		creativeContactInfoAddBoxImpl.setContactEmailAddress(
			this.<String>getColumnOriginalValue("contactEmailAddress"));
		creativeContactInfoAddBoxImpl.setCounterContact(
			this.<String>getColumnOriginalValue("counterContact"));
		creativeContactInfoAddBoxImpl.setCreativeApplicationId(
			this.<Long>getColumnOriginalValue("CreativeApplicationId"));

		return creativeContactInfoAddBoxImpl;
	}

	@Override
	public int compareTo(CreativeContactInfoAddBox creativeContactInfoAddBox) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), creativeContactInfoAddBox.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CreativeContactInfoAddBox)) {
			return false;
		}

		CreativeContactInfoAddBox creativeContactInfoAddBox =
			(CreativeContactInfoAddBox)object;

		long primaryKey = creativeContactInfoAddBox.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CreativeContactInfoAddBox> toCacheModel() {
		CreativeContactInfoAddBoxCacheModel
			creativeContactInfoAddBoxCacheModel =
				new CreativeContactInfoAddBoxCacheModel();

		creativeContactInfoAddBoxCacheModel.creativeContactBoxId =
			getCreativeContactBoxId();

		creativeContactInfoAddBoxCacheModel.groupId = getGroupId();

		creativeContactInfoAddBoxCacheModel.companyId = getCompanyId();

		creativeContactInfoAddBoxCacheModel.userId = getUserId();

		creativeContactInfoAddBoxCacheModel.userName = getUserName();

		String userName = creativeContactInfoAddBoxCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			creativeContactInfoAddBoxCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			creativeContactInfoAddBoxCacheModel.createDate =
				createDate.getTime();
		}
		else {
			creativeContactInfoAddBoxCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			creativeContactInfoAddBoxCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			creativeContactInfoAddBoxCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		creativeContactInfoAddBoxCacheModel.contactTelephone =
			getContactTelephone();

		String contactTelephone =
			creativeContactInfoAddBoxCacheModel.contactTelephone;

		if ((contactTelephone != null) && (contactTelephone.length() == 0)) {
			creativeContactInfoAddBoxCacheModel.contactTelephone = null;
		}

		creativeContactInfoAddBoxCacheModel.contactFax = getContactFax();

		String contactFax = creativeContactInfoAddBoxCacheModel.contactFax;

		if ((contactFax != null) && (contactFax.length() == 0)) {
			creativeContactInfoAddBoxCacheModel.contactFax = null;
		}

		creativeContactInfoAddBoxCacheModel.contactEmailAddress =
			getContactEmailAddress();

		String contactEmailAddress =
			creativeContactInfoAddBoxCacheModel.contactEmailAddress;

		if ((contactEmailAddress != null) &&
			(contactEmailAddress.length() == 0)) {

			creativeContactInfoAddBoxCacheModel.contactEmailAddress = null;
		}

		creativeContactInfoAddBoxCacheModel.counterContact =
			getCounterContact();

		String counterContact =
			creativeContactInfoAddBoxCacheModel.counterContact;

		if ((counterContact != null) && (counterContact.length() == 0)) {
			creativeContactInfoAddBoxCacheModel.counterContact = null;
		}

		creativeContactInfoAddBoxCacheModel.CreativeApplicationId =
			getCreativeApplicationId();

		return creativeContactInfoAddBoxCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CreativeContactInfoAddBox, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CreativeContactInfoAddBox, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CreativeContactInfoAddBox, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CreativeContactInfoAddBox)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CreativeContactInfoAddBox>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CreativeContactInfoAddBox.class, ModelWrapper.class);

	}

	private long _creativeContactBoxId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _contactTelephone;
	private String _contactFax;
	private String _contactEmailAddress;
	private String _counterContact;
	private long _CreativeApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<CreativeContactInfoAddBox, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CreativeContactInfoAddBox)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"creativeContactBoxId", _creativeContactBoxId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("contactTelephone", _contactTelephone);
		_columnOriginalValues.put("contactFax", _contactFax);
		_columnOriginalValues.put("contactEmailAddress", _contactEmailAddress);
		_columnOriginalValues.put("counterContact", _counterContact);
		_columnOriginalValues.put(
			"CreativeApplicationId", _CreativeApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("creativeContactBoxId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("contactTelephone", 128L);

		columnBitmasks.put("contactFax", 256L);

		columnBitmasks.put("contactEmailAddress", 512L);

		columnBitmasks.put("counterContact", 1024L);

		columnBitmasks.put("CreativeApplicationId", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CreativeContactInfoAddBox _escapedModel;

}