/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.miic.stages.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MiicCertificateOfIssuance service. Represents a row in the &quot;nbp_miic_certificate_of_issuan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nbp.miic.stages.service.model.impl.MiicCertificateOfIssuanceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nbp.miic.stages.service.model.impl.MiicCertificateOfIssuanceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MiicCertificateOfIssuance
 * @generated
 */
@ProviderType
public interface MiicCertificateOfIssuanceModel
	extends BaseModel<MiicCertificateOfIssuance>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a miic certificate of issuance model instance should use the {@link MiicCertificateOfIssuance} interface instead.
	 */

	/**
	 * Returns the primary key of this miic certificate of issuance.
	 *
	 * @return the primary key of this miic certificate of issuance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this miic certificate of issuance.
	 *
	 * @param primaryKey the primary key of this miic certificate of issuance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the miic certificate of issuance ID of this miic certificate of issuance.
	 *
	 * @return the miic certificate of issuance ID of this miic certificate of issuance
	 */
	public long getMiicCertificateOfIssuanceId();

	/**
	 * Sets the miic certificate of issuance ID of this miic certificate of issuance.
	 *
	 * @param miicCertificateOfIssuanceId the miic certificate of issuance ID of this miic certificate of issuance
	 */
	public void setMiicCertificateOfIssuanceId(
		long miicCertificateOfIssuanceId);

	/**
	 * Returns the group ID of this miic certificate of issuance.
	 *
	 * @return the group ID of this miic certificate of issuance
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this miic certificate of issuance.
	 *
	 * @param groupId the group ID of this miic certificate of issuance
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this miic certificate of issuance.
	 *
	 * @return the company ID of this miic certificate of issuance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this miic certificate of issuance.
	 *
	 * @param companyId the company ID of this miic certificate of issuance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this miic certificate of issuance.
	 *
	 * @return the user ID of this miic certificate of issuance
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this miic certificate of issuance.
	 *
	 * @param userId the user ID of this miic certificate of issuance
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this miic certificate of issuance.
	 *
	 * @return the user uuid of this miic certificate of issuance
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this miic certificate of issuance.
	 *
	 * @param userUuid the user uuid of this miic certificate of issuance
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this miic certificate of issuance.
	 *
	 * @return the user name of this miic certificate of issuance
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this miic certificate of issuance.
	 *
	 * @param userName the user name of this miic certificate of issuance
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this miic certificate of issuance.
	 *
	 * @return the create date of this miic certificate of issuance
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this miic certificate of issuance.
	 *
	 * @param createDate the create date of this miic certificate of issuance
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this miic certificate of issuance.
	 *
	 * @return the modified date of this miic certificate of issuance
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this miic certificate of issuance.
	 *
	 * @param modifiedDate the modified date of this miic certificate of issuance
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the certificate number of this miic certificate of issuance.
	 *
	 * @return the certificate number of this miic certificate of issuance
	 */
	@AutoEscape
	public String getCertificateNumber();

	/**
	 * Sets the certificate number of this miic certificate of issuance.
	 *
	 * @param certificateNumber the certificate number of this miic certificate of issuance
	 */
	public void setCertificateNumber(String certificateNumber);

	/**
	 * Returns the date certificate issued of this miic certificate of issuance.
	 *
	 * @return the date certificate issued of this miic certificate of issuance
	 */
	public Date getDateCertificateIssued();

	/**
	 * Sets the date certificate issued of this miic certificate of issuance.
	 *
	 * @param dateCertificateIssued the date certificate issued of this miic certificate of issuance
	 */
	public void setDateCertificateIssued(Date dateCertificateIssued);

	/**
	 * Returns the date of expiration of this miic certificate of issuance.
	 *
	 * @return the date of expiration of this miic certificate of issuance
	 */
	public Date getDateOfExpiration();

	/**
	 * Sets the date of expiration of this miic certificate of issuance.
	 *
	 * @param dateOfExpiration the date of expiration of this miic certificate of issuance
	 */
	public void setDateOfExpiration(Date dateOfExpiration);

	/**
	 * Returns the document file entry ID of this miic certificate of issuance.
	 *
	 * @return the document file entry ID of this miic certificate of issuance
	 */
	public long getDocumentFileEntryId();

	/**
	 * Sets the document file entry ID of this miic certificate of issuance.
	 *
	 * @param documentFileEntryId the document file entry ID of this miic certificate of issuance
	 */
	public void setDocumentFileEntryId(long documentFileEntryId);

	/**
	 * Returns the case ID of this miic certificate of issuance.
	 *
	 * @return the case ID of this miic certificate of issuance
	 */
	@AutoEscape
	public String getCaseId();

	/**
	 * Sets the case ID of this miic certificate of issuance.
	 *
	 * @param caseId the case ID of this miic certificate of issuance
	 */
	public void setCaseId(String caseId);

	/**
	 * Returns the name of licensed trustee of this miic certificate of issuance.
	 *
	 * @return the name of licensed trustee of this miic certificate of issuance
	 */
	@AutoEscape
	public String getNameOfLicensedTrustee();

	/**
	 * Sets the name of licensed trustee of this miic certificate of issuance.
	 *
	 * @param nameOfLicensedTrustee the name of licensed trustee of this miic certificate of issuance
	 */
	public void setNameOfLicensedTrustee(String nameOfLicensedTrustee);

	@Override
	public MiicCertificateOfIssuance cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}