/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.creative.application.form.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.creative.application.form.service.model.CreativeIndividualDetails;
import com.nbp.creative.application.form.service.service.CreativeIndividualDetailsLocalService;
import com.nbp.creative.application.form.service.service.persistence.CreativeApplicationCurrentStagePersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeApplicationPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeCompanyApplicantInformationPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeCompanyDetailsAddressPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeCompanyDetailsPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeCompanyDirectorInformationAddressPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeCompanyDirectorInformationPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeCompanyEconomicEffectPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeCompanyGeneralInformationPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeContactInfoAddBoxPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeDirectorListinAddBoxPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeIndividualDetailsAddressPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeIndividualDetailsPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeIndividualEconomicEffectPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeIndividualGeneralInformationPersistence;
import com.nbp.creative.application.form.service.service.persistence.CreativeSocialMediaAddBoxPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the creative individual details local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.creative.application.form.service.service.impl.CreativeIndividualDetailsLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.creative.application.form.service.service.impl.CreativeIndividualDetailsLocalServiceImpl
 * @generated
 */
public abstract class CreativeIndividualDetailsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CreativeIndividualDetailsLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CreativeIndividualDetailsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.creative.application.form.service.service.CreativeIndividualDetailsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the creative individual details to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CreativeIndividualDetailsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param creativeIndividualDetails the creative individual details
	 * @return the creative individual details that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CreativeIndividualDetails addCreativeIndividualDetails(
		CreativeIndividualDetails creativeIndividualDetails) {

		creativeIndividualDetails.setNew(true);

		return creativeIndividualDetailsPersistence.update(
			creativeIndividualDetails);
	}

	/**
	 * Creates a new creative individual details with the primary key. Does not add the creative individual details to the database.
	 *
	 * @param creativeIndividualDetailsId the primary key for the new creative individual details
	 * @return the new creative individual details
	 */
	@Override
	@Transactional(enabled = false)
	public CreativeIndividualDetails createCreativeIndividualDetails(
		long creativeIndividualDetailsId) {

		return creativeIndividualDetailsPersistence.create(
			creativeIndividualDetailsId);
	}

	/**
	 * Deletes the creative individual details with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CreativeIndividualDetailsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param creativeIndividualDetailsId the primary key of the creative individual details
	 * @return the creative individual details that was removed
	 * @throws PortalException if a creative individual details with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CreativeIndividualDetails deleteCreativeIndividualDetails(
			long creativeIndividualDetailsId)
		throws PortalException {

		return creativeIndividualDetailsPersistence.remove(
			creativeIndividualDetailsId);
	}

	/**
	 * Deletes the creative individual details from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CreativeIndividualDetailsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param creativeIndividualDetails the creative individual details
	 * @return the creative individual details that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CreativeIndividualDetails deleteCreativeIndividualDetails(
		CreativeIndividualDetails creativeIndividualDetails) {

		return creativeIndividualDetailsPersistence.remove(
			creativeIndividualDetails);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return creativeIndividualDetailsPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CreativeIndividualDetails.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return creativeIndividualDetailsPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.creative.application.form.service.model.impl.CreativeIndividualDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return creativeIndividualDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.creative.application.form.service.model.impl.CreativeIndividualDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return creativeIndividualDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return creativeIndividualDetailsPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return creativeIndividualDetailsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CreativeIndividualDetails fetchCreativeIndividualDetails(
		long creativeIndividualDetailsId) {

		return creativeIndividualDetailsPersistence.fetchByPrimaryKey(
			creativeIndividualDetailsId);
	}

	/**
	 * Returns the creative individual details with the primary key.
	 *
	 * @param creativeIndividualDetailsId the primary key of the creative individual details
	 * @return the creative individual details
	 * @throws PortalException if a creative individual details with the primary key could not be found
	 */
	@Override
	public CreativeIndividualDetails getCreativeIndividualDetails(
			long creativeIndividualDetailsId)
		throws PortalException {

		return creativeIndividualDetailsPersistence.findByPrimaryKey(
			creativeIndividualDetailsId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			creativeIndividualDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CreativeIndividualDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"creativeIndividualDetailsId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			creativeIndividualDetailsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CreativeIndividualDetails.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"creativeIndividualDetailsId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			creativeIndividualDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CreativeIndividualDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"creativeIndividualDetailsId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return creativeIndividualDetailsPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CreativeIndividualDetailsLocalServiceImpl#deleteCreativeIndividualDetails(CreativeIndividualDetails) to avoid orphaned data");
		}

		return creativeIndividualDetailsLocalService.
			deleteCreativeIndividualDetails(
				(CreativeIndividualDetails)persistedModel);
	}

	@Override
	public BasePersistence<CreativeIndividualDetails> getBasePersistence() {
		return creativeIndividualDetailsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return creativeIndividualDetailsPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the creative individual detailses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.creative.application.form.service.model.impl.CreativeIndividualDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of creative individual detailses
	 * @param end the upper bound of the range of creative individual detailses (not inclusive)
	 * @return the range of creative individual detailses
	 */
	@Override
	public List<CreativeIndividualDetails> getCreativeIndividualDetailses(
		int start, int end) {

		return creativeIndividualDetailsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of creative individual detailses.
	 *
	 * @return the number of creative individual detailses
	 */
	@Override
	public int getCreativeIndividualDetailsesCount() {
		return creativeIndividualDetailsPersistence.countAll();
	}

	/**
	 * Updates the creative individual details in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CreativeIndividualDetailsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param creativeIndividualDetails the creative individual details
	 * @return the creative individual details that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CreativeIndividualDetails updateCreativeIndividualDetails(
		CreativeIndividualDetails creativeIndividualDetails) {

		return creativeIndividualDetailsPersistence.update(
			creativeIndividualDetails);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CreativeIndividualDetailsLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		creativeIndividualDetailsLocalService =
			(CreativeIndividualDetailsLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CreativeIndividualDetailsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CreativeIndividualDetails.class;
	}

	protected String getModelClassName() {
		return CreativeIndividualDetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				creativeIndividualDetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected CreativeApplicationPersistence creativeApplicationPersistence;

	@Reference
	protected CreativeApplicationCurrentStagePersistence
		creativeApplicationCurrentStagePersistence;

	@Reference
	protected CreativeCompanyApplicantInformationPersistence
		creativeCompanyApplicantInformationPersistence;

	@Reference
	protected CreativeCompanyDetailsPersistence
		creativeCompanyDetailsPersistence;

	@Reference
	protected CreativeCompanyDetailsAddressPersistence
		creativeCompanyDetailsAddressPersistence;

	@Reference
	protected CreativeCompanyDirectorInformationPersistence
		creativeCompanyDirectorInformationPersistence;

	@Reference
	protected CreativeCompanyDirectorInformationAddressPersistence
		creativeCompanyDirectorInformationAddressPersistence;

	@Reference
	protected CreativeCompanyEconomicEffectPersistence
		creativeCompanyEconomicEffectPersistence;

	@Reference
	protected CreativeCompanyGeneralInformationPersistence
		creativeCompanyGeneralInformationPersistence;

	@Reference
	protected CreativeContactInfoAddBoxPersistence
		creativeContactInfoAddBoxPersistence;

	@Reference
	protected CreativeDirectorListinAddBoxPersistence
		creativeDirectorListinAddBoxPersistence;

	protected CreativeIndividualDetailsLocalService
		creativeIndividualDetailsLocalService;

	@Reference
	protected CreativeIndividualDetailsPersistence
		creativeIndividualDetailsPersistence;

	@Reference
	protected CreativeIndividualDetailsAddressPersistence
		creativeIndividualDetailsAddressPersistence;

	@Reference
	protected CreativeIndividualEconomicEffectPersistence
		creativeIndividualEconomicEffectPersistence;

	@Reference
	protected CreativeIndividualGeneralInformationPersistence
		creativeIndividualGeneralInformationPersistence;

	@Reference
	protected CreativeSocialMediaAddBoxPersistence
		creativeSocialMediaAddBoxPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CreativeIndividualDetailsLocalServiceBaseImpl.class);

}