<%@ include file="../init.jsp" %>
<script>
function activeSelectForm(){
	$(".laboratories-medical .tab-pane, .laboratories-testing .tab-pane, .laboratories-calibration .tab-pane, .laboratories-analyses .tab-pane").removeClass("active");
	$(".laboratories-medical .nav-link, .laboratories-testing .nav-link, .laboratories-calibration .nav-link, .laboratories-analyses .nav-link").removeClass("active");
	$(".certification-management .tab-pane, .certification-product .tab-pane, .certification-bodies .tab-pane").removeClass("active");
	$(".certification-management .nav-link, .certification-product .nav-link, .certification-bodies .nav-link").removeClass("active");
	$(".inspection-bodies .tab-pane").removeClass("active");
	$(".inspection-bodies .nav-link").removeClass("active");
	$(".third-party-cer .tab-pane").removeClass("active");
	$(".third-party-cer .nav-link").removeClass("active");
	accreditationType = $("#accreditationTypeVal").val();
	if(accreditationType == "Accreditation for Labs"){
		laboratoriesAccreditation = $("#laboratoriesAccreditationVal").val();
		if(laboratoriesAccreditation == "Accreditation of Medical Labs to the ISO 15189 Standard"){
			$(".laboratories-medical .tab-pane:first").addClass("active");
			$(".laboratories-medical .nav-link:first").addClass("active");
			$(".laboratories-medical .nav-link:first").removeClass("disabled");
		}else if(laboratoriesAccreditation == "Accreditation of Testing Labs to the ISO/IEC 17025 Standard"){
			$(".laboratories-testing .tab-pane:first").addClass("active");
			$(".laboratories-testing .nav-link:first").addClass("active");
			$(".laboratories-testing .nav-link:first").removeClass("disabled");
		}else if(laboratoriesAccreditation == "Accreditation of Calibration Labs to the ISO/IEC 17025 Standard"){
			$(".laboratories-calibration .tab-pane:first").addClass("active");
			$(".laboratories-calibration .nav-link:first").addClass("active");
			$(".laboratories-calibration .nav-link:first").removeClass("disabled");
		}
	}else if(accreditationType == "Accreditation for Certification Bodies"){
		certificationAccreditation = $("#certificationAccreditationVal").val();
		if(certificationAccreditation == "Accreditation of Certification Bodies to the ISO/IEC 17021-1 Standard"){
			$(".certification-management .tab-pane:first").addClass("active");
			$(".certification-management .nav-link:first").addClass("active");
			$(".certification-management .nav-link:first").removeClass("disabled");
		}else if(certificationAccreditation == "Accreditation of Certification Bodies to the ISO/IEC 17065 Standard"){
			$(".certification-product .tab-pane:first").addClass("active");
			$(".certification-product .nav-link:first").addClass("active");
			$(".certification-product .nav-link:first").removeClass("disabled");
		}else if(certificationAccreditation == "Accreditation of Certification Bodies to the ISO/IEC 17024 Standard"){
			$(".certification-bodies .tab-pane:first").addClass("active");
			$(".certification-bodies .nav-link:first").addClass("active");
			$(".certification-bodies .nav-link:first").removeClass("disabled");
		}  
	}else if(accreditationType == "Accreditation for Inspection Bodies"){
		$(".inspection-bodies .tab-pane:first").addClass("active");
		$(".inspection-bodies .nav-link:first").addClass("active");
		$(".inspection-bodies .nav-link:first").removeClass("disabled");
	}else if(accreditationType == "FDA Approvals"){
		thirdPartyAccreditation = $("#thirdPartyAccreditationVal").val();
		if(thirdPartyAccreditation == "FDA TPP Accreditation of 3rd Party Certification Bodies Under the FDA-Food Safety Modernisation Act (FSMA)"){
			$(".third-party-cer .tab-pane:first").addClass("active");
			$(".third-party-cer .nav-link:first").addClass("active");
			$(".third-party-cer .nav-link:first").removeClass("disabled");
		}else if(thirdPartyAccreditation == "FDA Labs Accreditation for Analyses of Foods to (LAAF) Accreditation Scheme"){
			$(".laboratories-analyses .tab-pane:first").addClass("active");
			$(".laboratories-analyses .nav-link:first").addClass("active");
			$(".laboratories-analyses .nav-link:first").removeClass("disabled");
		}
	}
	$(".form-preview-nav .nav-link").removeClass("disabled");
}
$("#medical-applicantion-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#medical-applicantion-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#medical-activity-desc-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#medical-activity-desc-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#medical-org-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#medical-org-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#human-resources-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#human-resources-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#medical-physical-res-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#medical-physical-res-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#medical-manag-sys-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#medical-manag-sys-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#medical-other-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#medical-other-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#testing-applicantion-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#testing-applicantion-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#testing-activity-desc-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#testing-activity-desc-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#testing-structural-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#testing-structural-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#testing-resource-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#testing-resource-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#testing-manage-sys-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#testing-manage-sys-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#testing-other-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#testing-other-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});

$("#calibration-applicantion-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#calibration-applicantion-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#calibration-activity-desc-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#calibration-activity-desc-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#calibration-structural-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#calibration-structural-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#calibration-resource-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#calibration-resource-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#calibration-manage-sys-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#calibration-manage-sys-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#calibration-other-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#calibration-other-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#manage-applicantion-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#manage-applicantion-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#manage-general-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#manage-general-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#manage-scope-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#manage-scope-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#manage-personal-res-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#manage-personal-res-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#manage-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#manage-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#manage-management-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#manage-management-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#manage-other-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#manage-other-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});

$("#cer-product-app-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#cer-product-app-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#general-pro-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#general-pro-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#scope-pro-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#scope-pro-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#personal-res-pro-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#personal-res-pro-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#information-pro-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#information-pro-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#management-pro-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#management-pro-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#other-req-pro-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#other-req-pro-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#cer-bodies-app-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#cer-bodies-app-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#general-bodies-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#general-bodies-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#scope-bodies-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#scope-bodies-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#personal-res-bodies-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#personal-res-bodies-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#information-bodies-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#information-bodies-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#management-bodies-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#management-bodies-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#other-req-bodies-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#other-req-bodies-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});

$("#inspection-applicantion-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#inspection-applicantion-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#inspection-org-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#inspection-org-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#human-inspection-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#human-inspection-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#inspection-physical-res-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#inspection-physical-res-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#inspection-manage-sys-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#inspection-manage-sys-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#inspection-other-requirements-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#inspection-other-requirements-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#third-party-app-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#third-party-app-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#general-third-party-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#general-third-party-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#third-party-scope-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#third-party-scope-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#third-party-personal-res-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#third-party-personal-res-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#third-party-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#third-party-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#third-party-management-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#third-party-management-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});
$("#third-party-other-req-info-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacFormsFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$("#third-party-other-req-info-tab").trigger("click");
	$(".form-section").addClass("active");
	$(".rm, .form-section").removeClass("activated");
	$(".last-step").removeClass("activated");
	$(".last-step").removeClass("active");
	scrollToPageTop();
});

$("#supporting-doc-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacSupportingDocumentFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$(".supporting-documents").addClass("active");
	$(".rm, .supporting-documents").removeClass("activated");
	$(".last-step").removeClass("activated");
    $(".last-step").removeClass("active");
    scrollToPageTop();
});
$("#fee-payment-edit-tab").click(function(){
	$('#janaacFormPreviewFieldset').removeClass("show");
	$('#janaacfeePaymentFieldset').addClass("show", "400");
	$(".form-wizard-next-btn ").show();
	$(".form-wizard-save-btn").show();
	$(".final-submit").addClass("hide");
	$(".final-submit-container").addClass("hide");
	$(".fee-payment").addClass("active");
	$(".fp, .fee-payment").removeClass("activated");
	$(".last-step").removeClass("activated");
    $(".last-step").removeClass("active");
    scrollToPageTop();
});
</script>