/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.jadsc.application.form.service.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.jadsc.application.form.service.model.JADSCCertificateOfServiceAddForm;
import com.nbp.jadsc.application.form.service.service.JADSCCertificateOfServiceAddFormLocalService;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCApplicationPersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCCertificateOfServiceAddFormPersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCCertificateOfServicePersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCCertificateOfVeracityPersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCChecklistAddPersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCChecklistPersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCCurrentStagePersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCInformationRequestPersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCNoticeOfAppearancePersistence;
import com.nbp.jadsc.application.form.service.service.persistence.JADSCOathRequestPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the jadsc certificate of service add form local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.jadsc.application.form.service.service.impl.JADSCCertificateOfServiceAddFormLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.jadsc.application.form.service.service.impl.JADSCCertificateOfServiceAddFormLocalServiceImpl
 * @generated
 */
public abstract class JADSCCertificateOfServiceAddFormLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   JADSCCertificateOfServiceAddFormLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>JADSCCertificateOfServiceAddFormLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.jadsc.application.form.service.service.JADSCCertificateOfServiceAddFormLocalServiceUtil</code>.
	 */

	/**
	 * Adds the jadsc certificate of service add form to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect JADSCCertificateOfServiceAddFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param jadscCertificateOfServiceAddForm the jadsc certificate of service add form
	 * @return the jadsc certificate of service add form that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public JADSCCertificateOfServiceAddForm addJADSCCertificateOfServiceAddForm(
		JADSCCertificateOfServiceAddForm jadscCertificateOfServiceAddForm) {

		jadscCertificateOfServiceAddForm.setNew(true);

		return jadscCertificateOfServiceAddFormPersistence.update(
			jadscCertificateOfServiceAddForm);
	}

	/**
	 * Creates a new jadsc certificate of service add form with the primary key. Does not add the jadsc certificate of service add form to the database.
	 *
	 * @param jadscCOSId the primary key for the new jadsc certificate of service add form
	 * @return the new jadsc certificate of service add form
	 */
	@Override
	@Transactional(enabled = false)
	public JADSCCertificateOfServiceAddForm
		createJADSCCertificateOfServiceAddForm(long jadscCOSId) {

		return jadscCertificateOfServiceAddFormPersistence.create(jadscCOSId);
	}

	/**
	 * Deletes the jadsc certificate of service add form with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect JADSCCertificateOfServiceAddFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param jadscCOSId the primary key of the jadsc certificate of service add form
	 * @return the jadsc certificate of service add form that was removed
	 * @throws PortalException if a jadsc certificate of service add form with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public JADSCCertificateOfServiceAddForm
			deleteJADSCCertificateOfServiceAddForm(long jadscCOSId)
		throws PortalException {

		return jadscCertificateOfServiceAddFormPersistence.remove(jadscCOSId);
	}

	/**
	 * Deletes the jadsc certificate of service add form from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect JADSCCertificateOfServiceAddFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param jadscCertificateOfServiceAddForm the jadsc certificate of service add form
	 * @return the jadsc certificate of service add form that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public JADSCCertificateOfServiceAddForm
		deleteJADSCCertificateOfServiceAddForm(
			JADSCCertificateOfServiceAddForm jadscCertificateOfServiceAddForm) {

		return jadscCertificateOfServiceAddFormPersistence.remove(
			jadscCertificateOfServiceAddForm);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return jadscCertificateOfServiceAddFormPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			JADSCCertificateOfServiceAddForm.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return jadscCertificateOfServiceAddFormPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.jadsc.application.form.service.model.impl.JADSCCertificateOfServiceAddFormModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return jadscCertificateOfServiceAddFormPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.jadsc.application.form.service.model.impl.JADSCCertificateOfServiceAddFormModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return jadscCertificateOfServiceAddFormPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return jadscCertificateOfServiceAddFormPersistence.
			countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return jadscCertificateOfServiceAddFormPersistence.
			countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public JADSCCertificateOfServiceAddForm
		fetchJADSCCertificateOfServiceAddForm(long jadscCOSId) {

		return jadscCertificateOfServiceAddFormPersistence.fetchByPrimaryKey(
			jadscCOSId);
	}

	/**
	 * Returns the jadsc certificate of service add form matching the UUID and group.
	 *
	 * @param uuid the jadsc certificate of service add form's UUID
	 * @param groupId the primary key of the group
	 * @return the matching jadsc certificate of service add form, or <code>null</code> if a matching jadsc certificate of service add form could not be found
	 */
	@Override
	public JADSCCertificateOfServiceAddForm
		fetchJADSCCertificateOfServiceAddFormByUuidAndGroupId(
			String uuid, long groupId) {

		return jadscCertificateOfServiceAddFormPersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the jadsc certificate of service add form with the primary key.
	 *
	 * @param jadscCOSId the primary key of the jadsc certificate of service add form
	 * @return the jadsc certificate of service add form
	 * @throws PortalException if a jadsc certificate of service add form with the primary key could not be found
	 */
	@Override
	public JADSCCertificateOfServiceAddForm getJADSCCertificateOfServiceAddForm(
			long jadscCOSId)
		throws PortalException {

		return jadscCertificateOfServiceAddFormPersistence.findByPrimaryKey(
			jadscCOSId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			jadscCertificateOfServiceAddFormLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			JADSCCertificateOfServiceAddForm.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("jadscCOSId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			jadscCertificateOfServiceAddFormLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			JADSCCertificateOfServiceAddForm.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("jadscCOSId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			jadscCertificateOfServiceAddFormLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			JADSCCertificateOfServiceAddForm.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("jadscCOSId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<JADSCCertificateOfServiceAddForm>() {

				@Override
				public void performAction(
						JADSCCertificateOfServiceAddForm
							jadscCertificateOfServiceAddForm)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, jadscCertificateOfServiceAddForm);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					JADSCCertificateOfServiceAddForm.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return jadscCertificateOfServiceAddFormPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement JADSCCertificateOfServiceAddFormLocalServiceImpl#deleteJADSCCertificateOfServiceAddForm(JADSCCertificateOfServiceAddForm) to avoid orphaned data");
		}

		return jadscCertificateOfServiceAddFormLocalService.
			deleteJADSCCertificateOfServiceAddForm(
				(JADSCCertificateOfServiceAddForm)persistedModel);
	}

	@Override
	public BasePersistence<JADSCCertificateOfServiceAddForm>
		getBasePersistence() {

		return jadscCertificateOfServiceAddFormPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return jadscCertificateOfServiceAddFormPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the jadsc certificate of service add forms matching the UUID and company.
	 *
	 * @param uuid the UUID of the jadsc certificate of service add forms
	 * @param companyId the primary key of the company
	 * @return the matching jadsc certificate of service add forms, or an empty list if no matches were found
	 */
	@Override
	public List<JADSCCertificateOfServiceAddForm>
		getJADSCCertificateOfServiceAddFormsByUuidAndCompanyId(
			String uuid, long companyId) {

		return jadscCertificateOfServiceAddFormPersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of jadsc certificate of service add forms matching the UUID and company.
	 *
	 * @param uuid the UUID of the jadsc certificate of service add forms
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of jadsc certificate of service add forms
	 * @param end the upper bound of the range of jadsc certificate of service add forms (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching jadsc certificate of service add forms, or an empty list if no matches were found
	 */
	@Override
	public List<JADSCCertificateOfServiceAddForm>
		getJADSCCertificateOfServiceAddFormsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<JADSCCertificateOfServiceAddForm>
				orderByComparator) {

		return jadscCertificateOfServiceAddFormPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the jadsc certificate of service add form matching the UUID and group.
	 *
	 * @param uuid the jadsc certificate of service add form's UUID
	 * @param groupId the primary key of the group
	 * @return the matching jadsc certificate of service add form
	 * @throws PortalException if a matching jadsc certificate of service add form could not be found
	 */
	@Override
	public JADSCCertificateOfServiceAddForm
			getJADSCCertificateOfServiceAddFormByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return jadscCertificateOfServiceAddFormPersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the jadsc certificate of service add forms.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.jadsc.application.form.service.model.impl.JADSCCertificateOfServiceAddFormModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of jadsc certificate of service add forms
	 * @param end the upper bound of the range of jadsc certificate of service add forms (not inclusive)
	 * @return the range of jadsc certificate of service add forms
	 */
	@Override
	public List<JADSCCertificateOfServiceAddForm>
		getJADSCCertificateOfServiceAddForms(int start, int end) {

		return jadscCertificateOfServiceAddFormPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of jadsc certificate of service add forms.
	 *
	 * @return the number of jadsc certificate of service add forms
	 */
	@Override
	public int getJADSCCertificateOfServiceAddFormsCount() {
		return jadscCertificateOfServiceAddFormPersistence.countAll();
	}

	/**
	 * Updates the jadsc certificate of service add form in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect JADSCCertificateOfServiceAddFormLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param jadscCertificateOfServiceAddForm the jadsc certificate of service add form
	 * @return the jadsc certificate of service add form that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public JADSCCertificateOfServiceAddForm
		updateJADSCCertificateOfServiceAddForm(
			JADSCCertificateOfServiceAddForm jadscCertificateOfServiceAddForm) {

		return jadscCertificateOfServiceAddFormPersistence.update(
			jadscCertificateOfServiceAddForm);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			JADSCCertificateOfServiceAddFormLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		jadscCertificateOfServiceAddFormLocalService =
			(JADSCCertificateOfServiceAddFormLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return JADSCCertificateOfServiceAddFormLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return JADSCCertificateOfServiceAddForm.class;
	}

	protected String getModelClassName() {
		return JADSCCertificateOfServiceAddForm.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				jadscCertificateOfServiceAddFormPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected JADSCApplicationPersistence jadscApplicationPersistence;

	@Reference
	protected JADSCCertificateOfServicePersistence
		jadscCertificateOfServicePersistence;

	protected JADSCCertificateOfServiceAddFormLocalService
		jadscCertificateOfServiceAddFormLocalService;

	@Reference
	protected JADSCCertificateOfServiceAddFormPersistence
		jadscCertificateOfServiceAddFormPersistence;

	@Reference
	protected JADSCCertificateOfVeracityPersistence
		jadscCertificateOfVeracityPersistence;

	@Reference
	protected JADSCChecklistPersistence jadscChecklistPersistence;

	@Reference
	protected JADSCChecklistAddPersistence jadscChecklistAddPersistence;

	@Reference
	protected JADSCCurrentStagePersistence jadscCurrentStagePersistence;

	@Reference
	protected JADSCInformationRequestPersistence
		jadscInformationRequestPersistence;

	@Reference
	protected JADSCNoticeOfAppearancePersistence
		jadscNoticeOfAppearancePersistence;

	@Reference
	protected JADSCOathRequestPersistence jadscOathRequestPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		JADSCCertificateOfServiceAddFormLocalServiceBaseImpl.class);

}