/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.osi.stages.services.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.osi.stages.services.model.OsiDeskVerification;
import com.nbp.osi.stages.services.service.OsiDeskVerificationService;
import com.nbp.osi.stages.services.service.persistence.OsiApplicationPermitPersistence;
import com.nbp.osi.stages.services.service.persistence.OsiApplicationStagesPersistence;
import com.nbp.osi.stages.services.service.persistence.OsiDeskVerificationPersistence;
import com.nbp.osi.stages.services.service.persistence.OsiInspectionPersistence;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the osi desk verification remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.osi.stages.services.service.impl.OsiDeskVerificationServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.osi.stages.services.service.impl.OsiDeskVerificationServiceImpl
 * @generated
 */
public abstract class OsiDeskVerificationServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, OsiDeskVerificationService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>OsiDeskVerificationService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.osi.stages.services.service.OsiDeskVerificationServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			OsiDeskVerificationService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		osiDeskVerificationService = (OsiDeskVerificationService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return OsiDeskVerificationService.class.getName();
	}

	protected Class<?> getModelClass() {
		return OsiDeskVerification.class;
	}

	protected String getModelClassName() {
		return OsiDeskVerification.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				osiDeskVerificationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected OsiApplicationPermitPersistence osiApplicationPermitPersistence;

	@Reference
	protected OsiApplicationStagesPersistence osiApplicationStagesPersistence;

	@Reference
	protected
		com.nbp.osi.stages.services.service.OsiDeskVerificationLocalService
			osiDeskVerificationLocalService;

	protected OsiDeskVerificationService osiDeskVerificationService;

	@Reference
	protected OsiDeskVerificationPersistence osiDeskVerificationPersistence;

	@Reference
	protected OsiInspectionPersistence osiInspectionPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		OsiDeskVerificationServiceBaseImpl.class);

}