/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.factories.registration.application.form.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.factories.registration.application.form.services.model.FactoriesApplicationRegistration;
import com.nbp.factories.registration.application.form.services.model.FactoriesApplicationRegistrationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FactoriesApplicationRegistration service. Represents a row in the &quot;nbp_factories_application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FactoriesApplicationRegistrationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FactoriesApplicationRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FactoriesApplicationRegistrationImpl
 * @generated
 */
@JSON(strict = true)
public class FactoriesApplicationRegistrationModelImpl
	extends BaseModelImpl<FactoriesApplicationRegistration>
	implements FactoriesApplicationRegistrationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a factories application registration model instance should use the <code>FactoriesApplicationRegistration</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_factories_application";

	public static final Object[][] TABLE_COLUMNS = {
		{"factoriesApplicationId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"entityId", Types.VARCHAR},
		{"status", Types.INTEGER}, {"applicationNumber", Types.VARCHAR},
		{"caseId", Types.VARCHAR}, {"expiredLicenseAppNumber", Types.VARCHAR},
		{"icmDocumentPath", Types.VARCHAR}, {"productCategory", Types.VARCHAR},
		{"areYouProcessing", Types.VARCHAR},
		{"typeOfTransaction", Types.VARCHAR}, {"pdfFileEntryId", Types.BIGINT},
		{"appCurrentStageName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("factoriesApplicationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("entityId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("applicationNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("caseId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("expiredLicenseAppNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("icmDocumentPath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productCategory", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("areYouProcessing", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("typeOfTransaction", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pdfFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appCurrentStageName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_factories_application (factoriesApplicationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,entityId VARCHAR(75) null,status INTEGER,applicationNumber VARCHAR(75) null,caseId VARCHAR(500) null,expiredLicenseAppNumber VARCHAR(75) null,icmDocumentPath VARCHAR(500) null,productCategory VARCHAR(1000) null,areYouProcessing VARCHAR(75) null,typeOfTransaction VARCHAR(75) null,pdfFileEntryId LONG,appCurrentStageName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_factories_application";

	public static final String ORDER_BY_JPQL =
		" ORDER BY factoriesApplicationRegistration.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_factories_application.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPLICATIONNUMBER_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CASEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPIREDLICENSEAPPNUMBER_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACTORIESAPPLICATIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPEOFTRANSACTION_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FactoriesApplicationRegistrationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _factoriesApplicationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFactoriesApplicationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _factoriesApplicationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FactoriesApplicationRegistration.class;
	}

	@Override
	public String getModelClassName() {
		return FactoriesApplicationRegistration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FactoriesApplicationRegistration, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String, Function<FactoriesApplicationRegistration, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FactoriesApplicationRegistration, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(FactoriesApplicationRegistration)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FactoriesApplicationRegistration, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FactoriesApplicationRegistration, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FactoriesApplicationRegistration)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FactoriesApplicationRegistration, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FactoriesApplicationRegistration, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<FactoriesApplicationRegistration, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<FactoriesApplicationRegistration, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<FactoriesApplicationRegistration, Object>>();

			attributeGetterFunctions.put(
				"factoriesApplicationId",
				FactoriesApplicationRegistration::getFactoriesApplicationId);
			attributeGetterFunctions.put(
				"groupId", FactoriesApplicationRegistration::getGroupId);
			attributeGetterFunctions.put(
				"companyId", FactoriesApplicationRegistration::getCompanyId);
			attributeGetterFunctions.put(
				"userId", FactoriesApplicationRegistration::getUserId);
			attributeGetterFunctions.put(
				"userName", FactoriesApplicationRegistration::getUserName);
			attributeGetterFunctions.put(
				"createDate", FactoriesApplicationRegistration::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate",
				FactoriesApplicationRegistration::getModifiedDate);
			attributeGetterFunctions.put(
				"entityId", FactoriesApplicationRegistration::getEntityId);
			attributeGetterFunctions.put(
				"status", FactoriesApplicationRegistration::getStatus);
			attributeGetterFunctions.put(
				"applicationNumber",
				FactoriesApplicationRegistration::getApplicationNumber);
			attributeGetterFunctions.put(
				"caseId", FactoriesApplicationRegistration::getCaseId);
			attributeGetterFunctions.put(
				"expiredLicenseAppNumber",
				FactoriesApplicationRegistration::getExpiredLicenseAppNumber);
			attributeGetterFunctions.put(
				"icmDocumentPath",
				FactoriesApplicationRegistration::getIcmDocumentPath);
			attributeGetterFunctions.put(
				"productCategory",
				FactoriesApplicationRegistration::getProductCategory);
			attributeGetterFunctions.put(
				"areYouProcessing",
				FactoriesApplicationRegistration::getAreYouProcessing);
			attributeGetterFunctions.put(
				"typeOfTransaction",
				FactoriesApplicationRegistration::getTypeOfTransaction);
			attributeGetterFunctions.put(
				"pdfFileEntryId",
				FactoriesApplicationRegistration::getPdfFileEntryId);
			attributeGetterFunctions.put(
				"appCurrentStageName",
				FactoriesApplicationRegistration::getAppCurrentStageName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<FactoriesApplicationRegistration, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FactoriesApplicationRegistration, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String,
						 BiConsumer<FactoriesApplicationRegistration, ?>>();

			attributeSetterBiConsumers.put(
				"factoriesApplicationId",
				(BiConsumer<FactoriesApplicationRegistration, Long>)
					FactoriesApplicationRegistration::
						setFactoriesApplicationId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<FactoriesApplicationRegistration, Long>)
					FactoriesApplicationRegistration::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<FactoriesApplicationRegistration, Long>)
					FactoriesApplicationRegistration::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<FactoriesApplicationRegistration, Long>)
					FactoriesApplicationRegistration::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<FactoriesApplicationRegistration, Date>)
					FactoriesApplicationRegistration::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<FactoriesApplicationRegistration, Date>)
					FactoriesApplicationRegistration::setModifiedDate);
			attributeSetterBiConsumers.put(
				"entityId",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setEntityId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<FactoriesApplicationRegistration, Integer>)
					FactoriesApplicationRegistration::setStatus);
			attributeSetterBiConsumers.put(
				"applicationNumber",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setApplicationNumber);
			attributeSetterBiConsumers.put(
				"caseId",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setCaseId);
			attributeSetterBiConsumers.put(
				"expiredLicenseAppNumber",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::
						setExpiredLicenseAppNumber);
			attributeSetterBiConsumers.put(
				"icmDocumentPath",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setIcmDocumentPath);
			attributeSetterBiConsumers.put(
				"productCategory",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setProductCategory);
			attributeSetterBiConsumers.put(
				"areYouProcessing",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setAreYouProcessing);
			attributeSetterBiConsumers.put(
				"typeOfTransaction",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setTypeOfTransaction);
			attributeSetterBiConsumers.put(
				"pdfFileEntryId",
				(BiConsumer<FactoriesApplicationRegistration, Long>)
					FactoriesApplicationRegistration::setPdfFileEntryId);
			attributeSetterBiConsumers.put(
				"appCurrentStageName",
				(BiConsumer<FactoriesApplicationRegistration, String>)
					FactoriesApplicationRegistration::setAppCurrentStageName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getFactoriesApplicationId() {
		return _factoriesApplicationId;
	}

	@Override
	public void setFactoriesApplicationId(long factoriesApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_factoriesApplicationId = factoriesApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFactoriesApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("factoriesApplicationId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getEntityId() {
		if (_entityId == null) {
			return "";
		}
		else {
			return _entityId;
		}
	}

	@Override
	public void setEntityId(String entityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityId = entityId;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public String getApplicationNumber() {
		if (_applicationNumber == null) {
			return "";
		}
		else {
			return _applicationNumber;
		}
	}

	@Override
	public void setApplicationNumber(String applicationNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_applicationNumber = applicationNumber;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalApplicationNumber() {
		return getColumnOriginalValue("applicationNumber");
	}

	@JSON
	@Override
	public String getCaseId() {
		if (_caseId == null) {
			return "";
		}
		else {
			return _caseId;
		}
	}

	@Override
	public void setCaseId(String caseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_caseId = caseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCaseId() {
		return getColumnOriginalValue("caseId");
	}

	@JSON
	@Override
	public String getExpiredLicenseAppNumber() {
		if (_expiredLicenseAppNumber == null) {
			return "";
		}
		else {
			return _expiredLicenseAppNumber;
		}
	}

	@Override
	public void setExpiredLicenseAppNumber(String expiredLicenseAppNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expiredLicenseAppNumber = expiredLicenseAppNumber;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExpiredLicenseAppNumber() {
		return getColumnOriginalValue("expiredLicenseAppNumber");
	}

	@JSON
	@Override
	public String getIcmDocumentPath() {
		if (_icmDocumentPath == null) {
			return "";
		}
		else {
			return _icmDocumentPath;
		}
	}

	@Override
	public void setIcmDocumentPath(String icmDocumentPath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_icmDocumentPath = icmDocumentPath;
	}

	@JSON
	@Override
	public String getProductCategory() {
		if (_productCategory == null) {
			return "";
		}
		else {
			return _productCategory;
		}
	}

	@Override
	public void setProductCategory(String productCategory) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productCategory = productCategory;
	}

	@JSON
	@Override
	public String getAreYouProcessing() {
		if (_areYouProcessing == null) {
			return "";
		}
		else {
			return _areYouProcessing;
		}
	}

	@Override
	public void setAreYouProcessing(String areYouProcessing) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_areYouProcessing = areYouProcessing;
	}

	@JSON
	@Override
	public String getTypeOfTransaction() {
		if (_typeOfTransaction == null) {
			return "";
		}
		else {
			return _typeOfTransaction;
		}
	}

	@Override
	public void setTypeOfTransaction(String typeOfTransaction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typeOfTransaction = typeOfTransaction;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTypeOfTransaction() {
		return getColumnOriginalValue("typeOfTransaction");
	}

	@JSON
	@Override
	public long getPdfFileEntryId() {
		return _pdfFileEntryId;
	}

	@Override
	public void setPdfFileEntryId(long pdfFileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pdfFileEntryId = pdfFileEntryId;
	}

	@JSON
	@Override
	public String getAppCurrentStageName() {
		if (_appCurrentStageName == null) {
			return "";
		}
		else {
			return _appCurrentStageName;
		}
	}

	@Override
	public void setAppCurrentStageName(String appCurrentStageName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appCurrentStageName = appCurrentStageName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FactoriesApplicationRegistration.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FactoriesApplicationRegistration toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FactoriesApplicationRegistration>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FactoriesApplicationRegistrationImpl
			factoriesApplicationRegistrationImpl =
				new FactoriesApplicationRegistrationImpl();

		factoriesApplicationRegistrationImpl.setFactoriesApplicationId(
			getFactoriesApplicationId());
		factoriesApplicationRegistrationImpl.setGroupId(getGroupId());
		factoriesApplicationRegistrationImpl.setCompanyId(getCompanyId());
		factoriesApplicationRegistrationImpl.setUserId(getUserId());
		factoriesApplicationRegistrationImpl.setUserName(getUserName());
		factoriesApplicationRegistrationImpl.setCreateDate(getCreateDate());
		factoriesApplicationRegistrationImpl.setModifiedDate(getModifiedDate());
		factoriesApplicationRegistrationImpl.setEntityId(getEntityId());
		factoriesApplicationRegistrationImpl.setStatus(getStatus());
		factoriesApplicationRegistrationImpl.setApplicationNumber(
			getApplicationNumber());
		factoriesApplicationRegistrationImpl.setCaseId(getCaseId());
		factoriesApplicationRegistrationImpl.setExpiredLicenseAppNumber(
			getExpiredLicenseAppNumber());
		factoriesApplicationRegistrationImpl.setIcmDocumentPath(
			getIcmDocumentPath());
		factoriesApplicationRegistrationImpl.setProductCategory(
			getProductCategory());
		factoriesApplicationRegistrationImpl.setAreYouProcessing(
			getAreYouProcessing());
		factoriesApplicationRegistrationImpl.setTypeOfTransaction(
			getTypeOfTransaction());
		factoriesApplicationRegistrationImpl.setPdfFileEntryId(
			getPdfFileEntryId());
		factoriesApplicationRegistrationImpl.setAppCurrentStageName(
			getAppCurrentStageName());

		factoriesApplicationRegistrationImpl.resetOriginalValues();

		return factoriesApplicationRegistrationImpl;
	}

	@Override
	public FactoriesApplicationRegistration cloneWithOriginalValues() {
		FactoriesApplicationRegistrationImpl
			factoriesApplicationRegistrationImpl =
				new FactoriesApplicationRegistrationImpl();

		factoriesApplicationRegistrationImpl.setFactoriesApplicationId(
			this.<Long>getColumnOriginalValue("factoriesApplicationId"));
		factoriesApplicationRegistrationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		factoriesApplicationRegistrationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		factoriesApplicationRegistrationImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		factoriesApplicationRegistrationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		factoriesApplicationRegistrationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		factoriesApplicationRegistrationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		factoriesApplicationRegistrationImpl.setEntityId(
			this.<String>getColumnOriginalValue("entityId"));
		factoriesApplicationRegistrationImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		factoriesApplicationRegistrationImpl.setApplicationNumber(
			this.<String>getColumnOriginalValue("applicationNumber"));
		factoriesApplicationRegistrationImpl.setCaseId(
			this.<String>getColumnOriginalValue("caseId"));
		factoriesApplicationRegistrationImpl.setExpiredLicenseAppNumber(
			this.<String>getColumnOriginalValue("expiredLicenseAppNumber"));
		factoriesApplicationRegistrationImpl.setIcmDocumentPath(
			this.<String>getColumnOriginalValue("icmDocumentPath"));
		factoriesApplicationRegistrationImpl.setProductCategory(
			this.<String>getColumnOriginalValue("productCategory"));
		factoriesApplicationRegistrationImpl.setAreYouProcessing(
			this.<String>getColumnOriginalValue("areYouProcessing"));
		factoriesApplicationRegistrationImpl.setTypeOfTransaction(
			this.<String>getColumnOriginalValue("typeOfTransaction"));
		factoriesApplicationRegistrationImpl.setPdfFileEntryId(
			this.<Long>getColumnOriginalValue("pdfFileEntryId"));
		factoriesApplicationRegistrationImpl.setAppCurrentStageName(
			this.<String>getColumnOriginalValue("appCurrentStageName"));

		return factoriesApplicationRegistrationImpl;
	}

	@Override
	public int compareTo(
		FactoriesApplicationRegistration factoriesApplicationRegistration) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), factoriesApplicationRegistration.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FactoriesApplicationRegistration)) {
			return false;
		}

		FactoriesApplicationRegistration factoriesApplicationRegistration =
			(FactoriesApplicationRegistration)object;

		long primaryKey = factoriesApplicationRegistration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FactoriesApplicationRegistration> toCacheModel() {
		FactoriesApplicationRegistrationCacheModel
			factoriesApplicationRegistrationCacheModel =
				new FactoriesApplicationRegistrationCacheModel();

		factoriesApplicationRegistrationCacheModel.factoriesApplicationId =
			getFactoriesApplicationId();

		factoriesApplicationRegistrationCacheModel.groupId = getGroupId();

		factoriesApplicationRegistrationCacheModel.companyId = getCompanyId();

		factoriesApplicationRegistrationCacheModel.userId = getUserId();

		factoriesApplicationRegistrationCacheModel.userName = getUserName();

		String userName = factoriesApplicationRegistrationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			factoriesApplicationRegistrationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			factoriesApplicationRegistrationCacheModel.createDate =
				createDate.getTime();
		}
		else {
			factoriesApplicationRegistrationCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			factoriesApplicationRegistrationCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			factoriesApplicationRegistrationCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		factoriesApplicationRegistrationCacheModel.entityId = getEntityId();

		String entityId = factoriesApplicationRegistrationCacheModel.entityId;

		if ((entityId != null) && (entityId.length() == 0)) {
			factoriesApplicationRegistrationCacheModel.entityId = null;
		}

		factoriesApplicationRegistrationCacheModel.status = getStatus();

		factoriesApplicationRegistrationCacheModel.applicationNumber =
			getApplicationNumber();

		String applicationNumber =
			factoriesApplicationRegistrationCacheModel.applicationNumber;

		if ((applicationNumber != null) && (applicationNumber.length() == 0)) {
			factoriesApplicationRegistrationCacheModel.applicationNumber = null;
		}

		factoriesApplicationRegistrationCacheModel.caseId = getCaseId();

		String caseId = factoriesApplicationRegistrationCacheModel.caseId;

		if ((caseId != null) && (caseId.length() == 0)) {
			factoriesApplicationRegistrationCacheModel.caseId = null;
		}

		factoriesApplicationRegistrationCacheModel.expiredLicenseAppNumber =
			getExpiredLicenseAppNumber();

		String expiredLicenseAppNumber =
			factoriesApplicationRegistrationCacheModel.expiredLicenseAppNumber;

		if ((expiredLicenseAppNumber != null) &&
			(expiredLicenseAppNumber.length() == 0)) {

			factoriesApplicationRegistrationCacheModel.expiredLicenseAppNumber =
				null;
		}

		factoriesApplicationRegistrationCacheModel.icmDocumentPath =
			getIcmDocumentPath();

		String icmDocumentPath =
			factoriesApplicationRegistrationCacheModel.icmDocumentPath;

		if ((icmDocumentPath != null) && (icmDocumentPath.length() == 0)) {
			factoriesApplicationRegistrationCacheModel.icmDocumentPath = null;
		}

		factoriesApplicationRegistrationCacheModel.productCategory =
			getProductCategory();

		String productCategory =
			factoriesApplicationRegistrationCacheModel.productCategory;

		if ((productCategory != null) && (productCategory.length() == 0)) {
			factoriesApplicationRegistrationCacheModel.productCategory = null;
		}

		factoriesApplicationRegistrationCacheModel.areYouProcessing =
			getAreYouProcessing();

		String areYouProcessing =
			factoriesApplicationRegistrationCacheModel.areYouProcessing;

		if ((areYouProcessing != null) && (areYouProcessing.length() == 0)) {
			factoriesApplicationRegistrationCacheModel.areYouProcessing = null;
		}

		factoriesApplicationRegistrationCacheModel.typeOfTransaction =
			getTypeOfTransaction();

		String typeOfTransaction =
			factoriesApplicationRegistrationCacheModel.typeOfTransaction;

		if ((typeOfTransaction != null) && (typeOfTransaction.length() == 0)) {
			factoriesApplicationRegistrationCacheModel.typeOfTransaction = null;
		}

		factoriesApplicationRegistrationCacheModel.pdfFileEntryId =
			getPdfFileEntryId();

		factoriesApplicationRegistrationCacheModel.appCurrentStageName =
			getAppCurrentStageName();

		String appCurrentStageName =
			factoriesApplicationRegistrationCacheModel.appCurrentStageName;

		if ((appCurrentStageName != null) &&
			(appCurrentStageName.length() == 0)) {

			factoriesApplicationRegistrationCacheModel.appCurrentStageName =
				null;
		}

		return factoriesApplicationRegistrationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FactoriesApplicationRegistration, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String, Function<FactoriesApplicationRegistration, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FactoriesApplicationRegistration, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FactoriesApplicationRegistration)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, FactoriesApplicationRegistration>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						FactoriesApplicationRegistration.class,
						ModelWrapper.class);

	}

	private long _factoriesApplicationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _entityId;
	private int _status;
	private String _applicationNumber;
	private String _caseId;
	private String _expiredLicenseAppNumber;
	private String _icmDocumentPath;
	private String _productCategory;
	private String _areYouProcessing;
	private String _typeOfTransaction;
	private long _pdfFileEntryId;
	private String _appCurrentStageName;

	public <T> T getColumnValue(String columnName) {
		Function<FactoriesApplicationRegistration, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FactoriesApplicationRegistration)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"factoriesApplicationId", _factoriesApplicationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("entityId", _entityId);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("applicationNumber", _applicationNumber);
		_columnOriginalValues.put("caseId", _caseId);
		_columnOriginalValues.put(
			"expiredLicenseAppNumber", _expiredLicenseAppNumber);
		_columnOriginalValues.put("icmDocumentPath", _icmDocumentPath);
		_columnOriginalValues.put("productCategory", _productCategory);
		_columnOriginalValues.put("areYouProcessing", _areYouProcessing);
		_columnOriginalValues.put("typeOfTransaction", _typeOfTransaction);
		_columnOriginalValues.put("pdfFileEntryId", _pdfFileEntryId);
		_columnOriginalValues.put("appCurrentStageName", _appCurrentStageName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("factoriesApplicationId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("entityId", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("applicationNumber", 512L);

		columnBitmasks.put("caseId", 1024L);

		columnBitmasks.put("expiredLicenseAppNumber", 2048L);

		columnBitmasks.put("icmDocumentPath", 4096L);

		columnBitmasks.put("productCategory", 8192L);

		columnBitmasks.put("areYouProcessing", 16384L);

		columnBitmasks.put("typeOfTransaction", 32768L);

		columnBitmasks.put("pdfFileEntryId", 65536L);

		columnBitmasks.put("appCurrentStageName", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FactoriesApplicationRegistration _escapedModel;

}