/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.quary.application.form.service.model.impl;

import com.nbp.quary.application.form.service.model.QuarryMaterialInformation;
import com.nbp.quary.application.form.service.service.QuarryMaterialInformationLocalServiceUtil;

/**
 * The extended model base implementation for the QuarryMaterialInformation service. Represents a row in the &quot;nbp_quarry_material_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QuarryMaterialInformationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuarryMaterialInformationImpl
 * @see QuarryMaterialInformation
 * @generated
 */
public abstract class QuarryMaterialInformationBaseImpl
	extends QuarryMaterialInformationModelImpl
	implements QuarryMaterialInformation {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a quarry material information model instance should use the <code>QuarryMaterialInformation</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			QuarryMaterialInformationLocalServiceUtil.
				addQuarryMaterialInformation(this);
		}
		else {
			QuarryMaterialInformationLocalServiceUtil.
				updateQuarryMaterialInformation(this);
		}
	}

}