create table nbp_delineation_area (
	miningFormFiveDelineationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	approximatelyArea VARCHAR(75) null,
	location VARCHAR(75) null,
	coordinates VARCHAR(75) null,
	northSide VARCHAR(75) null,
	eastSide VARCHAR(75) null,
	firstNorthSide VARCHAR(75) null,
	firstEastSide VARCHAR(75) null,
	firstLocationGrid VARCHAR(75) null,
	firstDegrees VARCHAR(75) null,
	secondNorthSide VARCHAR(75) null,
	secondEastSide VARCHAR(75) null,
	secondLocationGrid VARCHAR(75) null,
	secondDegrees VARCHAR(75) null,
	thirdCoordinates VARCHAR(75) null,
	thirdNorthSide VARCHAR(75) null,
	thirdEastSide VARCHAR(75) null,
	thirdDegrees VARCHAR(75) null,
	thirdGridLoc VARCHAR(75) null,
	thirdGridL VARCHAR(75) null,
	fourthCoordinates VARCHAR(75) null,
	fourthNorthSide VARCHAR(75) null,
	fourthEastSide VARCHAR(75) null,
	fourthDegrees VARCHAR(75) null,
	fourthGridLoc VARCHAR(75) null,
	fourthGridL VARCHAR(75) null,
	fifthCoordinates VARCHAR(75) null,
	fifthNorthSide VARCHAR(75) null,
	fifthEastSide VARCHAR(75) null,
	fifthDegrees VARCHAR(75) null,
	fifthGridLoc VARCHAR(75) null,
	fifthGridL VARCHAR(75) null,
	miningLeaseApplicationId LONG
);

create table nbp_exclusive_form_five (
	miningExclusiveLicFormFiveId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicantNameLicence VARCHAR(75) null,
	trnNumberLicence VARCHAR(75) null,
	applicantNationalityLicence VARCHAR(75) null,
	applicantAddressLicence VARCHAR(500) null,
	applicantTelephoneLicence VARCHAR(75) null,
	applicantEmailLicence VARCHAR(75) null,
	applicantNumberLicence VARCHAR(75) null,
	agentNameLicence VARCHAR(75) null,
	numProspectingLicence VARCHAR(75) null,
	agentNameLicenceGrant VARCHAR(500) null,
	applicantLicence VARCHAR(75) null,
	justicePeaceParish VARCHAR(75) null,
	applicantLandmarkLicence VARCHAR(75) null,
	applicantAreaLicence VARCHAR(75) null,
	applicantDesires VARCHAR(500) null,
	dateLocationLic DATE null,
	incorporationLodged VARCHAR(75) null,
	miningLeaseApplicationId LONG
);

create table nbp_mining_app_payment (
	miningAppPaymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	paymentMethod VARCHAR(75) null,
	paymentDocId VARCHAR(75) null,
	paymentStatus VARCHAR(75) null,
	paymentFee VARCHAR(75) null,
	amountPaid VARCHAR(75) null,
	amountCurrency VARCHAR(75) null,
	transactionNumber VARCHAR(75) null,
	miningLeaseApplicationId LONG
);

create table nbp_mining_applications (
	miningLeaseApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	entityId VARCHAR(75) null,
	typeOfApplicant VARCHAR(75) null,
	prospectingRightNumber VARCHAR(75) null,
	typeOfProspectingLicence VARCHAR(75) null,
	typeOfTransaction VARCHAR(75) null,
	areaDelinationTotalApprox VARCHAR(75) null,
	licenceExclusiveSpecial VARCHAR(75) null,
	miningMineralsTypeVal VARCHAR(75) null,
	otherMineralBox VARCHAR(75) null,
	areaDelination VARCHAR(75) null,
	status INTEGER,
	applicationNumber VARCHAR(75) null,
	prospRightsNum VARCHAR(75) null,
	prospLicenseNum VARCHAR(75) null,
	expiredLicenseAppNumber VARCHAR(75) null,
	caseId VARCHAR(500) null,
	icmDocumentsPath VARCHAR(500) null,
	pdfFileEntryId LONG,
	appCurrentStageName VARCHAR(75) null
);

create table nbp_mining_current_stage (
	uuid_ VARCHAR(75) null,
	miningAppCurrentStageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	currentStage VARCHAR(75) null,
	lastFormStep VARCHAR(75) null,
	miningLeaseApplicationId LONG
);

create table nbp_mining_pro_license_add (
	miningProspectingLicenseAddId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	nationality VARCHAR(75) null,
	directorsOfCompany VARCHAR(75) null,
	counter VARCHAR(75) null,
	miningLeaseApplicationId LONG
);

create table nbp_mining_prospect_license (
	miningProspectingLicenseId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfApplicant VARCHAR(75) null,
	trnNumber VARCHAR(75) null,
	nationalityOfApplicant VARCHAR(75) null,
	addressInJamaica VARCHAR(1000) null,
	telephoneNumber VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	numberOfApplicant VARCHAR(75) null,
	nameOfTheAgent VARCHAR(75) null,
	numberOfThisProspecting VARCHAR(75) null,
	prospectingRight VARCHAR(75) null,
	parish VARCHAR(75) null,
	licence VARCHAR(75) null,
	stateTheNearestLandmark VARCHAR(75) null,
	approximateArea VARCHAR(75) null,
	mineralForWhichApplicant VARCHAR(75) null,
	copyOfArticle VARCHAR(75) null,
	dateUponTheLocation DATE null,
	proslicenceFeeCheck VARCHAR(75) null,
	dateSurrender DATE null,
	areaOfApproximately VARCHAR(75) null,
	locationBeacon VARCHAR(75) null,
	intersectionCoordinates VARCHAR(75) null,
	northTopographical VARCHAR(75) null,
	eastTopographical VARCHAR(75) null,
	firstCornerOfNorth VARCHAR(75) null,
	firstCornerOfEast VARCHAR(75) null,
	firstCornerApproximateMeter VARCHAR(75) null,
	firstCornerApproximateDegree VARCHAR(75) null,
	secondCornerOfNorth VARCHAR(75) null,
	secondCornerOfEast VARCHAR(75) null,
	secondCornerApproximateMeter VARCHAR(75) null,
	secondCornerApproximateDegree VARCHAR(75) null,
	thirdCornerOfNorth VARCHAR(75) null,
	thirdCornerOfEast VARCHAR(75) null,
	thirdCornerApproximateMeter VARCHAR(75) null,
	thirdCornerApproximateDegree VARCHAR(75) null,
	fourthCornerOfNorth VARCHAR(75) null,
	fourthCornerOfEast VARCHAR(75) null,
	fourthCornerApproximateMeter VARCHAR(75) null,
	fourthCornerApproximateDegree VARCHAR(75) null,
	fifthCornerOfNorth VARCHAR(75) null,
	fifthCornerOfEast VARCHAR(75) null,
	fifthCornerApproximateMeter VARCHAR(75) null,
	fifthCornerApproximateDegree VARCHAR(75) null,
	miningLeaseApplicationId LONG
);

create table nbp_mining_prospect_rights (
	prospectingRightsId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nameOfApplicant VARCHAR(75) null,
	trnNum VARCHAR(75) null,
	nationalityOfApplicant VARCHAR(75) null,
	ageOfApplicant VARCHAR(75) null,
	telephoneNum VARCHAR(75) null,
	emailAddr VARCHAR(75) null,
	addressInJamaica VARCHAR(1000) null,
	applicantProspectAcc VARCHAR(75) null,
	otherPersonName VARCHAR(75) null,
	otherPersonAddr VARCHAR(1000) null,
	prevApplication VARCHAR(75) null,
	offenceMiningAct VARCHAR(75) null,
	validProspectRight VARCHAR(75) null,
	surrenderProspectRight VARCHAR(75) null,
	prospectRightsFeeCheck VARCHAR(75) null,
	miningLeaseApplicationId LONG
);

create table nbp_mining_renew_licence (
	miningRenewalLicenceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	renewApplicantName VARCHAR(75) null,
	renewTrnNum VARCHAR(75) null,
	renewApplicantLicNum VARCHAR(75) null,
	stateWhetherRenewIs VARCHAR(75) null,
	renewTelephone VARCHAR(75) null,
	renewEmailAddr VARCHAR(75) null,
	renewNumOfApplicantLease VARCHAR(75) null,
	renApplicantDesireToMine VARCHAR(75) null,
	renewTermDesired VARCHAR(75) null,
	renewFeeCheck VARCHAR(75) null,
	renewDate DATE null,
	miningLeaseApplicationId LONG
);