/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nbp.manufacturing.application.form.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ManuAdditionalComapnyInfo service. Represents a row in the &quot;ManuAdditionalCompanyInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nbp.manufacturing.application.form.service.model.impl.ManuAdditionalComapnyInfoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nbp.manufacturing.application.form.service.model.impl.ManuAdditionalComapnyInfoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ManuAdditionalComapnyInfo
 * @generated
 */
@ProviderType
public interface ManuAdditionalComapnyInfoModel
	extends BaseModel<ManuAdditionalComapnyInfo>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a manu additional comapny info model instance should use the {@link ManuAdditionalComapnyInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this manu additional comapny info.
	 *
	 * @return the primary key of this manu additional comapny info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this manu additional comapny info.
	 *
	 * @param primaryKey the primary key of this manu additional comapny info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the manu additional comapny info ID of this manu additional comapny info.
	 *
	 * @return the manu additional comapny info ID of this manu additional comapny info
	 */
	public long getManuAdditionalComapnyInfoId();

	/**
	 * Sets the manu additional comapny info ID of this manu additional comapny info.
	 *
	 * @param manuAdditionalComapnyInfoId the manu additional comapny info ID of this manu additional comapny info
	 */
	public void setManuAdditionalComapnyInfoId(
		long manuAdditionalComapnyInfoId);

	/**
	 * Returns the group ID of this manu additional comapny info.
	 *
	 * @return the group ID of this manu additional comapny info
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this manu additional comapny info.
	 *
	 * @param groupId the group ID of this manu additional comapny info
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this manu additional comapny info.
	 *
	 * @return the company ID of this manu additional comapny info
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this manu additional comapny info.
	 *
	 * @param companyId the company ID of this manu additional comapny info
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this manu additional comapny info.
	 *
	 * @return the user ID of this manu additional comapny info
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this manu additional comapny info.
	 *
	 * @param userId the user ID of this manu additional comapny info
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this manu additional comapny info.
	 *
	 * @return the user uuid of this manu additional comapny info
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this manu additional comapny info.
	 *
	 * @param userUuid the user uuid of this manu additional comapny info
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this manu additional comapny info.
	 *
	 * @return the user name of this manu additional comapny info
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this manu additional comapny info.
	 *
	 * @param userName the user name of this manu additional comapny info
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this manu additional comapny info.
	 *
	 * @return the create date of this manu additional comapny info
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this manu additional comapny info.
	 *
	 * @param createDate the create date of this manu additional comapny info
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this manu additional comapny info.
	 *
	 * @return the modified date of this manu additional comapny info
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this manu additional comapny info.
	 *
	 * @param modifiedDate the modified date of this manu additional comapny info
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the company name representative of this manu additional comapny info.
	 *
	 * @return the company name representative of this manu additional comapny info
	 */
	@AutoEscape
	public String getCompanyNameRepresentative();

	/**
	 * Sets the company name representative of this manu additional comapny info.
	 *
	 * @param companyNameRepresentative the company name representative of this manu additional comapny info
	 */
	public void setCompanyNameRepresentative(String companyNameRepresentative);

	/**
	 * Returns the company signature representative of this manu additional comapny info.
	 *
	 * @return the company signature representative of this manu additional comapny info
	 */
	@AutoEscape
	public String getCompanySignatureRepresentative();

	/**
	 * Sets the company signature representative of this manu additional comapny info.
	 *
	 * @param companySignatureRepresentative the company signature representative of this manu additional comapny info
	 */
	public void setCompanySignatureRepresentative(
		String companySignatureRepresentative);

	/**
	 * Returns the signature date of this manu additional comapny info.
	 *
	 * @return the signature date of this manu additional comapny info
	 */
	@AutoEscape
	public String getSignatureDate();

	/**
	 * Sets the signature date of this manu additional comapny info.
	 *
	 * @param signatureDate the signature date of this manu additional comapny info
	 */
	public void setSignatureDate(String signatureDate);

	/**
	 * Returns the custom broker name of this manu additional comapny info.
	 *
	 * @return the custom broker name of this manu additional comapny info
	 */
	@AutoEscape
	public String getCustomBrokerName();

	/**
	 * Sets the custom broker name of this manu additional comapny info.
	 *
	 * @param customBrokerName the custom broker name of this manu additional comapny info
	 */
	public void setCustomBrokerName(String customBrokerName);

	/**
	 * Returns the custom broker address of this manu additional comapny info.
	 *
	 * @return the custom broker address of this manu additional comapny info
	 */
	@AutoEscape
	public String getCustomBrokerAddress();

	/**
	 * Sets the custom broker address of this manu additional comapny info.
	 *
	 * @param customBrokerAddress the custom broker address of this manu additional comapny info
	 */
	public void setCustomBrokerAddress(String customBrokerAddress);

	/**
	 * Returns the telephone number of this manu additional comapny info.
	 *
	 * @return the telephone number of this manu additional comapny info
	 */
	@AutoEscape
	public String getTelephoneNumber();

	/**
	 * Sets the telephone number of this manu additional comapny info.
	 *
	 * @param telephoneNumber the telephone number of this manu additional comapny info
	 */
	public void setTelephoneNumber(String telephoneNumber);

	/**
	 * Returns the broker ID of this manu additional comapny info.
	 *
	 * @return the broker ID of this manu additional comapny info
	 */
	@AutoEscape
	public String getBrokerId();

	/**
	 * Sets the broker ID of this manu additional comapny info.
	 *
	 * @param brokerId the broker ID of this manu additional comapny info
	 */
	public void setBrokerId(String brokerId);

	/**
	 * Returns the manufacturing application ID of this manu additional comapny info.
	 *
	 * @return the manufacturing application ID of this manu additional comapny info
	 */
	public long getManufacturingApplicationId();

	/**
	 * Sets the manufacturing application ID of this manu additional comapny info.
	 *
	 * @param manufacturingApplicationId the manufacturing application ID of this manu additional comapny info
	 */
	public void setManufacturingApplicationId(long manufacturingApplicationId);

	@Override
	public ManuAdditionalComapnyInfo cloneWithOriginalValues();

}