/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.tourism.application.form.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.tourism.application.form.services.model.TourismBonaGroundPaymentInfo;
import com.nbp.tourism.application.form.services.model.TourismBonaGroundPaymentInfoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TourismBonaGroundPaymentInfo service. Represents a row in the &quot;nbp_tourism_bona_gro_pay&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TourismBonaGroundPaymentInfoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TourismBonaGroundPaymentInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TourismBonaGroundPaymentInfoImpl
 * @generated
 */
@JSON(strict = true)
public class TourismBonaGroundPaymentInfoModelImpl
	extends BaseModelImpl<TourismBonaGroundPaymentInfo>
	implements TourismBonaGroundPaymentInfoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tourism bona ground payment info model instance should use the <code>TourismBonaGroundPaymentInfo</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_tourism_bona_gro_pay";

	public static final Object[][] TABLE_COLUMNS = {
		{"tourismBonaGroundPayId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"paymentMethod", Types.VARCHAR},
		{"paymentOtherMethod", Types.VARCHAR}, {"paymentProof", Types.VARCHAR},
		{"tourismApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("tourismBonaGroundPayId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("paymentMethod", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paymentOtherMethod", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paymentProof", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tourismApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_tourism_bona_gro_pay (tourismBonaGroundPayId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,paymentMethod VARCHAR(75) null,paymentOtherMethod VARCHAR(75) null,paymentProof VARCHAR(75) null,tourismApplicationId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_tourism_bona_gro_pay";

	public static final String ORDER_BY_JPQL =
		" ORDER BY tourismBonaGroundPaymentInfo.tourismBonaGroundPayId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_tourism_bona_gro_pay.tourismBonaGroundPayId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TOURISMAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TOURISMBONAGROUNDPAYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TourismBonaGroundPaymentInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tourismBonaGroundPayId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTourismBonaGroundPayId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tourismBonaGroundPayId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TourismBonaGroundPaymentInfo.class;
	}

	@Override
	public String getModelClassName() {
		return TourismBonaGroundPaymentInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TourismBonaGroundPaymentInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TourismBonaGroundPaymentInfo, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TourismBonaGroundPaymentInfo, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(TourismBonaGroundPaymentInfo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TourismBonaGroundPaymentInfo, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TourismBonaGroundPaymentInfo, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TourismBonaGroundPaymentInfo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TourismBonaGroundPaymentInfo, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TourismBonaGroundPaymentInfo, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<TourismBonaGroundPaymentInfo, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<TourismBonaGroundPaymentInfo, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<TourismBonaGroundPaymentInfo, Object>>();

			attributeGetterFunctions.put(
				"tourismBonaGroundPayId",
				TourismBonaGroundPaymentInfo::getTourismBonaGroundPayId);
			attributeGetterFunctions.put(
				"groupId", TourismBonaGroundPaymentInfo::getGroupId);
			attributeGetterFunctions.put(
				"companyId", TourismBonaGroundPaymentInfo::getCompanyId);
			attributeGetterFunctions.put(
				"userId", TourismBonaGroundPaymentInfo::getUserId);
			attributeGetterFunctions.put(
				"userName", TourismBonaGroundPaymentInfo::getUserName);
			attributeGetterFunctions.put(
				"createDate", TourismBonaGroundPaymentInfo::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", TourismBonaGroundPaymentInfo::getModifiedDate);
			attributeGetterFunctions.put(
				"paymentMethod",
				TourismBonaGroundPaymentInfo::getPaymentMethod);
			attributeGetterFunctions.put(
				"paymentOtherMethod",
				TourismBonaGroundPaymentInfo::getPaymentOtherMethod);
			attributeGetterFunctions.put(
				"paymentProof", TourismBonaGroundPaymentInfo::getPaymentProof);
			attributeGetterFunctions.put(
				"tourismApplicationId",
				TourismBonaGroundPaymentInfo::getTourismApplicationId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<TourismBonaGroundPaymentInfo, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TourismBonaGroundPaymentInfo, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<TourismBonaGroundPaymentInfo, ?>>();

			attributeSetterBiConsumers.put(
				"tourismBonaGroundPayId",
				(BiConsumer<TourismBonaGroundPaymentInfo, Long>)
					TourismBonaGroundPaymentInfo::setTourismBonaGroundPayId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<TourismBonaGroundPaymentInfo, Long>)
					TourismBonaGroundPaymentInfo::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<TourismBonaGroundPaymentInfo, Long>)
					TourismBonaGroundPaymentInfo::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<TourismBonaGroundPaymentInfo, Long>)
					TourismBonaGroundPaymentInfo::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<TourismBonaGroundPaymentInfo, String>)
					TourismBonaGroundPaymentInfo::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<TourismBonaGroundPaymentInfo, Date>)
					TourismBonaGroundPaymentInfo::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<TourismBonaGroundPaymentInfo, Date>)
					TourismBonaGroundPaymentInfo::setModifiedDate);
			attributeSetterBiConsumers.put(
				"paymentMethod",
				(BiConsumer<TourismBonaGroundPaymentInfo, String>)
					TourismBonaGroundPaymentInfo::setPaymentMethod);
			attributeSetterBiConsumers.put(
				"paymentOtherMethod",
				(BiConsumer<TourismBonaGroundPaymentInfo, String>)
					TourismBonaGroundPaymentInfo::setPaymentOtherMethod);
			attributeSetterBiConsumers.put(
				"paymentProof",
				(BiConsumer<TourismBonaGroundPaymentInfo, String>)
					TourismBonaGroundPaymentInfo::setPaymentProof);
			attributeSetterBiConsumers.put(
				"tourismApplicationId",
				(BiConsumer<TourismBonaGroundPaymentInfo, Long>)
					TourismBonaGroundPaymentInfo::setTourismApplicationId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getTourismBonaGroundPayId() {
		return _tourismBonaGroundPayId;
	}

	@Override
	public void setTourismBonaGroundPayId(long tourismBonaGroundPayId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tourismBonaGroundPayId = tourismBonaGroundPayId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getPaymentMethod() {
		if (_paymentMethod == null) {
			return "";
		}
		else {
			return _paymentMethod;
		}
	}

	@Override
	public void setPaymentMethod(String paymentMethod) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentMethod = paymentMethod;
	}

	@JSON
	@Override
	public String getPaymentOtherMethod() {
		if (_paymentOtherMethod == null) {
			return "";
		}
		else {
			return _paymentOtherMethod;
		}
	}

	@Override
	public void setPaymentOtherMethod(String paymentOtherMethod) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentOtherMethod = paymentOtherMethod;
	}

	@JSON
	@Override
	public String getPaymentProof() {
		if (_paymentProof == null) {
			return "";
		}
		else {
			return _paymentProof;
		}
	}

	@Override
	public void setPaymentProof(String paymentProof) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentProof = paymentProof;
	}

	@JSON
	@Override
	public long getTourismApplicationId() {
		return _tourismApplicationId;
	}

	@Override
	public void setTourismApplicationId(long tourismApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tourismApplicationId = tourismApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTourismApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("tourismApplicationId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TourismBonaGroundPaymentInfo.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TourismBonaGroundPaymentInfo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TourismBonaGroundPaymentInfo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TourismBonaGroundPaymentInfoImpl tourismBonaGroundPaymentInfoImpl =
			new TourismBonaGroundPaymentInfoImpl();

		tourismBonaGroundPaymentInfoImpl.setTourismBonaGroundPayId(
			getTourismBonaGroundPayId());
		tourismBonaGroundPaymentInfoImpl.setGroupId(getGroupId());
		tourismBonaGroundPaymentInfoImpl.setCompanyId(getCompanyId());
		tourismBonaGroundPaymentInfoImpl.setUserId(getUserId());
		tourismBonaGroundPaymentInfoImpl.setUserName(getUserName());
		tourismBonaGroundPaymentInfoImpl.setCreateDate(getCreateDate());
		tourismBonaGroundPaymentInfoImpl.setModifiedDate(getModifiedDate());
		tourismBonaGroundPaymentInfoImpl.setPaymentMethod(getPaymentMethod());
		tourismBonaGroundPaymentInfoImpl.setPaymentOtherMethod(
			getPaymentOtherMethod());
		tourismBonaGroundPaymentInfoImpl.setPaymentProof(getPaymentProof());
		tourismBonaGroundPaymentInfoImpl.setTourismApplicationId(
			getTourismApplicationId());

		tourismBonaGroundPaymentInfoImpl.resetOriginalValues();

		return tourismBonaGroundPaymentInfoImpl;
	}

	@Override
	public TourismBonaGroundPaymentInfo cloneWithOriginalValues() {
		TourismBonaGroundPaymentInfoImpl tourismBonaGroundPaymentInfoImpl =
			new TourismBonaGroundPaymentInfoImpl();

		tourismBonaGroundPaymentInfoImpl.setTourismBonaGroundPayId(
			this.<Long>getColumnOriginalValue("tourismBonaGroundPayId"));
		tourismBonaGroundPaymentInfoImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		tourismBonaGroundPaymentInfoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		tourismBonaGroundPaymentInfoImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		tourismBonaGroundPaymentInfoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		tourismBonaGroundPaymentInfoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		tourismBonaGroundPaymentInfoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		tourismBonaGroundPaymentInfoImpl.setPaymentMethod(
			this.<String>getColumnOriginalValue("paymentMethod"));
		tourismBonaGroundPaymentInfoImpl.setPaymentOtherMethod(
			this.<String>getColumnOriginalValue("paymentOtherMethod"));
		tourismBonaGroundPaymentInfoImpl.setPaymentProof(
			this.<String>getColumnOriginalValue("paymentProof"));
		tourismBonaGroundPaymentInfoImpl.setTourismApplicationId(
			this.<Long>getColumnOriginalValue("tourismApplicationId"));

		return tourismBonaGroundPaymentInfoImpl;
	}

	@Override
	public int compareTo(
		TourismBonaGroundPaymentInfo tourismBonaGroundPaymentInfo) {

		long primaryKey = tourismBonaGroundPaymentInfo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TourismBonaGroundPaymentInfo)) {
			return false;
		}

		TourismBonaGroundPaymentInfo tourismBonaGroundPaymentInfo =
			(TourismBonaGroundPaymentInfo)object;

		long primaryKey = tourismBonaGroundPaymentInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TourismBonaGroundPaymentInfo> toCacheModel() {
		TourismBonaGroundPaymentInfoCacheModel
			tourismBonaGroundPaymentInfoCacheModel =
				new TourismBonaGroundPaymentInfoCacheModel();

		tourismBonaGroundPaymentInfoCacheModel.tourismBonaGroundPayId =
			getTourismBonaGroundPayId();

		tourismBonaGroundPaymentInfoCacheModel.groupId = getGroupId();

		tourismBonaGroundPaymentInfoCacheModel.companyId = getCompanyId();

		tourismBonaGroundPaymentInfoCacheModel.userId = getUserId();

		tourismBonaGroundPaymentInfoCacheModel.userName = getUserName();

		String userName = tourismBonaGroundPaymentInfoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tourismBonaGroundPaymentInfoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tourismBonaGroundPaymentInfoCacheModel.createDate =
				createDate.getTime();
		}
		else {
			tourismBonaGroundPaymentInfoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tourismBonaGroundPaymentInfoCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			tourismBonaGroundPaymentInfoCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		tourismBonaGroundPaymentInfoCacheModel.paymentMethod =
			getPaymentMethod();

		String paymentMethod =
			tourismBonaGroundPaymentInfoCacheModel.paymentMethod;

		if ((paymentMethod != null) && (paymentMethod.length() == 0)) {
			tourismBonaGroundPaymentInfoCacheModel.paymentMethod = null;
		}

		tourismBonaGroundPaymentInfoCacheModel.paymentOtherMethod =
			getPaymentOtherMethod();

		String paymentOtherMethod =
			tourismBonaGroundPaymentInfoCacheModel.paymentOtherMethod;

		if ((paymentOtherMethod != null) &&
			(paymentOtherMethod.length() == 0)) {

			tourismBonaGroundPaymentInfoCacheModel.paymentOtherMethod = null;
		}

		tourismBonaGroundPaymentInfoCacheModel.paymentProof = getPaymentProof();

		String paymentProof =
			tourismBonaGroundPaymentInfoCacheModel.paymentProof;

		if ((paymentProof != null) && (paymentProof.length() == 0)) {
			tourismBonaGroundPaymentInfoCacheModel.paymentProof = null;
		}

		tourismBonaGroundPaymentInfoCacheModel.tourismApplicationId =
			getTourismApplicationId();

		return tourismBonaGroundPaymentInfoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TourismBonaGroundPaymentInfo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TourismBonaGroundPaymentInfo, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TourismBonaGroundPaymentInfo, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TourismBonaGroundPaymentInfo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, TourismBonaGroundPaymentInfo>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						TourismBonaGroundPaymentInfo.class, ModelWrapper.class);

	}

	private long _tourismBonaGroundPayId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _paymentMethod;
	private String _paymentOtherMethod;
	private String _paymentProof;
	private long _tourismApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<TourismBonaGroundPaymentInfo, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TourismBonaGroundPaymentInfo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"tourismBonaGroundPayId", _tourismBonaGroundPayId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("paymentMethod", _paymentMethod);
		_columnOriginalValues.put("paymentOtherMethod", _paymentOtherMethod);
		_columnOriginalValues.put("paymentProof", _paymentProof);
		_columnOriginalValues.put(
			"tourismApplicationId", _tourismApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("tourismBonaGroundPayId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("paymentMethod", 128L);

		columnBitmasks.put("paymentOtherMethod", 256L);

		columnBitmasks.put("paymentProof", 512L);

		columnBitmasks.put("tourismApplicationId", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TourismBonaGroundPaymentInfo _escapedModel;

}