/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nbp.farm.application.form.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.farm.application.form.service.model.FarmerCurrentStage;
import com.nbp.farm.application.form.service.model.FarmerCurrentStageModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FarmerCurrentStage service. Represents a row in the &quot;nbp_farmer_stage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FarmerCurrentStageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FarmerCurrentStageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FarmerCurrentStageImpl
 * @generated
 */
@JSON(strict = true)
public class FarmerCurrentStageModelImpl
	extends BaseModelImpl<FarmerCurrentStage>
	implements FarmerCurrentStageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a farmer current stage model instance should use the <code>FarmerCurrentStage</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_farmer_stage";

	public static final Object[][] TABLE_COLUMNS = {
		{"farmerCurrentStageId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"currentStage", Types.VARCHAR},
		{"lastFormStage", Types.VARCHAR}, {"farmerApplicationId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("farmerCurrentStageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("currentStage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastFormStage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("farmerApplicationId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_farmer_stage (farmerCurrentStageId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,currentStage VARCHAR(75) null,lastFormStage VARCHAR(75) null,farmerApplicationId LONG)";

	public static final String TABLE_SQL_DROP = "drop table nbp_farmer_stage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY farmerCurrentStage.farmerCurrentStageId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_farmer_stage.farmerCurrentStageId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FARMERCURRENTSTAGEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FarmerCurrentStageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _farmerCurrentStageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFarmerCurrentStageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _farmerCurrentStageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FarmerCurrentStage.class;
	}

	@Override
	public String getModelClassName() {
		return FarmerCurrentStage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FarmerCurrentStage, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FarmerCurrentStage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FarmerCurrentStage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FarmerCurrentStage)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FarmerCurrentStage, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FarmerCurrentStage, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FarmerCurrentStage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FarmerCurrentStage, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FarmerCurrentStage, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, FarmerCurrentStage>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			FarmerCurrentStage.class.getClassLoader(), FarmerCurrentStage.class,
			ModelWrapper.class);

		try {
			Constructor<FarmerCurrentStage> constructor =
				(Constructor<FarmerCurrentStage>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<FarmerCurrentStage, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FarmerCurrentStage, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FarmerCurrentStage, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FarmerCurrentStage, Object>>();
		Map<String, BiConsumer<FarmerCurrentStage, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FarmerCurrentStage, ?>>();

		attributeGetterFunctions.put(
			"farmerCurrentStageId",
			FarmerCurrentStage::getFarmerCurrentStageId);
		attributeSetterBiConsumers.put(
			"farmerCurrentStageId",
			(BiConsumer<FarmerCurrentStage, Long>)
				FarmerCurrentStage::setFarmerCurrentStageId);
		attributeGetterFunctions.put("groupId", FarmerCurrentStage::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FarmerCurrentStage, Long>)
				FarmerCurrentStage::setGroupId);
		attributeGetterFunctions.put(
			"companyId", FarmerCurrentStage::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FarmerCurrentStage, Long>)
				FarmerCurrentStage::setCompanyId);
		attributeGetterFunctions.put("userId", FarmerCurrentStage::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FarmerCurrentStage, Long>)
				FarmerCurrentStage::setUserId);
		attributeGetterFunctions.put(
			"userName", FarmerCurrentStage::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FarmerCurrentStage, String>)
				FarmerCurrentStage::setUserName);
		attributeGetterFunctions.put(
			"createDate", FarmerCurrentStage::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FarmerCurrentStage, Date>)
				FarmerCurrentStage::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FarmerCurrentStage::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FarmerCurrentStage, Date>)
				FarmerCurrentStage::setModifiedDate);
		attributeGetterFunctions.put(
			"currentStage", FarmerCurrentStage::getCurrentStage);
		attributeSetterBiConsumers.put(
			"currentStage",
			(BiConsumer<FarmerCurrentStage, String>)
				FarmerCurrentStage::setCurrentStage);
		attributeGetterFunctions.put(
			"lastFormStage", FarmerCurrentStage::getLastFormStage);
		attributeSetterBiConsumers.put(
			"lastFormStage",
			(BiConsumer<FarmerCurrentStage, String>)
				FarmerCurrentStage::setLastFormStage);
		attributeGetterFunctions.put(
			"farmerApplicationId", FarmerCurrentStage::getFarmerApplicationId);
		attributeSetterBiConsumers.put(
			"farmerApplicationId",
			(BiConsumer<FarmerCurrentStage, Long>)
				FarmerCurrentStage::setFarmerApplicationId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getFarmerCurrentStageId() {
		return _farmerCurrentStageId;
	}

	@Override
	public void setFarmerCurrentStageId(long farmerCurrentStageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_farmerCurrentStageId = farmerCurrentStageId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCurrentStage() {
		if (_currentStage == null) {
			return "";
		}
		else {
			return _currentStage;
		}
	}

	@Override
	public void setCurrentStage(String currentStage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currentStage = currentStage;
	}

	@JSON
	@Override
	public String getLastFormStage() {
		if (_lastFormStage == null) {
			return "";
		}
		else {
			return _lastFormStage;
		}
	}

	@Override
	public void setLastFormStage(String lastFormStage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastFormStage = lastFormStage;
	}

	@JSON
	@Override
	public long getFarmerApplicationId() {
		return _farmerApplicationId;
	}

	@Override
	public void setFarmerApplicationId(long farmerApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_farmerApplicationId = farmerApplicationId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FarmerCurrentStage.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FarmerCurrentStage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FarmerCurrentStage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FarmerCurrentStageImpl farmerCurrentStageImpl =
			new FarmerCurrentStageImpl();

		farmerCurrentStageImpl.setFarmerCurrentStageId(
			getFarmerCurrentStageId());
		farmerCurrentStageImpl.setGroupId(getGroupId());
		farmerCurrentStageImpl.setCompanyId(getCompanyId());
		farmerCurrentStageImpl.setUserId(getUserId());
		farmerCurrentStageImpl.setUserName(getUserName());
		farmerCurrentStageImpl.setCreateDate(getCreateDate());
		farmerCurrentStageImpl.setModifiedDate(getModifiedDate());
		farmerCurrentStageImpl.setCurrentStage(getCurrentStage());
		farmerCurrentStageImpl.setLastFormStage(getLastFormStage());
		farmerCurrentStageImpl.setFarmerApplicationId(getFarmerApplicationId());

		farmerCurrentStageImpl.resetOriginalValues();

		return farmerCurrentStageImpl;
	}

	@Override
	public FarmerCurrentStage cloneWithOriginalValues() {
		FarmerCurrentStageImpl farmerCurrentStageImpl =
			new FarmerCurrentStageImpl();

		farmerCurrentStageImpl.setFarmerCurrentStageId(
			this.<Long>getColumnOriginalValue("farmerCurrentStageId"));
		farmerCurrentStageImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		farmerCurrentStageImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		farmerCurrentStageImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		farmerCurrentStageImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		farmerCurrentStageImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		farmerCurrentStageImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		farmerCurrentStageImpl.setCurrentStage(
			this.<String>getColumnOriginalValue("currentStage"));
		farmerCurrentStageImpl.setLastFormStage(
			this.<String>getColumnOriginalValue("lastFormStage"));
		farmerCurrentStageImpl.setFarmerApplicationId(
			this.<Long>getColumnOriginalValue("farmerApplicationId"));

		return farmerCurrentStageImpl;
	}

	@Override
	public int compareTo(FarmerCurrentStage farmerCurrentStage) {
		long primaryKey = farmerCurrentStage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FarmerCurrentStage)) {
			return false;
		}

		FarmerCurrentStage farmerCurrentStage = (FarmerCurrentStage)object;

		long primaryKey = farmerCurrentStage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FarmerCurrentStage> toCacheModel() {
		FarmerCurrentStageCacheModel farmerCurrentStageCacheModel =
			new FarmerCurrentStageCacheModel();

		farmerCurrentStageCacheModel.farmerCurrentStageId =
			getFarmerCurrentStageId();

		farmerCurrentStageCacheModel.groupId = getGroupId();

		farmerCurrentStageCacheModel.companyId = getCompanyId();

		farmerCurrentStageCacheModel.userId = getUserId();

		farmerCurrentStageCacheModel.userName = getUserName();

		String userName = farmerCurrentStageCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			farmerCurrentStageCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			farmerCurrentStageCacheModel.createDate = createDate.getTime();
		}
		else {
			farmerCurrentStageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			farmerCurrentStageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			farmerCurrentStageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		farmerCurrentStageCacheModel.currentStage = getCurrentStage();

		String currentStage = farmerCurrentStageCacheModel.currentStage;

		if ((currentStage != null) && (currentStage.length() == 0)) {
			farmerCurrentStageCacheModel.currentStage = null;
		}

		farmerCurrentStageCacheModel.lastFormStage = getLastFormStage();

		String lastFormStage = farmerCurrentStageCacheModel.lastFormStage;

		if ((lastFormStage != null) && (lastFormStage.length() == 0)) {
			farmerCurrentStageCacheModel.lastFormStage = null;
		}

		farmerCurrentStageCacheModel.farmerApplicationId =
			getFarmerApplicationId();

		return farmerCurrentStageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FarmerCurrentStage, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FarmerCurrentStage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FarmerCurrentStage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FarmerCurrentStage)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	
	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FarmerCurrentStage>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _farmerCurrentStageId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _currentStage;
	private String _lastFormStage;
	private long _farmerApplicationId;

	public <T> T getColumnValue(String columnName) {
		Function<FarmerCurrentStage, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FarmerCurrentStage)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"farmerCurrentStageId", _farmerCurrentStageId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("currentStage", _currentStage);
		_columnOriginalValues.put("lastFormStage", _lastFormStage);
		_columnOriginalValues.put("farmerApplicationId", _farmerApplicationId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("farmerCurrentStageId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("currentStage", 128L);

		columnBitmasks.put("lastFormStage", 256L);

		columnBitmasks.put("farmerApplicationId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FarmerCurrentStage _escapedModel;

}