/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.mining.stage.service.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.nbp.mining.stage.service.model.MiningApplicationDueDiligence;
import com.nbp.mining.stage.service.service.MiningApplicationDueDiligenceLocalService;
import com.nbp.mining.stage.service.service.persistence.MiningApplicationCertificateIssuancePersistence;
import com.nbp.mining.stage.service.service.persistence.MiningApplicationDeskVeriPersistence;
import com.nbp.mining.stage.service.service.persistence.MiningApplicationDueDiligencePersistence;
import com.nbp.mining.stage.service.service.persistence.MiningApplicationMinisterialDecisionPersistence;
import com.nbp.mining.stage.service.service.persistence.MiningApplicationStagesPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the mining application due diligence local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.nbp.mining.stage.service.service.impl.MiningApplicationDueDiligenceLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.nbp.mining.stage.service.service.impl.MiningApplicationDueDiligenceLocalServiceImpl
 * @generated
 */
public abstract class MiningApplicationDueDiligenceLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   MiningApplicationDueDiligenceLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MiningApplicationDueDiligenceLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.nbp.mining.stage.service.service.MiningApplicationDueDiligenceLocalServiceUtil</code>.
	 */

	/**
	 * Adds the mining application due diligence to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MiningApplicationDueDiligenceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param miningApplicationDueDiligence the mining application due diligence
	 * @return the mining application due diligence that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MiningApplicationDueDiligence addMiningApplicationDueDiligence(
		MiningApplicationDueDiligence miningApplicationDueDiligence) {

		miningApplicationDueDiligence.setNew(true);

		return miningApplicationDueDiligencePersistence.update(
			miningApplicationDueDiligence);
	}

	/**
	 * Creates a new mining application due diligence with the primary key. Does not add the mining application due diligence to the database.
	 *
	 * @param miningDueDiliId the primary key for the new mining application due diligence
	 * @return the new mining application due diligence
	 */
	@Override
	@Transactional(enabled = false)
	public MiningApplicationDueDiligence createMiningApplicationDueDiligence(
		long miningDueDiliId) {

		return miningApplicationDueDiligencePersistence.create(miningDueDiliId);
	}

	/**
	 * Deletes the mining application due diligence with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MiningApplicationDueDiligenceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param miningDueDiliId the primary key of the mining application due diligence
	 * @return the mining application due diligence that was removed
	 * @throws PortalException if a mining application due diligence with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MiningApplicationDueDiligence deleteMiningApplicationDueDiligence(
			long miningDueDiliId)
		throws PortalException {

		return miningApplicationDueDiligencePersistence.remove(miningDueDiliId);
	}

	/**
	 * Deletes the mining application due diligence from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MiningApplicationDueDiligenceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param miningApplicationDueDiligence the mining application due diligence
	 * @return the mining application due diligence that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MiningApplicationDueDiligence deleteMiningApplicationDueDiligence(
		MiningApplicationDueDiligence miningApplicationDueDiligence) {

		return miningApplicationDueDiligencePersistence.remove(
			miningApplicationDueDiligence);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return miningApplicationDueDiligencePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			MiningApplicationDueDiligence.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return miningApplicationDueDiligencePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.mining.stage.service.model.impl.MiningApplicationDueDiligenceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return miningApplicationDueDiligencePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.mining.stage.service.model.impl.MiningApplicationDueDiligenceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return miningApplicationDueDiligencePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return miningApplicationDueDiligencePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return miningApplicationDueDiligencePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public MiningApplicationDueDiligence fetchMiningApplicationDueDiligence(
		long miningDueDiliId) {

		return miningApplicationDueDiligencePersistence.fetchByPrimaryKey(
			miningDueDiliId);
	}

	/**
	 * Returns the mining application due diligence matching the UUID and group.
	 *
	 * @param uuid the mining application due diligence's UUID
	 * @param groupId the primary key of the group
	 * @return the matching mining application due diligence, or <code>null</code> if a matching mining application due diligence could not be found
	 */
	@Override
	public MiningApplicationDueDiligence
		fetchMiningApplicationDueDiligenceByUuidAndGroupId(
			String uuid, long groupId) {

		return miningApplicationDueDiligencePersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the mining application due diligence with the primary key.
	 *
	 * @param miningDueDiliId the primary key of the mining application due diligence
	 * @return the mining application due diligence
	 * @throws PortalException if a mining application due diligence with the primary key could not be found
	 */
	@Override
	public MiningApplicationDueDiligence getMiningApplicationDueDiligence(
			long miningDueDiliId)
		throws PortalException {

		return miningApplicationDueDiligencePersistence.findByPrimaryKey(
			miningDueDiliId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			miningApplicationDueDiligenceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			MiningApplicationDueDiligence.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("miningDueDiliId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			miningApplicationDueDiligenceLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			MiningApplicationDueDiligence.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"miningDueDiliId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			miningApplicationDueDiligenceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			MiningApplicationDueDiligence.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("miningDueDiliId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<MiningApplicationDueDiligence>() {

				@Override
				public void performAction(
						MiningApplicationDueDiligence
							miningApplicationDueDiligence)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, miningApplicationDueDiligence);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					MiningApplicationDueDiligence.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return miningApplicationDueDiligencePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement MiningApplicationDueDiligenceLocalServiceImpl#deleteMiningApplicationDueDiligence(MiningApplicationDueDiligence) to avoid orphaned data");
		}

		return miningApplicationDueDiligenceLocalService.
			deleteMiningApplicationDueDiligence(
				(MiningApplicationDueDiligence)persistedModel);
	}

	@Override
	public BasePersistence<MiningApplicationDueDiligence> getBasePersistence() {
		return miningApplicationDueDiligencePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return miningApplicationDueDiligencePersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the mining application due diligences matching the UUID and company.
	 *
	 * @param uuid the UUID of the mining application due diligences
	 * @param companyId the primary key of the company
	 * @return the matching mining application due diligences, or an empty list if no matches were found
	 */
	@Override
	public List<MiningApplicationDueDiligence>
		getMiningApplicationDueDiligencesByUuidAndCompanyId(
			String uuid, long companyId) {

		return miningApplicationDueDiligencePersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of mining application due diligences matching the UUID and company.
	 *
	 * @param uuid the UUID of the mining application due diligences
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of mining application due diligences
	 * @param end the upper bound of the range of mining application due diligences (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching mining application due diligences, or an empty list if no matches were found
	 */
	@Override
	public List<MiningApplicationDueDiligence>
		getMiningApplicationDueDiligencesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<MiningApplicationDueDiligence>
				orderByComparator) {

		return miningApplicationDueDiligencePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the mining application due diligence matching the UUID and group.
	 *
	 * @param uuid the mining application due diligence's UUID
	 * @param groupId the primary key of the group
	 * @return the matching mining application due diligence
	 * @throws PortalException if a matching mining application due diligence could not be found
	 */
	@Override
	public MiningApplicationDueDiligence
			getMiningApplicationDueDiligenceByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return miningApplicationDueDiligencePersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the mining application due diligences.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.nbp.mining.stage.service.model.impl.MiningApplicationDueDiligenceModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of mining application due diligences
	 * @param end the upper bound of the range of mining application due diligences (not inclusive)
	 * @return the range of mining application due diligences
	 */
	@Override
	public List<MiningApplicationDueDiligence>
		getMiningApplicationDueDiligences(int start, int end) {

		return miningApplicationDueDiligencePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of mining application due diligences.
	 *
	 * @return the number of mining application due diligences
	 */
	@Override
	public int getMiningApplicationDueDiligencesCount() {
		return miningApplicationDueDiligencePersistence.countAll();
	}

	/**
	 * Updates the mining application due diligence in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MiningApplicationDueDiligenceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param miningApplicationDueDiligence the mining application due diligence
	 * @return the mining application due diligence that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MiningApplicationDueDiligence updateMiningApplicationDueDiligence(
		MiningApplicationDueDiligence miningApplicationDueDiligence) {

		return miningApplicationDueDiligencePersistence.update(
			miningApplicationDueDiligence);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MiningApplicationDueDiligenceLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		miningApplicationDueDiligenceLocalService =
			(MiningApplicationDueDiligenceLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MiningApplicationDueDiligenceLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MiningApplicationDueDiligence.class;
	}

	protected String getModelClassName() {
		return MiningApplicationDueDiligence.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				miningApplicationDueDiligencePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected MiningApplicationCertificateIssuancePersistence
		miningApplicationCertificateIssuancePersistence;

	@Reference
	protected MiningApplicationDeskVeriPersistence
		miningApplicationDeskVeriPersistence;

	protected MiningApplicationDueDiligenceLocalService
		miningApplicationDueDiligenceLocalService;

	@Reference
	protected MiningApplicationDueDiligencePersistence
		miningApplicationDueDiligencePersistence;

	@Reference
	protected MiningApplicationMinisterialDecisionPersistence
		miningApplicationMinisterialDecisionPersistence;

	@Reference
	protected MiningApplicationStagesPersistence
		miningApplicationStagesPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		MiningApplicationDueDiligenceLocalServiceBaseImpl.class);

}