/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.acquire.stages.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.acquire.stages.service.model.AcquireDraftAgreement;
import com.nbp.acquire.stages.service.model.AcquireDraftAgreementModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AcquireDraftAgreement service. Represents a row in the &quot;nbp_acquire_draft_agree&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AcquireDraftAgreementModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AcquireDraftAgreementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AcquireDraftAgreementImpl
 * @generated
 */
@JSON(strict = true)
public class AcquireDraftAgreementModelImpl
	extends BaseModelImpl<AcquireDraftAgreement>
	implements AcquireDraftAgreementModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a acquire draft agreement model instance should use the <code>AcquireDraftAgreement</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_acquire_draft_agree";

	public static final Object[][] TABLE_COLUMNS = {
		{"acquireDraftId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"caseId", Types.VARCHAR},
		{"paymentAmountDue", Types.VARCHAR}, {"docFileEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("acquireDraftId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("caseId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paymentAmountDue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("docFileEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_acquire_draft_agree (acquireDraftId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,caseId VARCHAR(75) null,paymentAmountDue VARCHAR(75) null,docFileEntryId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_acquire_draft_agree";

	public static final String ORDER_BY_JPQL =
		" ORDER BY acquireDraftAgreement.acquireDraftId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_acquire_draft_agree.acquireDraftId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CASEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACQUIREDRAFTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AcquireDraftAgreementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _acquireDraftId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAcquireDraftId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _acquireDraftId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AcquireDraftAgreement.class;
	}

	@Override
	public String getModelClassName() {
		return AcquireDraftAgreement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AcquireDraftAgreement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AcquireDraftAgreement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AcquireDraftAgreement, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AcquireDraftAgreement)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AcquireDraftAgreement, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AcquireDraftAgreement, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AcquireDraftAgreement)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AcquireDraftAgreement, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AcquireDraftAgreement, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AcquireDraftAgreement, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AcquireDraftAgreement, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AcquireDraftAgreement, Object>>();

			attributeGetterFunctions.put(
				"acquireDraftId", AcquireDraftAgreement::getAcquireDraftId);
			attributeGetterFunctions.put(
				"groupId", AcquireDraftAgreement::getGroupId);
			attributeGetterFunctions.put(
				"companyId", AcquireDraftAgreement::getCompanyId);
			attributeGetterFunctions.put(
				"userId", AcquireDraftAgreement::getUserId);
			attributeGetterFunctions.put(
				"userName", AcquireDraftAgreement::getUserName);
			attributeGetterFunctions.put(
				"createDate", AcquireDraftAgreement::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AcquireDraftAgreement::getModifiedDate);
			attributeGetterFunctions.put(
				"caseId", AcquireDraftAgreement::getCaseId);
			attributeGetterFunctions.put(
				"paymentAmountDue", AcquireDraftAgreement::getPaymentAmountDue);
			attributeGetterFunctions.put(
				"docFileEntryId", AcquireDraftAgreement::getDocFileEntryId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AcquireDraftAgreement, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AcquireDraftAgreement, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AcquireDraftAgreement, ?>>();

			attributeSetterBiConsumers.put(
				"acquireDraftId",
				(BiConsumer<AcquireDraftAgreement, Long>)
					AcquireDraftAgreement::setAcquireDraftId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AcquireDraftAgreement, Long>)
					AcquireDraftAgreement::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AcquireDraftAgreement, Long>)
					AcquireDraftAgreement::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<AcquireDraftAgreement, Long>)
					AcquireDraftAgreement::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<AcquireDraftAgreement, String>)
					AcquireDraftAgreement::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AcquireDraftAgreement, Date>)
					AcquireDraftAgreement::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AcquireDraftAgreement, Date>)
					AcquireDraftAgreement::setModifiedDate);
			attributeSetterBiConsumers.put(
				"caseId",
				(BiConsumer<AcquireDraftAgreement, String>)
					AcquireDraftAgreement::setCaseId);
			attributeSetterBiConsumers.put(
				"paymentAmountDue",
				(BiConsumer<AcquireDraftAgreement, String>)
					AcquireDraftAgreement::setPaymentAmountDue);
			attributeSetterBiConsumers.put(
				"docFileEntryId",
				(BiConsumer<AcquireDraftAgreement, Long>)
					AcquireDraftAgreement::setDocFileEntryId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getAcquireDraftId() {
		return _acquireDraftId;
	}

	@Override
	public void setAcquireDraftId(long acquireDraftId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acquireDraftId = acquireDraftId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCaseId() {
		if (_caseId == null) {
			return "";
		}
		else {
			return _caseId;
		}
	}

	@Override
	public void setCaseId(String caseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_caseId = caseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCaseId() {
		return getColumnOriginalValue("caseId");
	}

	@JSON
	@Override
	public String getPaymentAmountDue() {
		if (_paymentAmountDue == null) {
			return "";
		}
		else {
			return _paymentAmountDue;
		}
	}

	@Override
	public void setPaymentAmountDue(String paymentAmountDue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentAmountDue = paymentAmountDue;
	}

	@JSON
	@Override
	public long getDocFileEntryId() {
		return _docFileEntryId;
	}

	@Override
	public void setDocFileEntryId(long docFileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_docFileEntryId = docFileEntryId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AcquireDraftAgreement.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AcquireDraftAgreement toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AcquireDraftAgreement>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AcquireDraftAgreementImpl acquireDraftAgreementImpl =
			new AcquireDraftAgreementImpl();

		acquireDraftAgreementImpl.setAcquireDraftId(getAcquireDraftId());
		acquireDraftAgreementImpl.setGroupId(getGroupId());
		acquireDraftAgreementImpl.setCompanyId(getCompanyId());
		acquireDraftAgreementImpl.setUserId(getUserId());
		acquireDraftAgreementImpl.setUserName(getUserName());
		acquireDraftAgreementImpl.setCreateDate(getCreateDate());
		acquireDraftAgreementImpl.setModifiedDate(getModifiedDate());
		acquireDraftAgreementImpl.setCaseId(getCaseId());
		acquireDraftAgreementImpl.setPaymentAmountDue(getPaymentAmountDue());
		acquireDraftAgreementImpl.setDocFileEntryId(getDocFileEntryId());

		acquireDraftAgreementImpl.resetOriginalValues();

		return acquireDraftAgreementImpl;
	}

	@Override
	public AcquireDraftAgreement cloneWithOriginalValues() {
		AcquireDraftAgreementImpl acquireDraftAgreementImpl =
			new AcquireDraftAgreementImpl();

		acquireDraftAgreementImpl.setAcquireDraftId(
			this.<Long>getColumnOriginalValue("acquireDraftId"));
		acquireDraftAgreementImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		acquireDraftAgreementImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		acquireDraftAgreementImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		acquireDraftAgreementImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		acquireDraftAgreementImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		acquireDraftAgreementImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		acquireDraftAgreementImpl.setCaseId(
			this.<String>getColumnOriginalValue("caseId"));
		acquireDraftAgreementImpl.setPaymentAmountDue(
			this.<String>getColumnOriginalValue("paymentAmountDue"));
		acquireDraftAgreementImpl.setDocFileEntryId(
			this.<Long>getColumnOriginalValue("docFileEntryId"));

		return acquireDraftAgreementImpl;
	}

	@Override
	public int compareTo(AcquireDraftAgreement acquireDraftAgreement) {
		long primaryKey = acquireDraftAgreement.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AcquireDraftAgreement)) {
			return false;
		}

		AcquireDraftAgreement acquireDraftAgreement =
			(AcquireDraftAgreement)object;

		long primaryKey = acquireDraftAgreement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AcquireDraftAgreement> toCacheModel() {
		AcquireDraftAgreementCacheModel acquireDraftAgreementCacheModel =
			new AcquireDraftAgreementCacheModel();

		acquireDraftAgreementCacheModel.acquireDraftId = getAcquireDraftId();

		acquireDraftAgreementCacheModel.groupId = getGroupId();

		acquireDraftAgreementCacheModel.companyId = getCompanyId();

		acquireDraftAgreementCacheModel.userId = getUserId();

		acquireDraftAgreementCacheModel.userName = getUserName();

		String userName = acquireDraftAgreementCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			acquireDraftAgreementCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			acquireDraftAgreementCacheModel.createDate = createDate.getTime();
		}
		else {
			acquireDraftAgreementCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			acquireDraftAgreementCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			acquireDraftAgreementCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		acquireDraftAgreementCacheModel.caseId = getCaseId();

		String caseId = acquireDraftAgreementCacheModel.caseId;

		if ((caseId != null) && (caseId.length() == 0)) {
			acquireDraftAgreementCacheModel.caseId = null;
		}

		acquireDraftAgreementCacheModel.paymentAmountDue =
			getPaymentAmountDue();

		String paymentAmountDue =
			acquireDraftAgreementCacheModel.paymentAmountDue;

		if ((paymentAmountDue != null) && (paymentAmountDue.length() == 0)) {
			acquireDraftAgreementCacheModel.paymentAmountDue = null;
		}

		acquireDraftAgreementCacheModel.docFileEntryId = getDocFileEntryId();

		return acquireDraftAgreementCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AcquireDraftAgreement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AcquireDraftAgreement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AcquireDraftAgreement, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AcquireDraftAgreement)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AcquireDraftAgreement>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AcquireDraftAgreement.class, ModelWrapper.class);

	}

	private long _acquireDraftId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _caseId;
	private String _paymentAmountDue;
	private long _docFileEntryId;

	public <T> T getColumnValue(String columnName) {
		Function<AcquireDraftAgreement, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AcquireDraftAgreement)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("acquireDraftId", _acquireDraftId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("caseId", _caseId);
		_columnOriginalValues.put("paymentAmountDue", _paymentAmountDue);
		_columnOriginalValues.put("docFileEntryId", _docFileEntryId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("acquireDraftId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("caseId", 128L);

		columnBitmasks.put("paymentAmountDue", 256L);

		columnBitmasks.put("docFileEntryId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AcquireDraftAgreement _escapedModel;

}