/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.creative.stages.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nbp.creative.stages.services.model.CreativeDeskVerification;
import com.nbp.creative.stages.services.model.CreativeDeskVerificationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CreativeDeskVerification service. Represents a row in the &quot;nbp_creative_desk_veri&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CreativeDeskVerificationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CreativeDeskVerificationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CreativeDeskVerificationImpl
 * @generated
 */
@JSON(strict = true)
public class CreativeDeskVerificationModelImpl
	extends BaseModelImpl<CreativeDeskVerification>
	implements CreativeDeskVerificationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a creative desk verification model instance should use the <code>CreativeDeskVerification</code> interface instead.
	 */
	public static final String TABLE_NAME = "nbp_creative_desk_veri";

	public static final Object[][] TABLE_COLUMNS = {
		{"creativeDeskVerificationId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"creativeApplicationId", Types.BIGINT},
		{"documentName", Types.VARCHAR}, {"documentStatus", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("creativeDeskVerificationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("creativeApplicationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentStatus", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nbp_creative_desk_veri (creativeDeskVerificationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,creativeApplicationId LONG,documentName VARCHAR(500) null,documentStatus VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nbp_creative_desk_veri";

	public static final String ORDER_BY_JPQL =
		" ORDER BY creativeDeskVerification.creativeDeskVerificationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nbp_creative_desk_veri.creativeDeskVerificationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATIVEAPPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATIVEDESKVERIFICATIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CreativeDeskVerificationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _creativeDeskVerificationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCreativeDeskVerificationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _creativeDeskVerificationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CreativeDeskVerification.class;
	}

	@Override
	public String getModelClassName() {
		return CreativeDeskVerification.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CreativeDeskVerification, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CreativeDeskVerification, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CreativeDeskVerification, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CreativeDeskVerification)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CreativeDeskVerification, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CreativeDeskVerification, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CreativeDeskVerification)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CreativeDeskVerification, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CreativeDeskVerification, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CreativeDeskVerification, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CreativeDeskVerification, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CreativeDeskVerification, Object>>();

			attributeGetterFunctions.put(
				"creativeDeskVerificationId",
				CreativeDeskVerification::getCreativeDeskVerificationId);
			attributeGetterFunctions.put(
				"groupId", CreativeDeskVerification::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CreativeDeskVerification::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CreativeDeskVerification::getUserId);
			attributeGetterFunctions.put(
				"userName", CreativeDeskVerification::getUserName);
			attributeGetterFunctions.put(
				"createDate", CreativeDeskVerification::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CreativeDeskVerification::getModifiedDate);
			attributeGetterFunctions.put(
				"creativeApplicationId",
				CreativeDeskVerification::getCreativeApplicationId);
			attributeGetterFunctions.put(
				"documentName", CreativeDeskVerification::getDocumentName);
			attributeGetterFunctions.put(
				"documentStatus", CreativeDeskVerification::getDocumentStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CreativeDeskVerification, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CreativeDeskVerification, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CreativeDeskVerification, ?>>();

			attributeSetterBiConsumers.put(
				"creativeDeskVerificationId",
				(BiConsumer<CreativeDeskVerification, Long>)
					CreativeDeskVerification::setCreativeDeskVerificationId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CreativeDeskVerification, Long>)
					CreativeDeskVerification::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CreativeDeskVerification, Long>)
					CreativeDeskVerification::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CreativeDeskVerification, Long>)
					CreativeDeskVerification::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CreativeDeskVerification, String>)
					CreativeDeskVerification::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CreativeDeskVerification, Date>)
					CreativeDeskVerification::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CreativeDeskVerification, Date>)
					CreativeDeskVerification::setModifiedDate);
			attributeSetterBiConsumers.put(
				"creativeApplicationId",
				(BiConsumer<CreativeDeskVerification, Long>)
					CreativeDeskVerification::setCreativeApplicationId);
			attributeSetterBiConsumers.put(
				"documentName",
				(BiConsumer<CreativeDeskVerification, String>)
					CreativeDeskVerification::setDocumentName);
			attributeSetterBiConsumers.put(
				"documentStatus",
				(BiConsumer<CreativeDeskVerification, String>)
					CreativeDeskVerification::setDocumentStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getCreativeDeskVerificationId() {
		return _creativeDeskVerificationId;
	}

	@Override
	public void setCreativeDeskVerificationId(long creativeDeskVerificationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creativeDeskVerificationId = creativeDeskVerificationId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreativeApplicationId() {
		return _creativeApplicationId;
	}

	@Override
	public void setCreativeApplicationId(long creativeApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creativeApplicationId = creativeApplicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCreativeApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("creativeApplicationId"));
	}

	@JSON
	@Override
	public String getDocumentName() {
		if (_documentName == null) {
			return "";
		}
		else {
			return _documentName;
		}
	}

	@Override
	public void setDocumentName(String documentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentName = documentName;
	}

	@JSON
	@Override
	public String getDocumentStatus() {
		if (_documentStatus == null) {
			return "";
		}
		else {
			return _documentStatus;
		}
	}

	@Override
	public void setDocumentStatus(String documentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentStatus = documentStatus;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CreativeDeskVerification.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CreativeDeskVerification toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CreativeDeskVerification>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CreativeDeskVerificationImpl creativeDeskVerificationImpl =
			new CreativeDeskVerificationImpl();

		creativeDeskVerificationImpl.setCreativeDeskVerificationId(
			getCreativeDeskVerificationId());
		creativeDeskVerificationImpl.setGroupId(getGroupId());
		creativeDeskVerificationImpl.setCompanyId(getCompanyId());
		creativeDeskVerificationImpl.setUserId(getUserId());
		creativeDeskVerificationImpl.setUserName(getUserName());
		creativeDeskVerificationImpl.setCreateDate(getCreateDate());
		creativeDeskVerificationImpl.setModifiedDate(getModifiedDate());
		creativeDeskVerificationImpl.setCreativeApplicationId(
			getCreativeApplicationId());
		creativeDeskVerificationImpl.setDocumentName(getDocumentName());
		creativeDeskVerificationImpl.setDocumentStatus(getDocumentStatus());

		creativeDeskVerificationImpl.resetOriginalValues();

		return creativeDeskVerificationImpl;
	}

	@Override
	public CreativeDeskVerification cloneWithOriginalValues() {
		CreativeDeskVerificationImpl creativeDeskVerificationImpl =
			new CreativeDeskVerificationImpl();

		creativeDeskVerificationImpl.setCreativeDeskVerificationId(
			this.<Long>getColumnOriginalValue("creativeDeskVerificationId"));
		creativeDeskVerificationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		creativeDeskVerificationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		creativeDeskVerificationImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		creativeDeskVerificationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		creativeDeskVerificationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		creativeDeskVerificationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		creativeDeskVerificationImpl.setCreativeApplicationId(
			this.<Long>getColumnOriginalValue("creativeApplicationId"));
		creativeDeskVerificationImpl.setDocumentName(
			this.<String>getColumnOriginalValue("documentName"));
		creativeDeskVerificationImpl.setDocumentStatus(
			this.<String>getColumnOriginalValue("documentStatus"));

		return creativeDeskVerificationImpl;
	}

	@Override
	public int compareTo(CreativeDeskVerification creativeDeskVerification) {
		long primaryKey = creativeDeskVerification.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CreativeDeskVerification)) {
			return false;
		}

		CreativeDeskVerification creativeDeskVerification =
			(CreativeDeskVerification)object;

		long primaryKey = creativeDeskVerification.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CreativeDeskVerification> toCacheModel() {
		CreativeDeskVerificationCacheModel creativeDeskVerificationCacheModel =
			new CreativeDeskVerificationCacheModel();

		creativeDeskVerificationCacheModel.creativeDeskVerificationId =
			getCreativeDeskVerificationId();

		creativeDeskVerificationCacheModel.groupId = getGroupId();

		creativeDeskVerificationCacheModel.companyId = getCompanyId();

		creativeDeskVerificationCacheModel.userId = getUserId();

		creativeDeskVerificationCacheModel.userName = getUserName();

		String userName = creativeDeskVerificationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			creativeDeskVerificationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			creativeDeskVerificationCacheModel.createDate =
				createDate.getTime();
		}
		else {
			creativeDeskVerificationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			creativeDeskVerificationCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			creativeDeskVerificationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		creativeDeskVerificationCacheModel.creativeApplicationId =
			getCreativeApplicationId();

		creativeDeskVerificationCacheModel.documentName = getDocumentName();

		String documentName = creativeDeskVerificationCacheModel.documentName;

		if ((documentName != null) && (documentName.length() == 0)) {
			creativeDeskVerificationCacheModel.documentName = null;
		}

		creativeDeskVerificationCacheModel.documentStatus = getDocumentStatus();

		String documentStatus =
			creativeDeskVerificationCacheModel.documentStatus;

		if ((documentStatus != null) && (documentStatus.length() == 0)) {
			creativeDeskVerificationCacheModel.documentStatus = null;
		}

		return creativeDeskVerificationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CreativeDeskVerification, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CreativeDeskVerification, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CreativeDeskVerification, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CreativeDeskVerification)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CreativeDeskVerification>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CreativeDeskVerification.class, ModelWrapper.class);

	}

	private long _creativeDeskVerificationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _creativeApplicationId;
	private String _documentName;
	private String _documentStatus;

	public <T> T getColumnValue(String columnName) {
		Function<CreativeDeskVerification, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CreativeDeskVerification)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"creativeDeskVerificationId", _creativeDeskVerificationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"creativeApplicationId", _creativeApplicationId);
		_columnOriginalValues.put("documentName", _documentName);
		_columnOriginalValues.put("documentStatus", _documentStatus);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("creativeDeskVerificationId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("creativeApplicationId", 128L);

		columnBitmasks.put("documentName", 256L);

		columnBitmasks.put("documentStatus", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CreativeDeskVerification _escapedModel;

}