/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nbp.mining.stage.service.model.impl;

import com.nbp.mining.stage.service.model.MiningApplicationDueDiligence;
import com.nbp.mining.stage.service.service.MiningApplicationDueDiligenceLocalServiceUtil;

/**
 * The extended model base implementation for the MiningApplicationDueDiligence service. Represents a row in the &quot;nbp_mining_due_dili&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MiningApplicationDueDiligenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MiningApplicationDueDiligenceImpl
 * @see MiningApplicationDueDiligence
 * @generated
 */
public abstract class MiningApplicationDueDiligenceBaseImpl
	extends MiningApplicationDueDiligenceModelImpl
	implements MiningApplicationDueDiligence {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mining application due diligence model instance should use the <code>MiningApplicationDueDiligence</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MiningApplicationDueDiligenceLocalServiceUtil.
				addMiningApplicationDueDiligence(this);
		}
		else {
			MiningApplicationDueDiligenceLocalServiceUtil.
				updateMiningApplicationDueDiligence(this);
		}
	}

}